### ISSUE TITLE
Deploy: Action to restore media

### ISSUE THREAD

**Issue by bjarnef** [umbraco/Umbraco.Cloud.Issues#102]
When right-clicking content root, it has an option the restore content, but in media section there isn't a similar option to restore media items. Sometimes you just want to restore the media items and not all content.

![image](https://user-images.githubusercontent.com/2919859/62214881-31070f00-b3a6-11e9-8572-bb3bb69b5984.png)

![image](https://user-images.githubusercontent.com/2919859/62214844-23ea2000-b3a6-11e9-8916-6b3d587b2745.png)

It is however possible to deploy media without deploying content to remote environment.

---
_This item has been added to our backlog [AB#5962](https://dev.azure.com/umbraco/243e7927-03b2-44e2-908f-d4ac7ea5daaa/_workitems/edit/5962)_

**Comment by Zweben** [comment]
I second this request. The lack of this option has posed a significant inconvenience for us a few times. In addition to a restore option, a "partial restore" option would be highly valuable. Basically, I'd like for Media to be treated as a first-class citizen by Deploy, with the same functionality as Content nodes.

**Comment by tormnator** [comment]
I agree. This is much needed (along with the ability to restore content nodes **without child nodes**).

**Comment by nul800sebastiaan** [comment]
Sorry for the delay on this one! We have recently launched the partial restore feature for Content items and we'll try to add restore/partial restore for media item in one of our upcoming sprints.

**Comment by clausjensen** [comment]
@bjarnef restoring media will be added in the next minor of Deploy. You'll have to wait a bit with the partial restores though as it requires a little more work.

.. and for the record - this wasn't planned so @nul800sebastiaan's answer is spot on 😄 .. I just had another fix I needed to make and then this was just nearby...

**Comment by jmayntzhusen** [comment]
This is added in Deploy 3.4.5 & 2.1.1
