### ISSUE TITLE
Creating a dev environment for an existing site throws a schema violation

### ISSUE THREAD

**Issue by simonproctor** [umbraco/Umbraco.Cloud.Issues#107]
I have an existing site with templates that include start nodes for media and content pickers.

If I create a dev environment from this live environment and attempt to restore the content, I get a schema mismatch error. Because the document type fields have entries that don't exist in the node tree, it throws a validation error (or appears to).

Consequently creating a fresh clone of the site or a new environment fails and no content or media can be synchronised. We can get around this in our local by taking an SQL backup and using that. However, it doesn't work for the cloud environment created.

I can provide our cloud details if provided with contact details.

**Comment by nul800sebastiaan** [comment]
Hey there @simonproctor - I'm sure our support will be happy to try and help you out. In the portal at https://s1.umbraco.io you should see a support option popping up in the bottom right:

![image](https://user-images.githubusercontent.com/304656/62721815-5bdc0d80-ba0d-11e9-8be8-ed3ae33acc55.png)

Make sure to send them a message so they can help you along! 👍
