### ISSUE TITLE
trees.config missing Forms settings after deploy

### ISSUE THREAD

**Issue by greystate** [umbraco/Umbraco.Cloud.Issues#11]
This was reported on the old tracker here: https://issues.umbraco.org/issue/UAAS-669 but we keep running into this problem (basically everytime we start a new site) and I can't really tell if the old issues are looked at or prioritized in any way, so reposting the issue here.

_(Feel free to close this if there are measures in motion that would automatically transfer the old issue here at some point)_ 

### Basic summary:

On a new site created with just a LIVE environment I create a Form and put it on a page.
I subsequently do some edits to templates etc. and push the new code (after pulling etc., no conflicts).

When going to the Forms section, the tree is now missing.

If I restart the site it returns.

### Workaround

Using Kudu, I find the `trees.config` file on LIVE and compare it to the one I have locally (from cloning the repository) and the local file is
indeed missing the forms entries. If I add these manually to my local file and commit that, the tree now works.

**Comment by greystate** [comment]
I *think* I know why this happens now...

I don't use Visual Studio, so I never build/run the site locally; I just clone down the repo and push/pull whenever necessary.

So I probably manage to do several push deployments to the site before we get to use Forms at all. I don't know when Forms gets 'installed' in a site, but it seems like my originally cloned trees.config always just overwrite the one in the site, whenever I push a new release.

So something extra special happens after a restart that seems to reinstall the Forms references...

But something's still fishy, since I never get a conflict on the file and never get the 'correct' version when pulling...

**Comment by greystate** [comment]
I just ran into this again today ☹️ 

_(Umbraco 7.13.2 | Forms 7.0.6 | Deploy 2.0.15)_

**Comment by greystate** [comment]
Happened again, and here's a little more info:

- I open Forms and notice the tree is gone
- I compare the trees.config from Kudu with my local version - no differences
- I restart the site
- I see that the Forms tree has now reappeared
- I compare the trees.config on Kudu with my local - while I get the following diff - _there are no changes whatsoever_ recorded in Git, i.e. `git pull` says "no changes/already up to date" ! 

```diff
-  <add initialize="true" sortOrder="0" alias="packager" application="developer" iconClosed="icon-folder" iconOpen="icon-folder-open" type="Umbraco.Web.Trees.PackagesTreeController, umbraco"/>
+  <add initialize="true" sortOrder="0" alias="packager" application="developer" iconClosed="icon-folder" iconOpen="icon-folder-open" type="Umbraco.Web.Trees.PackagesTreeController, umbraco" />
+  <add initialize="true" sortOrder="8" alias="contentBlueprints" application="settings" iconClosed="icon-folder" iconOpen="icon-folder-open" type="Umbraco.Web.Trees.ContentBlueprintTreeController, umbraco" />
+  <add initialize="true" sortOrder="2" alias="datasource" application="forms" title="Datasources" iconClosed="icon-folder" iconOpen="icon-folder-open" type="Umbraco.Forms.Web.Trees.DataSourceTreeController, Umbraco.Forms.Web" />
+  <add initialize="false" sortOrder="0" alias="emailTemplates" application="forms" title="Email Templates" iconClosed="icon-folder" iconOpen="icon-folder-open" type="Umbraco.Forms.Web.Trees.EmailTemplateTreeController, Umbraco.Forms.Web" />
+  <add initialize="true" sortOrder="0" alias="form" application="forms" title="Forms" iconClosed="icon-folder" iconOpen="icon-folder-open" type="Umbraco.Forms.Web.Trees.FormTreeController, Umbraco.Forms.Web" />
+  <add initialize="true" sortOrder="3" alias="prevaluesource" application="forms" title="Prevalue sources" iconClosed="icon-folder" iconOpen="icon-folder-open" type="Umbraco.Forms.Web.Trees.PreValueSourceTreeController, Umbraco.Forms.Web" />
+  <add initialize="true" sortOrder="3" alias="formsecurity" application="users" title="Forms Security" iconClosed="icon-folder" iconOpen="icon-folder-open" type="Umbraco.Forms.Web.Trees.FormSecurityTreeController, Umbraco.Forms.Web" />
```

Why are these changes not recorded? What am I donig so horribly wrong? 😀

**Comment by greystate** [comment]
So this happened again, only this time I don't get the Forms tree back after restarting.

It's happening on the Development environment of a 7.14.0 site with Forms 7.1.2.

There are no differences between the `trees.config` in Kudu and the on in the Git repo.

If I compare with the Live site's file I can see which lines are missing (spoiler alert - it's the Forms entries 😄 ):

```diff
+  <add initialize="true" sortOrder="2" alias="datasource" application="forms" title="Datasources" iconClosed="icon-folder" iconOpen="icon-folder-open" type="Umbraco.Forms.Web.Trees.DataSourceTreeController, Umbraco.Forms.Web" />
+  <add initialize="false" sortOrder="0" alias="emailTemplates" application="forms" title="Email Templates" iconClosed="icon-folder" iconOpen="icon-folder-open" type="Umbraco.Forms.Web.Trees.EmailTemplateTreeController, Umbraco.Forms.Web" />
+  <add initialize="true" sortOrder="0" alias="form" application="forms" title="Forms" iconClosed="icon-folder" iconOpen="icon-folder-open" type="Umbraco.Forms.Web.Trees.FormTreeController, Umbraco.Forms.Web" />
+  <add initialize="true" sortOrder="3" alias="prevaluesource" application="forms" title="Prevalue sources" iconClosed="icon-folder" iconOpen="icon-folder-open" type="Umbraco.Forms.Web.Trees.PreValueSourceTreeController, Umbraco.Forms.Web" />
+  <add initialize="true" sortOrder="3" alias="formsecurity" application="users" title="Forms Security" iconClosed="icon-folder" iconOpen="icon-folder-open" type="Umbraco.Forms.Web.Trees.FormSecurityTreeController, Umbraco.Forms.Web" />
``` 

So far, I think I've encountered this on _almost every single cloud site_ we're building and I still don't understand why it happens. And even though there's a [topic in the docs section](https://our.umbraco.com/documentation/Umbraco-Cloud/Deployment/Umbraco-Forms-on-Cloud/#the-forms-tree-is-missing) describing it, I think it's about time someone digs in and finds out what's going on... ?

**Comment by greystate** [comment]
Just to bang on this once again, Umbraco version **7.15.5** with Forms version **7.4.1**.

I push changes and then I have to restart the environment... not really a "solution", is it? 😏

**Comment by nul800sebastiaan** [comment]
Thanks for the nudge @greystate - it's definitely not great at all 🙈 

The bad news for you is that it's a uniquely v7 problem since v8 doesn't have the trees.config file any more.

The solution, I just realized, COULD be as simple as adding those entries to the trees.config file on your local environment and pushing them through to all of your environments on Cloud. Is that even necessary though? I would have thought that we commit those entries to begin with? 

Hmm, it looks like they're there in a project I created in May, yours might be a lot older though, maybe we didn't use to ship with the correct trees.config.

**Comment by greystate** [comment]
Thanks @nul800sebastiaan !

Looking at my earlier "excursions" I can kind of see that I _think_ I've actually arrived at that "solution" as well - given that the problem is that changes to the trees.config does not get committed to Git, unless you do it yourself.

I just hit this twice today and one of them was the client calling to say that they couldn't add or edit any forms... 

I'll try to manually add the entries and commit them to see if I'm lucky :D

**Comment by nul800sebastiaan** [comment]
Just for my understanding @greystate - is this an upgraded site by any chance? Or a new site? It could be that we fixed this along the way (if committing those entries works) but I'm not sure.

In any case, let me know how it goes 🤞

**Comment by greystate** [comment]
It's what would be categorized as "created on Cloud as probably 7.13.x or thereabouts, then upgraded regularly to current 'latest'..." :)

I've just manually added the entries and committed them, which seems to stick. So I'll add a note to remember doing that for all our remaining 7s.

Thanks again @nul800sebastiaan - appreciate the willingness to help 👍

**Comment by nul800sebastiaan** [comment]
Interesting! I'll ask around to see if this is something we started doing "recently" then (committing the forms entries to `trees.config`). 

Let's keep monitoring the situation, I hope to not hear back from you on this one for the next few months! 😉 And sorry that it took so long to come up with a (seemingly simple) solution!

**Comment by sitereactor** [comment]
I have scheduled this for our next sprint (coming up next week). Hopefully there are some low hanging fruit we an pick 😉

**Comment by mikkelhm** [comment]
A patch for this has now been applied, and future sites created on Umbraco v7 should not experience this issue (Version 8 does not have the trees.config)

**Comment by nul800sebastiaan** [comment]
@mikkelhm Thank you!

@greystate unfortunately this means your existing sites won't be fixed, but we have identified the actual cause of this problem: the trees.config file not getting committed in git on any environment means sometimes the tree will disappear. This is because the Forms codebase has an instruction in it: when the site starts, add the trees. When you do a deploy and the site doesn't restart, the trees.config without the Forms trees starts getting used and that's what you've been seeing.

I'll close this one as solved, if you have any other sites exhibiting this problem, make sure to add the entries to trees.config and push them to Cloud. Thank you for your patience Chriztian! 🙏

**Comment by greystate** [comment]
Thanks @mikkelhm & @nul800sebastiaan  — I'm totally cool with existing sites not being fixed automagically; *super* happy to finally know the cause of it, and that it's relatively simple to fix.
