### ISSUE TITLE
Bulk Queue for Transfer option for ListView

### ISSUE THREAD

**Issue by jezmaghuyop** [umbraco/Umbraco.Cloud.Issues#115]
I've been using Umbraco Cloud for almost a year now and hosting an Ecommerce with lots of content is becoming a pain, the problem I'm experiencing right now is that I just recently created a Staging Environment and have to transfer all of the contents from Dev to Staging which is around approximately 500-1000k contents.

The problem is after 2-3hrs of waiting it will end up in a timeout, see the exception below.

```
1f9eb124 - Executing, 80% - Exception!
1f9eb124 - Executing, 80% - Abort remote session
1f9eb124 - Failed, 80% - Total time 03:24:31.814.
-- EXCEPTION ---------------------------------------------------
(proper exception traces at the end of this log)
System.InvalidOperationException: This SqlTransaction has completed; it is no longer usable.
----------------------------------------------------------------
EXCEPTION:
System.InvalidOperationException: This SqlTransaction has completed; it is no longer usable.
at System.Data.SqlClient.SqlTransaction.ZombieCheck()
at System.Data.SqlClient.SqlTransaction.Rollback()
at StackExchange.Profiling.Data.ProfiledDbTransaction.Rollback()
at Umbraco.Core.Persistence.Database.CleanupTransaction()
at Umbraco.Core.Persistence.Database.AbortTransaction()
at Umbraco.Core.Scoping.Scope.DisposeLastScope()
at Umbraco.Core.Scoping.Scope.Dispose()
```

That is why I wanted to request a feature in ListView mode to have the ability to do a Bulk Transfer so that it is easier for us to do a batch transfer and prevent dealing with timeouts, with that feature we can just Check the desired content of a ListView page and add it to Queue then Transfer, rather than right clicking every content to add them in the Queue for batch transfer.

Btw, here is my UmbracoDeploy.Settings.Config

```
<?xml version="1.0" encoding="utf-8"?>
<settings xmlns="urn:umbracodeploy-settings">
  <deploy sessionTimeout="999999" sourceDeployTimeout="999999" httpClientTimeout="99999" />
<forms transferFormsAsContent="false" /></settings>
```

**Comment by nul800sebastiaan** [comment]
Thanks, this is certainly on our wish list. Unfortunately I don't have an expected date for you, make sure to keep following this issue: https://github.com/umbraco/Umbraco.Cloud.Issues/issues/10

**Comment by hfloyd** [comment]
I'd like something similar for transferring lots of child content nodes, perhaps an option added to the "bulk" toolbar?

![image](https://user-images.githubusercontent.com/1252593/79274460-a0f4f100-7e72-11ea-9393-fb1ecac2868f.png)

If there could be another button for "Deploy", that would be awesome. There is a real issue with large content transfers having to be broken down into smaller chunks.
