### ISSUE TITLE
Improve Umbraco-Cloud performance.

### ISSUE THREAD

**Issue by c9mbundy** [umbraco/Umbraco.Cloud.Issues#118]
Umbraco-Cloud performance can be pretty sluggish at times, particularly when it comes to media files.

The Amsterdam Data-Centre thing really doesn't work as well for non Euro-Centric locations, such as mine - Sydney, Australia.

Also, not having a standard CDN option, makes the Cloud-based setup more complex than necessary. I've been avoiding it because it's just another issue I don't have time for at the moment.

Competing managed solution options offer the ability to host in data-centres distributed around the world, and auto-config of built-in CDN services... similar to the way Umbraco-Latch is auto-configured.

A good example of what the competition is offering, would be WP-Engine - you can select data-centres closest to your location, and enable CDN on a site with a click.

Microsoft has the infrastructure available to provide the required solution to Umbraco-Cloud for both of these.

**Comment by nul800sebastiaan** [comment]
We'd love to! Currently this is not actually possible with the setup we have but we're working on better options in the future. I unfortunately don't have a good timeline for what "future" means in this case though, but we'll shout about it when the future has arrived. 

This idea is high on our list as well, so I'll close this for now with the promise that we have focus on it (but it will take a good while).
