### ISSUE TITLE
Permission to allow/disallow "Queue for transfer" and "Partial restore"

### ISSUE THREAD

**Issue by tormnator** [umbraco/Umbraco.Cloud.Issues#125]
We have a need for a group of users to only view nodes in the content tree (not edit or making any kind of changes), and have set the appropriate permissions for the group. But, when right-clicking on a node, the "Queue for transfer" and "Partial restore" menu items are active and usable. After queueing a node, it's also possible for the user to click on "Content" and "Send changes to the "Live" workspace".

We need new group permissions to remove these 2 actions from the menu.

**Comment by nul800sebastiaan** [comment]
Hi @tormnator - I've moved this issue to the Umbraco Cloud issue tracker as these are not core CMS features. I will need to talk to the Cloud team to figure out how to deal with these types of permissions. I'll get back to you.

**Comment by tormnator** [comment]
Ok, thanks!

**Comment by tormnator** [comment]
Down on the bottom right of the node's editor there's also "Deploy" on the Save popup menu. This should also be removed at the same time as "Queue for transfer"

I can work around the issue for the content menu by adding a handler to the TreeControllerBase.MenuRendering event, but is there a corresponding event I can hook to remove the "Deploy" button/item?

**Comment by nul800sebastiaan** [comment]
Yes, I was going to suggest the MenuRendering handler for now. Good question, it looks like `deploy.decorators.js` contains the button, maybe you can play with that?

**Comment by greystate** [comment]
Was going to report this issue — it's quite a problem that you lock down publishing for a usergroup and then discover that they're actually able to almost circumvent it and just send the content from STAGE (the only environment they have access to) to LIVE 😱

**Comment by AndyButland** [comment]
I think we have this already on the Deploy tracker in [issue 25](https://github.com/umbraco/Umbraco.Deploy.Issues/issues/25) and also that this is already partly resolved.  I can see in the latest version of Deploy that we have the ability to set the "Queue For Transfer" and "Restore" permissions by user group, so can lock this down.

What's still available is the "Transfer now" button on that you can get to from the "Save" button when editing a particular content item.  I've got a PR pending to resolve that, so would expect that in the next release (likely 4.1.1).

**Comment by sajumb** [comment]
As this is handled in the Deploy issues tracker (as stated by Andy in the previous comment) we are closing this issue.
