### ISSUE TITLE
SQL Azure firewall rules should be applied to new environments

### ISSUE THREAD

**Issue by samtruedig** [umbraco/Umbraco.Cloud.Issues#129]
When createing a new envionment the existing SQL Azure firewall rules are not applied to the newly created database.

Reproduction
------------
1. Create a SQL Azure firewall rule for your IP.
2. Manage environments -> Create new environment
3. Try and access the SQL database for the new environment

### Expected result
Successful access to new database without recreating firewall rule

### Actual result
Unsuccessful access

**Comment by jmayntzhusen** [comment]
Hey @samtruedig 

Thanks a lot for submitting this feature request. We rolled out a new version of the Cloud portal today that has this feature - so any new environments added from today will have the existing firewall rules applied to them 🙂
