### ISSUE TITLE
Portal Typo on "Manage Child projects" page

### ISSUE THREAD

**Issue by hfloyd** [umbraco/Umbraco.Cloud.Issues#130]
In the heading "Comfirm" should be "Confirm":

![image](https://user-images.githubusercontent.com/1252593/66703458-e0365f80-ece0-11e9-9271-9d9ad37b9a7f.png)

**Comment by Aaen** [comment]
Hi @hfloyd 

Thanks for letting us know this typo in the Manage Child projects page. I have just made a pull request for this so the typo can be fixed.

**Comment by jmayntzhusen** [comment]
Forgot to close this when it was merged in, will close now 🙂
