### ISSUE TITLE
Back-office "View Website" Link does direct to the hostname you are on

### ISSUE THREAD

**Issue by costerhout621** [umbraco/Umbraco.Cloud.Issues#134]
### Bug summary
When logged into the back-office on Umbraco Cloud v. 8.1.5 the "view website" link on the content tab does not direct to the correct hostname you are logged into.

### Specifics
URL: https://www.ecesharedresources.net/umbraco#/content

### Steps to reproduce

Click "View Website" link

### Expected result

User would be taken to: https://www.ecesharedresources.net/

### Actual result

User is taken to https://ece-national.s1.umbraco.io
<img width="1434" alt="Screen Shot 2019-10-17 at 7 38 39 AM" src="https://user-images.githubusercontent.com/56683414/67009795-ff066e80-f0b1-11e9-8e53-97df80bf1c7e.png">

**Comment by nul800sebastiaan** [comment]
That behavior is on purpose. The only URL that we KNOW will work all the time is the one that refers to your project alias on umbraco.io.

We would recommend you hide the umbraco.io domain by adding a redirect, this will also help to make sure that search engine crawlers don't see the same content on two different URLs.

We've got some documentation for that here: https://our.umbraco.com/Documentation/Umbraco-Cloud/Set-Up/Manage-Hostnames/Rewrites-on-Cloud/#hiding-the-default-umbracoio-url
