### ISSUE TITLE
Checkbox value in Nested Content is not transferred to next environment

### ISSUE THREAD

**Issue by jonat123** [umbraco/Umbraco.Cloud.Issues#138]
When transferring a check box list in a nested content, the clicked value will not be transferred over to the next environment

Reproduction
------------
### Specifics
Umbraco 7.15.3
Forms 7.2.0
Deploy 2.1.0

### Steps to reproduce

- create one document type with a nested content and another one with a checkbox list
- Add the Checkbox list to the nested content
- Click some values off in the check boxes.
- First deploy the changes, then transfer the content nodes to the next environment
- Check if the value have been transferred

### Expected result
The clicked value in the check boxes have been transferred and no need to check them off again
![image](https://user-images.githubusercontent.com/54025331/67565834-a294f600-f726-11e9-988e-fb3fd15b4078.png)

### Actual result
The clicked value is not transferred and will need to checked off again
![image](https://user-images.githubusercontent.com/54025331/67565861-ae80b800-f726-11e9-8594-006b398602bd.png)

---
_This item has been added to our backlog [AB#6448](https://dev.azure.com/umbraco/243e7927-03b2-44e2-908f-d4ac7ea5daaa/_workitems/edit/6448)_

**Comment by nul800sebastiaan** [comment]
This probably needs to be fixed somewhere in the https://github.com/umbraco/Umbraco.Deploy.Contrib project. I'm surprised this has never been reported before though.

**Comment by clausjensen** [comment]
This issue is fixed in Deploy 2.1.1 being released on Tuesday May 26th.
