### ISSUE TITLE
Add "Visual C++ Redistributable Package for Visual Studio 2013" to all Umbraco Cloud servers

### ISSUE THREAD

**Issue by jerpenol** [umbraco/Umbraco.Cloud.Issues#139]
We would love to use Next-Gen image formats (like WebP) on our websites in Umbraco Cloud. 

It is possible to add a plugin to ImageProcessor to fetch images in WebP-format, unfortunately this plugin needs "Visual C++ Redistributable Package for Visual Studio 2013" to be installed on the server the website is running on.

Since the servers of Umbraco Cloud do not have this redistributable package installed, it is impossible to use the WebP-plugin for ImageProcessor, which is a shame.

It would be nice if this package could be added to the servers, because more and more of our clients ask for NextGen image formats on Umbraco Cloud, since it's an upcoming development. 

Another possibility is to offer us the option to host a website on a server that has this package installed.

**Comment by jerpenol** [comment]
WebP Plugin: https://imageprocessor.org/imageprocessor/plugins/webp/#about

**Comment by jmayntzhusen** [comment]
This is a bit strange, because when investigating our servers I couldn't find the package installed. However I just saw one of our Cloud users tweet about them using the plugin: https://twitter.com/skttl/status/1190001627249426434

Are we absolutely sure the plugin requires this package? Have you tried just adding the imageprocessor plugin to see if it works on Cloud? 🙂

**Comment by jerpenol** [comment]
I have tried it on a similar environment (so we don't break our development environment in Umbraco Cloud).

**Comment by skttl** [comment]
Heres a webp image from a cloud site https://www.jernbanemuseet.dk/media/1074/_fw64072.jpg?anchor=center&mode=crop&width=200&height=100&format=webp

**Comment by jerpenol** [comment]
What did you do when deploying the plugin to Umbraco Cloud then?

**Comment by skttl** [comment]
I just copied the dll into `bin` in my website folder (I think Nuget did it for me though)

**Comment by hfloyd** [comment]
I would also like to have access to "Visual C++ Redistributable" on an Umbraco Cloud site. I have some PDF generation functionality developed, but it requires a plugin. It works on my local dev environment, but not when I deploy to the Umbraco Cloud dev environment.

The plugin I am interested in is explained here: https://www.e-iceblue.com/Tutorials/Spire.PDF/Spire.PDF-Program-Guide/Convert-HTML-to-PDF-with-New-Plugin.html

**Comment by hfloyd** [comment]
@nul800sebastiaan Any chance this will get reopened?

**Comment by stefankip** [comment]
@hfloyd guess not ;-)

**Comment by RGV2ZWxvcGVy** [comment]
For those that didn't get it working.

What I did to get this to work on Umbraco Cloud (with Umbraco 8.18.3):

- Search the 'msvcr120.dll' file on your local system or download it.
- Add the DLL file to your bin folder on your local project (and include in Git, if necessary).
- Deploy your changes to your Cloud environment.
- Upload a new image to the media library of Umbraco.
- Go to the new image, and add '?format=webp' to the end of the url.
