### ISSUE TITLE
Special characters not translated properly

### ISSUE THREAD

**Issue by jonat123** [umbraco/Umbraco.Cloud.Issues#141]
When creating a content node with a language using æåø the URL link created is translating å = a and ø = o instead of oe and aa

Reproduction
------------

### Specifics
Umbraco 8.2.2
Forms 8.2.0
Deploy 3.1.5

### Steps to reproduce

- Add a nordic language like Danish or Norwegian
- Create a document type that you can use to create a content node
- Create a content node using special characters like æøå ex: _spørgsmål_
- Publish the content node

### Expected result
When creating a content node named this: 
![image](https://user-images.githubusercontent.com/54025331/68396606-1fd25900-0172-11ea-9f16-659df163d359.png)

 expected the URL to look like this: **umbraco/spoergsmaal-naemmer-fam/**

### Actual result
This is how the special characters in the URL is translated:
![image](https://user-images.githubusercontent.com/54025331/68396858-85264a00-0172-11ea-855c-7d2680ce08ba.png)

**Comment by nul800sebastiaan** [comment]
This is expected behavior that can be updated using the following config in UmbracoSetting.config:
https://our.umbraco.com/Documentation/Reference/Config/umbracoSettings/#requesthandler
