### ISSUE TITLE
Umbraco 8.2+ nuget dependencies not reflected in the 8.2.0+ builds

### ISSUE THREAD

**Issue by mistyn8** [umbraco/Umbraco.Cloud.Issues#142]
detail posted in the main umbraco-cms repo as also affects non-cloud deployments.

https://github.com/umbraco/Umbraco-CMS/issues/7125

**Comment by nul800sebastiaan** [comment]
Thanks, I'll close this since it's a core issue and not a specific Cloud issue.

**Comment by jmayntzhusen** [comment]
Think Sebastiaan forgot to hit the close button 😄 Will close.
