### ISSUE TITLE
Issue with initials for name in avatar

### ISSUE THREAD

**Issue by bjarnef** [umbraco/Umbraco.Cloud.Issues#143]
Hi..

I noticed and issue with the initials for the name in the "avatar" in Umbraco Cloud portal.
E.g. our company name "Ørskov Web" shows initials "RW" instead of "ØW".

It was a similar issue previous in Umbraco CMS which has been fixed: https://github.com/umbraco/Umbraco-CMS/pull/2240

![chrome_2019-11-17_15-31-32](https://user-images.githubusercontent.com/2919859/69054603-3b5c2000-0a0c-11ea-85c9-431a02374725.png)

**Comment by jmayntzhusen** [comment]
@bjarnef This has now been closed as it is being rolled out today 🙂

Thanks a lot for letting us know about this issue!
