### ISSUE TITLE
Postpone delete of project for 1 hour

### ISSUE THREAD

**Issue by MrLeeAustin** [umbraco/Umbraco.Cloud.Issues#145]
Hi, it would be a great feature if when you delete a project it is postponed / scheduled for an hour later so you can change your mind or if you delete the wrong project by mistake.

**Comment by nul800sebastiaan** [comment]
Hi @MrLeeAustin - I realize I forgot to update this one, sorry about that.

We have a few different measures in place to make you very aware as to what you are deleting while you're doing it, we feel that these are acceptable barriers. We do have a delay in projects being actually deleted (how long exactly I can't tell you) so if you ever feel like you did something you shouldn't have then reach out to support as soon as you realize your mistake.
