### ISSUE TITLE
Regional Deployment

### ISSUE THREAD

**Issue by c9mbundy** [umbraco/Umbraco.Cloud.Issues#146]
From the Umbraco-Cloud FAQ

### Can I choose which Azure Region my projects run in?
**No. All services currently run in the Azure West Europe region.**

Competing Cloud-Based products offer regional deployment, and provide the ability to select the deployment data-centre during site creation, and even transfer post-creation with the assistance of tech-support - e.g. WPEngine.

Regional-Deployment ability has long (always?) been a feature of MS-Azure, and their Data-Centres around the world.

Issues of latency, international bandwidth, data regulation and decentralization of failure points (the current one-out all-out scenario) are among the many reasons why I believe that regional deployment options for Umbraco Cloud should be seriously considered.

**Comment by nul800sebastiaan** [comment]
Our current setup unfortunately doesn't allow for this option. At some point we will be changing our setup and at that time of course high on the wish list is this feature. Not for the foreseeable future however, sorry.
