### ISSUE TITLE
Dev and staging environment always in debug mode after deployment

### ISSUE THREAD

**Issue by dawoe** [umbraco/Umbraco.Cloud.Issues#150]
After a deployment from local to development or from development to staging the environment has debug mode turned on after the deployment.

This is strange because I have config transforms in place that actually remove the debug attribute from the compilation tag in the web.config.

So the only option now is to turn off debug mode through the portal, which is a manual step which can be forgotten.

Even if I turn off debug mode through the portal the environment is back in debug mode after a deployment.

I would love to see my config transform applied or at least leave the environment in the debug mode I set through the portal after a deployment.

Dave

**Comment by nul800sebastiaan** [comment]
This is expected, we do set debug to true on purpose on this environments, overruling any transforms you have. 

Can you tell us more about why this is unwanted, why do you need to be in non-debug mode when you are in test environments? 

I'll have to refresh my memory with the Cloud team as to why we enforce this, it may not be all that necessary, but I can't remember, I'll ask around.

**Comment by dawoe** [comment]
Some use cases
The bundling and [minification framework](https://www.nuget.org/packages/Microsoft.AspNet.Web.Optimization/)  we use only does the bundling and minification when not running debug mode.

Same goes for the [html minifying](https://www.nuget.org/packages/WebMarkupMin.AspNet4.Mvc/) framework.

And for umbraco it self ...client side assets for the backoffice don't get bundled and minified by the client dependency framework.

Also ASP.NET performs better when not running in debug mode. See [https://weblogs.asp.net/scottgu/442448](https://weblogs.asp.net/scottgu/442448)

So turning debug off by default is better for Cloud.. less resources used

At the least I would expect the transforms I apply are respected.

Dave

**Comment by dawoe** [comment]
Hi @nul800sebastiaan 

Any news on this one ?

dave

**Comment by sitereactor** [comment]
Hey @dawoe this makes sense to me, and I'm pretty sure we could move the transforms around so the debug setting is not enforced, but rather something you can override if necessary.
I don't have a timeframe yet, as we just restructured some of our cloud teams, so we have our hands full untill after xmas.

**Comment by sitereactor** [comment]
Oh, and just to elaborate. Some settings are enforced because they are either best practice or environment specific and other settings are loosely enforced - meaning that you can override them with your own config transforms.

**Comment by nul800sebastiaan** [comment]
Hi @dawoe, going through some old issue reports. We are in the process of moving to an improved Cloud platform and that is going to be our main focus for the foreseeable future.

This feature request is really good and when we're done moving to the new platform we will are in a much better position to work on feature requests like this, we'll get back to at at that time.

**Comment by sajumb** [comment]
This older issue is related to CMS8 projects in Umbraco Cloud. For the newer versions based on .NET Core, debug mode is not controlled by Umbraco Cloud, but by configuration of Umbraco CMS. That is why we are closing this issue.
