### ISSUE TITLE
Automatically suggest your own IP on "Public access"

### ISSUE THREAD

**Issue by hartviglarsen** [umbraco/Umbraco.Cloud.Issues#153]
Currently if you go to _Connection Details_ on a project you are able to simply hit _Add now_ if your IP is not added firewall, e.g. 

![image](https://user-images.githubusercontent.com/4366314/71894246-fe7bf200-314d-11ea-9257-92f2858a8fbd.png)

After which your IP will be added.

It would be awesome if we had the same feature on _Public access_:

![image](https://user-images.githubusercontent.com/4366314/71894346-4733ab00-314e-11ea-92c9-e6e9097168c4.png)

It would make the interface more consistent and allow customers to add their IPs ever so slightly faster. :)

---
_This item has been added to our backlog [AB#5122](https://dev.azure.com/umbraco/243e7927-03b2-44e2-908f-d4ac7ea5daaa/_workitems/edit/5122)_

**Comment by nul800sebastiaan** [comment]
@ksuvec tells me this is happening quite soon, so I've put it up as a sprint candidate for him to sync onto his Azure board! 👍

**Comment by ksuvec** [comment]
This feature has now been released. Thanks for the input @hartviglarsen
