### ISSUE TITLE
Allow super admins to add themself to all projects in an organization

### ISSUE THREAD

**Issue by soreng** [umbraco/Umbraco.Cloud.Issues#156]
You need to have been granted (admin) rights on a given project to administer the team.

If you are admin / super admin in an organization, there is no way to use these powers to access projects. You need someone to give you access.

I suggest that organization super admins, get a button that grants them access to a given project in the organization.

**Comment by nul800sebastiaan** [comment]
Hi @soreng - we had a little chat about this and it would indeed be great, the only thing we're wondering is: would you expect the super admin just to be able to see all the project or would you expect them to be added as a user to all backoffices for those projects too?

**Comment by nul800sebastiaan** [comment]
Let me know when you have more to add Søren! 

For now I've put this on the list of things to work on when we are going to do portal updates in the future.

**Comment by soreng** [comment]
Hi @nul800sebastiaan 
Sorry for the late reply. I would imagine being able to login to the backoffice for those projects. Say we need to support a customer, and quickly need to access the backoffice (remove a page, deactivate a user etc). It would be great for us, not to need a user to be added in advance (since we always forget).

Hth :)

**Comment by adampnielsen** [comment]
> Let me know when you have more to add Søren!
> 
> For now I've put this on the list of things to work on when we are going to do portal updates in the future.
Initially the ability to see all projects in the organisation and what users are currently have access is perfectly fine. The main issue is that we can not get an overview of projects in any other way than via the invoice specification excel sheet you send once every month.

**Comment by jhauge** [comment]
Since this is something discussed in a context of providing capabilities for orgs with lots of projects, and hence with fairly extensive needs and resources I think an API solution without UI could go a long way. An API could lend itself nicely to scripting solutions in various scripting languages like Powershell, bash or in console apps.  All that's missing in order to build a scripted solution that could do what is requested here would be an API endpoint along these lines

`GET umbraco.io/api/public/project?orgid=xxxx`

Returning 

```
[
  {
    "url": "...",
    "alias": "...",
    "users": [
      { "email": "xx@zz.yy", "isAdmin": "false", "furtherprops": "" },
      { "email": "nn@zz.yy", "isAdmin": "true", "furtherprops": "" }
    ]
  },
  { ... }
]
```

**Comment by stefankip** [comment]
We got converted to an organization account today and I thought it would be much easier to give team members access to projects. Then I found out an admin or super admin doesn't get access to the projects OOTB, which I find mind blowing.
I've invited a development team account to use in our CI/CD set-up for deployments, but we still have to give this account access to all project manually.
Not something I'd prefer.

**Comment by FransdeJong** [comment]
+1 for this feature.

When one of my colleagues is suddenly ill and we need to take over I need to call them and ask them to add me to the project.
Also if someone accidentally adds a professional subscription there is no way for me to find out until the next invoice. That seems very strange...

I think a super admin should be added as a user to all projects that are added to the organisation. That way we can always see what is happening and invite another dev in case of emergency.
