### ISSUE TITLE
Merge conflict when pushing upgrades to child projects

### ISSUE THREAD

**Issue by jmayntzhusen** [umbraco/Umbraco.Cloud.Issues#16]
When setting up a baseline site with some child sites a merge conflict occurs when pushing out changes. It seems to be related to having added an extra environment on the child site.

Reproduction
------------
I set up some brand new sites with no content for testing purposes, wrote down step for step what I did:

1. Create starter plan with v7.10 (just so I had a site I could upgrade, had a similar issue when testing with 7.9 and haven't tried other versions - don't think it is a version problem)
2. Create starter plan child of baseline
3. Add Dev env to child site
4. Deploy the dev env's changes to live on child site
5. Add dev env to baseline site
6. Deploy the dev env's changes to live on baseline site
7. Press upgrade button on baselines dev env
8. Deploy upgrade from dev to live on baseline
9. Go to manage child projects push upgrade to child
10. Get merge error - 1 uncommitted change would be overwritten by merge 

The file creating the merge conflict seems to be umbracoDeploy.config which was also the the only file changed when adding environments on step 4 and 6.

Following https://our.umbraco.com/documentation/Umbraco-Cloud/Getting-Started/Baselines/Baseline-Merge-Conflicts/ resolved the merge conflict and successfully upgraded the child site, but the error shouldn't have been there in the first place.

**Comment by mikkelhm** [comment]
x uncommitted changes will be overwritten by the merge

We had a issue where some projects would run into issues, when trying to update a child project from a baseline, where the baselinechild service would end with a "xx uncommitted changes would be overwritten by the merge"
This would normally indicate that the repository had files that were modified, but not committed. But when going into the repositories afterwareds, we were unable to see that anychanges had been made. `git status` showed no changes. cloning down the repository showed nothing wrong with the repository, and no changes as well. Installing git portable on the server, and trying git status from there, also didnt show anything wrong. 
We created a console application that would use ligbit2sharp, which is the library we are using for git operations in the baselinechild service, and make it do its git status, and when doing it via this library, it would show that the repository had modified files in it. normal git in a bash still didnt show any changes. 

After lots of time spent on figuring out what could be wrong, we found that the change in the files were line endings! so the files that libgit were seeing as changed, had their linendings changes, while git in a bash didnt see this as a change. 

Looking at the git documentation, we found that the setting `core.autocrlf` controlling how to handle lineendings - its ment to be set on windos machines, as windows handles lineendings different than linux machines. What tricked us in our tests is that using git from bash would default the setting to `true`, the same as using git that is installed on the webworkers(what we can use in Kudu), it had the setting set.
libgit2sharp is able to read global git configuration, if git is installed on its default locations - on Azure pack its not. This means that libgit2sharp would default the setting to `false`, meaning that lineendings changes would be seen as modifications in the repositories.

Why would we start to see these changes now then?
One of the reasons is that when we migrated from AppVayer to AzureDevops for building UmbracoCms, we also altered the lineendings, this hasn't been an issue untill now! When people upgrade older versions to the newer versions, everything will work, but when the baselienchild updatere becomes part of the mix, then if a file has been changed between the baseline and the child, we will end up in a conflict.

The solution is to explicit set the setting on our repositories on Umbraco Cloud, this will ensure that we control the setting on all the repositories that we have running. This has been done for all new projects on Umbraco Cloud, and we run a script that will update the setting for all existing projects as well.

**Comment by mikkelhm** [comment]
To review this - walk through the step-by-step guid that @jmayntzhusen provided, and ensure that it doesn't end up in the described error.

**Comment by sitereactor** [comment]
@mikkelhm do you need any kind of internal review of this or is it more about getting an update scheduled so this change is applied to all git repositories?

**Comment by mikkelhm** [comment]
this has all been deployed (months ago)and updated to all cloud sites - closing
