### ISSUE TITLE
Environment variables in transforms

### ISSUE THREAD

**Issue by sussexrick** [umbraco/Umbraco.Cloud.Issues#164]
I would like to avoid putting secrets into source control. On other services this is typically managed by setting environment variables. In Umbraco Cloud we can have settings for each environment but, since secrets are typically in *.config files, they have to be in transform files that we check into source control. If we don't check them in they don't get deployed.

Since each Umbraco Cloud environment appears to be an instance of Azure web apps, the application settings feature of web apps already provides a way to manage key/value pairs on a per-environment basis. They are encrypted at rest and made available automatically as environment variables. If the Umbraco Cloud management website used the Azure API to replicate the interface for adding/updating/removing application settings, you would have good support for environment variables.

To use these in transforms you'd just need a standard step on deployment. For each transform file you discover for the current deployment, loop through the application settings for the current environment and search and replace a token in the transform file, then run the modified transform. The token could be a typical environment variable format like ${MY_VARIABLE}.

**Comment by nul800sebastiaan** [comment]
Umbraco Cloud doesn't exactly run on Azure web apps, but I understand why it might look like it. Therefore, we unfortunately don't have the feature where we can manage secrets or key/value pairs. 

It is something that is on our wishlist to offer at some point, but we don't have it on the roadmap at the moment. The best we can offer right now is the suggestion to make use of Azure Keyvault,

I'll put this issue on the `idea` list, we have made a comitment to regularly review issues labelled as ideas and we will be sure to consider this along with those.

**Comment by idseefeld** [comment]
Any news for this topic regarding new (current) cloud infrastructure or the possibilities of Umbraco version 9.x / 10.x and .Net6?

**Comment by sajumb** [comment]
We will soon begin the development of a new secret management feature, where a user in the Umbraco Portal for each environment will be able to store secrets in Azure Key Vaults and have them served as environment settings during runtime. This feature is expected to land in the fall of 2022.

**Comment by mclausen** [comment]
I believe we already got this 😉
