### ISSUE TITLE
Partial restore without children

### ISSUE THREAD

**Issue by FransdeJong** [umbraco/Umbraco.Cloud.Issues#166]
Correct me if I'm wrong but I can't find a way to restore the homepage of a site without having to restore the entire site.

It would be a handy adition if there was a "include children" checkbox in the restore prompt. Now I have to wait for minutes to get the homepage restored and it will fail if one of the child or grandchild pages has a content error on it.

**Comment by nul800sebastiaan** [comment]
As far as I know, partially restoring a child node of the homepage will require the creation of the home page too. Have you tried to restore just the child node(s) that you need?

**Comment by FransdeJong** [comment]
Sorry, I meant it a little different.

I have a site structure where the root node (in my case) has to be restored from live.
What I do is a partial restore on the home node.

What I expect is that the home node and maybe refereed nodes are restored from live.
What actually happens is that the entire site is restored.

With a large site this takes up a lot of time.

Does that sound more logic?

**Comment by nul800sebastiaan** [comment]
Sure, but I don't think we have that feature at the moment. I'll have to talk to someone at HQ and get back to you (note: they're on holiday this week so it might take a little while).

Meanwhile, how about you work around it? Restore a child node of the home node, preferably a child node with few or no descendants. Then only those few nodes will be restored.

**Comment by c9mbundy** [comment]
I've encountered the same issue, and while it's not a show-stopper, it can be a frustrating. You want to restore just the home-page, but end up having to restore the entire site. Ideally, what it would offer is a tree dialog so you can mark child nodes to include/exclude when restoring the selected node - same as you would encounter when restoring a backup. That way you could select a node to be restored and disable restoring some or all of its child nodes e.g. just restore a home-page if that's all you wanted.

**Comment by emma-hq** [comment]
Hey @FransdeJong,

Thanks for raising this issue! We've implemented a toggle to include children or not to include children so I'll close this issue.

![image](https://user-images.githubusercontent.com/78740801/109822364-c88dad00-7c2e-11eb-8249-d35b17025435.png)

Emma
