### ISSUE TITLE
Missing email invitations for users

### ISSUE THREAD

**Issue by Jay-umbr** [umbraco/Umbraco.Cloud.Issues#170]
When inviting a user to a Cloud project via the Edit Team option, the invitation does not always get delivered to the inbox.

Reproduction
------------

Cannot really pinpoint why this happens and it is difficult to reproduce - some users report it happens to them more often than for the others.

### Bug summary

After inviting a Cloud user to an umbraco.io project (for both new and existing users) sometimes the invitation email does not make it to the recipient's inbox. Happens for both usual and admin users.
The recipient does however receive an invitation on the Cloud portal itself.

### Steps to reproduce

Create a new Umbraco cloud project, navigate to the project page, open "Edit team" menu, invite a new user to the project, specify the email to send the invite to

### Expected result

The recipient receives an email invitation.

### Actual result

Sometimes, the email is not delivered.

**Comment by tyradeveloper** [comment]
We tested this on 11.02.2020 with to different emails belonging to the same domain - one received invitation to the portal, the other one did not - not in spam or similar.

**Comment by Jay-umbr** [comment]
On the same note - because the new users sometimes do not get the initial activation email with activation token, their accounts **have to be activated manually by Support** staff. That is, once again, not great user experience

**Comment by nul800sebastiaan** [comment]
We'll need to look at individual invites that are failing to get an idea of why this is, do you have a list @Jay-umbr that you can share with @sitereactor?

**Comment by nul800sebastiaan** [comment]
I'll close this for now, since we haven't hear of this happening again. Please contact @ksuvec direclty if this happens again so his team can investigate.
