### ISSUE TITLE
Make it possible to break connection between baseline and child

### ISSUE THREAD

**Issue by skttl** [umbraco/Umbraco.Cloud.Issues#176]
We use a starter-kit like baseline for most of our projects, and because we want to be able to upgrade them without getting all the changes from baseline, we need to orphan the child projects.

Currently this is done by getting in touch with support, but it would be nice if it was possible to do from the portal.

**Comment by nul800sebastiaan** [comment]
Thanks @skttl - it's certainly a good feature request, I am not sure if all user types should be able to do this, I would think it makes sense to limit that to Admins, right?

We don't have immediate plans to implement this one but I'll put it on the list of things to consider when we're working on baseline features! 👍

**Comment by sajumb** [comment]
Thanks @skttl. We have created a task for this issue in the product backlog for the Cloud Feature Team, and we expect it to be included in one of the upcoming sprints.

**Comment by sajumb** [comment]
We have completed this feature request  The feature has the (yet unpublished) release noted added to it.

**Break reference between baseline and child project**
Umbraco Cloud Portal offers a powerful baseline-child relationship between projects. It is very similar to a fork (forked repository) on GitHub in that we create a clone of an existing project while maintaining a connection between the two projects.

If you at some point want to break this connection between the baseline and one of its child projects it is now really easy for an user with the role of admin to do so. But please be aware that the action can not be undone.

![Break reference between baseline and child project](https://user-images.githubusercontent.com/93588665/148965794-cf198874-7618-46a0-aa1c-40bbd270445d.gif)
