### ISSUE TITLE
On the dashboard, make it obvious that a website is  NOT owned by the current account.

### ISSUE THREAD

**Issue by AnthonyCogworks** [umbraco/Umbraco.Cloud.Issues#18]
We have admin access to our clients websites via our login. There is no way for us to see which website is owned by our account.

Please make it obvious that an Umbraco Cloud site is NOT owned by our account.

**Comment by nul800sebastiaan** [comment]
@AnthonyCogworks  Thanks for your feature request. We'll need to discuss this some further and will get back to you when we've done so.

In the mean time, can you clarify why you want this feature?

**Comment by sajumb** [comment]
We have added an organization page with all the projects of the organization. We believe that this is sufficient. Also, we have not heard a similar feature request since the original post. Accordingly, we are closing this issue.
