### ISSUE TITLE
Show more info on project overview

### ISSUE THREAD

**Issue by FransdeJong** [umbraco/Umbraco.Cloud.Issues#183]
It would be really helpful if the project files on the dashboard showed more info.

Things I'd like to see:
- version numbers of umbraco, forms and deploy (https://github.com/umbraco/Umbraco.Cloud.Issues/issues/127)
- Environments: can be just a number
- Error state of development in project

Example 1:
The dev environment of one of the projects has a deployment issue. I cant spot that in the overview.

Example 2:
I'm checking the invoice against my projects. I have to go and click on a project to find out if a extra environment is active

This information is visible on the project detail page so it could be showed on the overview to?

If we would also have the option for a listview (https://github.com/umbraco/Umbraco.Cloud.Issues/issues/46) than we could even filter on this information.

Is this something you are considering?

Thanks!
Frans

**Comment by nul800sebastiaan** [comment]
Thanks, these features are all basically covered in #46 - it's on our ideas list for future updates to the overview, but we have no immediate plans at the moment. I'll close this one as a duplicate but when reviewing the feature requests this one is linked to #183 so we'll also again go through the features you're describing here.
