### ISSUE TITLE
Portal uses proxy IP in SQL Azure firewall rules

### ISSUE THREAD

**Issue by ronaldbarendse** [umbraco/Umbraco.Cloud.Issues#184]
The Umbraco Cloud portal has a bug in the SQL Azure firewall rules panel that causes it to add the Cloudflare IP when clicking 'Add now'. 

Reproduction
------------
Go to the 'Connection details' page of a project and click the 'Add now' link:

![SQL Azure firewall rules](https://user-images.githubusercontent.com/1051287/75992525-62c1f480-5ef8-11ea-8c6c-721bf6a8741c.png)

Instead of adding your current IP, it adds the proxy IP instead. Even when the list already contains your IP, it still show the message 'Your IP address is not on the list'.

So besides using the `Request.UserHostAddress`, it should also parse the `X-Forwarded-For` header (that can contain multiple IPs: https://en.wikipedia.org/wiki/X-Forwarded-For).

This bug is introduced when Umbraco HQ added Cloudflare in front of the portal (not sure when, but I know it worked previously), but it has never worked correctly for clients that are behind a company proxy.

**Comment by sitereactor** [comment]
@ronaldbarendse Thanks for reporting that. It's an oversight on our part. We'll get it fixed in the next update roll-out of the Portal.

**Comment by ksuvec** [comment]
@ronaldbarendse 

Thanks for the error report and thanks for the fix suggestion. That helped us a lot to get this in order. It has now been fixed and released.
