### ISSUE TITLE
Changing default language does not correctly update UDA files

### ISSUE THREAD

**Issue by ronaldbarendse** [umbraco/Umbraco.Cloud.Issues#188]
After changing the default language (from the back-office), only the UDA file for the new default language is updated. The UDA file for the old default language is not updated, so both UDA files contain `"IsDefault": true`, which causes the deploy artifacts to be inconsistant (probably setting the default language to the last language that's processed).

As workaround, it's possible to run a full deploy export (by adding the `data\deploy-export` marker file), so all UDA files are updated and consistant again. This is easily forgotten however, causing problems when deploying the change.

Reproduction
------------
### Specifics
Umbraco 8.5.5
Umbraco Deploy 3.4.2

### Steps to reproduce
Change default language and check `IsDefault` in the `data\language_*.uda` files.

### Expected result
Both UDA files should be updated, so only one language is set as default.

### Actual result
Both old and new language UDA files are flagged as default.

---
_This item has been added to our backlog [AB#5984](https://dev.azure.com/umbraco/243e7927-03b2-44e2-908f-d4ac7ea5daaa/_workitems/edit/5984)_

**Comment by ronaldbarendse** [comment]
There's another problem when switching default languages and deploying the changes: when the previous default language is processed first, Deploy tries to set it to non-default and you get this error: `Cannot save the default language (en) as non-default. Make another language the default language instead.`

So besides updating both UDA-files, the deployment should also be done in 2 steps: first deploy all languages (without changing the default) and then set the default language. An additional check could be done when updating the default language to see if multiple languages are marked as default (in the UDA-files), so inconsistent metadata isn't deployed (this could also be caused by merge conflicts).

**Comment by clausjensen** [comment]
Initial issue is fixed in: https://github.com/umbraco/Umbraco-Deploy/pull/463

For the second part added in the comment above - please create a separate issue 👍

**Comment by warrenbuckley** [comment]
Is fixed in this Deploy PR due for 3.5.2 patch

**Comment by ronaldbarendse** [comment]
> For the second part added in the comment above - please create a separate issue 👍

I've created a new issue for this: https://github.com/umbraco/Umbraco.Cloud.Issues/issues/285.
