### ISSUE TITLE
IPv6 addresses are not working for public access whitelist

### ISSUE THREAD

**Issue by idseefeld** [umbraco/Umbraco.Cloud.Issues#192]
On the _Public access_ settings page you have the option to add your current IP address.
If you have an IPv6 address assigned this might be taken and gets added to the list correctly.
But it does not prevent the basic authentication dialog, when you browse the site.

I have added the IPv4 address manually and it works as expected.

Yours
Dirk

**Comment by nul800sebastiaan** [comment]
Thanks @idseefeld, sorry for the delay in getting back to you. A change has now been rolled out to only accept ipv4 addresses. At this time we can't support ipv6 addresses, see issue #210 for more info.
