### ISSUE TITLE
Public access settings are not working for added environments

### ISSUE THREAD

**Issue by idseefeld** [umbraco/Umbraco.Cloud.Issues#193]
Yesterday 2020-03-08 I have added a new development environment to my existing project.
Today I have noticed, that the environment was not protected by basic authentication.

On the _Public access_ settings page basic authentication was on and no IP was in the Whitelist.
Same was true fore Live-Site. 

I cannot tell you for sure, that I have ever changed the _Public access_ settings for the initial Live environment. But I guess not, because it had been public and I was not aware of the _Public access_ settings.

I toggled the setting for both sites and after this it worked as expected.

Yours
Dirk

**Comment by nul800sebastiaan** [comment]
Hey @idseefeld - sounds pretty strange. I would say that we'd have a lot more reports of this problem if it was an actual bug, seems like it works for everyone else. So if you can reproduce and have some steps for us to go through then we can try to see if there's anything wrong, let us know! 👍
