### ISSUE TITLE
UI: Update hostnames to report correct custom domains number

### ISSUE THREAD

**Issue by Jay-umbr** [umbraco/Umbraco.Cloud.Issues#200]
Spotted on starter projects, might be the same on others.
![image](https://user-images.githubusercontent.com/56038614/80101916-5c540e80-8572-11ea-96bc-51b14261496e.png)
as marketed on Pricing page (starter)
vs on Hostnames menu
![image](https://user-images.githubusercontent.com/56038614/80101985-70980b80-8572-11ea-8f78-be61b2b349ef.png)

**Comment by ksuvec** [comment]
thx @Jay-umbr this has been fixed and released
