### ISSUE TITLE
Umbraco.Web is not updated when autoupdating

### ISSUE THREAD

**Issue by FransdeJong** [umbraco/Umbraco.Cloud.Issues#201]
It looks like the Umbraco.Web nuget reference isn't updated when updating a project on Cloud.
I have to manually update the Umbraco.Web package in the web project.

This makes auto updating not so auto.

**Comment by nul800sebastiaan** [comment]
Ah yeah, I guess we didn't use to have that one on v7 and it seems we forgot to add an update for that new nuget package. I'll see what we can do 👍

**Comment by sitereactor** [comment]
@FransdeJong Can you clarify the version upgrades involved? That would help us narrow it down 😄 
'From version to version' would be sufficient, thanks!

**Comment by FransdeJong** [comment]
I've had it on every V8 update up until now.
It updates the files on cloud but not the reference. This creates issues when working in visual studio.

**Comment by sitereactor** [comment]
Thanks, I found that we haven't updated package.config for v8 as a new nuget was introduced. I was unfortunately not aware of this, but its now scheduled for update.
We will get to this as part of the next sprint (136).

I will report back once its been rolled out, which should ideally be done before next CMS update.

**Comment by FransdeJong** [comment]
Great! Thanks for the quick followup!

**Comment by mikkelhm** [comment]
Hi @FransdeJong 

We updated the upgrade process on Umbraco Cloud so it now includes updating the packages.config for the UmbracoCms.Web package as well as the other packages. This should solve the issue you've been experiencing. 

Thanks for reporting the issue 💪 ❤️
