### ISSUE TITLE
Sort order of allowed child node types is not correctly exported

### ISSUE THREAD

**Issue by ronaldbarendse** [umbraco/Umbraco.Cloud.Issues#203]
I just noticed the sort order of allowed child node types is not correctly deployed between environments, so when the following is configured locally:

![Local](https://user-images.githubusercontent.com/1051287/81346806-3a52a400-90bb-11ea-8199-f12fe07a3ef6.png)

After deploying to Umbraco Cloud, the order isn't the same:

![Live](https://user-images.githubusercontent.com/1051287/81346764-25761080-90bb-11ea-8c48-99280208dff1.png)

This order is used in the Create dialog and having a consistent and logical order makes it easier/faster to create the correct type of content:

![Create menu](https://user-images.githubusercontent.com/1051287/81347220-ff9d3b80-90bb-11ea-90c6-b9f8a2cd8a1d.png)

Looking at the UDA-file, it looks like the correct order isn't exported. It is equal to the deployed version though, so it probably does change the order on deployment (the Text document type is last, instead of first):

```json
{
  "Permissions": {
    "AllowedChildContentTypes": [
      "umb://document-type/8f22e21c8de844c7ae8923e5ceb6081d",
      "umb://document-type/bbce61dac03245febe7c19b09416278b",
      "umb://document-type/bf1653da267d467bb3483ab564858e82",
      "umb://document-type/d074202650df4775b5ad1b6770408df4",
      "umb://document-type/f2aee0a720b94fa88cc41a825edebccd"
    ]
  },
  "Udi": "umb://document-type/f2aee0a720b94fa88cc41a825edebccd",
  "Name": "Text",
  "Alias": "text"
}
```

Reproduction
------------
Umbraco 8.6.1
Umbraco Deploy 3.4.4

---
_This item has been added to our backlog [AB#6728](https://dev.azure.com/umbraco/243e7927-03b2-44e2-908f-d4ac7ea5daaa/_workitems/edit/6728)_

**Comment by ronaldbarendse** [comment]
Correctly sorting of entries in the UDA-files would also be beneficial for dictionary items, as I've seen the order of translations are also random (probably based on the order of returned languages from the database) and therefore causes unneeded changes in the files.

To summarize this issue: all arrays within the UDA-files should have a predictable order (e.g. `AllowedChildContentTypes` should equal the order within the back-office and translations sorted on language code).

**Comment by viralpayload** [comment]
I was referred to this thread by Dennis at Umbraco HQ after a text chat. I'm having a similar issue though, in my case, it relates to content rather than allowed child nodes. When I transfer content from my local environment to the Umbraco Cloud, many of the items will be re-arranged during the transfer. Now, after every deployment, I have to go to the Cloud and re-order about 30 items in various places in the content tree. Here's the most recent example from Aug 3 2020. On the left is the order locally. On the right is the order after I queue and transfer to the cloud.

![image](https://user-images.githubusercontent.com/3611260/89288606-ed338f00-d623-11ea-9ee8-156c67d00a56.png)

**Comment by ronaldbarendse** [comment]
@viralpayload Content is deployed differently then metadata (that's stored in UDA files) and is also explicitly sorted by the `sortOrder` property, so you're experiencing a different issue. Maybe this is caused by a bug in Umbraco that sets the sort order of new content/media to 0 (instead of correctly incrementing): https://github.com/umbraco/Umbraco-CMS/issues/8359.

**Comment by clausjensen** [comment]
This is fixed in the upcoming release of Deploy (3.5.3)

**Comment by ronaldbarendse** [comment]
When using Umbraco Deploy 3.5.3 (local and on the Live environment), I'm now getting schema mismatches on all document types that contain multiple allowed child node types when restoring content from Live to local:

![Full restore - Schema mismatch](https://user-images.githubusercontent.com/1051287/101493066-d69c9c00-3965-11eb-835c-32fe33bdef68.png)

I've even exported all deploy artifacts on Live and compared them to the local files, but there are no changes. The order is correct on both enviroments though, so it seems like only the checksum is generated/compared without taking the order of the allowed child node types into account (causing the mismatch)...

As workaround I've temporarly excluded document types from local deployment by adding this to the `UmbracoDeploy.Settings.config` file:
```xml
<excludedEntityTypes>
    <add type="document-type" />
</excludedEntityTypes>
```

**Comment by ronaldbarendse** [comment]
On a side note: the technical details doesn't contain the mismatches:
```
-- EXCEPTION ---------------------------------------------------
 (proper exception traces at the end of this log)
Umbraco.Deploy.Exceptions.RestoreSchemaMismatchException: Schema mismatch between environments. See 'Mismatches' for details.
----------------------------------------------------------------

EXCEPTION:

Umbraco.Deploy.Exceptions.RestoreSchemaMismatchException: Schema mismatch between environments. See 'Mismatches' for details.
   at Umbraco.Deploy.Work.WorkItems.DeployRestoreWorkItemBase.<ValidateManifest>d__19.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Umbraco.Deploy.Work.WorkItems.TargetRestoreWorkItem.<Proceed>d__16.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Umbraco.Deploy.Work.WorkItems.TargetRestoreWorkItem.<ExecuteAsyncSub>d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Umbraco.Deploy.Work.WorkItems.TargetRestoreWorkItem.<ExecuteAsyncSub>d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Umbraco.Deploy.Work.WorkItems.TargetRestoreWorkItem.<ExecuteAsync>d__14.MoveNext()
```

And the exception isn't logged and the error only contains a very generic `Deployment failed.` message:
![Log Viewer](https://user-images.githubusercontent.com/1051287/101496700-5cbae180-396a-11eb-9db8-3c157a46d563.png)

**Comment by jmayntzhusen** [comment]
Hey @ronaldbarendse 

I cannot reproduce this issue on the Deploy 3.5.3, would you mind reaching out to the support team so we can have a closer look at this? 🙂
Just reference this message and get it escalated straight away.

**Comment by ronaldbarendse** [comment]
Looks like I'm not the only one having this issue: https://github.com/umbraco/Umbraco.Cloud.Issues/issues/290.

Deploy is only saving the correct order when saving the document type from the back-office. When doing a full export (using the `deploy-export` marker file), the order is incorrect!

This is quite easy to replicate:
- Change the order of allowed child node types and save the document type in the back-office
- The UDA-file is updated and has the correct order
- Do a full export (`deploy-export` marker file)
- The UDA-file is updated with the incorrect order (while the order in the database/back-office is still correct)

Deploying the metadata (`deploy` marker file) at this stage does change the order in the database/back-office (at least that indicates this feature _does_ work), but that would mean just running a deploy-export and deploy would actually change the order!

**Comment by stefankip** [comment]
Having the same issue. Umbraco cloud support states:

> Yeah unfortunately this is a bug in deploy right now so we need to use the partial restore for now
