### ISSUE TITLE
Heartcore - access to repo

### ISSUE THREAD

**Issue by davidwandar** [umbraco/Umbraco.Cloud.Issues#205]
It would be nice to have access to the git-repo of a Heartcore-site. To inspect and change configurations and such.

**Comment by sitereactor** [comment]
Hi @davidwandar thanks for submitting your request. Umbraco Heartcore is a fully managed software as a service offering, so we cannot give access to things that are Internal in this context.

If there are specific settings or configuration you would like to see exposed in the UI we can check if that is something we can expose in one way or another.
