### ISSUE TITLE
Naming convention of child config transformation files

### ISSUE THREAD

**Issue by MichaelNielsenDK** [umbraco/Umbraco.Cloud.Issues#21]
As described here
https://our.umbraco.com/documentation/Umbraco-Cloud/Getting-Started/Baselines/Configuration-files/#handling-configuration-files 

naming convention for child config transformation files is

[child].[configfilename].[environment].xdt.config

It would be better if it was

[configfilename].[child].[environment].xdt.config

That would make sure that the files are listed together in a folder or file list view.

**Comment by MichaelNielsenDK** [comment]
An alternative to this, could be that Cloud looked in a folder called /Config-Transforms, that way the file system would not be cluttered with transform files for different environments and children.

**Comment by ronaldbarendse** [comment]
@MichaelNielsenDK Even better would be if the transform files could be stored out of the repository and in a vault (per environment), so passwords and API keys don't have to be added to the source code.

Alternatively, adding environment variables (also stored securely and per environment) would make most environment/child transforms obsolete, as you could add a single transform using the variable. This actually already happens with the database connection string and is supported OOTB by Azure: https://docs.microsoft.com/en-gb/azure/app-service/web-sites-configure#app-settings.

**Comment by nul800sebastiaan** [comment]
Hi @MichaelNielsenDK, going through some old issue reports. We are in the process of moving to an improved Cloud platform and that is going to be our main focus. Featu

**Comment by nul800sebastiaan** [comment]
Hi @MichaelNielsenDK, going through some old issue reports. We are in the process of moving to an improved Cloud platform and that is going to be our main focus. This feature request and @ronaldbarendse's suggestion are really good and we like it. As soon as we have the new platform in place we can look at updates to transforms and investigate how we can work with KeyVault or secrets per project. 👍
