### ISSUE TITLE
Umbraco Deploy 2.1.1 adds empty [deploy] application/trees

### ISSUE THREAD

**Issue by ronaldbarendse** [umbraco/Umbraco.Cloud.Issues#213]
I've update an Umbraco 7.15.5 project with the latest Umbraco Deploy 2.1.1 (from the nightlies builds URL) and when running the site, it adds the following application and trees:

```xml
<?xml version="1.0" encoding="utf-8"?>
<applications>
   ...
   <add alias="deploy" name="Deploy" icon="icon-car" sortOrder="15" />
</applications>
```
```xml
<?xml version="1.0" encoding="utf-8"?>
<trees>
   ...
   <add initialize="true" sortOrder="0" alias="externalMedia" application="deploy" title="Remote Media" iconClosed="icon-folder" iconOpen="icon-folder-open" type="Umbraco.Deploy.UI.Tree.ExternalMediaTreeController, Umbraco.Deploy.UI" />
   <add initialize="true" sortOrder="0" alias="externalContent" application="deploy" title="Remote Content" iconClosed="icon-folder" iconOpen="icon-folder-open" type="Umbraco.Deploy.UI.Tree.ExternalContentTreeController, Umbraco.Deploy.UI" />
</trees>
```

This section isn't added to the admin group by default, but if I give access, it just shows an empty section:
![Deploy section](https://user-images.githubusercontent.com/1051287/82817526-6c2a7f80-9e9d-11ea-981a-2051e36a5f65.png)

Reproduction
------------
### Steps to reproduce
- Install Deploy 2.1.1
- Start website
- Check modified `application.config` and `trees.config`
- Give current user access to the `[deploy]` section
- Reload backoffice and go to the newly added section: it's empty (and doesn't provide any 

### Expected result
No additional, useless section.

### Actual result
The application/trees are added every time the site boots, so it's not possible to remove the section.

**Comment by nul800sebastiaan** [comment]
Thanks @ronaldbarendse, as you have already discovered, the Deploy section does absolutely nothing. As far as I know it's a workaround for being able to pick items from remote trees. We should add a dashboard at some point saying something like: "sorry, there's nothing here, you don't need to enable this section".
