### ISSUE TITLE
UDAs are not generated/updated consistently on Cloud environments

### ISSUE THREAD

**Issue by Jay-umbr** [umbraco/Umbraco.Cloud.Issues#216]
Umbraco Deploy uses UDA files to keep track of changes in datatypes, document types etc. between environments.
The issue is, sometimes the UDAs fail to update accordingly and do not match the database records, in which case they could cause Deploy issues such as schema mismatches or "Could not find parent with id...".

I have found that even when there's no particular deployment errors (just by running the echo>deploy-export out of curiosity on my own test project) a lot of additional UDA files can be generated, which means they were not created there in the first place when some document types etc. were added.

Reproduction
------------

Not always easy to reproduce, though I have seen it happen on a lot of projects in our support cases - and some of those cases would not have been opened if not for the out-of-sync UDAs.

### Bug summary

    * UDAs are not always generated when saving metadata in the database
    * I could not pinpoint the exact cause
    * I suspect it has something to do with the saving action in the backoffice

### Specifics

* It seems to happen on all versions of Cloud projects
* It seems to be closely related to the saving action in the backoffice

**Comment by nul800sebastiaan** [comment]
Thanks @Jay-umbr, there's really nothing we can do without specific steps to reproduce the problem though. If you can cause the error and make it go away with a `deploy-export` then we need to know which uda files was the magic one, then we can look at what went wrong.

So feel free to update when you have specifics, but for now I'll close this one until something can be reproduced.
