### ISSUE TITLE
Umbraco Heartcore to parse internal links before returning rich text

### ISSUE THREAD

**Issue by marcusjroberts** [umbraco/Umbraco.Cloud.Issues#219]
When using the RTE and a user adds a media image or a link to another page in Umbraco, the link is written into the Rich Text response as either a `localLink:umb://document`

`<a href=\"/{localLink:umb://document/1178b12bcf364064b7dd92cd4c5a8f19}\">`

or as `umb://media`

`<img src=\"?width=500&amp;height=320\" alt=\"\" width=\"500\" height=\"320\" data-udi=\"umb://media/2905f194571b46dcb1ac26bc94a247db\" />`

neither of which are particularly useful to my bespoke front-end app. In the normal Umbraco I have access to the function `ParseInternalLinks` which lets me render the Rich Text and not worry about these links as they'll be parsed and written out in full as their current correct URL.

For the content to be returned by the Heartcore API like this is not very useful. I propose it's either changed outright to undergo `ParseInternalLinks` before the content is returned via the API, or a parameter is added to the API calls to indicate whether links should be parsed or not.

Without this, right now, we will have to identify every `umb://document` and `umb://media` link in our rich text responses and make a separate call to the Heartcore API in order to ascertain the "normal" URL to use in these link and image tags.

**Comment by sitereactor** [comment]
Hi @marcusjroberts which API and endpoint(s) are you using yo retrieve the content?

**Comment by marcusjroberts** [comment]
Sure thing!

`https://cdn.umbraco.io/content/url?url=/path/to/node/`

**Comment by sitereactor** [comment]
Thanks, I'll run some tests and report back. FWIW the output of the RTE is supposed to have the rendered values when fetched through the Content Delivery API.

There is the odd chance that its a caching issue, as the media tag you wrote looks correct apart from missing the path to the media file. The data-udi tag is only "extra" information.

**Comment by marcusjroberts** [comment]
Hi there! On further inspection it seems to only happen when the RTE is in the Grid, as opposed to being a native property on a node. Does that make a difference? Would seem to be a bug in that case, right?

**Comment by sitereactor** [comment]
I know we had issues with this in the old headless beta version, but I believe it was resolved for Heartcore.
Are you using the Depth parameter for getting additional levels of Content/Media?

**Comment by marcusjroberts** [comment]
Thanks @sitereactor, have had a quick test in the API browser but the depth parameter hasn't changed any of the references in the RTE in the Grid. Am asking another dev to double-check.

**Comment by sitereactor** [comment]
That should not be necessary. We double checked on our end and it is due to a missing converter for the Grid, which needs to handle the RTE. The RTE by itself does have it handled as you found, so we just need to enable this type of support for the Grid as well.
We are working on this now.

**Comment by marcusjroberts** [comment]
Thanks @sitereactor! Everyone's favourite question - when do you think this fix will be live? Just need to know if we need to implement a workaround ahead of waiting for the change.

**Comment by sitereactor** [comment]
I'd expect no later than next week. Sooner if physically possible :)

**Comment by marcusjroberts** [comment]
Hi @sitereactor, do you have any updates for us?

**Comment by sitereactor** [comment]
I'm planning to roll out an update tomorrow. I will post back when its done.

**Comment by sitereactor** [comment]
@marcusjroberts A fix has been rolled out and you should see changes similar to the examples for a media item in the Grid and for a media items in the RTE in a Grid shown below.

BEFORE
```json
"value": {
    "id": 1053,
    "udi": "umb://media/799741d9071049288b51be0957efbf4e",
    "image": "/media/8d80c4c316b4ae2/tshirt-azurefunctions.png"
}

"value": "<p>This is the rich text editor where images should be shown with Urls - see below if it works.</p>\n<p> </p>\n
<p><img src=\"?width=458.9108910891089&amp;height=500\" alt=\"\" width=\"458.9108910891089\" height=\"500\" data-udi=\"umb://media/799741d9071049288b51be0957efbf4e\" /></p>",
"editor": {
    "name": "Rich text editor",
    "alias": "rte",
    "view": "rte",
    "render": null,
    "icon": "icon-article",
    "config": {}
}
```

AFTER
```
"value": {
    "id": 1053,
    "udi": "umb://media/799741d9071049288b51be0957efbf4e",
    "image": "/media/8d80c4c316b4ae2/tshirt-azurefunctions.png",
    "url": "https://media.umbraco.io/mini-headless-rte-grid-test/8d80c4c316b4ae2/tshirt-azurefunctions.png"
}

"value": "<p>This is the rich text editor where images should be shown with Urls - see below if it works.</p>\n<p> </p>\n
<p><img src=\"https://media.umbraco.io/mini-headless-rte-grid-test/8d80c4c316b4ae2/tshirt-azurefunctions.png?width=458.9108910891089&amp;height=500\" alt=\"\" width=\"458.9108910891089\" height=\"500\"></p>",
"editor": {
    "name": "Rich text editor",
    "alias": "rte",
    "view": "rte",
    "render": null,
    "icon": "icon-article",
    "config": {}
}
```

**Comment by marcusjroberts** [comment]
Thanks so much @sitereactor! Very quick work 👍

**Comment by Jay-umbr** [comment]
This is still an issue with RTE links pointing to internal documents. 
They are formatted like this:
<p><a href="/{**localLink:umb://document/cd95df465aae4efe8ffb2c30ab578f09**}" title="Contact" data-anchor="#">test there</a></p>
where href should instead point to the actual page URL

**Comment by sitereactor** [comment]
@Jay-umbr can you please report this as a new issue given that this issue was fixed, and the one you mentioned is another issue (RTE in Nested Content). You can add a link back to this for reference. And ideally include details about the API and endpoints where you see this output.
