### ISSUE TITLE
Enable an AES-GCM-based cipher suite.

### ISSUE THREAD

**Issue by DarinPem** [umbraco/Umbraco.Cloud.Issues#220]
A brief description of your feature request goes here.

Our backendapi endpoints are not able to securely connect to Umbraco's  endpoints.  While investigating, we noticed this error when we did an inspect of the call: 

Umbraco Endpoint:
https://corcoran-coms-diligent-koala.s1.umbraco.io/umbraco/rest/v1/content/published/query?size=2147483647&page=0&query=%2F%2FnewDevelopments%5B%40isDoc%5D

Security overview warning: 
Connection - obsolete connection settings
The connection to this site is encrypted and authenticated using TLS 1.2, ECDHE_RSA with P-384, and AES_256_CBC with HMAC-SHA1.
AES_256_CBC is obsolete. Enable an AES-GCM-based cipher suite.

  Please enable AES-GCM-based cipher suite and disable AES_256_CBC with HMAC-SHA1

**Comment by sitereactor** [comment]
This appears to be a site based on the old Headless beta version, which was replaced by Umbraco Heartcore. When using Heartcore the APIs go through Cloudflare and I expect that the Ciphers would be different (i can double check which ones are available). But for the specific project you need to migrate it to an Umbraco Heartcore project or convert it to a regular Umbraco Cloud project in which case the ciphers would be the same.

**Comment by sitereactor** [comment]
These are the cipher suites available for Umbraco Heartcore's Content Delivery API:
https://developers.cloudflare.com/ssl/ssl-tls/cipher-suites/
