### ISSUE TITLE
📮 Feature request: Please include the Project name in notification emails.

### ISSUE THREAD

**Issue by jameswilki** [umbraco/Umbraco.Cloud.Issues#225]
Following a recent plan change, we received the following notification by email:

![image](https://user-images.githubusercontent.com/9935226/85401015-3f778f80-b551-11ea-9e7f-849082a761c6.png)

We currently manage several projects in Umbraco Cloud, so it would be really useful if the email included the Project name so that we can identify which site the change relates to.

Thanks, and kind regards,

James.

**Comment by sitereactor** [comment]
Yes, agreed. We are planning an update to the Plan and Database upgrade, and we'll make sure to include the project name as part of that update.

I will get back to this comment once the update had been rolled out.

**Comment by mclausen** [comment]
Hi @jameswilki

I am writing to let you know that we just rolled out an update to this template 👍 

Cheers, and thank you for reporting the issue 🤠
