### ISSUE TITLE
Forms gets overwritten when deploying to the next environment.

### ISSUE THREAD

**Issue by Frost117** [umbraco/Umbraco.Cloud.Issues#23]
### Bug summary

A cloud project with 3 environments - Development, Staging and Live. The client has access only to Live. This is where they edit all the content, be it text or images. And lately they've started using Umbraco Forms.

The client is happily working on their form on the prod environment. This form exist on the dev env as well. He has added a new property, short answer, to the form. He then saves it and all is well.

The developer is working on a new feature on the dev env. He is now ready to deploy this feature to the live environment. The client is happy with what the developer has done, and he now gets the new feature on his prod env.

When the client goes into the backoffice to see if all is well, he notices that the changes has he done on form is now gone.

### Specifics

Umbraco version 7.12.4
Forms version 7.0.4

This only occurs on UaaS with deploy.

### Steps to reproduce

You need at least 2 environments on UaaS to reproduce this.
Create a form on Dev env and deploy it to Live.
When the deployment is done on Live, go to the Live backoffice and add a new field to the form.
Save the form.

Now go to the Dev backoffice and create a new document type. Don't touch the form.
When you are happy with the document type, deploy it to live, and wait for the deployment to be done.
When it is done, go to the lives backoffice and see how the form has reverted back to it's original state.

### Expected result

Would have expected that the form has kept its changes. 

### Actual result

Form got overwritten with the form from the dev environment.

The reason why this happen is because the way Umbraco Forms is structured. It is based around .json files for the forms themselves, so unless the new changes on the Form comes from dev, the form on live will always be overwritten, making it pointless to make changes on live.

To actually solve this, The forms would have to saved in the database rather than .json files.

**Comment by ArnoldV** [comment]
With the latest love to forms 7.0.6 (22 January 2019), it would be really nice if this issue can also be addressed.

**Comment by mikkelbrusen** [comment]
I used to be able to pull the form changes to my local enviroment as they were treated as commits to the repo but it could take days before the commits were actually registered. Now it seems that the changes are no longer comitted, hence it is impossible to recover the changes that has been made to forms on the live enviroment, rendering Umbraco Forms completely useless as the forms get overwritten by developers, just like the other guys are mentioning, please fix this....

**Comment by esn303** [comment]
Ok, so about a year later ... just nothing has happened? It still is broken. To me this feels like Forms is getting phased out or something? 🤔

**Comment by alanmac** [comment]
I'd love some visibility on plans for addressing this also.

**Comment by FransdeJong** [comment]
It would be great if this issue could be picked up. This breaks the easy cloud workflow and we are back to manually comparing files.

Any updates from HQ?

**Comment by clausjensen** [comment]
We are planning to pick up this issue in the next sprint. I can't promise exactly when it will be done and ready for use on Cloud, as it will require a bunch of testing both on the proposed solutions and on the actual implementation.

However - be assured that it will get some attention now and we're getting this fixed! 😃

**Comment by esn303** [comment]
Thanks for picking this up, Claus. 👍 

Maybe you could communicate the internale stages every now and then, so we can see the progress being made. Just to keep us from feeling that it is probably postponed again? ☺️

**Comment by clausjensen** [comment]
@esn303 Yep! I'll try to make sure we give some updates when we know how it's progressing 😄

**Comment by jmayntzhusen** [comment]
Will close this as you can now transfer forms via a content transfer: https://our.umbraco.com/documentation/Umbraco-Cloud/Deployment/Umbraco-Forms-on-Cloud/#did-you-create-your-cloud-project-before-june-18th-2019
