### ISSUE TITLE
Heartcore Webhooks firing incorrectly, and so are currently unusable

### ISSUE THREAD

**Issue by natewoodbridge** [umbraco/Umbraco.Cloud.Issues#231]
I have 3 webhooks attached to a content type — Publish, Unpublish, Delete — however when I perform any of these actions all three webhooks will be fired, and these events are always Publish events, whatever the original action may be.
 

Reproduction
------------

I spoke with the Umbraco support team, and your colleague (Hjalte) was able to recreate the issue on a new instance of Heartcore:

> First I tried copying all of your doctypes to a new project, and on that, I was able to reproduce the issue. I then tried on a clean project with only one document type and I see the same behaviour.

#### Publish Action 

In Umbraco I have set up 3 webhooks, as shown in this screenshot:

![image](https://user-images.githubusercontent.com/123652/87019673-cae85600-c1ca-11ea-9851-1e927345f040.png)

I then created and published a new item (Redirect content type) in Umbraco, and looked to see which webhooks were fired. I can see three webhooks have been sent off, for this single action. I would only expect one to be fired.

![image](https://user-images.githubusercontent.com/123652/87019937-20246780-c1cb-11ea-8995-10437f16c2cd.png)

https://webhook.site/#!/593c8e5a-dcf2-464d-aa49-6c444fee93b3

When I look at the detail of each of these webhooks, I notice that it's not just the same webhook being run 3 times, but all three are activated, as there are different `umb-headless-event` headers.

![image](https://user-images.githubusercontent.com/123652/87020263-8315fe80-c1cb-11ea-878d-d092c5439e17.png)

![image](https://user-images.githubusercontent.com/123652/87020299-8dd09380-c1cb-11ea-86d1-fce2e14e1d3a.png)

![image](https://user-images.githubusercontent.com/123652/87020340-99bc5580-c1cb-11ea-8135-e98bf3ed6e91.png)

#### Delete Action

I thought I could maybe find a workaround for this, so my next course of action was to see what happens for a Delete event.

I set up a new sandbox, only changing the URL of the webhook nothing else, like so:

![image](https://user-images.githubusercontent.com/123652/87020645-0d5e6280-c1cc-11ea-9125-75d30619c09e.png)

I then deleted the same item I created before. But again, all three webhooks fired, when I would only expect one.

![image](https://user-images.githubusercontent.com/123652/87020833-531b2b00-c1cc-11ea-81d5-837f78e9b7aa.png)

https://webhook.site/#!/ae0b362d-7545-4299-9830-9a52a58b824b/72e5cfb9-7676-4c79-bf06-0fa10ca02cc1/1

Again, I wondered if I would work around this, but when I look a the detail of these events, I notice that they are showing the item I just deleted as being Published still.

![image](https://user-images.githubusercontent.com/123652/87021044-9aa1b700-c1cc-11ea-947f-84a3e1af7236.png)

![image](https://user-images.githubusercontent.com/123652/87021156-c15fed80-c1cc-11ea-80ba-bddade8e9818.png)

![image](https://user-images.githubusercontent.com/123652/87021115-b2793b00-c1cc-11ea-9ae9-604d8f4e4abc.png)

You will notice that these three responses look very similar to above. Therefore, I have no way of telling if the item has been deleted, and all webhooks become unusable.

I would appreciate your help with this.

### Additional Information

I also notice that the Umbraco logs contain multiple errors that relates to all the times the webhooks are fired. They all contain the following message:

![image](https://user-images.githubusercontent.com/123652/87021721-74304b80-c1cd-11ea-9a31-09b734a5f605.png)

**Comment by sitereactor** [comment]
I believe we found the issue surrounding webhooks mentioned. We will do some further testing before rolling it out.

I will post back once we know the details around rolling out an update.

**Comment by marcusjroberts** [comment]
Hi @sitereactor, any updates on this issue?

**Comment by sitereactor** [comment]
Hey @marcusjroberts sorry for the delay, everything is a bit slow during the summer vacation period 😅
We are planning to roll-out the fix during the week of July 27th. If you want this fix applied to your site sooner you can email me the alias of your project and I can have it applied next week.
My email is just morten at umbraco dot com.

**Comment by marcusjroberts** [comment]
Hi @sitereactor, my colleague @natewoodbridge has emailed you, but we haven't heard back. Are you able to give us an idea of when that change could be made this week?

**Comment by sitereactor** [comment]
Yes, sorry about the delay. I replied to the email.
