### ISSUE TITLE
Heartcore: Unable to populate Umbraco.MultipleTextstring field type when creating a content item

### ISSUE THREAD

**Issue by jfm5248** [umbraco/Umbraco.Cloud.Issues#233]
When creating a content item based on a document type with an Umbraco,MultipleTextstring (aka repeatable textstring) field, I am unable to populate that field with a value.

## Umbraco version
Heartcore

## Reproduction

Here I have a Document Type called Brand and the urlSegments field is a repeatable textstring type.

![image](https://user-images.githubusercontent.com/10039128/87332668-eaa0b680-c509-11ea-8cc8-c42a0fa4fde0.png)

Based on looking at the values in the DB of a local Umbraco install, forum threads, and even the [Umbraco code](https://github.com/umbraco/Umbraco-CMS/blob/v8/contrib/src/Umbraco.Web/PropertyEditors/MultipleTextStringPropertyEditor.cs) itself, this type is new line delimited.

Attempt populate the field with \r\n as the delimiter. The value is returned empty.

![image](https://user-images.githubusercontent.com/10039128/87333566-46b80a80-c50b-11ea-9999-c6e134a81230.png)

Attempt populate the field with \r as the delimiter. The value is returned empty.

![image](https://user-images.githubusercontent.com/10039128/87333618-5df6f800-c50b-11ea-9b62-a0aab3db3d69.png)

Attempt to populate the field with a comma delimited string. The value is returned empty.

![image](https://user-images.githubusercontent.com/10039128/87333865-c34ae900-c50b-11ea-976d-91ea46a9f8f6.png)

Attempt populate the field with a JSON array. The value is returned empty.

![image](https://user-images.githubusercontent.com/10039128/87333731-8979e280-c50b-11ea-8d9c-0f57123881ca.png)

### Expected result

The field should be populated.

### Actual result

The field is not populated, and I can't find any way to do so.

**Comment by sitereactor** [comment]
Hi @jfm5248 Thanks for reporting this and sorry about the delay in getting back to you. I have added this to our upcoming sprint, which starts monday next week. I'll get back to you as soon as we've had a chance to dive into the issue.

**Comment by sitereactor** [comment]
Hi @jfm5248 We had a look and the format is expected to be as follows:

```
urlSegments: {
"$invariant": [ {"value": "test1"}, {"value": "test2"} ]
}
```

We realize that this might not be super intuitive, so we'll work towards having a section for the API, which highlights how the values should be structured for the various Property Editors in Umbraco.

Hope this helps.

**Comment by jfm5248** [comment]
Thank you! Yes, such documentation would be extremely helpful and go a long way toward making the API more friendly to use.
