### ISSUE TITLE
Remote VS Debugging like with Azure App Service

### ISSUE THREAD

**Issue by Zweben** [umbraco/Umbraco.Cloud.Issues#235]
I've started using Azure App Service in some other projects, and one thing that I really like about it is the remote debugging capability. If I'm having an issue on a live environment that I can't replicate locally, I can just attach the debugger to it and set breakpoints like it's local. Can this be brought to Umbraco Cloud? It would be fantastic.

**Comment by nul800sebastiaan** [comment]
It would be fantastic wouldn't it! 

Right now, we can't bring that functionality to Cloud unfortunately. Right now we are working on a new platform from which Cloud will run, this will most likely provide added support for remote debugging. I'll put this on the ideas list for the future so we can close this once it's available. Thanks for the feature request!
