### ISSUE TITLE
On Content Restore/Deploy DateTime values are changed

### ISSUE THREAD

**Issue by hfloyd** [umbraco/Umbraco.Cloud.Issues#236]
I have a project with an Events section.  There are DateTime fields for Event Start and End. There is an additional field for the timezone of the event, for front-end display purposes. 

I noticed when restoring a content node from a live Umbraco Cloud site (servers in a European timezone) to my local copy (in EST timezone) the data was different:

LIVE:
![image](https://user-images.githubusercontent.com/1252593/88101384-e4df4c80-cb6b-11ea-9542-a5a19839b505.png)

LOCAL (after Restore):
![image](https://user-images.githubusercontent.com/1252593/88101424-f58fc280-cb6b-11ea-9773-2310b4210f5a.png)

It would seem to me that the location of the server vs. the local development machine should not affect the datetime data assigned to a content node.

### Specifics

What version are you using:

- Umbraco 8.6.3
- Forms 8.4.1
- Deploy 3.4.5

### Steps to reproduce

1. Add a DateTime property to a Doctype.
2. Create a node of the Doctype on a Cloud project (using  a remote development, staging, or live environment)
3. Clone the project locally to a computer in a different timezone from the Cloud servers.
4. Restore the content.
5. Check the DateTime values on the local vs. the remote environment

### Expected result

I feel that the servers should be irrelevant in terms of Content data. After all, world-wide dispersed teams are common these days, but DateTime data should remain consistent and invariant.

### Further thoughts

If this is expected behavior, is there any way to configure the DateTime type to manage this as timezone-independent data?

**Comment by jmayntzhusen** [comment]
Hey @hfloyd 

On the datetime datatype there should be an offset time option, do you have that enabled?

https://our.umbraco.com/Documentation/Getting-Started/Backoffice/Property-Editors/Built-in-Property-Editors/Date-Time/#data-type-definition-example 

It should do exactly what you are experiencing, so if that is on turning it off may help 🙂

**Comment by nul800sebastiaan** [comment]
I was just testing this, indeed when you save the date/time WITH offset it will do what you expect, if you save it without the server offset it will change between environments.

![image](https://user-images.githubusercontent.com/304656/88144878-e0fa0b80-cbf9-11ea-8e3f-54ecb8063aec.png)

**Comment by nul800sebastiaan** [comment]
Oops, other way around, not enabling the offset actually makes sure the difference between local and server gets calculated and the time changes. When saving it without the offset setting we "just" use the existing saved string.

**Comment by hfloyd** [comment]
Ah, very interesting. Is this feature new in v8? The site in question is a 7->8 migration, and it seems the default for the migrated datetime properties was set to "ON" for Offset.
