### ISSUE TITLE
Set an Environment Variable scoped to the User

### ISSUE THREAD

**Issue by giordanop** [umbraco/Umbraco.Cloud.Issues#244]
I would like to set an environment variable scoped to the User on my Umbraco Cloud application.

In my case this would make possible to use New Relic as APM (https://docs.newrelic.com/docs/agents/net-agent/install-guides/install-net-agent-using-nuget). 

An idea could be to use the existing powershell console to run this command: 
`[System.Environment]::SetEnvironmentVariable('siteName','example.com',[System.EnvironmentVariableTarget]::User)`

**Comment by nul800sebastiaan** [comment]
Hi @giordanop - I am not sure that's going to be easily possible in our current infrastructure. What would you want to store in those environment variables? 

As far as I know New Relic doesn't currently work on Umbraco Cloud, we're working on new infrastructure that might make it easier. At the moment we recommend using Application Insights instead: https://our.umbraco.com/documentation/Umbraco-Cloud/Set-Up/Application-Insights/

**Comment by giordanop** [comment]
Hi @nul800sebastiaan - this is what I would like to set: 
```
set COR_ENABLE_PROFILING=1
set COR_PROFILER={71DA0A04-7777-4EC6-9643-7D28B46A8A41}
set COR_PROFILER_PATH=C:\home\site\wwwroot\bin\newrelic\x86\NewRelic.Profiler.dll
set NEWRELIC_HOME=C:\home\site\wwwroot\bin\newrelic
set NEW_RELIC_LICENSE_KEY='license_key'
set NEW_RELIC_APP_NAME='app_Name'
```

Settings these 6 variables New Relic starts working with Umbraco Cloud. I can imagine that some of them might not be easy to set, but the outcome would be really valuable, imho.

**Comment by thomasknielsen** [comment]
Maybe this would be a nice place to add the possibility to control the timezone of the current user/installation.

**Comment by nul800sebastiaan** [comment]
@giordanop Thanks! Unfortunately it looks like we can't support this on the current setup of our infrastructure. We are in the process of modernizing the infrastructure and it should be possible at that point. Unfortunately I can't help getting New Relic to run and as said before we recommend Application Insights instead.
Sorry I can't help with adding these environment variables for you, I recommend investigating if New Relic can set these variables in some other way. However, I remember trying this and we couldn't get it to work at the time.

@thomasknielsen This is a server setting and can not be changed per website.
