### ISSUE TITLE
📮 Feature request: Add deployment datetime to the Environment history view

### ISSUE THREAD

**Issue by jameswilki** [umbraco/Umbraco.Cloud.Issues#249]
The Environment history view displays the timestamp from the commit. Please can the datetime of deployment be added as well, and the commits grouped under it so that we can see when code was deployed to an environment?

**Comment by hfloyd** [comment]
@jameswilki I had a similar request here: https://github.com/umbraco/Umbraco.Cloud.Issues/issues/128

**Comment by nul800sebastiaan** [comment]
Thanks, I've merged this into #128

**Comment by jameswilki** [comment]
Sorry @hfloyd, I don't know how I missed your issue :man_facepalming:
Thank you for merging into #128 @nul800sebastiaan :thumbsup:

**Comment by hfloyd** [comment]
@jameswilki  no worries! I'm glad others are interested in similar improvements :-)
