### ISSUE TITLE
Latch didn't renew certificate

### ISSUE THREAD

**Issue by FransdeJong** [umbraco/Umbraco.Cloud.Issues#251]
Yesterday a client called us about a certificate error on his site.

Latch didn't renew the certificate for some reason.
I checked the dns settings and all was fine.
When I removed the Url and added it again it renewed and the certificate was renewed.

If you want to look back in the logs please let me know what info you need.

This also is a great scenario to send a automated email that something went wrong so I can take action before the client has to call me.

**Comment by sitereactor** [comment]
@FransdeJong thanks for letting us know! This should obviously not be happening, so if you can please send the project and hostname to support and refer back to this thread that would be greatly appreciated and allow us to follow up on the issue.

Thanks!

**Comment by FransdeJong** [comment]
@sitereactor support chat? Or do you have a emailadress?

**Comment by sitereactor** [comment]
Yes, you can reach out to them via the Umbraco Cloud Portal -> support chat.

**Comment by dzordzs** [comment]
@FransdeJong Could you tell me what the hostname was? :)

**Comment by FransdeJong** [comment]
xyall.com. Don't know if it was with or without www...

**Comment by readingdancer** [comment]
We have the same issue for a client site's certificate that should have updated by yesterday, now the site is insecure. I have raised the issue on the Umbraco Cloud portal, but I fear we are outside of support hours as no one has responded so far.

The domain is: https://carpenterssw.org

**Comment by FransdeJong** [comment]
You should be within support hours...

@sitereactor any news on this issue?

**Comment by readingdancer** [comment]
I've been waiting 28 minutes for someone to respond to the chat, which is why I was wondering if they are no longer there. @FransdeJong do you have any idea if we can somehow manually trigger a certificate renewal?

**Comment by sitereactor** [comment]
@FransdeJong no, not beyond that was should have been resolved.
I will follow up on what caused the issues for renewing the certicates.

@readingdancer there should be someone from the support team looking at the issue now.

**Comment by readingdancer** [comment]
Thanks @sitereactor - Yes, it's now been fixed for my client site. I hope you manage to resolve the issue as we have another site due to renew in less than a month :)

**Comment by FransdeJong** [comment]
@readingdancer sorry, I know a fix and forgot to tell....
If you remove the url and add it again it works again.

This should be fixed or at least the cloud project owner should receive an email if renewal goes wrong.

**Comment by nul800sebastiaan** [comment]
Good morning all. Looks like we forgot to follow up on this one. As you may or may not know, we're in the process of moving everyone on Cloud to use CloudFlare DNS, at which point CloudFlare will also take over the tasks for making sure certs are added. 
As such, I'll close this issue now.
