### ISSUE TITLE
Variation ", " is not supported by the property type

### ISSUE THREAD

**Issue by alaasaeeddct** [umbraco/Umbraco.Cloud.Issues#255]
this issue appears in our umbraco 8, once we allow the multi languages, so now whatever new page that I want to create is give me this error, which's stop me from doing many pages, and our website is live, I am using Uskinned theme for our Umbraco.

the umbraco teams tried to resolve this but with no luck, i don't know why this error can't be fixed, looking for support to resolve this and i saw before one article for deleting some database entry and I did, but the issue still exist and now it makes un happy.

hope that you can support and help us.

best regards,

**Comment by nul800sebastiaan** [comment]
Thanks! This duplicates issue: #135
