### ISSUE TITLE
Allow Custom Hostnames to be assigned to multiple root nodes

### ISSUE THREAD

**Issue by c9mbundy** [umbraco/Umbraco.Cloud.Issues#258]
By default, the hostnames bound to the site via IIS are routed to all root-nodes, and you can structure your content how best suits your needs.

This also applies to the default Umbraco Cloud URL for a Cloud project, which is routed to all root-nodes by default.

However, with Umbraco-Cloud, a custom hostname that is bound using the Latch utility, and must then be assigned to a root-node using the 'Culture and Hostnames' function, and although the documentation does not explicitly state there is a limit to this, in fact a custom hostname can only be assigned to a single root node,  which limits the routing of that hostname to that single node.

![image](https://user-images.githubusercontent.com/42397042/94083017-938e5a80-fe45-11ea-90cd-3d5385fae623.png)

This means that with Umbraco-Cloud you can't actually structure your content as best suits your needs, but have to structure it to meet that limitation.

i.e. what works as expected on a local dev site, or on a privately hosted site, or even what works with the base cloud site URL during development, is broken once you assign a custom hostname to a cloud project.

e.g. suppose there are 2 root-nodes

Home
 +- Page-Node-1
 +- Page-Node-2
 +- etc

Products
 +- Product-1
 +- Product-2

With standard IIS routing, even on Cloud with the default project URL, both receive access to the bound hostnames.

However, with Umbraco-Cloud, only one of these can have 'custom' hostnames routed to them, so going live with a custom hostname results in only 1 of them being able to respond to requests, while the other throws 404s.

Being able to assign a custom hostname to multiple root-nodes, would allow finding of content using that hostname regardless of the root node it's located under, and behave in the same way as it does in other environments.

**Comment by nul800sebastiaan** [comment]
@c9mbundy I'm not sure how this relates to Cloud, this is a limitation in CMS, I had to try locally to see if I missed anything but I get the same error locally. And this is normal, we would have no idea where to route your request if it resolves to 2 different nodes.

Maybe you didn't realize that you're not required to set up a hostname in Umbraco itself when you add on to your cloud site? 

My test site has a hostname:

![image](https://user-images.githubusercontent.com/304656/94108178-2081e580-fe3f-11ea-92aa-d3364a2d4108.png)

And it works as any other website you set up on your own IIS:

![cloud258](https://user-images.githubusercontent.com/304656/94108230-398a9680-fe3f-11ea-8b41-b248c59caf86.gif)

You can also set up a specific route in your hostname setup like so if you want:

Home ➡ https://test.com/
+- Page-Node-1
+- Page-Node-2
+- etc

Products ➡ https://test.com/products
+- Product-1
+- Product-2


Anyway, none of this is specific to Cloud, it's "just" Umbraco. Let me know if I am misunderstanding something completely and we can have another look. I'll close this for now.

**Comment by c9mbundy** [comment]
Doh!

You are quite correct - I had literally interpreted [this documentation page](https://our.umbraco.com/documentation/Umbraco-Cloud/Set-Up/Manage-Hostnames/) as saying you MUST do this - missing the point that it only applied to multi-site setup - what an idiot.

**Comment by nul800sebastiaan** [comment]
No worries @c9mbundy! We all have moments like this! 👍
