### ISSUE TITLE
Heartcore: Dropdown Multiple returns each element in a char value (GraphQL)

### ISSUE THREAD

**Issue by Jay-umbr** [umbraco/Umbraco.Cloud.Issues#261]
A Dropdown multiple datatype, when querying the value through GraphQL, is coming through as a string array with each element is a char value of the string value., so - for example - if we have a drop down with a value of CAT, when we query it the array is like so: 
["C","A","T"]
where is should be
["CAT"]

Reproduction
------------

1. Create a new doctype
2.Add a Dropdown multiple datatype in a property on that doctype
3, Make some content with the above
4. Go to graphQL playground or in your app query for the value of the dropdown property

### Specifics

    Where applicable:
    * Heartcore
    * GraphQL

### Expected result

["VALUE"]

### Actual result

["V","A","L","U","E"]

**Comment by sitereactor** [comment]
A fix for this has been deployed to Production
