### ISSUE TITLE
Heartcore: cannot get a value in nested item of nested item in GraphQL

### ISSUE THREAD

**Issue by Jay-umbr** [umbraco/Umbraco.Cloud.Issues#262]
When trying to get a value from a nested item in a nested item on a page the GraphQL responds with 
"Error trying to resolve field 'startPage" (or content, depending on how you query for the content node itself).
Nothing else in the query is highlighted/throwing errors.

Reproduction
------------

1. Create a StartPage doctype, set allowed in root
2. Create SquaresBlock doctype, save as element type
3. Create BlockComponent, save as element type, add a property called blockHeading (textstring)
4. In SquaresBlock, add a new property called Squares Block (alias: squaresBlockNested) - nested content using BlockComponent doctype
5, Create a content node (startpage) called Home and some nested content
6. Go to GraphQL playground and run this query

```
{
startPage(url:"/home/"){
  ... on StartPage{
    squaresNested
    {
      ... on SquaresBlock
      { 
				squaresBlockNested{
          ... on BlockComponent{
            blockHeading
          }
        }
      }
      }
    }
}
}
```

### Specifics

    Where applicable:
    * Heartcore
    * GraphQL

### Expected result

Value of the blockHeading in blockComponent in SquaresBlock from the home page

### Actual result

Error msg:

```
{
  "errors": [
    {
      "message": "Error trying to resolve field 'startPage'.",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "startPage"
      ]
    }
  ],
  "data": {
    "startPage": null
  }
}
```

**Comment by joakimmillen** [comment]
Any updates on this?

**Comment by sitereactor** [comment]
The fix for this is a bit complex, so we had to schedule it as part of our sprints.
The expected timeframe is 2-3 weeks from now until a fix is rolled out.
