### ISSUE TITLE
Your Workspace Dashboard: Broken Link

### ISSUE THREAD

**Issue by BarryFogarty** [umbraco/Umbraco.Cloud.Issues#263]
The link to https://our.umbraco.com/Documentation/Umbraco-Cloud/Set-Up/Visual-Studio is broken. This is shown in Your Workspace - Local - Use Visual Studio

It should be https://our.umbraco.com/documentation/Umbraco-Cloud/Set-Up/Working-With-Visual-Studio/

**Comment by nul800sebastiaan** [comment]
Thanks @BarryFogarty! I assume this page has been renamed, we should set up a redirect for that. Can you confirm @sofietoft that we forgot to redirect this one?

**Comment by sofietoft** [comment]
Hmm! I just checked the IISRewriteMaps - and it looks like the rewrite is already setup 🤔 : https://github.com/umbraco/OurUmbraco/blob/37b9caa26503738ddf2485520f55c968119cf4fd/OurUmbraco.Site/config/IISRewriteMaps.config#L504

Can't really figure out, why it doesn't work though?

**Comment by nul800sebastiaan** [comment]
Fixed! 👍 Thanks @BarryFogarty
