### ISSUE TITLE
Heartcore/GraphQL: MultiURL Picker max 1 does not return values via graphql

### ISSUE THREAD

**Issue by Jay-umbr** [umbraco/Umbraco.Cloud.Issues#265]
When using MultiURL Picker Max 1 datatype, and trying to get the link value (name/url/any other) via GraphQL, we get an error saying "Error trying to resolve field 'name'.",

Reproduction
------------

If you're filing a bug, please describe how to reproduce it. Include as much
relevant information as possible, such as:

### Bug summary
Create a doctype called testpage
Add 2 properties - Multi URL picker Max 1and Multi URL picker. Name them medialink and medialinktwo
![image](https://user-images.githubusercontent.com/56038614/95955782-af11d300-0dfd-11eb-9ff9-305b1ef5a61c.png)
Make a new content item with this doctype on the page and fill out the links.
Go to graphQL playground and run the following.

```
{
    allTestpage{
      items
      {
      name
        medialink
        {
          name
          url
        }
      }
    }
}
```
It will return "cannot resolve name/url'. If you were to query the same for medialinktwo however it would resolve no problem.

Seems like the issue is only with the max 1 datatype version of the multi url picker.
![image](https://user-images.githubusercontent.com/56038614/95956005-f6985f00-0dfd-11eb-9ff3-79f4d34eed94.png)

![image](https://user-images.githubusercontent.com/56038614/95956020-fd26d680-0dfd-11eb-97fd-6c7434d4e7da.png)

**Comment by sitereactor** [comment]
A fix for this has been deployed to Production
