### ISSUE TITLE
When transferring content that uses the block list editor, picked items aren't transferred

### ISSUE THREAD

**Issue by sussexrick** [umbraco/Umbraco.Cloud.Issues#272]
When you have a media picker on a content node and select a media item, then transfer the content node using Umbraco Deploy, the media item is also transferred as a dependency.

When the document type includes a block list editor, and the element type used for a block has a media picker, that media is not transferred in the same way. If you subsequently transfer the media, that does not restore the link. You then have to retransfer the content which references the media.

Also when you have a form picker in the element type, the form is not transferred as a dependency of the content node either.

**Comment by nul800sebastiaan** [comment]
I'm afraid this all seems to work for me, what am I doing differently? 
Using: 
Umbraco 8.9.1
Forms 8.5.5
Deploy 3.5.1

![cloud272](https://user-images.githubusercontent.com/304656/98684261-3fdcbf80-2366-11eb-89e6-d5262bc7cd09.gif)

Whoops, forgot it was the media picker.. but that seems to work too! 

![cloud272_media](https://user-images.githubusercontent.com/304656/98684946-15d7cd00-2367-11eb-9b30-59f0a444ec63.gif)

**Comment by sussexrick** [comment]
@nul800sebastiaan Thanks for checking. I'll try to reproduce again and upload a repro project, but it won't be until the weekend at least.

**Comment by sussexrick** [comment]
@nul800sebastiaan I've upgraded to the versions you mention. It still doesn't work on my main solution, but starting a new one from scratch did work, as it did for you. I'll try another day to find what the difference is.
