### ISSUE TITLE
Heartcore: Translation of nested element types not possible

### ISSUE THREAD

**Issue by joakimmillen** [umbraco/Umbraco.Cloud.Issues#281]
When nesting content using the "nested content" property with element types it is not possible to individually translate these element type objects that are created even though you can mark them as "can vary by culture" which would indicate that it should be possible.

Reproduction
------------

### Steps to reproduce

1. Create a document type, name it **Element type**, set it to allow varying by culture.
2. Add a prop group and a property which is a markdown editor and set that prop to allow varying by culture.
3. Create a new document type called wrapper
4. Add a prop group and a "nested content" property which allows the **Element type** as a selection.
5. Create a new _Wrapper_ and create a new nested item of the _Element type_ type. 

### Expected result

When adding the nested element type and inputing text into the MD editor I expect to be able to translate it, but it seems I am not. 

### Actual result

There is no selection of language anywhere. If i add "allow varying by culture" to the _Wrapper_ type it shows the usual dropdown of languages but it affects the whole wrapper and what I want is to individually translate element types.

**Comment by sitereactor** [comment]
Hi @joakimmillen this is not supported in Umbraco. The Nested Content property editor is seen as one Property.
Reference: https://github.com/umbraco/Umbraco-CMS/issues/5532
Similarily for the BlockList Editor: https://github.com/umbraco/Umbraco-CMS/issues/9232
