### ISSUE TITLE
Queue for transfer with multiple users (deploy)

### ISSUE THREAD

**Issue by MahmoudUmbraco** [umbraco/Umbraco.Cloud.Issues#282]
Editor A  makes some changes to a content and wants to transfer it to live **tomorrow**,
Editor B and C work on other content and also wants to transfer it to live (not tomorrow, but **today**),
When editor B or C transfers the content that they have queued for transfer, they will also transfer the changes of editor A.

### Specifics

The latest version of Core and Deploy.
Bug on other browsers.

### Steps to reproduce

    User A: Queues content for transfer to next environment
    User B: Navigate to the content section and sees that some content is queued for transfer.

### Expected result
    
  User B, can't see or transfer content queued by other users.

### Actual result
 User B can transfer queued content that other users have queued.

**Comment by clausjensen** [comment]
Fixed in https://github.com/umbraco/Umbraco-Deploy/pull/462

**Comment by warrenbuckley** [comment]
Is fixed in this PR umbraco/Umbraco-Deploy#462 and will be due for next patch release in 3.5.2 of Deploy
