### ISSUE TITLE
Heartcore: Preview API header accept-language is ignored

### ISSUE THREAD

**Issue by ramondept** [umbraco/Umbraco.Cloud.Issues#288]
Hej!

We are trying to implement the preview API of Umbraco Heartcore, but we are running into an issue with the accept-language header being ignored.

Reproduction
------------

### Bug summary
We have a multilingual setup with language variants and we use the _Umbraco.Headless.Client.Net_ nuget package, which by default sends the culture in the Accept-Language header.

When retrieving an item by ID or URL it always returns the **en-us** variant and it ignores the Accept-Language header. It does work correctly when you set the language query string.

### Steps to reproduce
The problem can be reproduced with a direct call to the Preview API:

```
GET https://preview.umbraco.io/content/915d092d-6a09-4441-99ee-3da8a7788a3e
or GET https://preview.umbraco.io/content/url?url=/es-es/

Headers:
Accept-Language:es-es
```

This always returns the **en-us** variant of the item which is incorrect 🚫 

Now we add the culture as a query string:

```
GET https://preview.umbraco.io/content/915d092d-6a09-4441-99ee-3da8a7788a3e?culture=es-es
or GET https://preview.umbraco.io/content/url?url=/es-es/&culture=es-es

Headers:
Accept-Language:es-es
```

This returns the **es-es** variant of the page which is correct ✅ 

### Expected result

Return the correct language variant of the item based on the Accept-Language header.

### Actual result

Accept-Language header is ignored and the en-us variant of the item is returned.

**Comment by sitereactor** [comment]
This issue has been fixed and rolled out.
