### ISSUE TITLE
Property order is not deployed between environments

### ISSUE THREAD

**Issue by hjaltedaniel-umbraco** [umbraco/Umbraco.Cloud.Issues#289]
When changing the order of properties on a doctype and deploying those changes between environments, the changes is not applied to the destination environment.

Reproduction
------------

### Bug summary
It seems that the order is not even taken into account on deployments of schema between the environment. Since Deploy checks for the order on a content transfer, it means that the user ends up with a schema mismatch.

### Specifics
Seen recently on CMS v8.9.1 and Deploy 3.5.2

### Steps to reproduce

1. Create a document type in your local environment
2. Push the schema of the document type to your development environment on Cloud
3. Push the schema to the live environment.
4. Create a content node, using the doctype and transfer it through your environments.
5. Make a change to the order of the properties on your local environment - and push that change through the environments.
6. Restore content from a cloud environment - to your local environment, this will give you a schema mismatch.

### Expected result
Order is applied to the environments, respectively on the deployments.

### Actual result
Order is not applied - causing schema mismatches.

**Comment by jmayntzhusen** [comment]
Hey @hjaltedaniel-umbraco ,

This is fixed in Deploy 8.5.3, here is the original issue: https://github.com/umbraco/Umbraco.Cloud.Issues/issues/196 

8.5.3 will be released on Tuesday (Dec 8th).
