### ISSUE TITLE
Cannot consistently use dns.umbraco.io in Cloudflare hosted domain CNAMES

### ISSUE THREAD

**Issue by robertjf** [umbraco/Umbraco.Cloud.Issues#294]
As per the discussion in the Umbraco MVP Slack channel thread:

If you are using Cloudflare to manage your domain DNS and set the CNAME to dns.umbraco.io you can't use the Cloudflare proxy on your CNAME or it results in a "CNAME Cross-User Banned" error.

![image](https://user-images.githubusercontent.com/818101/102098913-d75c9300-3e7b-11eb-99db-b8d0f004cacd.png)

Moreover, using the dns.umbraco.io domain seems inconsistent - for example, I have 3 CNAMEs - one of them (staging targeting the dev instance) points at the site  dns.umbraco.io and works fine, the others I've had to revert back to hunterhunterv8.s1.umbraco.io in order for the site to be available...

![image](https://user-images.githubusercontent.com/818101/102099144-17237a80-3e7c-11eb-98b1-dd245e6178e1.png)

It may be partly because the staging CNAME entry is new that it works, while the other two were preexisting (the domain was migrated from another Cloudflare account recently as well); which may point at an issue with Cloudflare's records.

**Comment by sitereactor** [comment]
Can elaborate on how things are inconsistent? What didn't work for the two other hostname entries?

**Comment by sitereactor** [comment]
When I look it from our side all three hostnames are enrolled into Cloudflare with certificates provisioned.

**Comment by robertjf** [comment]
by inconsistent - when I changed the CNAMES for @ and www to point at dns.umbraco.io, I received the cf "CNAME Cross-User Banned" error shortly afterwards on all browsers.  the CNAME for staging only shows that error when I have proxy turned on.

**Comment by sitereactor** [comment]
Is this regardless of Proxying being turned off (no orange cloud) ?
As far as I know "CNAME Cross-User Banned" is only an issue when proxying is turned on.

**Comment by robertjf** [comment]
I was thinking that too, but the proxying is turned off in all cases, and the two domains still have issues.

**Comment by robertjf** [comment]
I did initially experience the problem with proxying turned on, and subsequently turned it off after some investigation and the realisation that dns.umbraco.io was a Cf domain entry :)

**Comment by sitereactor** [comment]
Can you elaborate on the issues you are still having?
It's a bit difficult to guess when `hunterhunter.com.au` is configured with an A-records for the old Public IP `23.100.15.180` and `www.hunterhunter.com.au` is setup to point to `hunterhunterv8.s1.umbraco.io` and serve a certificate from R3?

`https://staging.hunterhunter.com.au/` is correctly configured in Cloudflare and its serving a Cloudflare certificate as expected. So from my side I don't see any issues, but I'm keen to figure out what you have run into with the two other hostnames.

**Comment by robertjf** [comment]
there are no A records in the DNS for hunterhunter.com.au that I know of - there were some in the old accounts, so it may be that it's not fully propagated yet?

This is what I see when I look at the Cf account:

![image](https://user-images.githubusercontent.com/818101/102106655-f27fd080-3e84-11eb-9d8f-49406a65b60d.png)

hunterhunter.com.au is also redirected (via Url Rewrite) to www.hunterhunter.com.au - as soon as I update the CNAME to point at dns.umbraco.io I get the error (well, ~ 30 seconds later)

**Comment by robertjf** [comment]
I'm not sure why hunterhunter.com.au is pointing at an A record (just checked using https://mxtoolbox.com/SuperTool.aspx?action=a%3ahunterhunter.com.au&run=toolpage) - is this something Cloudflare may be doing internally?

**Comment by robertjf** [comment]
I've just reconfigured to point the two records (@ and www) to dns.umbraco.io - and immediately got the Cloudflare error - perhaps that may help with the troubleshooting?  I can afford to leave it like this for a couple of hours as no one will be browsing it right now :)

**Comment by sitereactor** [comment]
I just typed into https://dnsclient.michaco.net/ to see what how the naked domain was configured. But as you configured `hunterhunter.com.au` to use the website/environment name that would translate to pointing to `23.100.15.180`.

Can you verify that proxying is currently turned off for `www.hunterhunter.com.au` ?

This looks correct to me although one IP should be enough.
```
www.hunterhunter.com.au.         	153 	IN 	CNAME 	dns.umbraco.io.


hunterhunter.com.au.             	28 	IN 	A 	104.19.208.28
hunterhunter.com.au.             	28 	IN 	A 	104.19.191.28
```

**Comment by robertjf** [comment]
proxying is definitely turned off; the second A record turned up when I updated the CNAME to dns.umbraco.io - I've not added any A records at all - I think that's the Cloudflare flattening going on:
![image](https://user-images.githubusercontent.com/818101/102109684-6e2f4c80-3e88-11eb-8b81-3f7f82d3d20f.png)

**Comment by sitereactor** [comment]
I have reached out to Cloudflare to get a bit more clarity on the issue. It's a bit difficult for me to debug without access to your Cloudflare setup for this domain. But they should hopefully be able to tell us what has gone wrong with this setup.

**Comment by robertjf** [comment]
great - as soon as I can validate the email account associated with the account, I'll be able to give you access but unfortunately I've not been able to do that for a couple of weeks (I have a support ticket lodged with Cloudflare).

I need to revert the CNAME records back to bring the site back up again but can do another troubleshooting session tomorrow morning (AEST) if need be

**Comment by sitereactor** [comment]
Hi @robertjf I had a look at your project and hosted that you have two different domains added with snd without www. I didn't notice this when looking at our Cloudflare setup, and the `hunterhunter.com.au` hostnames hasn't actually been changed, so its still using Let's Encrypt certificate and our DNS (Cloudflare) doesn't actually know anything about it. That would explain why it doesn't work.

Maybe its not clear, but the new DNS setup is for new hostnames. So if you want to "move" the hostname to the new DNS setup you will have to remove the hostname from the project and then add it again. THEN it will be configured with our Cloudflare setup and my expectation is that it would just ad well as the staging hostname you added to the Development environment.

So just to be clear, nothing changes for existing hostnames unless you actively change it.

**Comment by robertjf** [comment]
Thanks, that makes a lot of sense... Will have a play with it when it's quiet and re-do the hostnames to see if that makes a difference...

**Comment by robertjf** [comment]
it worked!  going to close this now, but perhaps the instructions on the hostnames page of Umbraco Cloud needs to be updated?
