### ISSUE TITLE
Cloudflare DNS breaks subresource integrity

### ISSUE THREAD

**Issue by ronaldbarendse** [umbraco/Umbraco.Cloud.Issues#295]
After switching to the new Umbraco DNS (dns.umbraco.io) setup, all JS and CSS just recently seem to automatically get minimized and compressed by Cloudflare, which causes the file content hashes to change and the configured SRI verification to fail: https://developer.mozilla.org/en-US/docs/Web/Security/Subresource_Integrity.

**This in turn stops browsers rendering all stylesheets and executing any JavaScript code, breaking entire sites!**

Reproduction
------------
### Bug summary
Umbraco Cloud switched over from Let's Encrypt to Cloudflare certificates on December 8th 2020 for any new hostnames added to the project. This is all documented, blogged about and the text (on the hostnames page) in the portal is updated, so - besides not having a clear conformation text (with optional confirm checkbox) when deleting an existing hostname to ensure you need to change DNS-records if you want to re-add it later - this is very well communicated.

I can't find any documentation on whether other Cloudflare features were getting enabled though and the sites (that we launched/updated in the past week) were working fine before. So from what I can tell, Umbraco switched on the [Auto Minify feature](https://blog.cloudflare.com/an-all-new-and-improved-autominify/) without posting a maintenance notice on the [status page](https://status.umbraco.io/).

### Steps to reproduce
Add a JS/CSS file to a Umbraco Cloud project, get the SHA-hash and add a script/link tag with the `integrity` attribute containing the hash (see linked MDN article). This works correctly when viewing the site using the project URL (*.s1.umbraco.io), but breaks when viewed over a custom hostname that's setup with Cloudflare SSL certificates.

In a real production scenario, this is all automated (e.g. using webpack to generate a manifest containing the file hashes that get inserted into the script/link tags)...

### Expected result
Umbraco Cloud should not enable application specific features without a maintenance notice and/or provide a documented opt-out in case this doesn't work in a specific agency/client setup.

### Actual result
The browser blocks all stylesheets and JavaScript!

For now, I've had to remove the rendering of the integrity attributes to make the sites work again. I've tried adding the `no-transform` cache header to all resources (https://support.cloudflare.com/hc/en-us/articles/200168396-What-will-Cloudflare-compress-), but because the files were already cached by Cloudflare and I don't have access to purge the cache, couldn't reliably test whether this would disable the auto minify feature.

**Comment by sitereactor** [comment]
That's unfortunate. We were told that these settings wouldn't directly effect the custom hostnames.
I have turned off the autominify features again.

**Comment by sitereactor** [comment]
If you need anything purged from the cache you can send me an email with the url(s).
First name at Umbraco dot com.

**Comment by ronaldbarendse** [comment]
@sitereactor All assets were returned with a cache duration of 365 days and the `immutable` [directive](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Cache-Control#revalidation_and_reloading), so re-adding the `integrity` attribute might cause issues for visitors/clients that still have the minified version in their cache 😞 And because refreshing won't cause a cache revalidation request, the only reliable way is to change the file name/URL... Purging the Cloudflare cache also won't fix this issue for the same reason.

We'll re-add the SRI attributes when any of the affected sites require an update and the file names/hashes have changed, so no further action is required 😄
