### ISSUE TITLE
Coordinating meeting

### ISSUE THREAD

**Issue by MartinGrove** [umbraco/Umbraco.Cloud.Issues#296]
Hi Darek

As agreed this feature request is in order to arrange a meeting regarding an integration. We are not able to lower our security so we need to meet with you and e-Bureauet. When you accept I will find time in first week of the new year.

Thanks
Martin

**Comment by nul800sebastiaan** [comment]
Hi @MartinGrove, I think this was supposed to be an email to Darek? I'll close this, make sure to reach out to Darek through your normal support channels.
