### ISSUE TITLE
GraphQL query returning null for all URLs

### ISSUE THREAD

**Issue by AdrianFleming** [umbraco/Umbraco.Cloud.Issues#298]
Having created an editor based on Media Picker with the following properties:
Pick multiple items = false
Pick only images = true
Disable folder select = false
Start node set to a folder
Ignore user start nodes = false

Then the following query is returning null for all URLs:
```
query {
  allNewsPost {
    items {
      thumbnail {
        url
      }
      mainImage {
        url
      }
    }
  }
}

```

**Comment by sitereactor** [comment]
We will have a look at this in the upcoming sprint starting Januar 4th.

**Comment by sitereactor** [comment]
@AdrianFleming Hi Adrian, sorry about the delay in getting back on this bug report. Hope you had a good New Years!

Could we get you to reach out to the Support team through the Chat functionality in the Umbraco Cloud Portal with the project details for which this is happening and reference this bug report, so they know to forward it to me? We have a hard time replicating the issue, so it would be ideal if we can have a look at your project the and the content structure, data types, etc.
