### ISSUE TITLE
OrderBy a DateTime field returning invalid cursor

### ISSUE THREAD

**Issue by AdrianFleming** [umbraco/Umbraco.Cloud.Issues#299]
We have a document type with a field of type Date Picker with Time, and want to use this for sorting. The following query:

query {
  allNewsPost(
    orderBy: createDate_DESC
    first: 1
  ) {
    items{
      publishedDateTime
    }
    edges {
      cursor
    }
  }
}

Returns a cursor "eyJjcmVhdGVEYXRlIjoiMjAyMC0xMi0xN1QxNToxNTozMy4xMTcifQ==" which can successfully be used in an after parameter, however changing the orderBy parameter to publishedDateTime_DESC returns a cursor "eyJkYXRhLVx1MDAzRVx1MDAyN2VuLUdCXHUwMDI3LVx1MDAzRVx1MDAyN3Byb3BlcnRpZXNcdTAwMjctXHUwMDNFXHUwMDI3cHVibGlzaGVkRGF0ZVRpbWVcdTAwMjciOiIyMDIwLTEyLTE3VDEyOjAwOjAwIn0=".

The following query:

query {
  allNewsPost(
    orderBy: publishedDateTime_DESC
    first: 1
    after: "eyJkYXRhLVx1MDAzRVx1MDAyN2VuLUdCXHUwMDI3LVx1MDAzRVx1MDAyN3Byb3BlcnRpZXNcdTAwMjctXHUwMDNFXHUwMDI3cHVibGlzaGVkRGF0ZVRpbWVcdTAwMjciOiIyMDIwLTEyLTE3VDEyOjAwOjAwIn0="
  ) {
    items{
      publishedDateTime
    }
    edges {
      cursor
    }
  }
}

Throws an error "Error trying to resolve field 'allNewsPost'."

**Comment by sitereactor** [comment]
We will have a look at this in the upcoming sprint starting Januar 4th.
