### ISSUE TITLE
Be able to add name or description together with IP address on the ip-whitelist

### ISSUE THREAD

**Issue by jesperbrasmussen** [umbraco/Umbraco.Cloud.Issues#30]
It would be nice to be able to add a name or description that can be shown together with an IP address in the ip-whitelist. 
The reason is that it's hard to remember what the purpose was with the different IP's and to whom they belong.

**Comment by FransdeJong** [comment]
I was just about to add this issue to the tracker. It is really hard to keep track of who's IP is in the whitelist. Especially if you have clients without a fixed IP.

**Comment by soreng** [comment]
I was just about to add this request too :)

Also, it would be nice to have an indication of what IP is matched for getting the "Your IP address is on the list"
![image](https://user-images.githubusercontent.com/359492/106605727-87d44280-6561-11eb-8f06-92c02eccb256.png)

maybe something like:
![image](https://user-images.githubusercontent.com/359492/106605961-cff36500-6561-11eb-8c35-3722a3959a26.png)

**Comment by sajumb** [comment]
This issue is closed as the feature request has been implemented and is in production.
