### ISSUE TITLE
Cannot invite users with special characters in the mail to the project/backoffice

### ISSUE THREAD

**Issue by RyuLindow** [umbraco/Umbraco.Cloud.Issues#305]
## Description

It is currently not possible to invite users to the backoffice or to the project via the Cloud portal if they have a special character in their mail. e.g. æøå@mail.com

Do note that I wasn't able to test it properly with a mail that has a domain with special characters e.g. name@domæin.dk, as I don't have access to such mail.

## Testing
It's not possible to log in to a cloud project with a mail that has æøå or other special characters like ., etc.

So I bought ragnarøk.dk to test stuff on Cloud.

I also made a project with that name to see how it'll behave.

Today, I tried to create das@ragnarøk.dk in the backoffice as a user(it's a fake mail that doesn't exist) and I'm unable to log in.

ragnarøk.dk will get translated into Punycode into xn--rangark-v1a.dk

If you click on http://xn--rangark-v1a.dk/ then you will get taken to ragnarøk.dk and see that in the URL but if you copy it from the URL, you'll see http://xn--rangark-v1a.dk/

because of that, I thought that trying to log in with das@xn--rangark-v1a.dk would work but no luck either.

### More testing:

1. Created a user via the backoffice with a mail: das@ragnarøk.dk
2. Tried to log in with that user and got "Login failed for user das@ragnarøk.dk"
3. Then I changed the ø too in the backoffice so that the mail was das@ragnarok.dk instead and was able to log in just fine.

Since I don't have an actual mail with special characters in the domain that has an inbox I was unable to try to invite that user instead of or invite it via the portal.
I checked the Cloud and CMS issue trackers and was unable to find anything related which is very surprising, as I would expect at least 1 post about this.
Also, if I try to add a special character to the name part of the mail rather than to the domain, I get a validation error that says"Invalid mail".
![image](https://user-images.githubusercontent.com/56826332/104059813-351f9900-51f6-11eb-87bd-d936d07cad1d.png)

It does seem like the validation differs if you have special characters name@HERE.com instead of HERE@domain.com but like mentioned above, I cannot test inviting such user, as I don't have access to that a mail like that.

### Inviting a user to the backoffice:
![image](https://user-images.githubusercontent.com/56826332/104059885-56808500-51f6-11eb-9824-5fe0d1dcdc2d.png)

### Inviting a user to the project via the portal:
![image](https://user-images.githubusercontent.com/56826332/104059908-5f715680-51f6-11eb-8e0e-17a327f7e847.png)

**Comment by nul800sebastiaan** [comment]
As you've noticed, currently we don't support these characters in neither the portal nor in the CMS itself. I am not sure if this was a customer request or if you were just trying to get it to break? In any case, we're not currently planning on supporting these characters, but it would be good to be able to in the future, I'll put this on the list of ideas for later.

**Comment by RyuLindow** [comment]
A customer had a Danish domain the mail and could use that, so that's why I tested this further and made this amazing feature request :)

**Comment by sajumb** [comment]
We are closing this. As Dane with an 'ø' I am very much aware that the inclusion of this special letters are a no-go for 97% for all SaaS solutions out there. :-) We won't add support for the inclusion of e.g. ø, æ or å any time soon. Accordingly, we are closing this one.
