### ISSUE TITLE
Heartcore/GraphQL: Cache not updated when deleting a node with the Content Management API

### ISSUE THREAD

**Issue by HalldorLyngmo** [umbraco/Umbraco.Cloud.Issues#306]
When using the Content ManagementAPI to [delete ](https://our.umbraco.com/documentation/Umbraco-Heartcore/API-Documentation/Content-Management/content/#delete-content) published nodes they aren't removed from the GraphQL cache.

Reproduction
------------

### Bug summary

It doesn't matter if you create and publish the node with the Content Management API or use the default way in the backoffice. If the node hasn't been unpublished before it's deleted with the API it will stay in the GraphQL cache and show up even though it's not visible in the backoffice anymore.

It looks like the event to trigger the cache update is not being fired when deleting the node with the API. 
However, unpublishing the node with the API works as it should and the node is removed from the cache. 

### Specifics
Tested on a fresh project using latest on
- Umbraco Heartcore - Pro plan

### Steps to reproduce

1. Create a new document type and allow it as a root node.
2. Create a node and publish it.
3. Check the GraphQL playground using a query to see all the data
```
{
  allContent {
    edges {
      node {
        name
        id
      }
    }
  }
}
```
4. Delete the node with the Content Management API
5. Check the GraphQL playground and the node will still be there.

### Expected result

The node should be removed completely from the GraphQL cache. 

### Actual result

The node is still there.

**Comment by sitereactor** [comment]
We have found out why this is happening and working on getting a fix out this week.
I will update this thread once we have verified the fix.

Thanks for the detailed bug report!

**Comment by sitereactor** [comment]
Reopening this issue, as the fix hasn't been rolled out yet.
Will keep it open until the fix has been rolled out to all Heartcore projects.

**Comment by sitereactor** [comment]
The fix for this issue was released January 25th
