### ISSUE TITLE
Add users profile image to the API

### ISSUE THREAD

**Issue by RyuLindow** [umbraco/Umbraco.Cloud.Issues#309]
Currently, every node and image has these values when you call them via an API:

"_creatorName"
&
"_writerName"

As a backoffice user, you can upload an image which is then used as your profile picture, however, it's only visible in the backoffice.
![image](https://user-images.githubusercontent.com/56826332/104827300-73ebc980-585c-11eb-9b3d-ff676f79ee97.png)

I think that it would be a nice addition if that image got added below the creator and writer names as _creatorAvatar and _writerAvatar respectively.

The names can be used for e.g. adding an author field and it would be quite nice if you could just pull the image as well instead of having to create a custom field for that.

Our blogs are a perfect use case for this
![image](https://user-images.githubusercontent.com/56826332/104827392-63881e80-585d-11eb-80e0-bc3a74663b31.png)

**Comment by RyuLindow** [comment]
Related comment, although about GraphQL.

When I query the same data using GraphQL I can't seem to find either of the "creatorName" or "writerName" properties. They don't exist there and I would love to get them added together with the avatar to GraphQL as well if possible.
[GIF](https://i.imgur.com/Pdl5jne.gif)

I didn't want to spam the tracker, so I wrote this here but let me know if you would rather have me make a separate feature request for this, @nul800sebastiaan

**Comment by nul800sebastiaan** [comment]
They're really not very much meant for the frontend. We usually recommend setting up some writer profiles as Umbraco nodes instead that you can link to each article. That way you can also have multiple authors etc.

**Comment by RyuLindow** [comment]
I suppose that works as well 🤔

**Comment by rasmusjp** [comment]
As @nul800sebastiaan mentions the User info is not really meant for the frontend and you would be better of creating a "Author" document type instead, we do this in the Blog sample. This will also give you more flexibility in terms of having a different author than the one who creates the page in Umbraco.

I'm closing this for now.
