### ISSUE TITLE
Unable to restore Umbraco Forms from development environment

### ISSUE THREAD

**Issue by SRandomName** [umbraco/Umbraco.Cloud.Issues#310]
Created 4 forms and transferred them to our cloud development environment. A while after that I had a local database issue and created a new database. Result -> Forms offcourse are not there anymore. But the forms had been pushed earlier to cloud development environment so I want to use the 'Full Restore' button in the backoffice to restore the forms. 

**Problem ?**
The full restore UI is stuck and gives no information. No console errors aswell. Only these errors in the UmbracoTraceLog:
```
{"@t":"2021-01-19T08:44:52.5671615Z","@mt":"User {user} ({userId}) {message}","message":"starting restore from https://dev-cloudenvironment/umbraco/backoffice/Deploy/Environment/","SourceContext":"Umbraco.Deploy.UI.Controllers.UiControllerBase","ProcessId":33176,"ProcessName":"iisexpress"
{"@t":"2021-01-19T08:44:52.5671615Z","@mt":"Beginning deployment {id}.","id":"39968222-aca5-4a94-8273-f01ed4b6fba2","SourceContext":"Umbraco.Deploy.Work.WorkEnvironment","ProcessId":33176,"ProcessName":"iisexpress"
{"@t":"2021-01-19T08:44:52.5700468Z","@mt":"Suspend scheduled publishing.","SourceContext":"Umbraco.Web.Suspendable+ScheduledPublishing","ProcessId":33176,"ProcessName":"iisexpress"
{"@t":"2021-01-19T08:44:52.5700468Z","@mt":"Suspend database.","SourceContext":"Umbraco.Deploy.SignatureRefresher","ProcessId":33176,"ProcessName":"iisexpress"
{"@t":"2021-01-19T08:44:52.6354395Z","@mt":"Get remote session","SourceContext":"Umbraco.Deploy.Work.WorkItems.TargetRestoreWorkItem","ProcessId":33176,"ProcessName":"iisexpress"
{"@t":"2021-01-19T08:44:52.8098680Z","@mt":"Create manifest on source","SourceContext":"Umbraco.Deploy.Work.WorkItems.TargetRestoreWorkItem","ProcessId":33176,"ProcessName":"iisexpress"
{"@t":"2021-01-19T08:45:15.3518757Z","@mt":"Exception!","SourceContext":"Umbraco.Deploy.Work.WorkItems.TargetRestoreWorkItem","ProcessId":33176,"ProcessName":"iisexpress"
{"@t":"2021-01-19T08:45:15.3532765Z","@mt":"Abort remote session","SourceContext":"Umbraco.Deploy.Work.WorkItems.TargetRestoreWorkItem","ProcessId":33176,"ProcessName":"iisexpress"
```

**Steps to reproduce**
1. Create form on localhost
2. Queue for transfer to cloud environment
3. Delete localhost database
4. Full restore from same cloud environment where you transfered the forms to.

Any ideas how to fix this issue ? Thanks !

**Comment by SRandomName** [comment]
@nul800sebastiaan  - Extra information. This error does not only occurs when using the Umbraco Forms Full Restore button. But ALSO when using the partial/full restore button on the Umbraco Content.

**Comment by nul800sebastiaan** [comment]
Thanks @SRandomName I haven't gotten to this yet, but did you reach out to Cloud support with your problem?

Please also note version numbers (Umbraco, Forms, Deploy) when creating issue so we know how to reproduce. But first, please make sure to talk to Cloud support.

**Comment by SRandomName** [comment]
@nul800sebastiaan - Yes i've reached out to Cloud Support. But no solution yet.
**Version numbers:** 
Umbraco - v8.8.2
Forms - v8.5.3 - Saving forms in database
Deploy - v3.5.3

**Comment by Sven883** [comment]
Solution - Dashboard 'Workspaces' should always be in first place. If another package creates a new dashboard be sure to set the weight of the dashboard in package.manifest so the 'Workspaces' dashboard is still in first place.

**Comment by SRandomName** [comment]
@nul800sebastiaan : I changed the weight of the plumber 2 dashboard to 40 so my 'workspaces' dashboard is first in place. I can now restore content.

BUT, when restoring forms I get another error about 'Schema mismatch' which is weird because all my cloud environments are in sync and restoring normal content shouldn't not work either if there is a schema mismatch.

Any ideas ?

**Comment by nul800sebastiaan** [comment]
Good to hear that fixed it!

I would once again encourage you to reach out to Cloud support to get help with schema mismatch errors. :) 

Just as an FYI: the support chat is for asking questions as to why things do not work, they will encourage you to create a bug report if there's an issue that has been identified and can be reproduced. I'll close this one and trust that you will get the help you need from our support team. 👍
