### ISSUE TITLE
Heartcore: Adding a webhook to localhost breaks the webhook logs

### ISSUE THREAD

**Issue by hjaltedaniel-umbraco** [umbraco/Umbraco.Cloud.Issues#314]
If you add a webhook to localhost on your Heartcore project, and let the webhook fire it breaks your webhook log entries.

Reproduction
------------

If you're filing a bug, please describe how to reproduce it. Include as much
relevant information as possible, such as:

### Bug summary
If you go to the webhook section and add a webhook to eg. http://localhost:3000, you're not warned that something could be up with this. However - when the webhook fires, and you go into the logs to look into what has happened you get an error:
![image](https://user-images.githubusercontent.com/61144403/106114010-603f3d80-614f-11eb-8bbd-23f79d267368.png)

Nothing is logged in the Umbraco Logs around this.

### Specifics
I get this error on the newest versions of Heartcore. The following DLLs are present in the project;
- Umbraco.Cloud.Headless.dll: 2.4.3

I only get this in the developer console:
`{"errorMsg":"Failed to get webhook log entries","data":"","status":500}`
Nothing is logged in Umbraco logs.

### Steps to reproduce

1. Create a webhook that points towards a localhost url
2. Trigger the webhook by eg. publishing a content node

Then your log entries will be messed up

### Expected result
I see two possible;

1. You get an error when trying to add an invalid URL to the webhook
2. The log shows an error

### Actual result
Log is broken and you get an error when trying to show it:
![image](https://user-images.githubusercontent.com/61144403/106114010-603f3d80-614f-11eb-8bbd-23f79d267368.png)

**Comment by rasmusjp** [comment]
Note to self: I think this happens because the response is empty

**Comment by sitereactor** [comment]
A fix for this issue has been deployed to Production. There is a disconnect between this issue being closed and when its actually deployed to Production, because there is testing in between the fix and the deployment, which unfortunately is not automatically captured here on github.
