### ISSUE TITLE
Heartcore: Media URL transform creates invalid querystring

### ISSUE THREAD

**Issue by thebuilder** [umbraco/Umbraco.Cloud.Issues#318]
Using the `url()` method on [Media](https://our.umbraco.com/documentation/Umbraco-Heartcore/API-Documentation/GraphQL/Schema-Generation/#media) to resize the image, results in an invalid url being returned. The querystring begins with a `&` instead of `?`.

**Input**

```graphql
{
  homePage(url: "/") {
    pageContentHeroImage {
      url
      broken: url(width: 1200)
    }
  }
}
```

**Output**

```json
{
  "data": {
    "homePage": {
      "pageContentHeroImage": {
        "url": "https://media.umbraco.io/dev-charlie-tango-gr8-heartcore/8d8bb8fa7b6ca98/spaceman.jpg",
        "broken1": "https://media.umbraco.io/dev-charlie-tango-gr8-heartcore/8d8bb8fa7b6ca98/spaceman.jpg&width=1200&upscale=false"
      }
    }
  }
}
```

**Expected**

```diff
-spaceman.jpg&width=1200&upscale=false
+spaceman.jpg?width=1200&upscale=false
```

## Reproduction

Create a query for a media element, and try to transform the URL by setting a property.

```graphql
{
  homePage(url: "/") {
    heroImage {
      url(width: 1200)
    }
  }
}
```

**Comment by dawoe** [comment]
As mentioned in #350  is to use add a cropMode parameter to the url call.

**Comment by sitereactor** [comment]
A fix for this issue has been deployed to Production. There is a disconnect between this issue being closed and when its actually deployed to Production, because there is testing in between the fix and the deployment, which unfortunately is not automatically captured here on github.
