### ISSUE TITLE
Cloudflare DNS obfuscates email addresses

### ISSUE THREAD

**Issue by ronaldbarendse** [umbraco/Umbraco.Cloud.Issues#319]
Similar to https://github.com/umbraco/Umbraco.Cloud.Issues/issues/295, I just noticed when a hostname uses the new Cloudflare DNS (dns.umbraco.io), all email addresses are getting obfuscated and some JavaScript is added to the HTML: https://support.cloudflare.com/hc/en-us/articles/200170016-What-is-Email-Address-Obfuscation-.

Reproduction
------------

### Bug summary
Umbraco Cloud alters the HTML returned and doesn't allow turning this off.

### Steps to reproduce
- Add an email address to a page on Umbraco Cloud
- Visit the site using the *.s1.umbraco.io URL: it shows the correct email address in the HTML
- Visit the site using a custom hostname configured using dns.umbraco.io: the email address is obfuscated and a script in injected right before the `</body>` tag

### Expected result
Same as https://github.com/umbraco/Umbraco.Cloud.Issues/issues/295: Umbraco Cloud should not enable application specific features without a maintenance notice and/or provide a documented opt-out in case this doesn't work in a specific agency/client setup.

### Actual result
Application features are getting enabled randomly and not getting communicated/documented. Even though email obfuscation might be enabled with all good intentions, these kind of changes can break applications!

**Comment by sitereactor** [comment]
Hi @ronaldbarendse thanks for flagging this. There has been a few settings that were enabled for our custom hostnames (by default), which we didn't anticipate. That is of course super unfortunate, so apologies for that. Had this been intentional we would have advertised it.

I found the Email Obfuscation setting and turned it off, so it should be back to normal now. I will close this issue as it should have taken effect already, but do let me know if you find otherwise.

**Comment by ronaldbarendse** [comment]
@sitereactor Thanks for fixing/correcting this so quickly! I can confirm it has already taken effect 👍🏻

I really hope the transition to Cloudflare will be worth it, as I've noticed multiple issues like this (including missing documentation on CAA records, which I see is [updated about a month ago](https://our.umbraco.com/documentation/Umbraco-Cloud/Set-Up/Manage-Hostnames/#using-certificate-authority-authorization-caa-for-your-domain)) and having to update all DNS settings in the coming weeks, which is a major inconvenience (putting it mildly). All this will probably make it possible to change the endpoint per project/hostname in Cloudlfare, so the transition from the PaaS to SaaS platform will barely be noticeable, so I really hope this all goes well...

**Comment by sitereactor** [comment]
I would have hoped that anyone who actively sets a CAA record for their domain would be aware of the implications when using a service with automatic generation and use of ssl certificates. But interestingly we have seen it come as a surprise to some even though it was have been the same with Let's Encrypt certificates. Happy to have the documentation in place though, and we'll look into having it as a preflight check as well, so we can make it a lot more discoverable.

We'll be opening up for different caching and security settings per hostname on the other side of this DNS update, so we hope it will be worth it. We are well aware that its an inconvience, but it has to be done so we can use it to smooth the transition to the new infrastructure.

**Comment by ronaldbarendse** [comment]
> I would have hoped that anyone who actively sets a CAA record for their domain would be aware of the implications when using a service with automatic generation and use of ssl certificates.

Yes, but Cloudflare [uses different CAs](https://support.cloudflare.com/hc/en-us/articles/115000310832-Certification-Authority-Authorization-CAA-FAQ), so it's not as clear as adding `CAA 0 issue "letsencrypt.org"` for Let's Encrypt 😉 Having a check when adding the hostname would be a very nice addition indeed!

> We are well aware that its an inconvience, but it has to be done so we can use it to smooth the transition to the new infrastructure.
I totally understand and it would otherwise be an even bigger inconvenience if updating the DNS would require coordination with transitioning to the new infrastructure. Thanks for your replies!
