### ISSUE TITLE
Cannot add Emails and users with names containing æåø

### ISSUE THREAD

**Issue by Frost117** [umbraco/Umbraco.Cloud.Issues#32]
A brief description of the issue goes here.

Reproduction
------------

### Bug summary

In the cloud portal it is not possible to add a user with an email containing æåø.
Similar to the edit team page, it is not possible to add an email account with a user containing æåø.

![image](https://user-images.githubusercontent.com/32164310/50148703-78c6a380-02b9-11e9-8fa7-8288117e727c.png)

![image](https://user-images.githubusercontent.com/32164310/50148732-8a0fb000-02b9-11e9-96f5-e1b250478e81.png)

![image](https://user-images.githubusercontent.com/32164310/50148758-9ac02600-02b9-11e9-8472-2228c422e792.png)

### Specifics

The error happens on the project overview of a project and under the edit team section of the project.

Umbraco 7.12.4
Forms 7.0.4
Deploy 2.0.14

The same behavior is happening in Firefox and EE

I noticed that these validation errors only happens on the top field, so maybe something fishy is happening there?

### Steps to reproduce

Click add member, in the project overview.

Type in an email with "æøå" and fill in a name.
Click in the invite message section and you'll get a validation error.

Next go to the edit team section.

Click add member.
Fill in a name that contains a "æåø" character.
and a email that also has "æåø" character.

### Expected result

That you can add any email or name with these characters.

### Actual result

Get validation error.

**Comment by pijemcolu** [comment]
Should be fixed in https://github.com/umbraco/Concorde/pull/409 & https://github.com/umbraco/Concorde/pull/414

**Comment by mikkelhm** [comment]
Closing with latest PR 414
