### ISSUE TITLE
IPv6 support for environments protected with basic authentication (via Cloudflare)

### ISSUE THREAD

**Issue by orsinic** [umbraco/Umbraco.Cloud.Issues#320]
When enabling basic authentication on an environment (development or staging) to secure it, the following YSOD error appears when browsing the site from an IPv6 address:

> System.FormatException: Current ip '2a02' could not be converted to type IpAddress.
>    at Concorde.Security.WebsiteModule.BasicAuthentication.IsInIpRange(String ipAddress, String cidrIpRange)
>    at Concorde.Security.WebsiteModule.BasicAuthentication.IsWhitelisted(HttpApplication app)
>    at Concorde.Security.WebsiteModule.BasicAuthentication.NeedsBasicAuthentication(HttpApplication app)
>    at Concorde.Security.WebsiteModule.BasicAuthentication.ContextAuthenticateRequest(Object sender, EventArgs e)
>    at System.Web.HttpApplication.SyncEventExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute()
>    at System.Web.HttpApplication.ExecuteStepImpl(IExecutionStep step)
>    at System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously)

Using the same host name on the same project/environment worked when it was still using Latch. Since we changed the DNS yesterday (CNAME to dns.umbraco.io as per best practices) and re-added the host name the above error shows. So seems to be related to Cloudflare.

Workaround
------------
Had contact with Hjalte from support and he suggested to change my default TCP/IP settings to use IPv4 instead (https://www.irangers.com/how-to-change-default-tcpip-from-ipv6-to-ipv4/). After rebooting the (protected) website indeed works for me. But it's not an ideal solution since we cannot (or should not) ask our clients and testers to do this.

Please note that this error even appears before any authentication can be done. So in case your IP is not whitelisted you should get the popup to authenticate with your cloud credentials - but it doesn't get there.

Reproduction
------------
* Enable basic authentication for a cloud site/environment
* Add a custom domain (with Cloudflare TLS)
* Browse the custom domain from an IPv6 IP address
* Throws the error "System.FormatException: Current ip 'xxxx' could not be converted to type IpAddress."

Is this behavior expected and known? Is there another way around this?
I did not explicitly enable IPv6 myself, so I suppose this could be the case for others (including clients) as well.

Expected behavior
------------
* Enable basic authentication for a cloud site/environment
* Add a custom domain with Cloudflare TLS
* Browse the custom domain from an IPv6 IP address
* See the website without errors (considering any IP's whitelisted in the portal, preferably also IPv6)

**Comment by sitereactor** [comment]
Hi @orsinic thanks for reporting this. I looked through the code for our Basic Auth module and can see where it could go wrong with an IPv6 and IP filter ranges in IPv4. We'll work on a fix for this today and let you know when its rolled out.

**Comment by orsinic** [comment]
Hi @sitereactor: thanks a lot for your quick response, much appreciated!
Looking forward to your fix, let me know if we can test and/or provide further input.

**Comment by sitereactor** [comment]
Cheers! It's going through internal review now, but rolling it out is a little complicated, so you might need to get in touch with support when its ready for you to try out. But I will keep you posted and reply back when we have something ready for testing.

**Comment by orsinic** [comment]
Hi @sitereactor! Any news on this one? I believe nothing was rolled out yet to fix this, correct?
Thanks! :-)

**Comment by orsinic** [comment]
Hi @RobertCopilau - unfortunately I cannot confirm this is fixed. Should it be? Does anything need to be changed on the project or host name to activate this?
Would be great to get some extra context.

Thanks.

**Comment by sitereactor** [comment]
We might need to recycle or reprovision the site to ensure that it uses the updated basic auth module. We can do it for you if you reach out to support through the Umbraco Cloud Portal.
