### ISSUE TITLE
View assembly version in Cloud Portal

### ISSUE THREAD

**Issue by Adolfi** [umbraco/Umbraco.Cloud.Issues#325]
Besides the information of current Umbraco- / Forms- / Deploy version, it would be very useful if I could see the current assembly version from each environment in that view.

Background: We deploy using octopus deploy and feature branches and each time we do the assembly version reflects the release number. So when QA finds a bug in an environment they need to know in which version they should report that bug. Would be nice if we could see this in the portal.

**Comment by nul800sebastiaan** [comment]
Hi @Adolfi, just for clarification: is this so your customers can find the assembly version when reporting bugs in your custom dlls? Did I understand that correctly?

Would YOU and your team use this to find sites with this assembly version?

Thinking out loud I would say the customer is using the Umbraco backoffice and it might be easier for them to see the versions in a dashboard there. Maybe there's a good reason to put it in the Cloud Portal though?

**Comment by Adolfi** [comment]
Hi @nul800sebastiaan!
No this is for our developement team, mostly our QA/Project managers who are testing the website and reporting bugs.
But now as you mention it it might actually make more sense to create some sort of custom dashbord with this kind of information then we will get it in all our non-cloud sites as well. And as you mentioned, sometimes the end client reports bugs and they dont hang around in the cloud portal, so it makes sense to have it in a dashbord in back-office instead.

I'm closing this feature request and create a package for this and share on our instead.

Cheers!

**Comment by nul800sebastiaan** [comment]
Thanks @Adolfi - also makes more sense for us, as we would need to somehow figure out which assembly versions to show for you and a way to configure that. I think it makes a lot more sense inside the context of the actual site instead! 👍
