### ISSUE TITLE
Appearance for property label not being deployed between environments

### ISSUE THREAD

**Issue by tcmorris** [umbraco/Umbraco.Cloud.Issues#332]
There is an option when editing a property for the label to appear above the property editor.

![image](https://user-images.githubusercontent.com/2123628/110502355-0a1ccd00-80f3-11eb-93a5-8d0ad7645d3a.png)

Unfortunately, this doesn't appear to be persisted between environments. Looking at the .uda files in the data/revision folder, there is no data associated with this option.

In the example below, both of these have the 'Label above (full width)' option ticked in the property settings. 

![image](https://user-images.githubusercontent.com/2123628/110502753-6384fc00-80f3-11eb-8a62-c951e362e401.png)

Reproduction
------------

### Bug summary

'Label above (full width)' option is not deployed between environments.

### Specifics

Umbraco 8.11.1
Deploy 3.5.4

### Steps to reproduce

1. Create doc type
2. Create new property
3. Add required info for property
4. Tick the 'Label above (full width)' option
5. Commit changes of the .uda files
6. Deploy to another environment
7. The value is not updated

### Expected result

Would expect the 'Label above (full width)' option to persist between environments.

### Actual result

Have to tick this option manually on each environment instead.

**Comment by nul800sebastiaan** [comment]
Thanks @tcmorris - that is a funny one, we haven't added any new properties like that for ages so we didn't remember to also update Deploy for this, whoops! We're looking into it and will keep you posted :)

**Comment by warrenbuckley** [comment]
Fixed in this PR https://github.com/umbraco/Umbraco-Deploy/pull/475
Due for release in Deploy 4.0.3
