### ISSUE TITLE
Rename "Invite member" on Umbraco Cloud project

### ISSUE THREAD

**Issue by bjarnef** [umbraco/Umbraco.Cloud.Issues#336]
Currently on Umbraco Cloud project there a feature "Invite member". However I think this should be renamed to "Invite user" to not confuse with Umbraco Members and since it actually add an Umbraco Backoffice User.

![image](https://user-images.githubusercontent.com/2919859/111440726-ea932f00-8706-11eb-9fe6-5978f7db2f21.png)

**Comment by nul800sebastiaan** [comment]
Good point! 👍

**Comment by bjarnef** [comment]
@nul800sebastiaan I think this can be closed now 😁

**Comment by bjarnef** [comment]
@nul800sebastiaan wasn't this fixed some time ago?

![image](https://user-images.githubusercontent.com/2919859/191007260-9dee60b9-1087-4b04-a653-b47a5ba4ee33.png)

it is fixed here though.

![image](https://user-images.githubusercontent.com/2919859/191007365-8cf47d81-68fc-447b-aa21-179b53700e0a.png)

**Comment by bjarnef** [comment]
I think it makes sense to be consistent using "Users" to not refuse with Umbraco members.

and maybe redirect https://www.s1.umbraco.io/organization/my-organization/members to https://www.s1.umbraco.io/organization/my-organization/users

**Comment by sajumb** [comment]
Hi @bjarnef,
Thanks for highlighting this. I can understand that mentioning "User" and "Member" in the portal can seem related to concepts of users and members in the backoffice. We are planning to do something about this to avoid any confusion.

We prefer the terms "Team member" and "Organization member" in Umbraco Portal. Currently, we are not explicit in our use of these terms, but we plan to change the references soon. In this future change, we might avoid the term "User" and instead use the terms "Team member" and "Organization member" where possible. The button text "Invite member" / "Invite user" (which naturally should be consisted) could be changed to "Invite to Project Team" and "Invite to Organization", respectively.

Would the above approach from your perspective outline the differences between the types of users/members more efficiently?

**Comment by bjarnef** [comment]
Hi @sajumb 

Yes, I think that would eliminate the confusion. Previously I think "Invite user/member" always created a backoffice user as well, but I am not sure if that is still the case. I guess someone could have access to project and contribute with code, without having access to backoffice.

**Comment by c9mb** [comment]
@bjarnef - Yes I believe that inviting a team member still requires providing backoffice access. You can invite someone with 'No Access' to the project, but must provide some access to the backoffice. I think it would be reasonable to provide a 'No Access' option for the backoffice in an invite. A dev needing project access to work locally doesn't necessarily need backoffice access, and similarly support typically doesn't need backoffice access. Invites currently clutter the backoffice with unnecessary user accounts because there is no option to avoid them being created by the invite.

**Comment by sajumb** [comment]
@bjarnef Great, thanks for verifying.

@c9mb Yes, that would definitely be a nice feature in order to minimize the number of users in the backoffice. Previously an older dependency required that we also created a backoffice user in this scenario. We will look into this as well. Thanks!
