### ISSUE TITLE
Webhooks not working as supposed (in my oppinion)

### ISSUE THREAD

**Issue by patadata** [umbraco/Umbraco.Cloud.Issues#337]
I listen all events to figure out what is happening and the following happens:

- Create an "Item" - Works as expected - content.publish sent to webhook with createdDate = updateDate
- Update an "Item" - Works as expected - content.publish sent to webhook with createdDate < updateDate
- Unpublish an "Item" - Does not work as expected - content.publish sent to webhook with same data as for "Update". There is no way to figure out that it has been unpublished. Umb-Headless-Event should be content.unpublish
- Delete an "Item" - Does not work as expected - content.delete sent to webhook but content is {"_id":"00000000-0000-0000-0000-000000000000"}. No way to figure out what "Item" it is, ID is wrong

## Umbraco version

I am seeing this issue on Umbraco version: Heartcore on the web

Reproduction
------------

If you're filing a bug, please describe how to reproduce it. Include as much
relevant information as possible, such as:

### Bug summary

Se above. Just create, publish, unpublish and delete "Items" and the above will happen

### Specifics

This is specific for Webhooks.

### Steps to reproduce

Se above

### Expected result

Expected result would be

- content.publish is OK for Publish (on create and update)
- content.unpublish with ID = ID of "Item"
- content.delete with ID = ID of "Item"

### Actual result

- content.publish  is OK for Publish (on create and update)
- content.unpublish does not exist
- content.delete with ID = 00000000-0000-0000-0000-000000000000

**Comment by nul800sebastiaan** [comment]
Hi @patadata, thanks for the report. We'll need to investigate and get back at you.

**Comment by sitereactor** [comment]
A fix for this issue has been deployed to Production. There is a disconnect between this issue being closed and when its actually deployed to Production, because there is testing in between the fix and the deployment, which unfortunately is not automatically captured here on github.
