### ISSUE TITLE
The "where" argument doesn't work with a boolean in GraphQL

### ISSUE THREAD

**Issue by RyuLindow** [umbraco/Umbraco.Cloud.Issues#340]
If you try to use the "where" argument in a GraphQL query in Heartcore, you'll get a bug listed at the very bottom.
 
Reproduction
------------
### Bug summary

At first, I've written the query myself. Then followed GraphQL playgrounds' suggestions as I typed. The difference was only some additional spaces in the query but both resulted in the error I've pasted below.

Removing the "where" argument will return a successful response without any problems.

### Specifics

This will work:
```
query {
  all{contentTypeAlias} {
    items {
      name
      {propertyALIAS}
    }
  }
}
```
but this won't:

```
query {
  all{contentTypeAlias} (where: {{propertyALIAS}: false}) {
    items {
      name
      {propertyALIAS}
    }
  }
}
```

It doesn't matter how many nodes of this content type you have.
It doesn't matter at what level in the content tree these nodes are.
The where argument does work of other stuff like text strings but I haven't tested every data type.
I've tried with having the data type set to true and then to false by default - didn't change anything.

### Steps to reproduce

1. Create a doc type with a boolean property
![image](https://user-images.githubusercontent.com/56826332/111871961-19223b80-898d-11eb-8d9c-a744f6bb77fd.png)
2. Create a few content nodes of that type and set the boolean to true while leaving some on false
3. Go to the GrapQL playground and write this query:
```
query {
  all{contentTypeAlias} (where: {{propertyALIAS}: false}) {
    items {
      name
      {propertyALIAS}
    }
  }
}
```
4. Get an error
[VIDEO](https://www.dropbox.com/s/8guaih5heg5ejuz/Pl8hGfK9iA.mp4?dl=0)

### Expected result

The API response returns the data for the content nodes where the boolean is set to false or true depending on what you search for.

### Actual result

```
{
  "errors": [
    {
      "message": "Error trying to resolve field 'allBoolTest'.",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "allBoolTest"
      ]
    }
  ]
}
```

**Comment by sitereactor** [comment]
A fix for this issue has been deployed to Production. There is a disconnect between this issue being closed and when its actually deployed to Production, because there is testing in between the fix and the deployment, which unfortunately is not automatically captured here on github.
