### ISSUE TITLE
Consider adding 51Degrees device detection as a built-in service

### ISSUE THREAD

**Issue by c9mbundy** [umbraco/Umbraco.Cloud.Issues#346]
Umbraco-Cloud is a good candidate for making a standard service such as 51Degrees available to all sites, by implementing access to a common local installation for high-performance, accurate and up-to-date device detection at the server. I note that Sitecore provides 51Degrees as a built-in service. https://51degrees.com/web-platforms

**Comment by nul800sebastiaan** [comment]
Thanks for the suggestion @c9mbundy. Right now we recommend people install packages and/or add this functionality on using NuGet etc. (which I know was not your point). 
We don't have plans to integrate 3rd party platforms at the moment. We have talked about some day providing types of preconfigured sites, but if we pick that up again that's further in the future. 
I'll close this one with the note that we share the desire to have easier 3rd party integrations. 👍

**Comment by c9mbundy** [comment]
Understood @nul800sebastiaan - the comment I would make for future review is that with a platform such as Umbraco-Cloud it's not just about ease of integration, it's also about economy of scale when it comes to providing access to valuable commercial 3rd-party service options - i.e. increasing the value of Umbraco-Cloud by providing access to add-on services that would otherwise be unaffordable for the individual site to install - which was actually my main point. Yes, you can install free versions at the individual site level, but typically if you want to access the advanced features from server-side code then a commercial license is required, at which point strategic agreements with providers of such services can allow Umbraco-Cloud to offer an advantage that private-hosting could not economically match.
