### ISSUE TITLE
Heartcore: Webhooks return nested content in incorrect order (Database fetching order)

### ISSUE THREAD

**Issue by UnicornSez** [umbraco/Umbraco.Cloud.Issues#347]
Description
------------

If a project is using the “new” webhooks which are sent from the platform and not Umbraco, then the data is fetched from a database instead, and we don’t do any ordering when fetching references. This causes the webhook log to look something like this:
```
"component": [
    {
      "position": "3",
      "contentTypeAlias": "component"
    },
    {
      "position": "2",
      "contentTypeAlias": "component"
    },
    {
      "position": "1",
      "contentTypeAlias": "component"
    }
  ]
```

When the actual order should look something like this:
1, 2, 3 and not 3, 2, 1

**Comment by zacheatonvp** [comment]
### **Heartcore Issue**

**--Issue Area--**
    Umbraco Heartcore - Publish Webhook

**--Issue--**
There is an issue with how Heartcore provides the page data at Webhook publish time.

Working functionality:

- Presentation of pages and UI works as normal
- Triggering the page in API playground functions normally in accordance to the presentation in the UI of a page

Broken functionality:
- When you publish a page, the request data from the webhook comes back completely un-ordered for any nested content.

This has worked reliably for the last weeks of development with webhooks.

**--Working Example--**
Myself and Darek commissioned a new project to test this theory, see below (nc-webhooks-test).
We have proved that the order of the nested content comes back as expected, and reliably. 

You can see the order comes back as presented in the UI. 
Item 1
Item 2
Item 3
Item 4
Item 5

`{
    "_totalItems": 8,
    "_totalPages": 8,
    "_page": 1,
    "_pageSize": 1,
    "_links": {
        "self": {
            "href": "https://cdn.umbraco.io/webhook/logs?page=1&pageSize=1"
        },
        "next": {
            "href": "https://cdn.umbraco.io/webhook/logs?page=2&pageSize=1"
        },
        "page": {
            "href": "https://cdn.umbraco.io/webhook/logs{?page,pageSize}",
            "templated": true
        },
        "webhooklogentry": {
            "href": "https://cdn.umbraco.io/webhook/logs{?page,pageSize}",
            "templated": true
        }
    },
    "_embedded": {
        "webhookLogEntry": [{
            "id": "a1eef0b7-ca59-4d08-a0c4-0553cef6ca20",
            "request": {
                "url": "https://nonprod-webhooks.victorianplumbing.co.uk/dev/contentservice/Content/PublishPage",
                "body": "{\r\n  \"_creatorName\": \"Zach Eaton\",\r\n  \"_url\": \"/home/page-example/\",\r\n  \"_writerName\": \"Zach Eaton\",\r\n  \"_urls\": {},\r\n  \"contentTypeAlias\": \"page\",\r\n  \"_hasChildren\": false,\r\n  \"_level\": 2,\r\n  \"name\": \"Page Example\",\r\n  \"parentId\": \"f4ff8a96-1645-4ffd-ae29-fdacf4f734e9\",\r\n  \"sortOrder\": 0,\r\n  \"_createDate\": \"2021-03-29T13:59:44.990Z\",\r\n  \"_id\": \"9557f6cc-5cc0-40f7-9608-39ccf2e275fa\",\r\n  \"_updateDate\": \"2021-03-29T14:20:00.577Z\",\r\n  \"_links\": {\r\n    \"self\": {\r\n      \"href\": \"https://cdn.umbraco.io/content/9557f6cc-5cc0-40f7-9608-39ccf2e275fa\"\r\n    },\r\n    \"ancestors\": {\r\n      \"href\": \"https://cdn.umbraco.io/content/9557f6cc-5cc0-40f7-9608-39ccf2e275fa/ancestors\"\r\n    },\r\n    \"url\": {\r\n      \"href\": \"https://cdn.umbraco.io/content/url?url=%2Fhome%2Fpage-example%2F\"\r\n    },\r\n    \"children\": {\r\n      \"href\": \"https://cdn.umbraco.io/content/9557f6cc-5cc0-40f7-9608-39ccf2e275fa/children\"\r\n    },\r\n    \"descendants\": {\r\n      \"href\": \"https://cdn.umbraco.io/content/9557f6cc-5cc0-40f7-9608-39ccf2e275fa/descendants\"\r\n    },\r\n    \"root\": {\r\n      \"href\": \"https://cdn.umbraco.io/content{?contentType}\",\r\n      \"templated\": true\r\n    },\r\n    \"parent\": {\r\n      \"href\": \"https://cdn.umbraco.io/content/f4ff8a96-1645-4ffd-ae29-fdacf4f734e9\"\r\n    }\r\n  },\r\n  \"components\": [\r\n    {\r\n      \"field\": \"This is some data\",\r\n      \"title\": \"Item 1\",\r\n      \"contentTypeAlias\": \"component\"\r\n    },\r\n    {\r\n      \"field\": \"This is some data\",\r\n      \"title\": \"Item 2\",\r\n      \"contentTypeAlias\": \"component\"\r\n    },\r\n    {\r\n      \"field\": \"This is some data\",\r\n      \"title\": \"Item 3\",\r\n      \"contentTypeAlias\": \"component\"\r\n    },\r\n    {\r\n      \"field\": \"This is some data\",\r\n      \"title\": \"Item 4\",\r\n      \"contentTypeAlias\": \"component\"\r\n    },\r\n    {\r\n      \"field\": \"This is some data\",\r\n      \"title\": \"Item 5\",\r\n      \"contentTypeAlias\": \"component\"\r\n    }\r\n  ]\r\n}",
                "headers": "Content-Type: application/json; charset=utf-8\r\nContent-Language: en-US\r\nUmb-Headless-Event: content.publish\r\nUmb-Headless-Delivery: a1eef0b7-ca59-4d08-a0c4-0553cef6ca20"
            },
            "response": {
                "body": "{\r\n  \"message\": \"Page definition for page could not be found\",\r\n  \"data\": {}\r\n}",
                "headers": "Content-Length: 79\r\nDate: Mon, 29 Mar 2021 14:20:01 GMT\r\nConnection: keep-alive\r\nServer: Microsoft-IIS/10.0\r\nRequest-Context: appId=cid-v1:364dcd0c-e6f2-47ab-a7b0-2042fe8a409d\r\nX-Powered-By: ASP.NET\r\nSet-Cookie: ARRAffinity=3815f870faefb5586c964e997f19c9c687f9ec3d8051f30672296989b835faa3;Path=/;HttpOnly;Secure;Domain=vp-contentservice-dev.azurewebsites.net, ARRAffinitySameSite=3815f870faefb5586c964e997f19c9c687f9ec3d8051f30672296989b835faa3;Path=/;HttpOnly;SameSite=None;Secure;Domain=vp-contentservice-dev.azurewebsites.net",
                "isSuccess": false,
                "statusCode": 400,
                "statusDescription": "Bad Request"
            },
            "requestDate": "2021-03-29T14:20:01.640",
            "event": {
                "id": "content.publish",
                "name": "Publish content"
            },
            "retryCount": 2,
            "_links": {
                "self": {
                    "href": "https://cdn.umbraco.io/webhook/logs{?page,pageSize}",
                    "templated": true
                }
            }
        }]
    }
}`

**Comment by zacheatonvp** [comment]
### **Heartcore Issue**

**--Issue Area--**
    Umbraco Heartcore - Publish Webhook

**--Issue--**
There is an issue with how Heartcore provides the page data at Webhook publish time.

Working functionality:

- Presentation of pages and UI works as normal
- Triggering the page in API playground functions normally in accordance to the presentation in the UI of a page

Broken functionality:
- When you publish a page, the request data from the webhook comes back completely un-ordered for any nested content.

This has worked reliably for the last weeks of development with webhooks.

**--Broken Example--**
This has been provided directly to the Umbraco support team. Please contact Darek. 

**--Working Example--**
Myself and Darek commissioned a new project to test this theory, see below (nc-webhooks-test).
We have proved that the order of the nested content comes back as expected, and reliably. 

You can see the order comes back as presented in the UI. 
Item 1
Item 2
Item 3
Item 4
Item 5

`{
    "_totalItems": 8,
    "_totalPages": 8,
    "_page": 1,
    "_pageSize": 1,
    "_links": {
        "self": {
            "href": "https://cdn.umbraco.io/webhook/logs?page=1&pageSize=1"
        },
        "next": {
            "href": "https://cdn.umbraco.io/webhook/logs?page=2&pageSize=1"
        },
        "page": {
            "href": "https://cdn.umbraco.io/webhook/logs{?page,pageSize}",
            "templated": true
        },
        "webhooklogentry": {
            "href": "https://cdn.umbraco.io/webhook/logs{?page,pageSize}",
            "templated": true
        }
    },
    "_embedded": {
        "webhookLogEntry": [{
            "id": "a1eef0b7-ca59-4d08-a0c4-0553cef6ca20",
            "request": {
                "url": "https://{projectalias}/dev/contentservice/Content/PublishPage",
                "body": "{\r\n  \"_creatorName\": \"Zach Eaton\",\r\n  \"_url\": \"/home/page-example/\",\r\n  \"_writerName\": \"Zach Eaton\",\r\n  \"_urls\": {},\r\n  \"contentTypeAlias\": \"page\",\r\n  \"_hasChildren\": false,\r\n  \"_level\": 2,\r\n  \"name\": \"Page Example\",\r\n  \"parentId\": \"f4ff8a96-1645-4ffd-ae29-fdacf4f734e9\",\r\n  \"sortOrder\": 0,\r\n  \"_createDate\": \"2021-03-29T13:59:44.990Z\",\r\n  \"_id\": \"9557f6cc-5cc0-40f7-9608-39ccf2e275fa\",\r\n  \"_updateDate\": \"2021-03-29T14:20:00.577Z\",\r\n  \"_links\": {\r\n    \"self\": {\r\n      \"href\": \"https://cdn.umbraco.io/content/9557f6cc-5cc0-40f7-9608-39ccf2e275fa\"\r\n    },\r\n    \"ancestors\": {\r\n      \"href\": \"https://cdn.umbraco.io/content/9557f6cc-5cc0-40f7-9608-39ccf2e275fa/ancestors\"\r\n    },\r\n    \"url\": {\r\n      \"href\": \"https://cdn.umbraco.io/content/url?url=%2Fhome%2Fpage-example%2F\"\r\n    },\r\n    \"children\": {\r\n      \"href\": \"https://cdn.umbraco.io/content/9557f6cc-5cc0-40f7-9608-39ccf2e275fa/children\"\r\n    },\r\n    \"descendants\": {\r\n      \"href\": \"https://cdn.umbraco.io/content/9557f6cc-5cc0-40f7-9608-39ccf2e275fa/descendants\"\r\n    },\r\n    \"root\": {\r\n      \"href\": \"https://cdn.umbraco.io/content{?contentType}\",\r\n      \"templated\": true\r\n    },\r\n    \"parent\": {\r\n      \"href\": \"https://cdn.umbraco.io/content/f4ff8a96-1645-4ffd-ae29-fdacf4f734e9\"\r\n    }\r\n  },\r\n  \"components\": [\r\n    {\r\n      \"field\": \"This is some data\",\r\n      \"title\": \"Item 1\",\r\n      \"contentTypeAlias\": \"component\"\r\n    },\r\n    {\r\n      \"field\": \"This is some data\",\r\n      \"title\": \"Item 2\",\r\n      \"contentTypeAlias\": \"component\"\r\n    },\r\n    {\r\n      \"field\": \"This is some data\",\r\n      \"title\": \"Item 3\",\r\n      \"contentTypeAlias\": \"component\"\r\n    },\r\n    {\r\n      \"field\": \"This is some data\",\r\n      \"title\": \"Item 4\",\r\n      \"contentTypeAlias\": \"component\"\r\n    },\r\n    {\r\n      \"field\": \"This is some data\",\r\n      \"title\": \"Item 5\",\r\n      \"contentTypeAlias\": \"component\"\r\n    }\r\n  ]\r\n}",
                "headers": "Content-Type: application/json; charset=utf-8\r\nContent-Language: en-US\r\nUmb-Headless-Event: content.publish\r\nUmb-Headless-Delivery: a1eef0b7-ca59-4d08-a0c4-0553cef6ca20"
            },
            "response": {
                "body": "{\r\n  \"message\": \"Page definition for page could not be found\",\r\n  \"data\": {}\r\n}",
                "headers": "Content-Length: 79\r\nDate: Mon, 29 Mar 2021 14:20:01 GMT\r\nConnection: keep-alive\r\nServer: Microsoft-IIS/10.0\r\nRequest-Context: appId=cid-v1:364dcd0c-e6f2-47ab-a7b0-2042fe8a409d\r\nX-Powered-By: ASP.NET\r\nSet-Cookie: ARRAffinity=3815f870faefb5586c964e997f19c9c687f9ec3d8051f30672296989b835faa3;Path=/;HttpOnly;Secure;Domain={projectalias}, ARRAffinitySameSite=3815f870faefb5586c964e997f19c9c687f9ec3d8051f30672296989b835faa3;Path=/;HttpOnly;SameSite=None;Secure;Domain={projectalias}",
                "isSuccess": false,
                "statusCode": 400,
                "statusDescription": "Bad Request"
            },
            "requestDate": "2021-03-29T14:20:01.640",
            "event": {
                "id": "content.publish",
                "name": "Publish content"
            },
            "retryCount": 2,
            "_links": {
                "self": {
                    "href": "https://cdn.umbraco.io/webhook/logs{?page,pageSize}",
                    "templated": true
                }
            }
        }]
    }
}`

**Comment by zacheatonvp** [comment]
### **Update**

After experiencing this issue on our project across all three environments a couple weeks ago. We requested to be moved to a new project, and our configuration cloned across. Thanks Darek for doing this. 

We believed we had a better chance of not encountering this issue again on a fresh project, however, yesterday on our STAGE environment we saw this introduced on a small scale. It was the top level nested content array in the page, this shortly reverted after a few more publishes. 

Fast forward to today, we have published across all three environments on our new project, and gradually, all of our pages have become infected with this ordering bug. 

After an internal discussion with our team, we have a better idea of what this could be. 

**Predication**
We believe the likely cause for this issue is purely with the management and publishing in webhooks. The most likely candidate for this issue is async calls. There is a reached complexity with using nested content, and at that point, nested content enters a race to retrieve data back regardless of natural order in the page JSON. 

We would like to refer to the approach used in the API playground, in which returns the order of presentation in the page. 

**Questions**
- Whats the main difference between API playground and Webhooks that would create this ordering issue?
- Can the webhook functionality be debugged/ reviewed?
- Why would we experience a normal webhook publish journey on day 1, and with gentle small changes and publishes the next day would trigger an issue such as this? 

Many thanks again for all your time, I hope this helps 

Please contact me if you have any questions. 

@UnicornSez @sitereactor @RyuLindow

**Comment by sitereactor** [comment]
A fix for this issue has been deployed to Production.

**Comment by zacheatonvp** [comment]
> A fix for this issue has been deployed to Production.

This is working perfectly in our new project, thank you!
