### ISSUE TITLE
ArchetypeValueConnector - performance issues

### ISSUE THREAD

**Issue by mikkelhm** [umbraco/Umbraco.Cloud.Issues#35]
We have a case where a site is using the Archetype datatype alot throughout the site. 
Archetype allows the user to nest pieces of content, alot like Nested Content does. When Umbraco Deploy get installed on a site, we also add the Umbraco.Deploy.Contrib dll to the project, which is where the ValueConnector for Archeeype is located. 

When the site contains simple Archetype datatypes, its no big deal, but when using larger and comlex datatypes, it starts to slow the site down on the following operations:
- Save
- Publish
- Transfer content

The reason for the slowdown, seem to come from the GetValue method in the ArchetypeValueConnector, and more specific in its methods `RetrieveAdditionalProperties`. These methods will, for each, fields in a archetype datatype, hit the `_dataTypeservice.GetDataTypeDefinitionById()`-method. The method by it self is not slow, but as it can be called alot of times, during the same method call, the operations will seem to take up alot of time.

A solution could be to cache the calls the the GetDataTypeDefinitionById, as they usually wont be called with alot of different id's but rather use the same handfull of id's. 

For testing/testdata - please contact me @mikkelhm

**Comment by nul800sebastiaan** [comment]
Going through some old issues, this one is was fixed quite a while ago, closing! :)
