### ISSUE TITLE
Checkbox list is emtied after adding a new item

### ISSUE THREAD

**Issue by lisaarman** [umbraco/Umbraco.Cloud.Issues#351]
### Reproduction
------------

When adding a new item to a checkbox list, the list is being emptied in backoffice. 
Here "Test" was added which caused all selected items to be unselected.

Before "Test" was added:
![test](https://user-images.githubusercontent.com/14056633/114388231-b723b300-9b93-11eb-96ae-f013b9434e18.png)

Same page in backoffice after "Test" was added to the checkbox list:
![test-after](https://user-images.githubusercontent.com/14056633/114388306-cc004680-9b93-11eb-872c-74db1a8d26f6.png)

### Specifics

Umbraco versions:
Umbraco 7.12.5
Forms 7.1.3
Deploy 2.0.17

Using Chrome version 89.0.4389.114

### Steps to reproduce

Create a checkbox list, with different values
Check some of the values on a page in backoffice
Add a new value to the checkbox list

### Expected result

The new value is added to the list, and the values that were aldready checked, is still checked.

### Actual result

The new value is added to the list, but the previously checked values are gone, on all pages where it's being used, and must be checked again.

**Comment by nul800sebastiaan** [comment]
Thanks for the report @lisaarman! I unfortunately cannot reproduce this problem on my test project. I also tried deploying the checkbox list from local to live, to see if that was the problem you were seeing, but everything is still checked as it was before. 

I would recommend you upgrade your project to the latest Umbraco 7 (7.15.7
) through

**Comment by nul800sebastiaan** [comment]
Thanks for the report @lisaarman! I unfortunately cannot reproduce this problem on my test project. I also tried deploying the checkbox list from local to live, to see if that was the problem you were seeing, but everything is still checked as it was before. 

I would recommend you upgrade your project to the latest Umbraco 7 (7.15.7) through the [Cloud portal](https://s1.umbraco.io), you should be offered an upgrade when you go to the project you're having trouble with.

**Comment by lisaarman** [comment]
Hi,
I got this answer from Umbraco support, where they were able to reproduce the issue in 7.15.7

_I have tried to reproduce your issue on the following setup:_

_Umbraco 7.15.7
Forms 7.4.1
Deploy 2.1.1_

_And unfortunately, I am able to reproduce the picture that you are seen. So it would be a huge help if you can create an issue on this here on our tracker for Umbraco Cloud._

**Comment by nul800sebastiaan** [comment]
Thanks again @lisaarman - I didn't know this was already tested by support!

I have done some investigations and this started to ring a little bell. I found that this is actually a duplicate issue, the same problem was reported here: https://github.com/umbraco/Umbraco.Deploy.Issues/issues/45

After trying again, I could now indeed see what happened and that it is an actual bug. Please subscribe to issue https://github.com/umbraco/Umbraco.Deploy.Issues/issues/45 to get updates on progress. This will require an upgrade of Deploy in your site when this is fixed, I am unsure if you can do that without having to upgrade the Umbraco version as well.
