### ISSUE TITLE
Heartcore GraphQL : can not  apply a filter on ancestors

### ISSUE THREAD

**Issue by dawoe** [umbraco/Umbraco.Cloud.Issues#352]
According to the documentation it should be possible to apply filters on ancestors, descendants and children .
https://our.umbraco.com/documentation/Umbraco-Heartcore/API-Documentation/GraphQL/Schema-Generation/#default-filter-fields

When I try to do this in the graphql playground I get a error.

Reproduction
------------

### Steps to reproduce

Enter the following query in the graphql playground

```
query {
  content(url: "your-url-here") {   
    ancestors(where: { contentTypeAlias: "homepage" }) {
      items {
        id,
        level,
        name
      }
    }
  }, 
}
```

Replace the url with a url of a existing item, and homepage with the alias of a doctype higher up in the tree.

### Expected result

I would expect the ancestors to be returned that match the filter.

### Actual result

A error is shown in the playground.

```
{
  "errors": [
    {
      "message": "Error trying to resolve field 'content'.",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "content"
      ]
    }
  ],
  "data": {
    "content": null
  }
}
```

So it seems, filters in ancestors calls don't work.

The filter is correct because when I execute this query it works

```
query {
  allContent(where : {contentTypeAlias : "homepage"}){
    items{
      id,
      name,
      contentTypeAlias
    }
  }
}
```

**Comment by sitereactor** [comment]
Thanks for reporting. We'll have a look and get back to this issue when we have an update.

**Comment by sitereactor** [comment]
We are testing a fix for this issue internally and working towards a release later this week. I will keep you posted.

**Comment by sitereactor** [comment]
A fix for this issue has been deployed to Production. There is a disconnect between this issue being closed and when its actually deployed to Production, because there is testing in between the fix and the deployment, which unfortunately is not automatically captured here on github.
