### ISSUE TITLE
Heartcore - allow Tags datatype in Nested content

### ISSUE THREAD

**Issue by Jay-umbr** [umbraco/Umbraco.Cloud.Issues#355]
![image](https://user-images.githubusercontent.com/56038614/114742729-4ecc0180-9d4c-11eb-8ab2-4ee65d2e9f0c.png)

At the moment it is not possible, unsure why.

**Comment by sitereactor** [comment]
Is this specific to Heartcore or is it a CMS limitation?

**Comment by Jay-umbr** [comment]
Good question, one I did not consider. It is actually a CMS limitation.

**Comment by Jay-umbr** [comment]
Since Blocklist has pretty much replaced Nested at this point, I don't think there's much of a chance of making changes to nested content datatype.
Closing this PR

**Comment by jeppeschibsted** [comment]
https://github.com/umbraco/Umbraco.Heartcore.Issues/issues/59

**Comment by sitereactor** [comment]
Tags datatype as well as Upload field, Image Cropper, Block List are not supported within Nested Content.

Not sure what the link to Media Picker v3 is supposed to mean. But I would recommend opening up a new issue or feature request instead of commenting on closed ones.
