### ISSUE TITLE
Login issue for editors without cloud portal credentials

### ISSUE THREAD

**Issue by Ramya-Devendiran** [umbraco/Umbraco.Cloud.Issues#359]
Our project is in Umbraco cloud and it is in development phase. I added Content editors from Umbraco backoffice . When they tried to open cloud.dev.url/Umbraco, the page prompts them to enter Cloud portal credentials first. As they dont have one, they were not able to open the backoffice. 

To fix the issue, I added them as team members in Cloud portal.
 
Actually I don't want editors to have cloud portal access. 

question is how the editors can go to backoffice with only User access provided from backoffice.

**Comment by nul800sebastiaan** [comment]
Hi @Ramya-Devendiran - I am not sure what you've tried, but the invite process is documented here: https://our.umbraco.com/documentation/Umbraco-Cloud/Set-Up/Users-On-Cloud/#umbraco-id

In short: invite your content editors from the backoffice of the site they need to edit and they will be guided through the access process. 

I hope the documentation above helps!

**Comment by Ramya-Devendiran** [comment]
[
[Umbraco cloud login issue - number -359.docx](https://github.com/umbraco/Umbraco.Cloud.Issues/files/6356836/Umbraco.cloud.login.issue.-.number.-359.docx)
](url)
