### ISSUE TITLE
Allow Errors to Be Hidden from Umbraco Could UI

### ISSUE THREAD

**Issue by Nicholas-Westby** [umbraco/Umbraco.Cloud.Issues#36]
After speaking with Umbraco Cloud support, they recommended I create a feature request here.

This is what I'm trying to do with an XDT file to transform the log4net.config file:

```xml
<?xml version="1.0"?>
<log4net xmlns:xdt="http://schemas.microsoft.com/XML-Document-Transform">
  <appender name="UCDbErrors" type="log4net.Appender.AdoNetAppender" xdt:Locator="Match(name)" xdt:Transform="InsertIfMissing">
    <filter type="log4net.Filter.LoggerMatchFilter" xdt:Transform="Insert">

      <!-- There are thousands of "Provider=PDFIndexer" errors, so this ignores them so we get less noise. -->
      <loggerToMatch value="UmbracoExamine.DataServices.UmbracoLogService" />
      <acceptOnMatch value="false" />

    </filter>
  </appender>
</log4net>
```

In short, I'm trying to add a filter to the UCDbErrors appender so that I can ignore certain errors (errors that number in the thousands and that add so much noise to the "View errors" page in Umbraco Cloud that it's useless to try and sift through them all). These are innocuous errors I don't care about from a third party component that I can't change.

So my request is to be able to hide certain types of errors from the Umbraco Cloud UI. That could be via XDT files or via some other mechanism, but it seems right now it is not possible via XDT files.

One idea would be for the XDT file I assume you are using behind the scenes to merge things in a bit more granularly rather than replacing the entire UCDbErrors appender element.

**Comment by nul800sebastiaan** [comment]
Note: this isn't currently possible because we transform this file and add the `UCDbErrors` logger after your transforms run. It's a good idea though to be able to run your updates after we've done ours, but this is currently not implemented that way.

**Comment by sajumb** [comment]
We will be closing this. If this is still relevant please contact us and we might reconsider and open the ticket once again.
