### ISSUE TITLE
Cloud: More than 3 environments

### ISSUE THREAD

**Issue by Jay-umbr** [umbraco/Umbraco.Cloud.Issues#361]
It would be awesome to have more than 3 environments on the Cloud, perhaps some kind of flexible model?
Just an idea for the future 🤞

**Comment by nickrusman** [comment]
As you can see below, we need quite a few more..

How else can we make this happen?
![Umbraco (1)](https://user-images.githubusercontent.com/31825768/115561159-93f4b400-a2b5-11eb-88b4-f437cfb9bd08.jpg)

**Comment by nul800sebastiaan** [comment]
Thanks for the request, at the moment we don't have the infrastructure to support more than 3 environments. We're in the process of migrating to a new infrastructure over the next few months but as far as I know we haven't planned to offer additional environments at this time (I might be wrong).

I know people have worked around this before by hosting their own Azure Web Apps for the environments before production (and of course, we understand that this is not ideal).

I will need to ask around what the plans are for the future and get back to you.

**Comment by nul800sebastiaan** [comment]
I learned that this is indeed something we want to be more flexible about but we don't have a timeline for this yet, so I'll put it on the list of ideas for the future.

As an alternative workaround, you could achieve this using baselines:
Master project: Development, Staging, Live (Pre-Prod or QA)
Child project: Development (Pre-Prod or QA) and Live as the Production instance.

**Comment by nickrusman** [comment]
btw, we use Umbraco Heartcore, how can i add a "Child Project" ?

**Comment by nul800sebastiaan** [comment]
Ah, unfortunately, for Heartcore we don't have baselines available that can be used for this.
