### ISSUE TITLE
Add "Resend Invitation" button to "Manage Team" page

### ISSUE THREAD

**Issue by hfloyd** [umbraco/Umbraco.Cloud.Issues#363]
On the "Manage Team" page, under "Member(s) who still needs to accept project invitation:", it would be great if there was a button to "resend invitation email"

![image](https://user-images.githubusercontent.com/1252593/116277809-d570dd80-a753-11eb-906b-32364e0068f2.png)

So many times I get requests to "resend me the invite" because people can't find the invite in their email or deleted it, or whatever...

As it is, I have to delete and re-add the person, which isn't a big deal, but is kinda silly.

---
_This item has been added to our backlog [AB#11695](https://dev.azure.com/umbraco/243e7927-03b2-44e2-908f-d4ac7ea5daaa/_workitems/edit/11695)_

**Comment by nul800sebastiaan** [comment]
Definitely a great request @hfloyd - let me check at HQ!

**Comment by nul800sebastiaan** [comment]
Got word back from @ksuvec that we can fix this in our next sprint, so hopefully this should be an option in the next few weeks!

**Comment by hfloyd** [comment]
Thanks, @nul800sebastiaan & @ksuvec !

**Comment by ksuvec** [comment]
Hi @hfloyd 

Great input - thank you very much! This feature has been released this morning, so you can re-send the invite!

Keep the inputs coming - we love them!

**Comment by hfloyd** [comment]
Great! Thanks, @ksuvec !
