### ISSUE TITLE
Add a confirmation step to the "Restart environment" button.

### ISSUE THREAD

**Issue by RyuLindow** [umbraco/Umbraco.Cloud.Issues#364]
Pretty much the title.
![image](https://user-images.githubusercontent.com/56826332/116480367-832dda80-a881-11eb-8545-8ddf0334f3f7.png)

Currently, if you click on restart then the env will, well, restart.

Now, there are other options above and below the restart button, so if you happen to misclick, you'll bring the site down for a few minutes.

Adding a confirmation step would be a nice addition.

I was thinking about:
1. only having it on live - my favorite option
2. making it optional, so you can just not use it if you don't like the extra step - kinda eh
3. just add it to all envs - playing it safe

I'm not a fan of this type of security cause it kinda annoys me but it would be a nice addition to make the UI less human error prone :)

**Comment by c9mbundy** [comment]
I would think that argument suggests the same verification should be applied to the DebugMode On/Off switch - which changes  web.config and currently results in an immediate restart when you touch that button.

**Comment by RyuLindow** [comment]
Good point!

**Comment by Frost117** [comment]
This would definitely be nice to have, since I just had a small incident where I pressed restart env when I wanted to log into the kudu.

**Comment by sajumb** [comment]
A confirmation step for restarting an environment in dev/staging/live has been added. Accordingly this ticket is closed.
