### ISSUE TITLE
Heartcore: Webhooks return request result incorrectly

### ISSUE THREAD

**Issue by zacheatonvp** [umbraco/Umbraco.Cloud.Issues#365]
Our project is having intermittent issues with ContentPicker since the webhook fix from this ticket:
https://github.com/umbraco/Umbraco.Cloud.Issues/issues/347

**Background**
When creating a component with a link to a page. We have used a content picker to retrieve a content node within umbraco. 
For the last months of our project this has returned an object that reflected the selected page. 
However, since the recent release, this had returned a string of the pageId instead. 

**Reproduction**
Settings:
- Create a document type to reflect a page. 
- Create a document type to reflect a component. 
- Create a link field within the component using the Umbraco.ContentPicker. 
- Setup a webhook for Page. 

Content: 
- Create a page called "Page 1", Publish
- Create a page called "Page 2", Publish
- On page 2, create a component, link to "Page 1", Publish. 

Settings:
- Review Webhooks logs to find the output of the link field. 

NOTE: This is intermittent. 

**Bug summary**
I believe the bug has been introduced in the recent release to heartcore (Umbraco-Heartcore-2.4.4, 28th April Release), as this was working consistently for the last months. And the bug appeared the same day. 

**Bug investigation**
If I add another link field into the document type, it seemed to resolve itself. But we are worried how this will affect our pages in the future if this happened again. 

**Specifics**
Area = Webhooks
Functionality = Umbraco.ContentPicker
Version: Umbraco-Heartcore-2.4.4
Browser: Chrome
Error messages: None
Intermittent = Yes

**Expected result**
Url is returned as an object. 
```
{
    "_links": null,
    "linkRef": {
        "id": "f05236cc-0c8d-44e3-aa93-51ee0645a630",
        "url": {
            "_id": "a3ca325a-c01f-4b48-862f-634f8089c748",
            "_url": "/home/about-us/",
            "name": "About us",
            "_urls": {
                "en-GB": "/home/about-us/"
            },
            "_level": 2,
            "regions": [{
                "_links": null,
                "fragments": [{
                    "_links": null,
                    "richText": "\u003Cp\u003E\u003Cspan class=\u0022red-text text-align-center\u0022\u003ECURRENTLY IN DEVELOPMENT\u003C/span\u003E\u003C/p\u003E",
                    "internalTitle": "CURRENTLY IN DEVELOPMENT",
                    "contentTypeAlias": "richText",
                    "mobileFragmentWidth": "Full",
                    "tabletFragmentWidth": "Full",
                    "desktopFragmentWidth": "Full"
                }],
                "regionConfig": {
                    "id": "351baaa2-f318-426c-bfc9-a463d507720d",
                    "_links": null,
                    "backgroundColor": "ffffff",
                    "contentTypeAlias": "regionAttributes"
                },
                "internalTitle": "About us",
                "contentTypeAlias": "standardWidthGeneral"
            }],
            "parentId": "e70dc673-600c-41a2-a1a9-5c3259a919bb",
            "metaTitle": "About Us",
            "pageTitle": "About us",
            "promotion": null,
            "sortOrder": 9,
            "_createDate": "2021-04-12T12:27:25.067Z",
            "_updateDate": "2021-04-28T13:03:04.100Z",
            "_writerName": "",
            "_hasChildren": false,
            "metaKeywords": [
                "About Us"
            ],
            "showPageTitle": true,
            "showBreadcrumb": true,
            "umbracoUrlName": "about-us",
            "metaDescription": "Discover a bit more about our company by taking a little look at our About Us section. Features all you need to know about who we are and what we do.",
            "contentTypeAlias": "generalpage",
            "showGlobalPromotion": true
        },
        "icon": "",
        "text": "Click me",
        "_links": {
            "url": {
                "href": "https://cdn.umbraco.io/content/a3ca325a-c01f-4b48-862f-634f8089c748",
                "title": "About us"
            }
        },
        "internalTitle": "",
        "contentTypeAlias": "internalLinkButton"
    }
```
**Actual result**
Url is returned as a string rather than an object. 

```
{
    "url": "39caf53e-85ec-47a4-a6be-ac673d13ab93",
    "icon": "",
    "text": "Returns Information",
    "_links": null,
    "internalTitle": "Returns Information",
    "contentTypeAlias": "internalLinkButton"
}
```

Please contact me if you have any questions

@UnicornSez @sitereactor @RyuLindow

**Comment by zacheatonvp** [comment]
![Link as string](https://user-images.githubusercontent.com/82599541/116543226-86f34880-a8e5-11eb-8387-3a92dc28b92c.PNG)
This has just occurred again on our TEST site. 

Cta is meant to display an object for the given page. 

`  
{
"cta": [
            "e435a15f-5be5-4f27-8a4d-8b756607e801"
          ]
}
`

**Comment by zacheatonvp** [comment]
UPDATE:
This actually doesnt seem linked to ContentPicker as first initially thought. 

This looks like Nested Items have an ID and there is an issue with evaluating the data. This requires further investigation. Will update soon.

**Comment by sitereactor** [comment]
@zacheatonvp If you find more details that can be posted here then please also reach out to our support team through the Umbraco Cloud portal and reference this post, so we can look into your project. We have not been able to reproduce any issues related to the Content Picker.

**Comment by zacheatonvp** [comment]
Thank you for your update. 
Myself and Darek are working closely on the issue. 

I will update my issue to not be for content picker as first initially thought.

**Comment by zacheatonvp** [comment]
This issue has not re-occurred for us. I will keep a close eye on this. 
Closing for now. 

Thanks
Zack
