### ISSUE TITLE
Umbraco Deploy tends to import UDA's automatically

### ISSUE THREAD

**Issue by LennardF1989** [umbraco/Umbraco.Cloud.Issues#37]
_Copy/Paste of https://github.com/umbraco/Umbraco-CMS/issues/3970 - Aside from @nul800sebastiaan reasoning, this also happens when developing on a single machine and switching between different versions of branches. The fact that we use a single shared database is just a minor detail._

I have seen this particular issue a few times over the last year, but it pestered me three times in a row on a single day few weeks back. So I figured it's time to report it.

When we have a local Umbraco project running, multiple developers are usually working on it at the same time, both code and DB-wise (we have a shared Azure DB instance). It's not uncommon for me to regularly switch branches to review and merge code of my co-workers.

When Umbraco Deploy is installed on a project, as such that it keeps track of UDA-files, I have noticed that if you switch between branches with different versions of the UDA-files, it can happen that when the AppPool spins up Umbraco Deploy decides to import those by itself (as in: without making a deploy marker file to do so).

This behavior, regardless if it's intended or a bug, is really annoying and has caused me to lose all my properties thee times on the same day. After import, not only does it wipe properties that do not exist anymore, it will also wipe all data associated to it. So re-importing the UDA's that contain the now-deleted properties from a different branch, does not recover the data that had been set on the content.

Aside from it begin annoying, it would be really great if we can have a Web.config option to completely disable Umbraco Deploy during development,. Then whenever we want to prepare a build for the Dev-environment, we switch it on, "deploy-export" and push that to our deployment pipeline. This last stap we already do every time we want to deploy anyway.

**Comment by LennardF1989** [comment]
Example situation. Say you have a doctype "Home" and the UDA file for it lives in the master-branch of a Git repository. You branch into a "feature/somethingcool" and make changes to the "Home" doctype, the UDA reflects these.

You leave your work for a moment and switch back to the master-branch, for example because you want to rebase/merge a branch of someone else.

During that switch, back to an older version of the UDA file, Umbraco Deploy can decide to import those (without me asking for it by means of a marker-file), and will remove all the work I've done on the database in the other branch.

No matter if the database is shared, or if the branch is made by someone else, this is a problem on your local environment with Umbraco Deploy.

**Comment by nul800sebastiaan** [comment]
Switching branches is on our wishlist but I am not sure I understand why you'd lose data when you've committed your changes before switching, what data do you lose? 

I've had a look but I don't know why the deploy import would be kicking in, as far as I can tell it shouldn't, but I don't know how it decides. I've added it to the list to discuss at HQ.

**Comment by LennardF1989** [comment]
I figured it out... this was going to be another issue I wanted to raise but I guess its the culprit.

Umbraco Deploy installs Git Hooks on your repository, one of those is "post-merge", which creates a "deploy" marker file when it runs.

Can we get a Web.config-option to prevent the installation of these hooks? We don't want Umbraco Deploy to do this on our internal Git repositories.

**Comment by sitereactor** [comment]
@LennardF1989 No I'm afraid not. It's there for a reason, and while I understand its annoying that it runs when you switch branches you should ideally be using a (unique) database per branch and we highly discourage the use of shared databases when working with Umbraco Cloud sites / Deploy locally. We have done a lot of work to have Sql CE and LocalDb work seemlessly locally.

It would be interesting for us to know a bit about how you work with Umbraco / Umbraco Cloud in your team, so we can improve the guidance and possibly additional features/scenarios, which are currently not covered when working with Umbraco Cloud.

**Comment by LennardF1989** [comment]
@sitereactor I have already shared a large write out with one of the Umbraco Cloud support guys explaining in detail how we work. I was under the impression this was to be shared with you, but I can dig it up again for you.

As for the Git hooks thing, we've been working with Cloud for about 2 years now, and this is literally our only issue that makes stuff disappear in our current workflow. Seeing how this hook creation is literally one line of code inside `LocalInitializer` of `Umbraco.Deploy.Cloud.dll`, it would mean a lot to our workflow in general if this can be disabled (preferably through code, eg. by registering a EventApplicatiionHandler that runs earlier in the process). For now, I'll probably hack the line away using ILSpy.

**Comment by LennardF1989** [comment]
The problem is that we have a lot of developers working on Cloud projects. This means that we would have to wipe the hooks every time when clone a project of our VSTS environment, hence I would prefer an automated solution that prevents the problem in the first place.

**Comment by nul800sebastiaan** [comment]
Hi @LennardF1989 , going through some old issue reports. We are in the process of moving to an improved Cloud platform and that is going to be our main focus for the foreseeable future.

This feature request is really good and when we're done moving to the new platform we will need to work on making a good workflow for branching. There's a related issue to this as well, https://github.com/umbraco/Umbraco.Cloud.Issues/issues/14 which is an existing problem with branching as well. We'll group these types of issues together.

**Comment by jaandrews** [comment]
I got bit by this today unfortunately. After switching away from the feature branch and then switching back. The structural and content changes I made were gone since umbraco deploy automatically. Was able to recover the structure, since that had all been committed to version control, but wasn't able to restore the content, since no uda files are generated for those, at least out of the box. I'm used to a usync setup configured to require me to manually trigger the sync, so the potential issue didn't occur to me.

Not sure whether anything can be done on the umbraco side to improve, but sharing it as a pain point for reference. Maybe something to cover in the umbraco cloud documentation and training, if it's not already (looked through the documentation a bit, but didn't see it).

**Comment by LennardF1989** [comment]
@jaandrews Been using this "hack" for years, works fine (v9+). Just drop this Composer somewhere in your code:
```cs
[ComposeAfter(typeof(UmbracoDeployCloudComposer))]
public class StartupComposer : IComposer
{
    public void Compose(IUmbracoBuilder builder)
    {
        var gitHooksDescriptor = new UniqueServiceDescriptor(
            typeof(INotificationHandler<UmbracoApplicationStartingNotification>),
            Assembly
                .GetAssembly(typeof(UmbracoDeployCloudComposer))
                .GetType("Umbraco.Deploy.Cloud.NotificationHandlers.UmbracoDeployCloudStartingHandler"),
            ServiceLifetime.Transient
        );

        builder.Services.Remove(gitHooksDescriptor);
    }
}
```

It's slightly more annoying for v8, but a similar trick.
