### ISSUE TITLE
Invite user fails

### ISSUE THREAD

**Issue by bjarnef** [umbraco/Umbraco.Cloud.Issues#371]
On Umbraco Cloud projects we have issues with the "Invite User" since Umbraco ID was introduced.
Currently testing on a project on Umbraco v8.12.2.

The documentation mention here a user can be added/invited from Umbraco Cloud portal. However that's is not an options to editors who may have access to Users section an invite other users.
https://our.umbraco.com/documentation/Umbraco-Cloud/set-up/Users-On-Cloud/

It seems to fail when inviting the user and also when re-sending an invitation, where the user doesn't receive a mail.

At the time the user was invited and failed I can find this log error:
![image](https://user-images.githubusercontent.com/2919859/117107074-4aaa6700-ad81-11eb-8b75-9f579cfdd84f.png)

Since the status of the user is "Invited" it is not possible from backoffice directly to change the password, so the workaround is from users overview to select the user and disable this from bulk actions. The enable the user again and after this manually change password on the user.

From time to time I also get an YSOD when using the "Sign in with Umbraco ID" button from login screen.

![image](https://user-images.githubusercontent.com/2919859/117107839-8db90a00-ad82-11eb-8702-88c0fa9dcdc2.png)

**Comment by nul800sebastiaan** [comment]
Hi @bjarnef, please reach out to support on the Cloud portal so they can help you along with this! 👍
