### ISSUE TITLE
Umbraco Heartcore - Webhooks - Availability and Performance

### ISSUE THREAD

**Issue by zacheatonvp** [umbraco/Umbraco.Cloud.Issues#375]
Our project is having intermittent issues with webhook availability. 

Webhook outcomes:
- Webhook fires immediately 👍 
- Webhook takes upto 10 minutes to fire 👎 
- Webhook attempt doesnt appear in webhook logs. 👎 

**Impact**
We are unable to publish pages on environments, so pages will not create or update when this issue is present. 

**Background**
When publishing a wilcard or targeted content type in Heartcore, I see a mix of outcomes. 

**Reproduction**
Content:
- Go to Page
- Publish Page

Settings:
- Go to Headless > Webhooks
- Webhook Logs

Result = One of the three outcomes mentioned above. 

**Bug summary**
I believe the bug has been introduced in the recent release to heartcore (Umbraco-Heartcore-2.4.4, 28th April Release), as this was working consistently for the last months. And the bug appeared the same day.

**Bug investigation**
- I have tried with both wildcard and targeted content types
- I have reset the environment
- I have refreshed publish settings
- I have deleted and re-added webhooks
- I have disabled and re-enabled webhooks

**Specifics**
Priority = High
Impact = High
Area = Webhooks
Functionality = Webhooks
Environments = All
Version: Umbraco-Heartcore-2.4.4
Browser: Chrome
Error messages: None
Intermittent = Yes 
Project = [Please ask Darek]

**Expected result**
I would expect any publish that gets triggered should fire a webhook if related by wildcard or content type. 
This would output a log in the webhooks regardless of outcome. 

**Actual result**
As the outcomes mentioned above, we either receive:
- Immediate response
- Delayed response (upto 10 minutes)
- No response

Please contact me if you have any questions

Umbraco Support Lead: Darek

Attachments: 2 Videos (Darek has these files)

Many thanks
Zack

**Comment by zacheatonvp** [comment]
Good morning all, 

This was fixed for a short time, however, this re-occurred last friday and is still an issue today (Monday). 

Please can this be looked into whilst the issue is active?

Steps:
- Publish any node
Result:
- No webhook fired

**Comment by zacheatonvp** [comment]
Update:
After refreshing the published settings in Umbraco, I seem to consistently get this type of result where SaveMedia images all get fired at the same time, when no interaction has happened with media. See attached. 

![image](https://user-images.githubusercontent.com/82599541/118472569-e1234480-b700-11eb-8e91-4006ee45eff6.png)

**Comment by zacheatonvp** [comment]
Update:
Still receiving the same issue with this, its now affecting publishing of targeted content types.

**Comment by zacheatonvp** [comment]
Update:
I have sent a video to the support team. Please contact Andre for the video. 
Recording #5.mp4.

**Comment by zacheatonvp** [comment]
Update:
I have sent a part 2 video that demonstrates an attempt to fix the webhook. Please contact Andre for the video. 
Recording #6.mp4. 
Thanks!

**Comment by zacheatonvp** [comment]
Update:
I have sent part 3 that demonstrates the webhook working! However, would still consider this as broken and a bug. 
In my example I have deleted 2 of 4 Nested Content nodes from a page, and this seemed to resolve the issue. 
Please contact Andre for the video. 
Recording #7.mp4

Thanks for your time. 
Apologies for the mass updates!

**Comment by sitereactor** [comment]
@zacheatonvp Thanks for the details and updates. We believe we have found an issue revolving around the size of the payload that has caused exceptions meaning the webhook would not have been sent.
We are looking into it now and will post an update when we have tested our update.

**Comment by zacheatonvp** [comment]
No worries, thank you Morten.

Let me know if I can assist in any way. 

Many thanks

**Comment by sitereactor** [comment]
I'm sorry, I totally forgot to update this issue, as I rolled out the fix on a public holiday 😅 
Either way, we spent a bit of time on testing it related to the refactoring was done to ensure we wouldn't run into this type of issue again.

The root of the issue was related to the size of the payload for which there were certain limitations when passed around. With the last update the payload is not passed around, but saved to a datastore from where its also retrieved when the webhook is posted.

We have tested all 5 variations of the event triggers with various sized content and everything worked as expected.

Let us know if you should experience any other issues related to webhooks.

**Comment by zacheatonvp** [comment]
Hi Morten, 

Thank you very much for this update, really happy with how this works with our infrastructure now.

We have commenced testing on this new fix and it is working for most cases.

However, we have just published a development library page and have received an issue that I have seen previously. 


**New Issue**
This issue has surfaced on a few pages during development, but did not raise it because we thought it would be fixed as part of this issue. 

It seems we have an issue with nested items nulling out. 

I can send full snippets and case scenarios to your team directly. 

Example 1 - Snippet:
`{
      "_links": null,
      "fragments": [
        null,
        null,
        null,
        null,
        null,
        null
      ],
      "internalTitle": "Main Section",
      "contentTypeAlias": "standardWidthGeneral"
    }`

Example 2 - Snippet: 
`{
      "_links": null,
      "fragments": [
        null,
        null
      ],
      "internalTitle": "Image Tile List Section",
      "contentTypeAlias": "standardWidthComponentLibrary"
    },
    {
      "_links": null,
      "fragments": [
        null,
        null,
        null
      ],
      "internalTitle": "Feature Card List Section",
      "contentTypeAlias": "standardWidthComponentLibrary"
    },
    {
      "_links": null,
      "fragments": [
        null,
        null,
        null,
        null
      ],
      "internalTitle": "Info Card List Section",
      "contentTypeAlias": "standardWidthComponentLibrary"
    }`

Snippet 3 - Full
`{
    "...": "2021-05-24T13:59:47.607Z",
    "regions": [{
        "_links": null,
        "fragments": [null],
        "internalTitle": "Introduction",
        "contentTypeAlias": "standardWidthComponentLibrary"
    }, {
        "_links": null,
        "fragments": [null, null],
        "internalTitle": "Elliot Development",
        "contentTypeAlias": "standardWidthComponentLibrary"
    }, {
        "_links": null,
        "fragments": [{
            "cta": [],
            "cards": [null, null],
            "title": "",
            "_links": null,
            "internalTitle": "Icon & Text",
            "contentTypeAlias": "deliveryInfoCardList",
            "mobileFragmentWidth": "Full",
            "tabletFragmentWidth": "Full",
            "desktopFragmentWidth": "Full"
        }, {
            "cta": [],
            "cards": [null, null, null, null],
            "title": "",
            "_links": null,
            "internalTitle": "Product Picture & Link",
            "contentTypeAlias": "deliveryInfoCardList",
            "mobileFragmentWidth": "Full",
            "tabletFragmentWidth": "Full",
            "desktopFragmentWidth": "Full"
        }],
        "internalTitle": "Development",
        "contentTypeAlias": "standardWidthComponentLibrary"
    }, {
        "_links": null,
        "fragments": [null, null, null, null, null],
        "internalTitle": "Delivery Page",
        "contentTypeAlias": "standardWidthComponentLibrary"
    }],
    "metaTitle": "Development Library",
    "pageTitle": "Development Library",
    "promotion": null,
    "metaKeywords": [],
    "showPageTitle": false,
    "showBreadcrumb": false,
    "umbracoUrlName": "developmentlibrary",
    "metaDescription": "Development Library",
    "showGlobalPromotion": true
}`
