### ISSUE TITLE
Uninstalling Forms on Cloud results in an error: `No connector registered for entity type "form-form"`

### ISSUE THREAD

**Issue by jomehmet** [umbraco/Umbraco.Cloud.Issues#376]
It should be possible to uninstall Umbraco Forms in Umbraco Cloud.

I've uninstalled it, and everything seem ok, the label Umbraco Form: {version} is gone from Umbraco Cloud Portal.

There is though one issue. When I hit Restore all content from the Stage environment, I'm getting the error shown in the following snippet: No connector registered for entity type "form-form" 

![image](https://user-images.githubusercontent.com/840606/117944257-5cee4d00-b30d-11eb-8322-d95a83bb043e.png)

Extra info: I verified that we are not having Umbraco.Deploy.Forms.dll in the environment I used for Restore, neither on my local machine.

**Comment by AndyButland** [comment]
Think it could be because you still have `<forms transferFormsAsContent="true" />` in your `config\UmbracoDeploy.Settings.config` setting file.  By having that I believe Deploy would still be looking to restore forms from your upstream environment.  I'd suggest setting that to false and seeing if that resolves the issue.

**Comment by RyuLindow** [comment]
Hi @jomehmet 

Deploy depends on Forms as per - https://our.umbraco.com/documentation/Umbraco-Cloud/Upgrades/Product-Dependencies/

If you don't wish to use them then you can simply hide the Forms section for various user groups and I advise against trying to remove them completely, as I've seen several Cloud users do it which then resulted in various issues.

The person you wrote with in support told me about why you removed them.

It sounds to be like the initial cause of you removing Forms was the IP filtering you've added to your project :)

I gave him a potential solution that he will present to you shortly.

**Comment by nul800sebastiaan** [comment]
Thanks for the report @jomehmet, could you please let us know why you would want to remove Forms? You might not use it and that's fine, you can disable the Forms section in user permissions. Is there any other reason to want to uninstall it?

**Comment by jomehmet** [comment]
The reason I'm reporting this is because my expectation is that Umbraco Forms is a modular extension. The only thing that has given an exception is Full Restore. Partial Restore works fine. Cloud Portal handles is fine, by not showing the version anymore. For me it seems like there is a small piece of work missing to let Umbraco Cloud have Forms as Optional.

In all other projects in our organization we strive to have just the dependencies we are using, so we don't spend time on maintaining dead code. Getting notification in Umbraco Portal about "Upgrade available" when it's about Umbraco Forms is stealing cognitive capacity as you need to click the button and see it's about a dead dependency.

I hope you have the time to check if it's possible to let Umbraco Cloud handle Opt-Out of Umbraco Forms. In the mean while thank you for the advice on how to handle it.

**Comment by nul800sebastiaan** [comment]
Thanks for the explanation @jomehmet! I understand and unfortunately it looks like there's not much we can do at the moment. I've heard back from my colleagues that, for the time being, Forms is an essential past of Cloud sites and we are  currently unable to support sites without the Forms files present. 
Our workflows (and dependencies like Deploy) currently all rely on Forms being there and will break when it's not found. 

So our advise for now is to disable access to Forms for your users and every once in a while to click that upgrade button when it pops up. Sorry that I don't have better news for you. We're keeping it in mind for the future, but currently we don't have the bandwidth to separate out Forms everywhere.
