### ISSUE TITLE
Set "target="_blank" on links in the notification popup

### ISSUE THREAD

**Issue by hfloyd** [umbraco/Umbraco.Cloud.Issues#377]
More than once I've been waiting for a deployment or something to complete in the Portal and checked out the handy little "read more" button on the notification:
![image](https://user-images.githubusercontent.com/1252593/118042973-c5a3ec80-b342-11eb-95c4-0bc39e49f272.png)

![image](https://user-images.githubusercontent.com/1252593/118042851-9b522f00-b342-11eb-80f6-a7fd1e6e6824.png)

...And clicked the "Status" page link in the pop-up, which doesn't currently open in a new tab/window, so I lose my Cloud Portal (and thus my current operational status message). Perhaps all links in the notification can be set to "target="_blank"?

**Comment by AndyButland** [comment]
Not sure how easy this will be to amend on rendering to update links in that way, but there's certainly no reason why we can't code them with a `"target="_blank"` when we write the messages.

I've updated the current one and will keep a note for further ones regarding Forms and Deploy releases.

**Comment by hfloyd** [comment]
Well, I suppose any "technical" solution will be based on how you create those messages, but I just wanted to mention it as a general UX issue. 😉

**Comment by nul800sebastiaan** [comment]
Good point I'm sure we can find a way to automatically add a target attribute if it doesn't yet exist! Even if it's a bit of JS to help us out, for example: https://stackoverflow.com/a/6823034/5018

**Comment by sajumb** [comment]
We are closing this issue as we have noted the friendly tip on always opening links on a new tab. :-) We will definitely do our best to always doing this in the future.
