### ISSUE TITLE
Heartcore: Adding document type to another as composition, will break that document type in graphql

### ISSUE THREAD

**Issue by thejokerd3** [umbraco/Umbraco.Cloud.Issues#382]
Adding any document type to another as composition, will break that document type in graphql, and no content will be returned from the graphql query, even after removing that document type as a composition

Reproduction
------------

### Specifics

This is seen on the newest version of Heartcore

### Steps to reproduce

1. Create a document type named Vehicle
2. Create a document type named Car
3. Then run a query in the GraphQL Playground for Vehicle: get items or contentypealias:
![image](https://user-images.githubusercontent.com/20074364/119821761-3aeef000-bef3-11eb-988f-712b08e10363.png)

As you can see you can actually get some data back after running this query

4. Go back to the document type Car and add Vehicle as a composition
5. Go back to GraphQL to run the same query as in step 3 -> This will throw an error:
"Cannot query field \"allVehicle\" on type \"Query\".", 
![image](https://user-images.githubusercontent.com/20074364/119822060-8903f380-bef3-11eb-8731-96ef2b31c67e.png)

Notice that in the GraphQL you dont get recommended the field either..

![image](https://user-images.githubusercontent.com/20074364/119822129-991bd300-bef3-11eb-9357-e5dba83690c1.png)

6. Go back to Car Documenttype and remove Vehicle as a composition
7. Go back to GraphQL and run the query again -> STILL throws error. (Would assume that when you remove the composition it would start working again, as it did BEFORE we added the composition)

**Comment by sitereactor** [comment]
There are to parts to this
1. Querying using Compositions is not possible (not supported), so it is not possible to query by Vehicle when its used as a composition in the Car document type. If this was meant as a feature request then it should be (re)created as a feature request :)
2. The point mentioned in 7 is a bug in the platform and something we can fix. It seems that we are currently not able to detect the change to Vehicle when its removed from Car. Only Car is advertised as being changed, so the Platform continues to see Vehicle as a Composition.
This is something we can fix and I will get included as part of our next sprint starting next week.
