### ISSUE TITLE
Docs for Cloud portal permissions don't match with what's actually happens

### ISSUE THREAD

**Issue by RyuLindow** [umbraco/Umbraco.Cloud.Issues#386]
### Issue description

Regarding these docs - https://our.umbraco.com/documentation/Umbraco-Cloud/set-up/Team-Members/#team-member-roles - the part about Read permissions is incorrect or the Read permissions are bugged.

If you have the Write permissions on all environments then you will be able to see the settings and also the dropdowns with options next to each env.

If you set the permissions to Read on just 1 environment you'll lose these permissions from all environments.

[VIDEO](https://www.dropbox.com/s/0qildxtwvbwf1su/D6ld5GeTOa.mp4?dl=0)

**Comment by sajumb** [comment]
Hi,
Thank you for reporting this.
We have created a development ticket for this issue. It is a candidate for the next sprint started at December 6th.
best regards

**Comment by sajumb** [comment]
We have fixed this so the permission is handled correctly per environment.
We are closing this issue.

**Comment by sajumb** [comment]
We will handle this at some point in the future. For now, we will be closing this task and handle it internally.
