### ISSUE TITLE
GQL: Fragmenting in different order gives varying result

### ISSUE THREAD

**Issue by Frost117** [umbraco/Umbraco.Cloud.Issues#397]
### Issue description

When you perform a content query with the following query, you will get errors where it can't find the specific variables:

![image](https://user-images.githubusercontent.com/32164310/123615142-50627d00-d805-11eb-870c-d4ba980722fa.png)

Or 

![image](https://user-images.githubusercontent.com/32164310/123615363-84d63900-d805-11eb-8754-1478da02f17b.png)

Looking at how we got here, if the meta field is loaded first, the last variable will not be able to be found. 
The procedure happens if you load the meta variable as the 2nd item.

![image](https://user-images.githubusercontent.com/32164310/123615651-cb2b9800-d805-11eb-9cf4-14bd86dd1550.png)

In order to get the error resolved, you **have** to load the meta variable as the last item in the query. Else you will keep getting the same issue. 

This can be reproduced on a new project of Heartcore, however there is a lot of files and steps to go through in order to get the exact same scenario. If needed the files can be uploaded to the issue. 

The query is as follows:
`# Write your query or mutation here
query GetPageContent {
  content(url: "/homeurl") {
    __typename
    ...HomePage
  }
  
  header: homePage(url: "/homeurl") {
    ...Header
  }
  meta: content(url: "/homeurl") {
    ...PageMeta
  }
  footer: homePage(url: "/homeurl") {
    ...Footer
  }
  
}

fragment HomePage on HomePage {
  name
  pageModuleList {
    ...TextAndImage
    ...ImageGallery
    ...Hero
    ...Interaction
    ...Text
  }
}
fragment TextAndImage on TextAndImageElement {
  ... on TextAndImageElement {
    __typename
    textAndImageTitle
    textAndImageLink {
      ...Link
    }
    textAndImageContents
    textAndImageMedia {
      ...Image
    }
    textAndImageAltDirection
  }
}
fragment Link on Link {
  __typename
  url
  name
  target
}
fragment Image on Image {
  __typename
  url
  ... on Image {
    altText
    umbracoWidth
    umbracoHeight
    umbracoFile {
      focalPoint {
        left
        top
      }
    }
  }
}
fragment ImageGallery on ImageGalleryElement {
  ... on ImageGalleryElement {
    __typename
    imageGalleryLink {
      ...Link
    }
    imageGalleryTitle
    imageGalleryContents
    imageGalleryMediaList {
      ...Image
    }
  }
}
fragment Hero on HeroElement {
  __typename
  heroMessage
  heroMediaList {
    ...HeroImage
  }
}
fragment HeroImage on HeroImageElement {
  __typename
  heroImageLabel
  heroImageMedia {
    ...Image
  }
}
fragment Interaction on InteractionElement {
  __typename
  interactionAreaList {
    ...InteractionArea
  }
}
fragment InteractionArea on InteractionAreaElement {
  __typename
  interactionAreaLabel
  interactionAreaTitle
  interactionAreaColor {
    color
    label
    __typename
  }
  interactionAreaLink {
    ...Link
  }
  interactionAreaSlides {
    ...InteractionImage
  }
}
fragment InteractionImage on InteractionImageElement {
  __typename
  interactionImageText
  interactionImagemedia {
    ...Image
  }
}
fragment Text on TextElement {
  __typename
  textTitle
	textColumns {
    ... on TextColumnElement {
      textColumnText
    }
  }
  textLink {
    name
    target
    url
    __typename
  }
}
fragment PageMeta on PageMetaComposition {
  pageMetaTitle
  pageMetaDescription
  pageMetaMedia {
    url(format: JPG, width: 1200, height: 630, cropMode: CROP)
    ... on Image {
      id
    }
  }
}
fragment Header on HeaderComposition {
  headerLinkGroups {
    ...LinkGroup
  }
  headerMedia {
    ...Image
  }
  headerText
}
fragment LinkGroup on LinkGroupElement {
  __typename
  linkGroupLabel
  linkGroupUrlList {
    ...Link
  }
}

fragment Footer on FooterComposition {
  __typename
  footerHeadline
  footerLinkGroups {
    ... on LinkGroupElement {
      linkGroupLabel
      linkGroupUrlList {
        ...Link
      }
    }
  }
}`

**Comment by Frost117** [comment]
If the meta field is loaded last, then the response received is the correctly shown:
![image](https://user-images.githubusercontent.com/32164310/123616768-e64ad780-d806-11eb-9f80-9601d8c2f016.png)

**Comment by rasmusjp** [comment]
Hey @Frost117

We've released a fix for this, could you try again and verify it works now? Thanks.

FYI it had nothing to do with fragments, but the number of fields being queried and the order they were queried in.

**Comment by Frost117** [comment]
Hey @rasmusjp I can confirm that the query now works no matter what order you do the Header, Meta and Footer
