### ISSUE TITLE
Feature: remove myself from projects

### ISSUE THREAD

**Issue by jesperordrup** [umbraco/Umbraco.Cloud.Issues#4]
We need to be able to remove ourselves from projects. This so we can control ourself what we want to have access to and  keep our setup clean.

We do ask customers to remove us. But sometimes they don't (reason unknown - big companies and bs rules).

**Comment by pijemcolu** [comment]
@jesperordrup I assume you aren't able to remove yourself from a project due to not having write permissions. Am I correct?

**Comment by sajumb** [comment]
Details about feature request is not provided. We believe it is caused by the reporter missing the permission to alter project (the _Write_ permission. Accordingly this issue is closed.
