### ISSUE TITLE
Opt-Out of Upgrades for Unused Components

### ISSUE THREAD

**Issue by Nicholas-Westby** [umbraco/Umbraco.Cloud.Issues#40]
Umbraco Cloud includes Umbraco Deploy and Umbraco Forms. For Umbraco Deploy, I have a temporary workaround in place in which I deleted the Contrib DLL (long story). For Umbraco Forms, I don't use that (I use Formulate).

A recent Umbraco Deploy automatic upgrade added the Contrib DLL back to the project, which removed my workaround, and made life more painful for the content editors.

For Umbraco Forms, I haven't even tried removing it, as I was told by support that it'd probably just be added back by an automatic upgrade. I noticed today that an automatic upgrade is indeed scheduled.

So my request is this:

**The ability to opt-out of automatic upgrades for particular components, such as Umbraco Deploy and Umbraco Forms.**

In my case, that would be temporary for some components (i.e., Umbraco Deploy) and permanent for others (Umbraco Forms).

**Comment by sajumb** [comment]
This is supported. People can contact support with a list of projects and the products they don't want to get updated. Then we put the projects on the ignore list for these products.

We have planned to make this a self-service feature during 2024.
