### ISSUE TITLE
Project invites - specify user access level in the invite

### ISSUE THREAD

**Issue by Jay-umbr** [umbraco/Umbraco.Cloud.Issues#408]
### Issue description

Whenever you invite someone to a project you have the option to add them as admin.
However, even if that field is not checked, the user gets read/write access to all environments regardless.
While this can be corrected after the invite has been accepted, it would be good to have an option to define such roles in the invitation form itself.
Note: this might be considered more of a feature request

**Comment by sajumb** [comment]
Thanks for this feature request. We have created a ticket for the request and made it a candidate to be included in one of the upcoming sprints.

**Comment by callumbwhyte** [comment]
Looks like this was rolled out in an update this week! Much improved 😀

**Comment by sajumb** [comment]
@callumbwhyte We are glad that you liked this update. More updates on the project invite flow and management to be launched on the portal in the upcoming weeks. The most significant ones will be mentioned in the portal release notes https://our.umbraco.com/documentation/Umbraco-Cloud/release-notes/

We are closing this issue.
