### ISSUE TITLE
Can't change owner of a project

### ISSUE THREAD

**Issue by dawoe** [umbraco/Umbraco.Cloud.Issues#409]
### Issue description

In our organization we have several projects that are created by people using their personal account. 

Some of those people have left the company. It would be nice that we or HQ support would be able to change this.

According to HQ support this not possible at the moment (see Zendesk ticket : 61633)

Dave

**Comment by emma-hq** [comment]
Hey @dawoe 

We'll take a look at this one! Thanks for reporting

Emma

**Comment by mattou07** [comment]
We've also ran into this issue at Moriyama. Would be great if this was possible. Thanks!

Matt

**Comment by emma-hq** [comment]
Heya folks,

I will put this in front of the cloud team and let you know when it makes it into a sprint. We've got out hands full for this one but beyond this we should be freer.

Emma
