### ISSUE TITLE
Stuck on the "loading potential baselines" step if you're trying to create a Cloud project right after creating another one

### ISSUE THREAD

**Issue by RyuLindow** [umbraco/Umbraco.Cloud.Issues#412]
## Issue description

I've found a bug with the Cloud project creation flow when you try to create a new project right after trying to create one.

You'll get stuck on the loading baselines screen until the first project has finished creating.

It seems to only happen with Cloud projects, as these are the only ones where you can use the baseline feature.

## Steps to reproduce
1. Create a Cloud project
2. Instantly try to create a new one by clicking on the "Create project" button.
3. You'll be stuck at the "Loading potential baselines" until the project has finished creating

I believe that it's due to the fact that the project you're waiting for to finish creating isn't ready to be a baseline yet which makes the potential baselines unable to load.

Attached a video below :)

https://user-images.githubusercontent.com/56826332/126980546-12e966cb-38c5-42c8-845d-b97b2c7f8f0e.mp4

**Comment by sajumb** [comment]
We have now moved the loading of potential baselines and hiding it behind a baselines button. Due to this I am closing this issue.

**Comment by RyuLindow** [comment]
Amazing, thanks!
