### ISSUE TITLE
Add additional filtering options to the /projects page

### ISSUE THREAD

**Issue by RyuLindow** [umbraco/Umbraco.Cloud.Issues#414]
### Feature description

I would like to ask for some additional filtering on the /projects page such as:

- 3 step toggle which allows for the following:
1. show all projects
2. show projects created by me
3. show projects not created by me

- Filter by project type:
Uno, Cloud, Heartcore
In this case, it could be a be dropdown that allows for the selection of more than just one type.

- Allow for the creation of folders which then could be used for the grouping of multiple projects.
g drive has a very good example of a UI that could be replicated. I'm referring to the way you can move files into folders.

**Comment by sajumb** [comment]
We have started the design process of creating a new projects overview page. The feature request in this issue has been noted and will be taken into account when designing the new projects overview. We will close this issue and related feature requests to the projects overview. Thanks for the input and sorry about the late response!
