### ISSUE TITLE
Feature request: Change email invitation workflow

### ISSUE THREAD

**Issue by HalldorLyngmo** [umbraco/Umbraco.Cloud.Issues#437]
### Issue description

When the users have some automation that goes through the emails inspecting/clicking the links it will reject the invite before it can be accepted by the user. This automation might be a spam filter, automation to forward to slack, etc.

In the invitation email there are two links. 

![image](https://user-images.githubusercontent.com/42831978/132318815-d8a80a38-daa4-4e74-ac21-43c501c85e76.png)

1. One to accept which sends you to Umbraco Cloud and you'll either log in or if already logged in you can continue the invitation flow. 
2. The other outright rejects the invite even if you're not logged in.
![image](https://user-images.githubusercontent.com/42831978/132319040-f26a2a89-5aae-46c9-b869-3a1523743eab.png)

### Proposed solution
Change the rejection link so it needs confirmation action on the Cloud page after clicking the link. 
This way the automation won't reject the invite by clicking/inspecting the link and the user doesn't have to reach out to support and then change their automation to work with our invitation emails.

**Comment by sajumb** [comment]
Hi Halldor,
Thank you for the feature request. I agree that the suggested solution would be a good fix for the automation issue. We have created a ticket in the backlog of the Cloud Feature Team. And we are likely to consider this in the next sprint.

**Comment by sajumb** [comment]
The change in the email invitation workflow has been deployed to production. Accordingly, this ticket is closed.
