### ISSUE TITLE
Deactivate umbraco.io subdomain, use added hostname

### ISSUE THREAD

**Issue by MichaelNielsenDK** [umbraco/Umbraco.Cloud.Issues#44]
Being able to to visit websites via the s1.umbraco.io domains on projects, gives the risk with duplicate content on search engines like Google. 

It can of course be solved by adding a conditional noindex, nofollow in header. But it would be better if the test domain could not access the frontend after a hostname is added.

**Comment by nul800sebastiaan** [comment]
We currently don't have a way to unbind the umbraco.io domain from your sites. We recommend using rewrite rules for this: https://our.umbraco.com/Documentation/Umbraco-Cloud/Set-Up/Manage-Hostnames/Rewrites-on-Cloud/#hiding-the-default-umbracoio-url

**Comment by MichaelNielsenDK** [comment]
Yea, my point was that it would be a whole lot easier to manage. 

Also, we've had a support issue on Cloud, where we've been told that redirecting umbraco.io subdomains would break the upgrading process, as the frontend has to be accessible on the umbraco.io subdomain.
