### ISSUE TITLE
Git-hooked Schema Deployment failing for no reason

### ISSUE THREAD

**Issue by hfloyd** [umbraco/Umbraco.Cloud.Issues#440]
### Issue description

I have noticed this issue after our cloud site was updated to Deploy 4.14. 

My understanding is that, when working locally, when UDA files are changed (via back-office operations), then those files are committed/pushed to Cloud Dev, a git-hook on Cloud-Dev will run the schema deployment on the dev site. The assumption being that just pushing via git locally will make sure the Dev site DB is updated.

Recently, whenever I do the git push, then attempt to transfer content from local to Cloud Dev, I am getting schema mismatch errors reported on my local site. I then log into the back-office of the Cloud Dev site and go to **Settings > Deploy**. I see the message "Last deployment operation failed". There are no messages in the error log pointing to a deployment failure, and if I just click the maroon button to "Trigger Operation" for "Schema Deployment From Data Files", It then completes successfully. 

So, it seems that for some reason, the git-hook triggered "Schema Deployment" is always failing, but not because there is actually any UDA issues. I'm not sure if there is just some sort of "race condition" where the UDAs or the DB are not quite ready for the deployment, or what... 

It's an annoying issue, making something which was once a one-step process (git push from local) into a 2+ step process (log into Dev back-office, trigger deployment manually).

**Comment by AndyButland** [comment]
Hi Heather - I've been doing some more testing on 4.1.4 trying to replicate this in new projects on both infrastructures, but haven't been able to as yet - deployments look to be going through as expected.  Not sure if there'll be anything useful to see, but would you be able to repeat the operation, confirm you see the same unexpected behaviour, and share the deployment and site log for the period with me please?  abl AT umbraco DOT dk is my email.  Thanks.

**Comment by hfloyd** [comment]
Hi Andy, Thanks for looking into this. I will see if the issue persists and provide the details you requested.

**Comment by hfloyd** [comment]
I'm not sure if this is related or not - but it showing in the Log Viewer:

```
Exception
System.InvalidOperationException: Already shadowing.
   at Umbraco.Core.IO.FileSystems.BeginShadow(String id)
   at Umbraco.Core.IO.FileSystems.Shadow()
   at Umbraco.Core.Scoping.Scope..ctor(ScopeProvider scopeProvider, ILogger logger, FileSystems fileSystems, Scope parent, ScopeContext scopeContext, Boolean detachable, IsolationLevel isolationLevel, RepositoryCacheMode repositoryCacheMode, IEventDispatcher eventDispatcher, Nullable`1 scopeFileSystems, Boolean callContext, Boolean autoComplete)
   at Umbraco.Core.Scoping.ScopeProvider.CreateScope(IsolationLevel isolationLevel, RepositoryCacheMode repositoryCacheMode, IEventDispatcher eventDispatcher, Nullable`1 scopeFileSystems, Boolean callContext, Boolean autoComplete)
   at Umbraco.Deploy.Persistence.DeployScopeProvider.CreateDeployScope(Boolean scopeFileSystems)
   at Umbraco.Deploy.Work.WorkItems.DiskReadWorkItem.<ExecuteAsyncSub>d__16.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Umbraco.Deploy.Work.WorkItems.DiskReadWorkItem.<ExecuteAsync>d__15.MoveNext()
```

I have never seen this specific error before.

**Comment by hfloyd** [comment]
@AndyButland I've sent you an email.

**Comment by AndyButland** [comment]
We've made Deploy 4.4 available now @hfloyd and having checked on another project I can see the site extension update also required for this fix is in place, so hopefully this is now resolved.

If you are still having trouble can you confirm please that you have:

- Deploy 4.4.0
- In `C:\home\SiteExtensions\Umbraco.Cloud.Deployment.SiteExtension.Artifacts\umbracodeploy\  EnsureUmbracoDeployExtraction.ps1` a file that includes the following line at the base of the header comment:

```
# From Umbraco.Deploy 4.4.0 a different file from that used to monitor for extraction requests whilst
# the application is running is used ("deploy-on-start").
```

I had temporary access to the project which is now removed, so I can't check directly, so this would just be to confirm the update is in place in your environments.  Thanks.

**Comment by hfloyd** [comment]
Hi @AndyButland ,

I have verified that all three environments are currently running Deploy 4.4.0 and the "deploy-on-start" comment is in the file on all three environments.

We were able to delete a bunch of legacy schema from this site as well, so hopefully that will help extraction run faster as well. 

I will keep an eye on the deployments and see if I encounter the same issue.

**Comment by AndyButland** [comment]
Will close this one now given the release with the expected fix has been rolled out.
