### ISSUE TITLE
Package versions are not listed in same order

### ISSUE THREAD

**Issue by bjarnef** [umbraco/Umbraco.Cloud.Issues#443]
### Issue description

I noticed on different Umbraco Cloud projects that the versions on projects isn't listed in same order, which I think it confusing.

![image](https://user-images.githubusercontent.com/2919859/133390929-19752f38-aaae-4101-8e6b-c58b42d3904f.png)

![image](https://user-images.githubusercontent.com/2919859/133391001-b1dab2ac-df85-4ed6-b784-480c10550427.png)

I think the order should be: Umbraco CMS | Forms | Deploy | Umbraco Id

**Comment by sajumb** [comment]
Hi bjarnef
Thank you for reporting this. You are right. We should definitely fix this.
I have created a task in the product backlog of the Cloud Feature Team and we are likely to fix this in December.
