### ISSUE TITLE
Show that there is an upgrade available, even when no development environment is present

### ISSUE THREAD

**Issue by aguyfromdenmark** [umbraco/Umbraco.Cloud.Issues#444]
### Issue description

On starter plans, there is no indication that an upgrade is available, unless the project has a development environment.
A development environment is of course required for applying to update to, to ensure uptime and so on. 
But the presence of a development environment should not be required for you to know that there is an upgrade available. 
This could potentially have unknown cloud users waiting for an upgrade to be released, when it already is.

**Comment by sajumb** [comment]
Thanks for this request. We have created a ticket in product backlog and will consider this for the upcoming sprints.

**Comment by sajumb** [comment]
The portal is now showing an _upgrade available_ icon on starter projects without DEV environment.
Accordingly, we are closing this issue.
