### ISSUE TITLE
Uaas.cmd doesn't work now cloud projects have been moved to vNext

### ISSUE THREAD

**Issue by HTDL-Andrew** [umbraco/Umbraco.Cloud.Issues#445]
### Which *exact* Umbraco version are you using? For example: 8.13.1 - don't just write v8

v8.16

### Bug summary

No project solution is created and no visible errors are reported 

### Steps to reproduce

Downloaded latest uaas.cmd, ran on clone url for new Umbraco cloud instance v.8.16

### Expected result / actual result

Expected an sln file with 2 projects

**Comment by nul800sebastiaan** [comment]
Please elaborate? 

But maybe before you do: `UaaS.cmd` was updated a few weeks ago. Did you download the latest version or use a version you had laying around? I've just tried with the latest version and it worked as expected.

**Comment by HTDL-Andrew** [comment]
Thank you, I must have had an older version as you said. I did download from the Umbraco site, whilst trying to sort out the issue, but now it works. Many Thanks
