### ISSUE TITLE
Cloud project overview: when making a new project the UI does not refresh automatically

### ISSUE THREAD

**Issue by Jay-umbr** [umbraco/Umbraco.Cloud.Issues#447]
### Issue description

When you create a new project on the Cloud, it will say it is setting up all the necessary components.
At this stage you can only see the project name and the number of environments.
When the project is done creating the UI should refresh and list all the options, settings etc.

At the moment it does not do so - so you can spin up a new project, have it say it's setting up for an indefinite amount of time until you refresh the page manually.

Video showcase:
https://www.dropbox.com/s/f1oupv9iwl436fz/x5dfOPe8hu.mp4?dl=0

**Comment by mikkelhm** [comment]
This has been fixed with the latest updated to the Cloud portal
