### ISSUE TITLE
Option to mark a hostname as 'primary' and redirect all others to it

### ISSUE THREAD

**Issue by MichaelNielsenDK** [umbraco/Umbraco.Cloud.Issues#45]
The cloud portal makes it very easy to add hostnames to a project. However if you want to redirect any of them to a single domain, you would have to clone a site down, and handle it in the web.config or trnasformation file. 

If you could mark a hostname as 'primary', optional of course, and then have all other hostnames redirect to that, it would be a lot easier and faster to manage.

**Comment by nul800sebastiaan** [comment]
Thanks, this can be managed using rewrite rules for your site:

https://our.umbraco.com/Documentation/Umbraco-Cloud/Set-Up/Manage-Hostnames/Rewrites-on-Cloud

**Comment by MichaelNielsenDK** [comment]
I know, my point was that it would be a whole lot easier to manage. Not needing to clone a project down to do it.
