### ISSUE TITLE
Unable to configure IIS Rewrite rules for a v9 Cloud project

### ISSUE THREAD

**Issue by sussexrick** [umbraco/Umbraco.Cloud.Issues#456]
### Issue description

[Configuration transforms](https://our.umbraco.com/Documentation/Umbraco-Cloud/Set-Up/Config-Transforms/) have been a useful feature of Cloud for v8. They don't appear to be applied for v9 projects.

Although *.config files play a much smaller part in v9, there is still a `web.config` file which controls the IIS proxy, and there's still a need for transforms to customise this `web.config`, for example to populate the `system.webServer/httpErrors` section or to set up IIS Rewrite rules.

I tried putting a `web.live.xdt.config` file that I know to work from a v8 site into a v9 site but it was not applied. I tried it in the repository root (where it used to be), in the `src\UmbracoProject` folder and in the `src\UmbracoProject\wwwroot` folder.

**Comment by bergmania** [comment]
IMO it is correct Umbraco.Cloud do not support IIS transforms.

I would suggest to do rewrites in recommended ASP.NET Core way, as rewrites are not an umbraco specific thing.

MS has good documentation about how to use middleware:
https://docs.microsoft.com/en-us/aspnet/core/fundamentals/url-rewriting?view=aspnetcore-5.0

**Comment by c9mbundy** [comment]
I thought that web.config transforms were supported in ASP.Net Core
https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/iis/transform-webconfig?view=aspnetcore-5.0
Transforms were essential on cloud-7/8 to support multiple environments.

**Comment by sussexrick** [comment]
@bergmania OK, that's worth a try. It would work for setting HTTP headers too which is another scenario I had in mind. However, on [a thread on Our](https://our.umbraco.com/forum/umbraco-9/106697-custom-error-pages-in-umbrac0-9) the `system.webServer/httpErrors` section was the only way we could get custom error pages working for status codes other than 404 and 500. Any suggestions there?

**Comment by sussexrick** [comment]
@c9mbundy Genius, that works! 👍 The trick is to put Web.Release.config into the src\UmbracoProject folder. I'm not sure it would support environment-specific transforms but I don't have a scenario in mind that needs that. Do you?

**Comment by sitereactor** [comment]
I haven't tried this myself, but from the documentation it sounds like `web.Production.config` should work (live environment only)

**Comment by sussexrick** [comment]
@sitereactor I just tried - it doesn't.

**Comment by sitereactor** [comment]
I tried a few different combinations and it looks like it only works (for environment specific transforms) when this flag is added to dotnet publish `/p:EnvironmentName=Production`. I think this is something we can easily add to the default publish command, so environment specific web.config files can be added - ie. web.Development.config, web.Staging.config, web.Production.config.
I would have expected it to work given we have a `DOT_ENVIRONMENT` emvironment variable there by default. Also tried with `ASPNETCORE_ENVIRONMENT`, but it didn't make a difference.

**Comment by sitereactor** [comment]
This is now part of the deployment pipeline, so closing this issue.

Will look into getting it documented on our.umbraco.com
