### ISSUE TITLE
Option to view projects in List View

### ISSUE THREAD

**Issue by MichaelNielsenDK** [umbraco/Umbraco.Cloud.Issues#46]
When you have a lot of projects in the portal, the current Grid View does not offer a good overview. 

An option to change to List View and with the following additions, would make managing many projects a lot easier. 

- Show all environments on a project, grouped together
- Baseline children grouped under their Baseline Master
- Show version numbers in the list view 
- Show status (red/yellow/green) in the list view
- Option to filter list view by:
o	Version number
o	Status
o	Debug mode
o	Category/Client
- Option to sort listview by:
o	Creation date
o	Update date
o	Umbraco version
o	Category/Client
o	Name

**Comment by nul800sebastiaan** [comment]
Thanks, I need to check with the Cloud team as to what the plans are for UI updates in the future, we'll get back to you on this one.

**Comment by nul800sebastiaan** [comment]
This links to https://github.com/umbraco/Umbraco.Cloud.Issues/issues/47

As said in https://github.com/umbraco/Umbraco.Cloud.Issues/issues/47 - great suggestion as well and I've put it on the list of ideas we should use for when we start improving the overview!

**Comment by FransdeJong** [comment]
Any news on this request?

**Comment by sajumb** [comment]
We have started the design process of creating a new projects overview page. The feature request in this issue has been noted and will be taken into account when designing the new projects overview. We will close this issue and related feature requests to the projects overview. Thanks for the input and sorry about the late response!
