### ISSUE TITLE
Feature request: Make it possible to change technical contact on an organization level

### ISSUE THREAD

**Issue by hjaltedaniel** [umbraco/Umbraco.Cloud.Issues#469]
### Issue description

When you have an organization on Umbraco Cloud, it should be possible to set a technical contact for all projects under the organization instead of having to do it individually for every project.

**Comment by FransdeJong** [comment]
To add to this issue:

I would like to have a default technical contacts for the organization that gets added on creating a new project instead of the creator.
I would also like the same with the Account contacts.

**Comment by sajumb** [comment]
Thanks for this great feature request. We have created a ticket in our product backlog and marked it as an candidate for upcoming sprints.
