### ISSUE TITLE
Option to create and group projects by category/client

### ISSUE THREAD

**Issue by MichaelNielsenDK** [umbraco/Umbraco.Cloud.Issues#47]
We have several clients with several projects on Cloud.

Being able to create groups and grouping projects together would be a great addition, and would make managing those projects easier.

**Comment by nul800sebastiaan** [comment]
Thanks, I need to check with the Cloud team as to what the plans are for UI updates in the future, we'll get back to you on this one.

**Comment by nul800sebastiaan** [comment]
Yikes, that took a while to get back to @MichaelNielsenDK 🙈 

It's definitely a wish for us to improve the project overview and your suggestion here is great. We're not working on this in the immediate future but I've put it on the list of ideas we'll use as inspiration for when we do start working on it.

**Comment by sajumb** [comment]
We have started the design process of creating a new projects overview page. The feature request in this issue has been noted and will be taken into account when designing the new projects overview. We will close this issue and related feature requests to the projects overview. Thanks for the input and sorry about the late response!
