### ISSUE TITLE
Kudu button doesn't initially work on a freshly created project

### ISSUE THREAD

**Issue by RyuLindow** [umbraco/Umbraco.Cloud.Issues#470]
### Issue description

Repro steps:
1. create a new project
2. without leaving or refreshing the page try to access Kudu via the dropdown
3. the button won't work

It'll start working first after you've refreshed the page.
If you watch the video below you'll see that the Kudu button isn't pointing to any URL when you hover over it until after I've refreshed the page.

It's a v9 created on the new infra but I doubt that the version matters.

[VIDEO](https://www.dropbox.com/s/qakdcglqi9dzv99/AEBqssCVZN.mp4?dl=0)

**Comment by sajumb** [comment]
This has been resolved. Accordingly, we are closing this issue.
