### ISSUE TITLE
background color of instagram widget 

### ISSUE THREAD

**Issue by Dmitri-U** [umbraco/Umbraco.Cloud.Issues#472]
### Bug summary

Cannot change the background colour of instagram widget to "black" on Uno

Reproduction
------------

In the backoffice of Uno, I worked with Instagram widget. However, when I proceed to widget settings, and try to modify background color to black, it does not change, nor it changes to any other color (grey, blue)

### Specifics

   
Uno version 8.7.1 also 8.7.3

**Comment by nul800sebastiaan** [comment]
Hi there @Dmitri-U - by now all Uno users should have had an email announcing that Uno is being sunsetted. 🌇
If you haven't been notified yet then all the details are here: https://umbraco.com/products/knowledge-center/long-term-support-and-end-of-life/umbraco-uno-discontinued/

This means we will be closing the remaining open Uno issues as we're no longer going to be working on those. Thanks!
