### ISSUE TITLE
Workspaces dashboard doesn't work initially

### ISSUE THREAD

**Issue by skttl** [umbraco/Umbraco.Cloud.Issues#474]
### Issue description

When going to site.umbraco.io/umbraco the workspaces dashboard doesn't work at first.

It just gives a loading spinner, and the console gets "Could not get deploy configuration" logged.

![image](https://user-images.githubusercontent.com/3726467/138234796-0d2da435-7e7c-4dff-af8b-57f46c244b6a.png)

This is coming from this part of the dashboard controller:

```js
    if (Umbraco.Sys.ServerVariables.deploy !== undefined && Umbraco.Sys.ServerVariables.deploy !== null) {
        angular.extend(instance, Umbraco.Sys.ServerVariables.deploy);
    } else {
        console.log('Could not get deploy configuration');
    }
    return instance;
```

It seems like the dashboard can be loaded before the server variables is loaded.

If I go to `/umbraco#/media?dashboard=mediaFolderBrowser` first, and then switch to content, the dashboard loads correctly, probably because the servervariables then have been loaded, before loading the workspaces dashboard.

I've only seen this after upgrading some projects to 8.17 (from 8.15 and below), not sure if there has been made some changes in between 8.15 and 8.17 to how the server variables, or dashboards are loaded.

**Comment by skttl** [comment]
Seems like it works in 4.4.0 🤞

**Comment by AndyButland** [comment]
Good to hear.  Sorry, I thought I'd updated on this issue if only to say that I looked into this and couldn't seem to replicate it... but seems I forgot to actually do post an update.

I'm not sure what, if anything, was updated in 4.4 that should have resolved this, but at least it seems to be working for you now.  I'll close the issue then,
