### ISSUE TITLE
Connection details in cloud portal should have info regarding blob container

### ISSUE THREAD

**Issue by skttl** [umbraco/Umbraco.Cloud.Issues#475]
### Issue description

In the connection details (https://www.s1.umbraco.io/project/projectname/connection-details), it would be nice if you had the blob storage information available here, preferably as the complete url you need to paste into Storage Explorer.

Described here: https://our.umbraco.com/Documentation/Umbraco-Cloud/Set-Up/Media/Connect-to-Azure-Storage-Explorer/#configuring-the-connection-to-your-azure-blob-storage

**Comment by sajumb** [comment]
Thanks for the feature request. We have created a ticket for this and added it to the backlog. Currently we have no estimate for the handling of the request. I've update this issue when we have an update.

**Comment by sajumb** [comment]
This feature request has been served. See https://our.umbraco.com/documentation/Umbraco-Cloud/release-notes/2022-01-31-ReleaseNotes for more info.
