### ISSUE TITLE
Icons missing from external login providers

### ISSUE THREAD

**Issue by bjarnef** [umbraco/Umbraco.Cloud.Issues#476]
### Issue description

I noticed on a v9 Umbraco Cloud project the icons are missing here:

![image](https://user-images.githubusercontent.com/2919859/138483694-0592c319-ff6c-45dc-9f0c-fcf3cb9bd0e2.png)

In `/App_Plugins/UmbracoId/BackOffice/custom-login.html` it has the following:

```
<div ng-if="vm.state === 'backoffice' && vm.isLocalLogin === false">
	<div ng-if="vm.isUmbracoIdUser && vm.loadingUmbracoIdSetting === false">
		<form ng-submit="vm.submitUmbIdProfileForm($event)"
			  method="POST"
			  action="{{vm.umbIdProfileFormEndpoint}}"
			  name="umbIdProfileForm" id="umbIdProfileForm">
			<umb-button type="submit"
						button-style="action"
						label-key="umbId_editProfile"
						icon="fa {{login.properties.SocialIcon}}">
			</umb-button>
		</form>
		<form ng-submit="vm.submitUmbIdPasswordForm($event)"
			  method="POST"
			  action="{{vm.umbIdPasswordFormEndpoint}}"
			  name="umbIdPasswordForm" id="umbIdPasswordForm">
			<umb-button type="submit"
						button-style="action"
						label-key="umbId_changePassword"
						icon="fa {{login.properties.SocialIcon}}">
			</umb-button>
		</form>
	</div>
	<div ng-if="vm.isUmbracoIdUser === false && vm.loadingUmbracoIdSetting === false">
		<p>Local users cant be linked to Umbraco Id</p>
	</div>
</div>
```

The icon is passed in to  `<umb-icon>` inside `<umb-button>` component here:

https://github.com/umbraco/Umbraco-CMS/blob/v9/contrib/src/Umbraco.Web.UI.Client/src/views/components/buttons/umb-button.html#L51

which then render either inline SVG icon or fallback to legacy font icon.

It seems it try to render the SVG icon, but with no content.

There is something similar in core here:
https://github.com/umbraco/Umbraco-CMS/blob/v9/contrib/src/Umbraco.Web.UI.Client/src/views/common/overlays/user/user.html#L74

**Comment by bjarnef** [comment]
Has anything recently changed on Cloud projects as I noticed it currently throws this console errors on the same project. @AndyButland 

For some reason `Umbraco.Cloud.Identity.CustomLoginController` isn't registred.

![image](https://user-images.githubusercontent.com/2919859/141069205-95f93624-71b3-41d7-a138-af3a2a826ced.png)

**Comment by bjarnef** [comment]
@AndyButland it seems this is still an issue.. any plan to update the icons or remove the icons?

**Comment by AndyButland** [comment]
Thanks @bjarnef - I've created a PR for the Cloud team to review that will resolve this, at least for V10 and moving forward.

**Comment by devantler** [comment]
The PR has been merged and should be out soon :-)
