### ISSUE TITLE
Some commits get stuck in limbo and doesn't show until you ask for them in Kudu

### ISSUE THREAD

**Issue by greystate** [umbraco/Umbraco.Cloud.Issues#477]
### Issue description

It sounds weird, but I've tried this several times now, so can describe what happens.

It's a scenario that I do regularly, in Umbraco on the environment that was cloned (these are performed on the cloud server, not locally):

1. I modify an Element Type used in a BlockList Editor (e.g. add a new property)
2. I also modify the partial that renders said item
3. I restart the environment to make sure "some cache" has the new models (I use the default PureLive mode for Models Builder so technically shouldn't be necessary, I'm told)
4. I do a `git pull` locally to pull the changes down to my local repository
5. The changes doesn't show up in my git history _("What??")_
6. I then need to open Kudu, go to the `C:\home\site\repository>` and type `git status`
7. The commits are listed here _("What? Seriously?)_
8. I do another git pull locally, and lo and behold - the changes come flying down _("What? Really?")_

The problem here of course is that even though I do a git pull locally before pushing something, I could end up overwriting the changes I just did...

**Comment by greystate** [comment]
Just an update here; it is very consistently happening on this project today. It's an `Umbraco 8.13.1` using `Deploy 4.1.4` if that helps.

Made a change to an existing partial and still waiting for it to appear when pulling from the repo.

I know that as soon as I do `git status` in the _repository_ directory on Kudu it will appear...

**Comment by greystate** [comment]
I have an `Umbraco 7.15.7` site with `Deploy 2.1.6` where this is happening; very consistently too...

I can create a new Partial in the backoffice and it never shows up when pulling; but as soon as I open the site/repository directory in Kudu, I am able to pull the change down, even before issuing any commands in the directory.

**Comment by greystate** [comment]
Today's appearance of this problem is in an **Umbraco** `8.3.1` (can not upgrade due to a package) with **Deploy** `4.1.4`

**Comment by greystate** [comment]
Currently experiencing this in an **Umbraco** `10.3.2` with **Deploy** `10.1.2`

(Save a partial in Umbraco - file not being committed)

**Comment by greystate** [comment]
This issue has become the bane of my existence...

On one specific v7 site I can't even trigger the changes by `git status` or similar commands. And I can't even see the changes in the site's files (e.g. no .uda seem to be generated).

Is there *anything at all* I can do manually in Kudu to fix this?

**Comment by greystate** [comment]
**UPDATE:** For anyone following along at home (😁); I managed to get the changes committed by performing this little dance in the `site/wwwroot/data/` directory in Kudu (on DEV):

```bash
$ echo > deploy-export
$ # Wait for the deploy-complete marker file...
$ echo > deploy
```

**Comment by sajumb** [comment]
Hi @greystate 
I'm sorry we haven't given you much feedback on your questions and challenges in this thread. But our support would be very happy to help you regarding this issue through the usual channels. So feel free to contact them. 😄

**Comment by sajumb** [comment]
@greystate I believe that these issues have been resolved with changes in Umbraco Cloud and Umbraco Deploy combined. In case you see it differently please reach out to me. Thanks 😄
