### ISSUE TITLE
Header block should have property to specify anchor value

### ISSUE THREAD

**Issue by bjarnef** [umbraco/Umbraco.Cloud.Issues#478]
### Issue description

When inserting an header block it should be possible to specify the anchor value so it is easy to link to this, e.g. "#my-heading`

There should then be a `<a id="my-heading"></a>` right before heading.

![image](https://user-images.githubusercontent.com/2919859/139026710-cb0f9f7c-044e-44b9-976e-cd627fabd2cb.png)

See also to insert anchor point in richtext editor: https://github.com/umbraco/Umbraco.Uno.Issues/issues/83

**Comment by nul800sebastiaan** [comment]
Hi there @bjarnef - by now all Uno users should have had an email announcing that Uno is being sunsetted. 🌇
If you haven't been notified yet then all the details are here: https://umbraco.com/products/knowledge-center/long-term-support-and-end-of-life/umbraco-uno-discontinued/

This means we will be closing the remaining open Uno issues as we're no longer going to be working on those. Thanks!
