### ISSUE TITLE
Add a link to access the env logs even if there are no unread errors.

### ISSUE THREAD

**Issue by RyuLindow** [umbraco/Umbraco.Cloud.Issues#481]
### Issue description

Currently, the view errors button is only available if you have any unread errors.

![image](https://user-images.githubusercontent.com/56826332/139115032-d0476925-2018-4ca2-89e0-2bfa43276849.png)

It is still possible to access the error log by manually navigating to its URL when you have no unread errors but it would be a nice QoL change to have that access point permanently available.

**Comment by sajumb** [comment]
We have added an option on the environment setting. This link is always available for every environment.
![LogsAlwaysAvailable](https://user-images.githubusercontent.com/93588665/154433625-7b88ac5f-6968-4c6d-8db9-4b4a74c5fbf1.gif)
