### ISSUE TITLE
Can't create an extra environment because of too many files in the repository

### ISSUE THREAD

**Issue by HalldorLyngmo** [umbraco/Umbraco.Cloud.Issues#483]
## Issue
This is probably a bit of an edge case. But when you've got around 30k of files in your repository and try to create an extra environment it fails. 

### Exception
```
The request was canceled due to the configured HttpClient.Timeout of 100 seconds elapsing. 
System.Net.Sockets.SocketException at Umbraco.Cloud.Deployment.SiteExtension.Client.Git+<MergeRemoteBranchWithHttpMessagesAsync>d__5.MoveNext
```

Nr. of files in the repo on Cloud
![image](https://user-images.githubusercontent.com/42831978/139408130-8fd72aa4-0e64-45fd-9c50-06c48b2dcb5a.png)

Size in mb
![image](https://user-images.githubusercontent.com/42831978/139409202-70290100-fe6b-44b3-a5e6-5764f6fcf23b.png)

### Portal logs
```
The request was canceled due to the configured HttpClient.Timeout of 100 seconds elapsing. The operation was canceled. 
The operation was canceled. Unable to read data from the transport connection: The I/O operation has been aborted because of either a thread exit or an application request.. 
The I/O operation has been aborted because of either a thread exit or an application request. 
```
```
Unable to perform merge from remote branch on environment with Id c0b1f2db-754e-40ab-9075-8cc4a128e964, and scmUrl https://dev-hly-large-repo.scm.euwest01.umbraco.io. 
Message returned was The request was canceled due to the configured HttpClient.Timeout of 100 seconds elapsing.
```

Tested on the 28th of October around 2:36 PM CEST
Project id: 965b7e77-a928-41d8-9f61-f7461e8ed41d

**Comment by sitereactor** [comment]
Closing this as fixed, but pending deployment to PROD, which will be done no later than Monday - possibly before then.

**Comment by hfloyd** [comment]
The Project having this issue is one I help manage. I am still unable to create a staging environment, and I wonder if I should try to reduce the GIT repo size? (https://stackoverflow.com/questions/2116778/reduce-git-repository-size)

This was a HUGE v7 site, with a lot of obsolete file and schema objects. We have been cleaning it up, deleting unneeded templates, etc. but I imagine all that activity is not really reducing the GIT size, but rather increasing it (due to it tracking all those deletes, while still maintaining versions of those deleted files)

**Comment by sitereactor** [comment]
How long does it take to do a fresh clone?
FWIW we rolled out an update, which increases the timeout when creating a new environment, so it should have at least 5 minutes to work with. This is quite a long time in git, but would be curious to know if its still an issue. And the timing of course :)

**Comment by hfloyd** [comment]
Testing right now, cloning from Dev to local, it takes only about 2-3 minutes. The final git message is "Updating files: 100% (18222/18222), done."

**Comment by sitereactor** [comment]
The previous timeout was 100 seconds, so that could certainly explain it.

Do you need the Staging environment added still? In which case I would assume it to be possible now.

**Comment by hfloyd** [comment]
I just tested cloning from live to my local and it took only about a minute. 

Then I guess the problem with getting a staging environment on Cloud is not related to git, then, because When I try to do it, it runs, and runs, and runs, then just pops up a failure message.

**Comment by sitereactor** [comment]
Well to be fair its not exclusively related to cloning, as a few different things happen when creating a new environment. The error that Halldor listed in this bug report was from after the new Staging environment had fetched changes from Live and was in the process of merging and then deploying these changes onto the staging environment itself.

Does it still fail to successfully add a new Staging environment? If it does then we need to investigate what is going on.

**Comment by hfloyd** [comment]
Yes, I am unable to add a staging environment right now. Check in with Dennis. He was just looking at it with me.

**Comment by hfloyd** [comment]
FYI - I was able to significantly clean up the site schema (deleting almost 600 old templates and almost 100 old doctypes). I deleted these in both the dev and live environments, and was then able to set up the staging environment. So, it might be less about GIT size than about SCHEMA size...?
