### ISSUE TITLE
Where _any argument doesn't work with integer properties

### ISSUE THREAD

**Issue by RyuLindow** [umbraco/Umbraco.Cloud.Issues#484]
### Issue description

`
query {
  allBlogArticle (where: {readTime: 7}) {
    items {
	readTime
    }
  }
}
`
This works

`query {
  allBlogArticle (where: {readTime_any: 7}) {
    items {
      readTime
    }
  }
}
`
This doesn't work

I get this error:
![image](https://user-images.githubusercontent.com/56826332/139681661-1b9ce653-38bd-49a6-9b32-59de70144915.png)

[VIDEO](https://www.dropbox.com/s/wjd29isbi445ax4/fYRTZmgeKh.mp4?dl=0)

**Comment by rasmusjp** [comment]
Hi @RyuLindow 

We've deployed a fix for this
