### ISSUE TITLE
Can't view page due to basic auth on dev and stage

### ISSUE THREAD

**Issue by Frost117** [umbraco/Umbraco.Cloud.Issues#495]
### Issue description

When you click on View page to see the front-end on an environment that has basic auth on it, you will not be able to log in, until you have logged into the backoffice. 

Even when you type your login information correctly in the basic auth prompt, you will simply be redirected back to the prompt.

When you log in through the backoffice, you'll get a cookie associated to that env and from there you are able to log in.
This only happens on the new infrastructure and wasn't a problem on the old infrastructure. 

If you do not have the cookie set, you'll get the prompt again and again until you have gotten the cookie from the backoffice.

**Comment by rhealefever** [comment]
I also ran into this problem today after enabling basic auth and pushing my changes to Cloud.

**Comment by tormnator** [comment]
Same here. I chatted with cloud support and they thought it was an issue with our Dev site and wanted to recreate it (backup/restore). I declined.

**Comment by JasonDeJesuz** [comment]
We are still having this issue on our environments, any updates yet? It's pretty hard to get client approvals on staging without this.

**Comment by ivanpnikolov** [comment]
If you have defined custom domains, you will not be able to visit the site even if you are logged in the BackOffice. I guess, because the cookie is not handled by the custom domain.

**Comment by sajumb** [comment]
Thanks. We will look into this issue and see what can be done.

**Comment by sajumb** [comment]
Hi @rhealefever @tormnator  @JasonDeJesuz @ivanpnikolov @ninatevelde,
We have discovered that the migration to the new infrastructure for some environments have had a negative effect on the SiteExtension.BasicAuth module. Accordingly, we need to update this module on the environments that are having the issue with basic auth as outlined in this thread.

Unfortunately, this will have to be done manually by our Support. So if one or more of your projects is facing this issue, please reach out to our support and ask them to update the SiteExtention.BasicAuth module for the environments of your project(s). Sorry for the inconvenience.

**Comment by sajumb** [comment]
We expect to consider this issue with the user being redirected to the backoffice instead of the page (for the first try) within the next month.

**Comment by sajumb** [comment]
This has been resolved for all impacted versions of Umbraco CMS in Umbraco Cloud (V9 and newer).
