### ISSUE TITLE
html lang="en" can't be changed

### ISSUE THREAD

**Issue by rjkoning** [umbraco/Umbraco.Cloud.Issues#496]
### Issue description

The html lang="en" tag can't be changed in the head of the source of the website,and that's very important for SEO optimisation.
So al Umbraco Uno customers that don't have the english language on their site have a seo problem. And wil not score.

Ability to choose the language setting of a page
Currently the default language setting is English <html lang="en">. Of course for non English websites it should be possible to alter the language setting to the applicable language. At this time this is not possible. It should be possible to do this as this is required for SEO optimization and an optimal indexing bij search engines.

**Comment by nul800sebastiaan** [comment]
Hi there @rjkoning - by now all Uno users should have had an email announcing that Uno is being sunsetted. 🌇
If you haven't been notified yet then all the details are here: https://umbraco.com/products/knowledge-center/long-term-support-and-end-of-life/umbraco-uno-discontinued/

This means we will be closing the remaining open Uno issues as we're no longer going to be working on those. Thanks!
