### ISSUE TITLE
Prevent two URL variants

### ISSUE THREAD

**Issue by rjkoning** [umbraco/Umbraco.Cloud.Issues#499]
### Issue description

Prevent two URL variants

Currently it is not possible to select if the url is standard with or without a trailing slash.
For example: umbraco.com/about-us/ or umbraco.com/about-us.
The current set-up results in two different url’s. One with an / and one without. Although there is a canonical url in place that directs to the main url, for SEO this is not ideal. 
Internal linking and backlinks are potentially redirected. From a sitespeed perspective and the flow of link juice within the site you want only one url technically generated within the installation. Furthermore it demands unnecessary crawling budget from the Google bot. 

So the request is to make it possible to select if you want an url with or without a trailing / and prevent the other variant from being generated in Umbraco Uno.

**Comment by nul800sebastiaan** [comment]
Hi there @rjkoning - by now all Uno users should have had an email announcing that Uno is being sunsetted. 🌇
If you haven't been notified yet then all the details are here: https://umbraco.com/products/knowledge-center/long-term-support-and-end-of-life/umbraco-uno-discontinued/

This means we will be closing the remaining open Uno issues as we're no longer going to be working on those. Thanks!
