### ISSUE TITLE
When trying to use a media picker as a **writer**, you are prompted to authenticate with basic authentication.

### ISSUE THREAD

**Issue by hartviglarsen** [umbraco/Umbraco.Cloud.Issues#5]
When trying to use a media picker as a **writer**, you are prompted to authenticate with basic authentication.

If I cancel the authentication I will get logged out. However, if I then sign back in, I can - still as a **writer** - use the media picker just fine.

Reproduction
------------

### Specifics

Umbraco 7.12.2
Forms 7.0.4
Deploy 2.0.14

### Steps to reproduce

1. Create a user who is a **writer**
2. Create a node with a media picker
3. Sign in with the **writer** user
4. Try to use the media picker
5. I get promoted to sign in with basic auth.

![image 9](https://user-images.githubusercontent.com/4366314/45950518-69102980-c000-11e8-819c-5081c13979a2.png)

### Expected result

I expect to be able to use the media picker.

### Actual result
I get signed out.

**Comment by hartviglarsen** [comment]
I was playing around with members groups on a trial project, when suddenly I was asked to authenticate with basic auth.

![basic auth](https://user-images.githubusercontent.com/4366314/46130718-3ea9b080-c23a-11e8-98d4-e4e972370815.PNG)

**Comment by nul800sebastiaan** [comment]
@hartviglarsen It's been a year and a half.. I haven't seen other issues around this, so either it's been fixed or nobody  is actually running into it. I'll close this for now but happy to re-open if you can still reproduce.
