### ISSUE TITLE
Uda-files for Nested Content datatypes should have a dependency on selected doctypes

### ISSUE THREAD

**Issue by skttl** [umbraco/Umbraco.Cloud.Issues#50]
When creating a Nested Content data type, and inspecting the generated uda-file, I noticed, that the data-type has no dependencies at all.

Shouldn't it have a dependency on the doctype(s) selected in the prevalues of the datatype?

```
{
  "EditorAlias": "Umbraco.NestedContent",
  "DatabaseType": 0,
  "PreValues": {
    "confirmDeletes": "1",
    "contentTypes": "[\r\n  {\r\n    \"ncAlias\": \"topbanner\",\r\n    \"ncTabAlias\": \"Topbanner\",\r\n    \"nameTemplate\": \"{{ headline }}\"\r\n  }\r\n]",
    "hideLabel": "1",
    "maxItems": "1",
    "minItems": "1",
    "showIcons": "1"
  },
  "Parent": null,
  "Udi": "umb://data-type/50d1e58a5b794707a63e78ac1a4637ed",
  "Dependencies": [],
  "Name": "Topbanner",
  "Alias": null,
  "__type": "Umbraco.Deploy,Umbraco.Deploy.Artifacts.DataTypeArtifact",
  "__version": "2.0.14"
}
```

**Comment by nul800sebastiaan** [comment]
Hi @skttl, that would be semantically more correct for sure. However, we're not too sure what the actual problem is you're running into, can you tell us more please?

**Comment by skttl** [comment]
Hi @nul800sebastiaan 

I'm trying to build a collection of compositions I can drop into any project. Every composition consists of the schema (uda-files), and maybe some views. The content is then added to a nuget package, which I can install in my projects.

In order to find the necessary uda-files, I started from the uda-file for my composition, and worked my way through the dependencies. And then I noticed, that the nested content datatype didn't have a dependency on its document types.

I know it is not a textbook way of using Umbaco Cloud. It just seemed simpler for me to use the uda files, in stead of creating a package which would need a manual install.

**Comment by nul800sebastiaan** [comment]
Aha I see. As you said this is not a scenario we support unfortunately, the assumption is that you have the data folder committed to git and we make sure everything necessary exists in there :)

We currently have no plans to add this data to uda files.

**Comment by zpqrtbnk** [comment]
That being said @nul800sebastiaan I would say this is definitively a bug, that would for example hit standalone Deploy. Can you file a Deploy bug for it?

**Comment by nul800sebastiaan** [comment]
Thanks @zpqrtbnk - yup, standalone deploy has different requirements, will add to that tracker.

**Comment by skttl** [comment]
Standalone deploy? 😍😍😍

**Comment by skttl** [comment]
This is probably a bug/feature of Nested Content though, as it doesn't reference an id or guid of the document type, but just the alias.

I have not tested it, but I suspect, that if I change the alias of an already used document type, the nested content data type would fail.
