### ISSUE TITLE
No Image Alt tag when we use image in grid with sub grid

### ISSUE THREAD

**Issue by rjkoning** [umbraco/Umbraco.Cloud.Issues#500]
### Issue description

When we use an image alt text in the image and we put the image in a sub grid from a grid then the alt tag is not working in the 
![2021-11-25_09-46-57](https://user-images.githubusercontent.com/89451943/143412699-aeaaed6a-5035-4d22-bae3-79355f5dfd4d.png)

**Comment by nul800sebastiaan** [comment]
Hi there @rjkoning - by now all Uno users should have had an email announcing that Uno is being sunsetted. 🌇
If you haven't been notified yet then all the details are here: https://umbraco.com/products/knowledge-center/long-term-support-and-end-of-life/umbraco-uno-discontinued/

This means we will be closing the remaining open Uno issues as we're no longer going to be working on those. Thanks!
