### ISSUE TITLE
Git URL isn't available from the "Workspaces" dashboard

### ISSUE THREAD

**Issue by AndyButland** [umbraco/Umbraco.Cloud.Issues#503]
### Issue description

As per the following screenshot, we are making available the next workspaces Git URL to indicate how to clone into a local environment.

![image](https://user-images.githubusercontent.com/1993459/143871395-87f1cf08-a0d4-4419-a4c4-70195a16b34a.png)

It's empty though.

Tracing through it seems we are expecting this information to be in the `umbraco-cloud.json` file along with details like the name and ID, but it's not present.

E.g.

```
{
  "Deploy": {
    "Project": {
      "Name": "andy v9 test 29 11 2021",
      "Alias": "andy-v9-test-29-11-2021",
      "Id": "619114b9-7553-4b8e-b017-460927a684f3",
      "Workspaces": [
        {
          "Id": "a7be198d-463a-4403-9311-2326e550af76",
          "Name": "Live",
          "Type": "live",
          "Url": "https://andy-v9-test-29-11-2021.euwest01.umbraco.io",
          // This is missing and expected by the Deploy UI: "Git": "GIT URL"
        }
      ]
    },
    "Settings": {
      "ApiKey": "..."
    }
  },
  "Identity": {
    ...
  }
}
```

**Comment by sitereactor** [comment]
If you take the `andy-v9-test-29-11-2021` and `euwest01` parts out of the hostname then you can easily construct the git scm url:
`https://scm.umbraco.io/euwest01/andy-v9-test-29-11-2021.git`. But if the git url is missing then that will likely have been an oversight when creating the umbraco-cloud.json file.

**Comment by AndyButland** [comment]
OK... I can see now for Umbraco 8 (Deploy V4) we had this `Git` property, but it was a calculated one (basically using the convention you described above).  So it wasn't previously in a configuration file, and so doesn't seem to be a need to have it for V9.  Rather I'll look to migrate over this logic to the V9 configuration

**Comment by AndyButland** [comment]
Will close this and create a new issue in Umbraco.Deploy.Issues so can track to a release.
