### ISSUE TITLE
Cloud portal: Usage page returning incorrect bandwidth data

### ISSUE THREAD

**Issue by HalldorLyngmo** [umbraco/Umbraco.Cloud.Issues#509]
### Issue description

Tested today on a customer project. There seems to be some caching going on with the request for the Cloudflare data.

Going to the usage page and refreshing it a couple of times gave me different results almost every time. The result was adding the total of the first response. Then after a couple of refreshes, or going to a different page then come abck, it would go back to the initial result.

![image](https://user-images.githubusercontent.com/42831978/145977603-9320d26e-2124-4aef-a596-7252b9c94064.png)

![image](https://user-images.githubusercontent.com/42831978/145977667-2d921577-db1d-435e-bf2e-3f33cde8f1c9.png)

![image](https://user-images.githubusercontent.com/42831978/145977743-68672a40-9722-408d-964e-1564025b9f13.png)

**Comment by HalldorLyngmo** [comment]
After writing the issue I went back to test it one last time. I had a hard time reproducing, it wasn't until 10+ refreshes where it happened and went from 368GB down to 124GB.

**Comment by sajumb** [comment]
Hi Halldor. Thanks for reporting this. We have in the previous weeks modernized and improved the usage handling in a new service in our infrastructure. When this service is to be used in the portal this caching issue will be fixed as well. The change is expected to happen within few weeks. I'll return with an update when the change has been deployed to production.

**Comment by sajumb** [comment]
We are now using a Cloudflare endpoint for the bandwidth usage which should be 100% reliable.
We consider this issue fixed and are closing the ticket.
