### ISSUE TITLE
Unable to protect IDN domain with Umbraco Latch

### ISSUE THREAD

**Issue by greystate** [umbraco/Umbraco.Cloud.Issues#51]
Currently it's not possible to use Umbraco Latch for IDN domains (i.e. domains that include non-ASCII characters like **æ** or **ö**).

Steps to reproduce
------------

- Under **Manage Hostnames**, add the domain `løverne-i-zoo.dk`
- Wait a couple of minutes
- Revisit the **Manage Hostnames** screen and observe the status "Special characters" instead of the expected **Protected by LATCH**.

That status doesn't look like an error message, so I need to ask Support what happened.

**Comment by sitereactor** [comment]
ÆØÅ Hostnames with certificate is not currently supported in Umbraco Cloud due to missing support for "special characters" in an infrastructure component. You can add the hostname and it will work over HTTP, but not HTTPS as we cannot bind the certificate because of missing support in the mentioned component.

Unfortunately its not something that is easily fixed, so we won't be able to add support in the near future.

Only workaround so far is to have a proxy in front - possibly something like Cloudflare.

**Comment by greystate** [comment]
Thanks @sitereactor 

While it's unfortunate to find out about this in the final stages of getting a project online, I guess we'll make do with "only" HTTP for now since it's not a huge website and they're weren't using HTTPS before, and I really don't feel like adding another layer of complexity by putting a proxy in front, however "easy" it probably is :)

**Comment by greystate** [comment]
Is _"not in the near future"_ still the current time-frame for this?

Just asking because we're now in a somewhat far distant future from when that answer was given and the component in question might possibly have been updated 😁 ?

**Comment by sitereactor** [comment]
We are in the process of modernizing our infrastructure, so once that is done we should be able to support certificates for IDN domains.
I'm afraid we don't have a time frame for when it will be available/possible. But hopefully by the end of the calendar year.

**Comment by greystate** [comment]
That's good to hear; thanks for the update Morten ⭐

**Comment by sitereactor** [comment]
FINALLY !! 🎉 I'm closing this issue as IDN hostnames are now fully supported for custom hostnames end to end.
It is now possibe to add a custom hostname like ællebælle.dk through the Cloud Portal and Umbraco Cloud will handle the rest.
🌮 🌮 🌮

**Comment by RyuLindow** [comment]
Heya. @sitereactor 

Just tried to add my IDN domain, ragnarøk.dk and found a bug.

Add ragnarøk.dk in the manage hosnames section makes it stuck on the pending status.

Then I added the Punycode version of that domain, xn--ragnark-v1a.dk, and it worked just fine.

Is it intended or just a bug? If it's intended then it would be nice to add a warning msg, when someone tries to add a hostname with special characters :)

**Comment by sitereactor** [comment]
It should not be necessary to add the puny code version of the hostname. It's been tested multiple times, so not sure why it wouldn't work for you.
