### ISSUE TITLE
Deploying schema changes restarts the sites on app service

### ISSUE THREAD

**Issue by HalldorLyngmo** [umbraco/Umbraco.Cloud.Issues#510]
### Issue description

Tested on New Cloud

## Versions:
Umbraco: 
- v8.17.1 and v7.15.7

Deploy: 
- v2.1.5 and v4.4.0.0

Site extensions:
![image](https://user-images.githubusercontent.com/42831978/146002783-b0244f1b-3ea7-4ee8-aff9-0d73f3493c0d.png)

## Issue
When deploying small changes to document types or data types the application should not be restarting. However, that is now happening for both v7 and v8 projects. The deployment from the Repository folder to wwwroot will always touch the `web.config`. No changes, it's just saved. 

This creates an issue with v7 sites where the deployment extraction might have begun.  When the `web.config` is changed and the site restarts it will sometimes kill the deployment but report it as complete. Meaning no changes were extracted to the backoffice.

On v8 the same thing happens with the restart but Deploy handles it a bit better with creating a different marker which fires on application start `deploy-on-start`.

## Reproduction

1. Create a v7 or v8 project with the latest versions.
2. I used two environments Dev and Live. (I saw the issue on Deployments from Local to Dev and Dev to Live.)
3. Create a UDA files and deploy it, or make a small change to the UDA file already there.
4. You should now see the `web.config` having "changed" by the timestamp and if you look in the logs there is a shutdown because of a config change.

![image](https://user-images.githubusercontent.com/42831978/146006707-1af6e870-3970-45e9-bc2e-9bfc422587e9.png)

```
2021-12-14 13:17:35 INF Application shutdown. Details: ConfigurationChange
_shutDownMessage=IIS configuration change
HostingEnvironment initiated shutdown
CONFIG change
HostingEnvironment caused shutdown
_shutDownStack= at System.Environment.GetStackTrace(Exception e, Boolean needFileInfo)
at System.Environment.get_StackTrace()
at System.Web.Hosting.HostingEnvironment.InitiateShutdownInternal()
at System.Web.Hosting.HostingEnvironment.InitiateShutdownWithoutDemand()
at System.Web.Hosting.PipelineRuntime.StopProcessing()
```

**Comment by AndyButland** [comment]
I've back-ported the use of the `deploy-on-start` into Deploy for Umbraco 7 now, which will be in release 2.1.6.  When that and the related update to the site extension are released, we'll have this more reliable process for extractions across site restarts available for Umbraco 7 projects in Cloud too.
