### ISSUE TITLE
Kudu performance on new infrastructure

### ISSUE THREAD

**Issue by c9mb** [umbraco/Umbraco.Cloud.Issues#513]
### Issue description

Kudu has never provided stellar performance, but was something you put up with to get the job done.

However, I'm finding that on all sites migrated to the new infrastructure, the performance is excruciatingly slow, to the point of almost being unusable at times, and the debug console can be totally unresponsive at times.

Is this just me and my sites, or is it actually worse now than before ?

**Comment by RyuLindow** [comment]
I completely agree.

I've seen it across a couple of different projects, however, it's quite random as most of them work just fine.

It's just an unclear % of them that's slower -.-
