### ISSUE TITLE
Logs not updated for almost 5 months in the portal 

### ISSUE THREAD

**Issue by PratheesUmbraco** [umbraco/Umbraco.Cloud.Issues#519]
### Issue description

I have project where the Umbraco ogs haven't been updated since September 21
<img width="636" alt="image" src="https://user-images.githubusercontent.com/74538774/149223682-b3b2d1bb-3dd5-4b06-a9f0-7e2bb9cac4b4.png">

In Kudu, it's updated, as it should, but that doesn't reflect in portal 

Kudu:
<img width="626" alt="image" src="https://user-images.githubusercontent.com/74538774/149223532-486bbf74-73e9-471a-96b5-85e8ce6353d8.png">

**Comment by sajumb** [comment]
Thanks for the report. We will look into this issue.

**Comment by sajumb** [comment]
Closing this as the issue was casued by bad sorting of dates as solved in https://github.com/umbraco/Umbraco.Cloud.Issues/issues/532
