### ISSUE TITLE
"This project is based on the baseline" should be a link

### ISSUE THREAD

**Issue by skttl** [umbraco/Umbraco.Cloud.Issues#52]
![billede](https://user-images.githubusercontent.com/3726467/52775692-8e99e000-3040-11e9-8c6c-fe83f2e14e1d.png)

I feel this should be a link to the baseline project. And maybe even add an option to update the child project from here already.

**Comment by pijemcolu** [comment]
The PR has been merged and this is in the release pipeline very soon. Thanks for bringing this up @skttl.
