### ISSUE TITLE
Feature request: Improve the /profile/pendinginvites view

### ISSUE THREAD

**Issue by RyuLindow** [umbraco/Umbraco.Cloud.Issues#520]
### Issue description

Okay, so invites expire after 2 days if I remember correctly.

The thing is that if you don't accept an invite it'll stay in the pending invites view forever.

[VIDEO](https://www.dropbox.com/s/layzsjgfltnwzsj/brave_ZtdNZjJZAw.mp4?dl=0)

I would like to ask for the following:

1. For the invites to be greyed out when they've expired including a button to remove them all at once or some sort of a filter. I'm open to suggestions :)

2. Some sort of ordering system. Currently, we don't order it either by date, project alias or name of the person who invited you, so the project you got invited to can be anywhere on that list.

3. A date column next to each invite to see when it was sent and maybe also when it expires(not sure if the expiration date makes sense, though.)

**Comment by sajumb** [comment]
Thanks for this feature request.
We are planning to improve the _pendinginvites_ views within one of the next sprints. I have updated the existing backlog item with the information above.

**Comment by sajumb** [comment]
Closing this at the pending invites page has been updated with the content of this feature request.
