### ISSUE TITLE
ApplicationUrl gets set as Localhost on the live env.

### ISSUE THREAD

**Issue by Frost117** [umbraco/Umbraco.Cloud.Issues#526]
### Issue description

In odd scenarios the applicationUrl from the umbracoSettings.config gets its applicationUrl set to localhost.

Whilst not hurting performance or cause the site to go down, atleast in the tests that I have done, it does provide a lot of errors in other aspects.

Forexample:
https://github.com/umbraco/Umbraco.Cloud.Issues/issues/466 

In this issue I want to bring highlight to the invitation from the backoffice.

For certain types of projects on the Umbraco Cloud service, if the applicationUrl gets set to localhost, any invites to the backoffice will have its url look like the following:
![image](https://user-images.githubusercontent.com/32164310/150990186-2eda3382-2f41-46d6-a6cd-fcfc62dd2705.png)

The only way around this, without changing the umbracoSettings.config file is to add them to the project through the Cloud portal.

A potential workaround is to add a transform file for the umbracoSettings.config that would then apply the correct applicationUrl so the invites and pinging gets down correctly.

**Comment by Zero3** [comment]
I created a Heartcore project for testing last week, and I also just ran into this issue. So presumably it affects all (new?) Heartcore projects.

**Comment by Frost117** [comment]
Aye, though it is not an error imposed by the Heartcore package.

This issue was introduce with the mending of this:
https://umbraco.com/blog/security-advisory-january-20-2022-medium-severity-security-vulnerability-identified-in-umbraco-cms/ 

8.18 should address the issue for us though, once that is released 😄

**Comment by mikkelhm** [comment]
I'm closing this issue down.
We have 8.18 released on Umbraco Cloud - we are currently on 8.18.14 - and the Heartcore edition going through a major upgrade. This issue should be closed by now.
