### ISSUE TITLE
Umbraco Logs are not ordered correctly by date. 

### ISSUE THREAD

**Issue by readingdancer** [umbraco/Umbraco.Cloud.Issues#532]
### Issue description

When looking at any project within Umbraco.io, if you click to look at the logs you will first see a list of Umbraco Log files, these should be ordered by date with the most recent file at the top, however I think they are being ordered alphabetically and hence the date order is all muddled up.

See the attached screen shot, what you can't see is that all the 2022 dates are below the 2021 dates, as well as the wrong ordering you can see in this screenshot.

![Log ordering](https://user-images.githubusercontent.com/4398217/151820199-1df81bf7-7420-4549-b063-a66e76da1058.jpg)

I don't currently have any other types of logs showing, but I assume you probably need to do the same for the other three tabs.

**Comment by sajumb** [comment]
@readingdancer
Thanks. We should definitely fix this. I have added this task to our backlog and I expect that we include in one of the upcoming sprints.

**Comment by sajumb** [comment]
@readingdancer 
We are now ordering all log entries by date and not by string. Thanks for your reporting this.
