### ISSUE TITLE
media.umbraco.io/[projectname]/{hash}/file.ext?utm_source=test returns 400

### ISSUE THREAD

**Issue by PascalIcatt** [umbraco/Umbraco.Cloud.Issues#540]
### Issue description

The media endpoint is unable to process additional parameters.
There are 2 different scenario's:

1: images
- ~/picture.png?extraParam=test < 400 error
- ~/picture.png?width=100&extraParam=test < 200 OK

Workaround: Adding extra params only works when also using width or height params

2: files
- ~/file.pdf?extraParam=test < 400 error

Currently no workaround available to my knowledge.

Background information:
Many customers and marketing bureaus use newsletter generators and tools to send out emails.
In these newsletters extra parameters are added to provide some form of campaign tracking, like utm_source.

Impact: high
Severity: high

**Comment by sitereactor** [comment]
Thanks reporting this! We are including it as a bug fix for our upcoming sprint (Feb.28-Mar.4).
I will post back when a fix has been deployed.

**Comment by sitereactor** [comment]
The fix for this has been deployed, so you can now add "unknown" parameters without issues and we will no longer attempt to process files that are not images :)
