### ISSUE TITLE
Align the way we can add IP's between Connection details and public access

### ISSUE THREAD

**Issue by FransdeJong** [umbraco/Umbraco.Cloud.Issues#541]
### Issue description

I would like the way of adding IP's to be the same everywhere it is used in the portal (currently only public access and connection details I believe).
At the moment the one in connection details is the best one since it contains a name and a possibility to add an IP range.

A extra bonus would be to add a button "add my IP" to add my own IP without looking it up. This removes an extra step.

**Comment by sajumb** [comment]
Our great and dedicated frontend team are working on a new portal frontend using the Umbraco UI Library and web components.  The first pages to be migrated are the project subpages with _Connection details_ and _Usage_ being the first two pages to be published. Even though the migration of the pages primary will be a technical migration we will natural fix what is worth improving along the way. This is definitely one of these easy fixes. Thanks for the request!

**Comment by jesp209i** [comment]
Hi @FransdeJong 
Suddenly a lot of time went by, but luckily we have since updated the Cloud portal, and the two pages have been aligned as you requested. Even adding the "Add my Ip" to both functionalities 👍 

Thanks for the great feedback
