### ISSUE TITLE
Lock down changes that can cause sync issues and errors for Staging and Live

### ISSUE THREAD

**Issue by SimonAndrews** [umbraco/Umbraco.Cloud.Issues#55]
Hi,

Having recently started to use Umbraco Cloud I've come across the same problem a couple of times.

Basically while prototyping I kept changing Document Types / Templates within the staging environment which in turn causes issues with syncing the schema's and depending on how many changes made would make it complicated to resolve the issues.

So my suggestion is to lock down any changes that would cause sync errors on environments higher than Development behind some kind of admin option so if anyone does want to make these potentially breaking changes they would need to change the admin option or agree to some kind of popup stating that the changes have the potential to break the sync and deploy process.

**Comment by nul800sebastiaan** [comment]
Hi @SimonAndrews - this is a very broad request "any changes that would cause sync errors".

You should be able to get pretty far by giving people the correct permissions and following some kind of workflow with your team. You kind of have to look at it as if the Umbraco schema was a git repository where you'd make changes. You wouldn't put a feature request in for git saying "lock down all the clones of my repository while I make changes". 

So: 

1. We're happy to look at specific examples ("if I follow these steps I always get sync error x"), make sure to create separate issues so we can either explain or fix
2. Make sure to review who has permissions to do what and consider if they need those permissions
