### ISSUE TITLE
Not detecting LocalDB when only latest version (Sql Server 2019) is installed

### ISSUE THREAD

**Issue by soreng** [umbraco/Umbraco.Cloud.Issues#550]
### Issue description

Hi,

When running an umbraco cloud site locally, you can use LocalDB (https://our.umbraco.com/documentation/Umbraco-Cloud/Databases/Local-Database/) if a few prerequisites are fulfilled. The documenation however fails to mention what version of Sql Server is required. 

The check is made by looking for folders named "140", "130", "120" etc inside C:\Program Files\Microsoft SQL Server. The folder that contains the latest version is named "150". If you only have the latest version installed, the check for LocalDB will then fail.

We came across this when a couple of new hires, tried to work with an umbraco cloud project locally. Our workaround internally is to also install Sql Server 2017 on the dev machines.

Another, untested, workaround, it is described in https://github.com/umbraco/Umbraco.Cloud.Issues/issues/2 with information on how to force the usage of LocalDB.

**Comment by AndyButland** [comment]
Thanks - it looks like this needs a fix in CMS, so I've raised a PR for it that you can see linked above.

**Comment by sajumb** [comment]
As the fixes was merged in 8.18.1 we will be closing this issue.
Thanks again for reporting this,  @soreng .
