### ISSUE TITLE
Rewrites.xml file is not extracting in the wwwroot

### ISSUE THREAD

**Issue by sergiutesu** [umbraco/Umbraco.Cloud.Issues#558]
### Issue description

**Versions:** 
Umbraco 9.3.1
Forms 9.3.0
Deploy 9.3.0
Umbraco Id

**Issue:**
Following this documentation https://our.umbraco.com/documentation/Reference/routing/iisrewriterules/#example to add rewrites to our project, ends up in an issue on Cloud.

**Steps to reproduce:**
1. Create a new project on Cloud
2. Clone it down
3. Follow the documentation https://our.umbraco.com/documentation/Reference/routing/iisrewriterules/#example
Add the following to the startup.cs 

            using (StreamReader iisUrlRewriteStreamReader = File.OpenText("Umbraco/Rewrites.xml"))
            {
                var options = new RewriteOptions()
                    .AddIISUrlRewrite(iisUrlRewriteStreamReader);
                app.UseRewriter(options);
            }

_Remember to add the usings as well:_
_using System.IO;
using Microsoft.AspNetCore.Rewrite;_

4. Create a Rewrites.xml file under the umbraco folder.
And add a rewrite there.

```
<?xml version="1.0" encoding="utf-8" ?>
<rewrite>
	<rules>
		<rule name="Redirects umbraco.io to actual domain" stopProcessing="true">
			<match url=".*" />
			<conditions>
				<add input="{HTTP_HOST}" pattern="^(.*)?.euwest01.umbraco.io$" />
				<add input="{REQUEST_URI}" negate="true" pattern="^/umbraco" />
				<add input="{REQUEST_URI}" negate="true" pattern="^/DependencyHandler.axd" />
				<add input="{REQUEST_URI}" negate="true" pattern="^/App_Plugins" />
				<add input="{REQUEST_URI}" negate="true" pattern="localhost" />
			</conditions>
			<action type="Redirect" url="http://domain.domain.dk/{R:0}"
			  appendQueryString="true" redirectType="Permanent" />
		</rule>
	</rules>
</rewrite>
```

5. Push to Umbraco Cloud
6. Try to open the project after the deployment.
7. You'll get an error.
![image](https://user-images.githubusercontent.com/83580347/157236630-6f85f767-d25f-43bf-9e51-3c4a210033b3.png)

Checking the repository in Kudu the Rewrites.xml file is there.
![image](https://user-images.githubusercontent.com/83580347/157236758-ba49a137-d2ec-4d5a-b820-63bf987792fb.png)

Checking the wwwroot (site>wwwroot>umbraco) the Rewrites.xml file is not there.
![image](https://user-images.githubusercontent.com/83580347/157236866-fd68a62a-e28f-4213-bb2d-e69c206f5bff.png)

Temporary workaround: 
1. Go to Kudu site>wwwroot>umbraco 
2. Drag & drop the Rewrites.xml file you have locally
3. The rewrite should be working now

**Comment by sitereactor** [comment]
That's because it needs to be part of what is deployed to the wwwroot ad defined in the csproj file.

Umbraco 9 follows standard deployment practices, so just because the file is in the git repository doesn't mean it will be copied to the wwwroot. Check the configuration of the csproj file and verify that the file/extension/location is handled.
Locally you can do a dotnet publish to verify the output.

**Comment by sergiutesu** [comment]
Long story short.

/Umbraco is not the best place to have your Rewrites.xml file in.

Better to place it at the root of the project next to the appsettings.json
And make sure to specify the path to it in your .csproj

```
         <ItemGroup>
		<Content Include="Rewrites.xml">
			<CopyToPublishDirectory>Always</CopyToPublishDirectory>
		</Content>
	</ItemGroup>
```
