### ISSUE TITLE
Image CDN is broken, cropping / resizing urls not working

### ISSUE THREAD

**Issue by ICATT** [umbraco/Umbraco.Cloud.Issues#559]
### Issue description

Currently, images served from media.umbraco.io only work if you don't include cropping / resizing parameters in the url. Requests that do include these query parameters, take a very long time and eventually end in a 503 status code response.

This issue persists across all our Heartcore projects.
![image](https://user-images.githubusercontent.com/9265746/157425370-520ad84c-9868-4c87-8784-845941d1c313.png)

**Comment by RyuLindow** [comment]
Hey @ICATT 

We've resolved the issue. Sorry about the inconvenience.

**Comment by ICATT** [comment]
Thank you, I can confirm it works now.
