### ISSUE TITLE
add manage subscriptions in the profile on umbraco.io

### ISSUE THREAD

**Issue by dampee** [umbraco/Umbraco.Cloud.Issues#56]
A small feature request which would saved me 15 minutes and one support call.
 
Can you add “manage subscriptions” in the profile menu at the top.  That link can redirect to http://shop.umbraco.com.  Would have helped a lot as I did not understood where to update creditcard information when logged in on umbraco.io.

![afbeelding](https://user-images.githubusercontent.com/1857460/53019980-43c00400-3456-11e9-8466-de485eb165d8.png)

(as mentioned in zendesk ticket 41184)

**Comment by ksuvec** [comment]
@dampee 
THANK YOU for submitting this issue! It was just released today. Wish you a good weekend :)
