### ISSUE TITLE
Add a quick way to see create date of environments

### ISSUE THREAD

**Issue by FransdeJong** [umbraco/Umbraco.Cloud.Issues#563]
### Issue description

We've ran into a few occasions where we needed to know the date when a environment and the entire project was created.
Is it possible to add this information to one of the project screens?

**Comment by sajumb** [comment]
The creation date for the project should be displayed on the projects information page at https://www.s1.umbraco.io/project/{project-alias}/overview
![image](https://user-images.githubusercontent.com/93588665/158121176-d40d0c4f-0a25-4db0-870f-cb8e54e53029.png)

We could definitely add the creation day for the environments on the environment history page https://www.s1.umbraco.io/project/{project-alias}s/development/history

This has been added to the product backlog!

**Comment by FransdeJong** [comment]
Ok, I didn't know the creation date was there. Thanks for that info.

The environment history on the history page is a good idea.
The major drawback of this page is the load more button. It takes ages to scroll down to say a year ago.

It would be nice if we can add the create dates of the environments under creation date on the overview page?

**Comment by sajumb** [comment]
This feature request has been implemented and launched. Accordingly, we are closing this issue.
