### ISSUE TITLE
Invite to the backoffice are not sent.

### ISSUE THREAD

**Issue by Frost117** [umbraco/Umbraco.Cloud.Issues#564]
### Issue description

When inviting a user to the backoffice the email for the invitation are not being sent out to the user.

This can be reproduced on a new Uno starter and an existing Uno. If needed I can provide a project where the issue currently is.

In order to reproduce do the following steps:

1. Login into the backoffice on your uno site.
2. Navigate to user section
3. invite a new user
4. add in this email: mrcold@mailinator.com (or create your own test email with {string}@mailinator.com
5. visit this public email domain: https://www.mailinator.com/v4/public/inboxes.jsp?=mrcold // https://www.mailinator.com/v4/public/inboxes.jsp?={string}
6. verify that no invites have arrived.

I've checked the Umbraco Cloud Sendgrid activity feed and there is no registration of an email being sent out to my test user.

**Comment by sajumb** [comment]
As agreed with Frost117 we are closing this issue as we have a similar report in https://github.com/umbraco/Umbraco.Cloud.Issues/issues/547. We are considering this in the upcoming sprint and will have a fix out soon after.
