### ISSUE TITLE
Config transforms on v9

### ISSUE THREAD

**Issue by krebil** [umbraco/Umbraco.Cloud.Issues#568]
### Issue description

I recently posted this issue https://github.com/umbraco/Umbraco.Cloud.Issues/issues/560

I later found out, after a week or two of back and forth with the cloud support, that config transforms are not available for anything other than development, staging & live for v9. 

Not having child-project transforms limits the use-cases for baselines or at least add a lot of unnecessary complexity to baselines that simply want to swap out a setting or two.

Package transforms also do not work on v9.

Furthermore, the documentation does not reflect this unavailability, in fact, it's listed as a feature in several places in the docs including this page:
https://our.umbraco.com/documentation/umbraco-cloud/Set-up/Config-Transforms/#including-transforms-in-umbraco-packages
![image](https://user-images.githubusercontent.com/1363512/160994570-776e6b35-f528-4728-91e9-7b0bd81c5674.png)

This page has not been updated to reflect that this is not available on v9:
https://our.umbraco.com/documentation/Umbraco-Cloud/Getting-Started/Baselines/Configuration-files/

**Comment by sajumb** [comment]
Thanks for highlighting this. We are sorry that our documentation is not updated the lack of support for child-project and package transforms for CMS9 projects. And also that the transform options currently is not supported for v9 projects. We have added this to the backlog and will hopefully be able to consider soon.

**Comment by sajumb** [comment]
Thanks for highlighting this. We are sorry that our documentation is not updated correctly and doesn't mention the lack of support for child-project and package transforms for CMS9 projects.

And also that the transform options currently is not supported for v9 projects. We have added this to the backlog. We want to consider this really soon in order to offer this feature for v9 projects as well.

**Comment by krebil** [comment]
For anyone that needs a temporary solution that hopefully work when a appsettings config transform is implemented.

In the program.cs file, check if there is a file following the naming convention for the current project and "workspace"
```
public static IHostBuilder CreateHostBuilder(string[] args) =>
            Host.CreateDefaultBuilder(args)
                .ConfigureLogging(x => x.ClearProviders())
                .ConfigureWebHostDefaults(webBuilder => webBuilder.UseStartup<Startup>()).ConfigureAppConfiguration(
                    (hostingContext, config) =>
                    {
                        //config.AddJsonFile("appsettings.Kommunikationsplatform.Local.json", optional: true, reloadOnChange: true);
      
                        var projectAlias = EnvironmentHelper.GetProjectAlias();

                        if (!string.IsNullOrWhiteSpace(projectAlias))
                        {
                            var currentEnvironment = hostingContext.HostingEnvironment.GetCurrentEnvironment();
                            var fileName = $"appsettings.{projectAlias}.{currentEnvironment}.json";
                            if (File.Exists(fileName))
                            {
                                config.AddJsonFile(fileName);
                            }
                        }
                    });
    }
```

A helper class that extracts project information from a umbraco-cloud file. 
```
public static class EnvironmentHelper
{
    public static string GetProjectAlias()
    {
        if (!File.Exists("umbraco-cloud.json")) return null;
        
        var config = (Dictionary<string, object>) JSON.Parse(File.ReadAllText("umbraco-cloud.json"));
        var deployConfig = (Dictionary<string, object>) config["Deploy"];
        var projectConfig = (Dictionary<string, object>) deployConfig["Project"];

        return projectConfig["Alias"].ToString();
    }
}
```

**Comment by sajumb** [comment]
We are closing this issue as this now seems outdated. It won't have an impact on the latest four major versions.
