### ISSUE TITLE
On Cloud in /connection-details in Safari the delete firewall button isn't there

### ISSUE THREAD

**Issue by jacklawry** [umbraco/Umbraco.Cloud.Issues#569]
### Issue description

On Cloud in /connection-details in Safari the delete firewall button isn't there...

Please see attached in Safari:
![Safari](https://user-images.githubusercontent.com/3786136/161244359-c5957f72-9647-408a-a5f6-0270053774eb.png)

Vs Chrome:
![Chrome](https://user-images.githubusercontent.com/3786136/161243976-cb356169-6f83-4b90-be37-436611163c9c.png)

Note: The button is there in the code and does work if you apply some css to it to make it clickable.

**Comment by sajumb** [comment]
The _Connection Details_ is one of the first pages to be migrated to using the Umbraco UI Library and web components. It seems like we have missed this in our test with the Safari browser. We will fix it as soon as possible.

**Comment by sajumb** [comment]
The reported issue in S1 has been fixed
