### ISSUE TITLE
Select root node to restore from

### ISSUE THREAD

**Issue by bjarnef** [umbraco/Umbraco.Cloud.Issues#57]
When having multiple root nodes, e.g. in a baseline project with several child projects, and you want to work on one of these sites, but haven't the specific root node you can't you restore this project from root node, but have to restore entire content tree from root.

E.g. in a multisite solution as a baseline project when adding a new child project and copying one of the other projects, where this project will be the new site (child project). But this site you might adjust the overall theme as logo, colors, fonts etc. while the base functionality is more or less the same.

If your colleagues later need to work on this project, they have to restore the entire content tree since they haven't the root node on local to restore from.

When restoring from root, it would be great to select the root nodes to restore content from.
Sometimes on baseline projects when restoring all content from root (even with LocalDB) we have had timeout issues after running restore for an hour or so. Maybe also with a single site with lots of nodes, so it should probably restore in batches or similar.

Furthermore it seems to restore all or nothing.. it is a bit annoying when e.g. a single node has issues. It would be great it then successfully restored the other nodes, e.g. starting with root node, then try children, etc.

Often it is okay with us a image, link, etc. is broken because the dependency failed for some reason. Maybe is should just restore what is can and return some kind of report in case part of the content failed to restore.

**Comment by jmayntzhusen** [comment]
Partial restores are available from Deploy 3.3.0 🙂
