### ISSUE TITLE
Bug when transferingg empty Tag field

### ISSUE THREAD

**Issue by jpkeisala** [umbraco/Umbraco.Cloud.Issues#571]
### Issue description

I have reported issue in [Umbraco CMS](https://github.com/umbraco/Umbraco-CMS/issues/12204) Issues but since this issue boils down to Umbraco Deploy, I report details how the bug affects to Umbraco Deploy.
André from Umbraco HQ was able to reproduce the bug as following:

﻿I can reproduce this on a fresh v8.18 project:

- Created Document Type with a tag field + 2 other properties on Dev
- Added where it should render in the Template also
- Created a Content Node base on this document type.
- Filled out the 2 other properties, but not the Tag field
- Transfered the page to Live
- Accessed it on Live and I get a runtime error (like him)
- Enabling debug mode shows:
![runttime error](https://user-images.githubusercontent.com/229413/161752528-ce79c486-c189-48fd-b2aa-c01b42dc37d7.png)

The issue is also within the CMS, but it boils down to the way Deploy engine handles pushing changes between environments.

**Comment by AndyButland** [comment]
Thanks for reporting.  I think this duplicates [this issue](https://github.com/umbraco/Umbraco.Deploy.Issues/issues/104) where someone else found the same thing.  There's a workaround listed there where you can use `HasValue` and we'll fix the underlying issue with the Deploy transfer of this tags data in the next release.

**Comment by HamDerAndrew** [comment]
Thanks for adding this @jpkeisala 💪

Let me just add that the Deploy version used here is 4.5.0.0

As to the theory on the issue coming from the way Deploy handles deploying changes from one environment to another, this is mostly my personal speculation 😀
Thanks again for bringing it to our attention!

**Comment by jpkeisala** [comment]
> think this duplicates [this issue](https://github.com/umbraco/Umbraco.Deploy.Issues/issues/104) where someone else found the same thing.

Yes, the same issue.
