### ISSUE TITLE
Getting locked out when trying to access a new environments too soon after creation

### ISSUE THREAD

**Issue by sofietoft** [umbraco/Umbraco.Cloud.Issues#572]
### Issue description

After creating a new environment on a Umbraco Cloud project, the environment needs some time to be properly created and set up.

However, this is not clear from the Portal overview, and the buttons to access it are available right after creation.
If you try to access the environment before it's done initializing, your user will be locked out and will continue to be locked out.
The only way to resolve this is to **restart the environment**.

Would it make sense to somehow disable the options to access the environment before it's done being set up?

**Comment by sajumb** [comment]
Thanks for the report.
We will look into this today.

**Comment by sajumb** [comment]
This issue is now fixed and pushed to production. Accordingly, we are closing this ticket.
