### ISSUE TITLE
Umbraco Cloud ID login fails when adding web.config with appsettings in Umbraco folder

### ISSUE THREAD

**Issue by PGGMTeam5** [umbraco/Umbraco.Cloud.Issues#573]
### Issue description

Using Umbraco Cloud project v8.18.3

We have the need to add some specific appsettings for the Umbraco backoffice (related to CSP headers).
One way of doing this, is to add a web.config file to the "\umbraco" folder in the web site.

However, even just adding a test setting like this:
```
<configuration>
 <appSettings>
     <add key="foo" value="bar" />
</appSettings>
</configuration>

```
will then break the Umbraco Cloud login.

Using the link "Go to backoffice" in an incognito window will give the Umbraco Cloud ID login view.
After entering the correct login credentials, the following error is displayed:
```
Login failed
AADB2C90088: The provided grant has not been issued for this endpoint. Actual Value : B2C_1A_SignInLocal and Expected Value : B2C_1A_SignInBackOffice

```

**Comment by sajumb** [comment]
Thanks for reaching out. I have brought your question to the attention of our cloud team. I will post the answer here.

**Comment by sajumb** [comment]
I have talked to our 2nd level support who referenced the support ticket that led to this feature request. I have created a ticket in our backlog for this request.

**Comment by sajumb** [comment]
I will be closing this ticket as our backlog item both contain this and https://github.com/umbraco/Umbraco.Cloud.Issues/issues/574.

**Comment by PGGMTeam5** [comment]
> I will be closing this ticket as our backlog item both contain this and #574.

OK.
I had created two seperate issues, because the cause of and/or the solution to this error could be different.
But it is great if you fix both issues at once :-)
