### ISSUE TITLE
Umbraco Cloud: Usage. Issue with custom domains calculation/displaying

### ISSUE THREAD

**Issue by AndreyKarandashovUKAD** [umbraco/Umbraco.Cloud.Issues#576]
### Issue description

It seems that custom domains calculation doesn't work properly.

Usage page: 
![image](https://user-images.githubusercontent.com/51944778/162947203-d488d076-07b3-44d6-84a0-a48887fff58b.png)
Hostnames for LIVE:
![image](https://user-images.githubusercontent.com/51944778/162947268-dcf4c676-9172-41d9-b197-f485d88c9b1a.png)

**Comment by AndreyKarandashovUKAD** [comment]
@RyuLindow Ah, I see. Now it's clear for me :)
Is usage related to the "LIVE" environment only? :)

**Comment by sajumb** [comment]
Yes, only live environment counts towards to the total for usage.
A bit more info regarding the usage limits: https://our.umbraco.com/documentation/Umbraco-Cloud/Set-Up/Usage/

**Comment by RyuLindow** [comment]
I was in the middle of typing my answer but @sajumb was faster than me this time :)

Feel free to close this issue if you don't have any further questions about the usage page.
