### ISSUE TITLE
Allow to change project color

### ISSUE THREAD

**Issue by bjarnef** [umbraco/Umbraco.Cloud.Issues#579]
### Issue description

By default a project in Umbraco Cloud portal gets a random color, but previously this could be changed via UmbracoDeploy.config
This seems no longer to be possible on V9 projects.
https://our.umbraco.com/forum/using-umbraco-and-getting-started/108750-color-tag-in-umbracodeployconfig

I think this was useful the change the color to fit the branding identify color of the specific project. Furthermore maybe an avatar/logo could be useful as the number of Umbraco Cloud projects in the organization grows.

**Comment by c9mbundy** [comment]
I seem to recall - way-back mode - that it was actually possible to select a colour from a limited palette when spinning up a site on Cloud, but that option seemed to disappear. I agree that setting the colour and/or avatar-logo-svg would be useful, as the MS-Office style of contact avatar is not something that adds much value as it is.

**Comment by sajumb** [comment]
Yes, in the past it has been possible to set the color of the project using the config file, but it is no longer supported by the portal. The reports I get is that no one was actually using this, so the feature has been neglected. The feature will not return in its current form.

However, we will soon start the implementation of a new projects dashboard that will replace (or at least be an alternative to) the current grid view version with a list view with a lot more relevant info for each cloud project . When this first version has been launched we are likely to make it possible to add either a color and/or an icon to project groups and/or projects.

So... it might return in one way of another. But more importantly, we will in Q3 launch a new projects overview that we consider a huge upgrade to the current quite limited overview of cloud projects.

**Comment by bjarnef** [comment]
@sajumb thanks for the elaboration.
I think the reason many didn't use this feature, may be because they wasn't aware of it existed. Not sure if this was documented on https://our.umbraco.com
Anyway if would probably be easier to discover from the portal via some advanced settings or similar.

**Comment by sajumb** [comment]
Thanks for the input here. We will take this into account while creating the new projects dashboard. In our implementation, we want to invite users to try it out and report feature requests as we progressive. Here I will be sure to invite you, @bjarnef. If you in this testing of the new projects dashboard find it beneficial to add a support for project colors, we will consider it then.
