### ISSUE TITLE
Missing Upgrade Available Notification Bar

### ISSUE THREAD

**Issue by MichaelNielsenDK** [umbraco/Umbraco.Cloud.Issues#586]
### Issue description

The blue notification bar that shows when an upgrade is available for a project, is currently not showing on any projects which have possible upgrades.

There is an error in the console calling this api
https://www.s1.umbraco.io/api/upgrade/GetUpgradeStatus?id={projectGuid}
which I assume is related to the issue

**Comment by sajumb** [comment]
Hi @MichaelNielsenDK
Thanks for your report. We are currently investigating and looking into the issue and we will provide a solution as soon as possible.

**Comment by sajumb** [comment]
Hi @MichaelNielsenDK,
This issue has been resolved a couple of weeks ago. The blue notification bar is now shown as intended along with the "Upgrade available" tag next to the "Development" environment.
