### ISSUE TITLE
Missing translation for external login providers buttons

### ISSUE THREAD

**Issue by bjarnef** [umbraco/Umbraco.Cloud.Issues#587]
### Issue description

On a new Umbraco Cloud project based on Umbraco v10.0.1 I noticed the translations are missing for these buttons under **External Login Providers**

![image](https://user-images.githubusercontent.com/2919859/178267362-6a69676e-aa4f-4176-9149-062e2d4b6287.png)

**Comment by sajumb** [comment]
Hi @bjarnef ,
Thanks for the report. The proper set of translations for the _External login providers_ sections have been added.
