### ISSUE TITLE
Bad color choice on project renaming confirmation notification

### ISSUE THREAD

**Issue by aguyfromdenmark** [umbraco/Umbraco.Cloud.Issues#592]
### Issue description

When you rename a project, the background of the confirmation is colored red. It all screams error, but the actual message begs to differ. The color of the notification should be green, or another positive color indicating success. 
![image](https://user-images.githubusercontent.com/6904597/183894052-5d472cc9-a6dd-464e-853a-8bb1d9060dcf.png)

**Comment by sajumb** [comment]
Yes, you are completely right. This is definitely not the right color to use in this context. We will change that as soon as possible. Thanks for reporting this.

**Comment by sajumb** [comment]
The rename notification now has a green instead of red color. 
![ProjectRenamedGreen](https://user-images.githubusercontent.com/93588665/185572564-3e08e17a-e027-4a53-aaeb-60552157cc2c.gif)
