### ISSUE TITLE
Project/environment creation fails when the code from the repository is unable to boot 

### ISSUE THREAD

**Issue by RyuLindow** [umbraco/Umbraco.Cloud.Issues#593]
### Issue description

If the project can't boot then you won't be able to create a working child project or an environment since it copies the code over to it.
If the env/child site returns e.g. 50x errors during creation then it'll be marked as a failed creation and deleted.

Example:
- The cloud project works fine.
- you push code from local to cloud that prevents the project from booting
- repo->wwwroot deployment fails
- this results in a working wwwroot and a broken repository
- creating a project or an env based on that repo would fail

There's a pop up message that tells you that the creation failed but it doesn't tell you why.

It would be great for it to mention that the project failed due to e.g. returning a 50x error.

**Comment by sajumb** [comment]
Hi @RyuLindow ,
Thanks for reporting this. We should definitely do something about this. We have created a product backlog item and will handle it in one of the upcoming sprints.

**Comment by meyntony** [comment]
We could have a git tag on the latest successful build from cloud, and when baselines are created, they are made from the latest tag, instead of master?

**Comment by sajumb** [comment]
@RyuLindow @meyntony 
We have ensured that all potential baselines are checked and evaluated while being exposed in the drop-down box.
If the baseline project had a last failed build, the baseline is shown with a red error message and cannot be selected.
If the baseline project fails to load, the baseline is shown with a golden warning message but can be selected.

![image](https://user-images.githubusercontent.com/93588665/193811047-cec9954e-1bab-423d-bb8e-a0d4d4021cdc.png)

Please let me know your thoughts about this and close the ticket if accepted.

**Comment by RyuLindow** [comment]
That looks great, @sajumb 

Now, that we have this functionality could we also add it to env creation as well?

**Comment by MikkelBangAtUmbraco** [comment]
Ran into this issue on this project.
https://www.s1.umbraco.io/project/lab-of-misfits-site

Umbraco 8.14.4
Forms 8.7.6
Deploy 4.1.4

The Umbraco version was set as 8.14.1 and changing it to 8.14.4. fixed the issue and the dev environment could be created.
