### ISSUE TITLE
Special characters in image filesnames returns 404

### ISSUE THREAD

**Issue by albintoxic** [umbraco/Umbraco.Cloud.Issues#594]
### Which exact Umbraco version are you using?
10.1.0 - Umbraco Cloud

### Bug summary
If I upload an image that has an å, ä or ö in the filename to the media section of the backoffice, the URL decoding seems to fail. The image is uploaded to the media section without any error messages but its URL still contains the special character and returns a 404 error. 

### Specifics
It works locally but not in the cloud environment. Regarding operating systems, the issue is only present on Windows. When trying to reproduce the issue on MacOS it works as expected, for example **unsplåsh.jpg** translates to **unspla-sh.jpg** in the URL.

Uploading a image to the media section in the backoffice, Windows, Umbraco Cloud environment:
![image](https://user-images.githubusercontent.com/97619940/186700141-fa55a85b-cc88-4b35-97ba-06daf97a0dcb.png)

Uploading a image to the media section in the backoffice, MacOS, Umbraco Cloud environment:
![image](https://user-images.githubusercontent.com/97619940/186700530-d726ecca-42e5-4215-934b-d63830895c3f.png)

### Steps to reproduce
Using a Umbraco Cloud environment, upload an image with å, ä and/or ö in the filename using Windows and try to access its URL.

### Expected result / actual result
**Desired result:**
Uploaded images to the cloud environment with a filename containing å, ä and/or ö should be decoded like intended. 

**Actual result:**
Images that are uploaded to the cloud environment keeps the special characters (å, ä and/or ö) in the URL and returns 404.

**Comment by sajumb** [comment]
Hi @albintoxic 
Thanks for the report! We have added this issue to the product backlog and will have it as a candidate for the next sprint.
We have already noted the same issue with special chars containing such as ´ and ^ for V9 projects (https://github.com/umbraco/Umbraco.Cloud.Issues/issues/517). We will consider both cases in our future fix.
