### ISSUE TITLE
Invalid ApplicationUrl and failing KeepAlive issues

### ISSUE THREAD

**Issue by c9mb** [umbraco/Umbraco.Cloud.Issues#597]
### Issue description

Cloud-Support recommended I log this issue here.

I have a long-standing issue where an invalid ApplicationUrl is auto-created by a request using a .: (dot-colon) delimiter for the port reference instead of a : (colon). 

This request is coming from an unknown source, but occurs at random on multiple sites.

This was never an issue prior to all sites being migrated to the current Umbraco-Cloud platform, and it's focus on CloudFlare as the request-handling front-end.

With my many v7 sites running on Umbraco-Cloud, this causes the default empty "auto" setting of UmbracoApplicationUrl to be updated to an invalid URL, and that cascades into a repeating failure of the Keep-alive, as it's hard-coded in v7 to use UmbracoApplicationUrl

I believe that this is an Umbraco-Cloud issue, rather than an Umbraco-v7 issue, but it causes a problem for v7 because of the way it defaults UmbracoApplicationUrl to the last request.

I can work-around the failing Keep-Alive issue by configuring UmbracoApplicationUrl in UmbracoSettings to a known valid URL.

I currently have it set to use the native project domain - e.g. https://myproject.euwest01.umbraco.io/umbraco

However, I don't know if hard-setting it in v7 is a good or bad idea for as a "fix" to the issue, and what (if any) ramifications it might have for other services/functions.

I also recall there being a security issue centred around UmbracoApplicationUrl and I can not find a clear guidance as to what would be a "correct" setting - i.e. should I do it, and what should it be.

I'd appreciate any feedback on this - why it might be happening, and whether or not this is a valid workaround to the problem.

**Comment by sajumb** [comment]
Hi @c9mb,
Sorry about the late reply. We will get our 2nd level support to look into this and get back with more when we have found a possible solution for this issue for V7 projects.

**Comment by HalldorLyngmo** [comment]
Hello @c9mb 

I was looking into your issue and I can confirm that it's a valid workaround to use the native project domain for the `umbracoApplicationUrl`. 
Using a [child config transform](https://our.umbraco.com/documentation/Umbraco-Cloud/Getting-Started/Baselines/Configuration-files/) would be my recommendation for your baseline setup. Which, I can see you already did so well done👍

Regarding the security issue, I believe you referencing this [one](https://umbraco.com/blog/security-advisory-january-20-2022-medium-severity-security-vulnerability-identified-in-umbraco-cms/). 

>Umbraco Cloud, Heartcore and Uno projects are not affected. This also goes for sites hosted on Azure Web App Service.

You can see from that post that Umbraco Cloud sites are not in danger here. But for sites hosted elsewhere, the fix would be to specifically set the `UmbracoApplicationUrl` within the Umbraco Configuration. 

As for why the `umbracoApplicationUrl` is sometimes a localhost or broken URL with extra symbols I, unfortunately, don't have the answer for that.

**Comment by c9mb** [comment]
Thanks for that feedback - I'll use that approach as my workaround to the issue.
