### ISSUE TITLE
Feature request: Extending Public access features (the IP whitelisting)

### ISSUE THREAD

**Issue by swedeofenbound** [umbraco/Umbraco.Cloud.Issues#598]
### Issue description

Backstory:
Today at umbraco.io/project/NAME/publicaccess where you whitelist IPs per environment you can "only" add the IP itself or a range. However when you have multiple projects and starting to add IPs back and forth and possibly on a time schedule ahead, administrating them can be a pickle.

Therefor, kindly asking to extend the Public access feature with:
1.1) An optional text field for describing the IP (or range) you are currently adding to the list.
1.2) With editing support of this note.
2.1) Date ranges, from and to, for when the IP rule is active.
2.2) option for indefinite time (disregarding date range, i.e. always ON).
2.3) should also be possible to edit this.

🙏

**Comment by sajumb** [comment]
Thanks for the feature request. You will soon be able to add a text when adding a new IP address (1.1) on the public access page. Just as you are able when adding an IP on the "Connection details" page. We have added the remaining suggestions to our product backlog.
