### ISSUE TITLE
Enforce 2FA under organization

### ISSUE THREAD

**Issue by bjarnef** [umbraco/Umbraco.Cloud.Issues#599]
### Issue description

We noticed the option to configure 2FA on Umbraco Cloud documented here: https://our.umbraco.com/documentation/Umbraco-Cloud/Set-Up/2-factor-authentication-on-cloud/

However we couldn't find an option to enforce this for the organization, which would be useful to ensure all users in an organization have 2FA configured. Currently it's up to each individual user to configure 2FA.

**Comment by sitereactor** [comment]
I have mentioned this internally, and for now the prioritization lies with our Feature team. Tagging @sajumb - I mentioned it to KEC not too long ago. But not sure if its made it to the backlog yet.

**Comment by sajumb** [comment]
Thanks for highlighting this. We will start the planning of the feature and include it in the product backlog. I will post an update here when we start implementing it.

**Comment by sajumb** [comment]
This feature request has been delivered. We are closing this thread.
