### ISSUE TITLE
Partial restore on Fresh clone

### ISSUE THREAD

**Issue by Frost117** [umbraco/Umbraco.Cloud.Issues#60]
A brief description of your feature request goes here.

Imagine a site on cloud with that has around 250 articles with images on each of them.
These article lives under a repository node, and for this purpose it is named blog.

Separate to the Blog content node is the Home node, where the users are placed upon visting the site for the first time. See screenshot for clarification.
![image](https://user-images.githubusercontent.com/32164310/54187263-6bcae200-44ad-11e9-9c34-ea74d5a83314.png)

A developer spots a problem, or the content editor notices a big red error on the home node.

The developer then proceeds to reproduce the issue on his local environment. He gets a fresh clone going and is about to restore the content. 

Here is where the FR comes in. Because the error has only been spotted on the home node, then it would be in the developers best interest, in saving time, that he is giving an option to either perform a Full restore or perform a partial restore.

This can also help avoid the timeout that deploy has as standard setting, since restoring 250 article will exceed the 10 minutes that Deploy comes with.

**Comment by skttl** [comment]
Also, if you could pick which node on the other environment you want to restore, and then get that, and its dependencies.

Say you have a structure like this

- Site
 - Frontpage
 - NewsArchive
  - NewsItem
  - NewsItem2
 - About us
  - Contact page

And you select to restore the contact page, you will get the following pages
- Site
 - About us
  - Contact page

**Comment by tormnator** [comment]
Another much missed feature  is to restore a page, but not its descendants. For instance you may want to restore the "NewsArchive" page, but not each and every "NewsItem..." child node.

**Comment by jmayntzhusen** [comment]
Partial restores are available from Deploy 3.3.0 🙂

**Comment by skttl** [comment]
Is this going the be available for Umbraco 7 solutions too?
