### ISSUE TITLE
Feature Request: Add project to Groups when creating new project

### ISSUE THREAD

**Issue by jonat123** [umbraco/Umbraco.Cloud.Issues#602]
### Issue description

With the introduction of the new project Dashboard, you can sort projects into groups.

A nice addition to the feature would be to be able to add projects to a group in the project creation flow.

An example of how it could be:

- I have a group called "Heartcore" where I place all my Heartcore projects in it.
- I need to create a new project.
- I create the project where I can choose the group (Hearcore) in a drop-down on the project creation page.

Once the project has been created it is then added to the chosen group (Heartcore).

The users then don't need to go in and added it manually once it has been created.

**Comment by sajumb** [comment]
We have decided not to do this. So we will be closing this issue.
