### ISSUE TITLE
Deleted language "English (United States)" is added again when cloning the environment

### ISSUE THREAD

**Issue by HamDerAndrew** [umbraco/Umbraco.Cloud.Issues#605]
### Issue description

By default Umbraco uses `English (United States)` for its _default language_.
On Cloud, if you have selected a new _default language_ and removed the `English (United States)`, then the `English (United States)` is added again when you clone the environment to local.

I have tested this on v9 and v10. It happens on both.

### Steps to reproduce
1. Add a new default language on a Cloud project
2. Remove the default `English (United States)`.
3. Clone down the environment
4. Check the "languages" section under "Settings". `English (United States)` has been added.

#### My v10 Live env on Cloud:
![Screenshot 2022-10-20 at 11 02 30](https://user-images.githubusercontent.com/2794633/196905481-405982f2-7af5-4c0d-9d54-91271bfcaa84.png)

#### My v10 Live env on local:
![Screenshot 2022-10-20 at 11 04 29](https://user-images.githubusercontent.com/2794633/196905930-ee86335d-e56b-4652-90a8-f5eec31ca191.png)

**Comment by AndyButland** [comment]
We've added some CMS configuration to handle this type of situation, which is documented [here](https://our.umbraco.com/documentation/Reference/Configuration/InstallDefaultDataSettings/).  So if you configure your project with the settings to not install the `en-US` language on start up, you should find a new clone won't add it, and will get your configured default language from the serialized `.uda`. files.

**Comment by meyntony** [comment]
```
"InstallDefaultData": {
  "Languages": {
	  "InstallData": "Values",
	  "Values": [  "en"  ]
  }
}
```

I tried the above configuration on a project that has only en (English) and da (Danish)
But got an error after trying a fresh clone on Startup.

> "There is no default language. Fix this anomaly by editing the language table in database and setting one language as the default language."

```
"System.NullReferenceException: Object reference not set to an instance of an object.
\r\n   at Umbraco.Cms.Infrastructure.Persistence.Repositories.Implement.LanguageRepository.GetDefaultIsoCode()
\r\n   at Umbraco.Cms.Core.Services.LocalizationService.GetDefaultLanguageIsoCode()
\r\n   at Umbraco.Cms.Core.PublishedCache.DefaultCultureAccessor.get_DefaultCulture()
\r\n   at Umbraco.Cms.Web.Common.Middleware.UmbracoRequestMiddleware.InvokeAsync(HttpContext context, RequestDelegate next)
\r\n   at Microsoft.AspNetCore.Builder.UseMiddlewareExtensions.<>c__DisplayClass6_1.<<UseMiddlewareInterface>b__1>d.MoveNext()
\r\n--- End of stack trace from previous location ---
\r\n   at Umbraco.Cms.Web.Common.Middleware.PreviewAuthenticationMiddleware.InvokeAsync(HttpContext context, RequestDelegate next)
\r\n   at Microsoft.AspNetCore.Builder.UseMiddlewareExtensions.<>c__DisplayClass6_1.<<UseMiddlewareInterface>b__1>d.MoveNext()
\r\n--- End of stack trace from previous location ---
\r\n   at Umbraco.Cms.Web.Common.Middleware.UmbracoRequestLoggingMiddleware.InvokeAsync(HttpContext context, RequestDelegate next)
\r\n   at Microsoft.AspNetCore.Builder.UseMiddlewareExtensions.<>c__DisplayClass6_1.<<UseMiddlewareInterface>b__1>d.MoveNext()
\r\n--- End of stack trace from previous location ---
\r\n   at Umbraco.Forms.Web.HttpModules.ProtectFormUploadRequestsMiddleware.InvokeAsync(HttpContext context, RequestDelegate next)
\r\n   at Microsoft.AspNetCore.Builder.UseMiddlewareExtensions.<>c__DisplayClass6_1.<<UseMiddlewareInterface>b__1>d.MoveNext()
\r\n--- End of stack trace from previous location ---
\r\n   at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
\r\n   at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
\r\n   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)
```

This does not happen if the default language is en-US in the appsettings.json ,but that defeats the purpose of making the default en instead of en-US

**Comment by AndyButland** [comment]
Yes, it looks like we've not accounted for this properly.  My thinking is we need to support a config like this:

```
"InstallDefaultData": {
  "Languages": {
	  "InstallData": "Values",
	  "Values": [  "en"  ],
          "DefaultLanguage: "en"
  }
}
```

So then the install data script could use that to know that when it's creating the `en` language, it should make it the default.  I'll have a look at implementing this in the upcoming sprint.

**Comment by ronaldbarendse** [comment]
I've seen the same issue when using `Umbraco:CMS:InstallDefaultData:Languages:InstallData = None` to prevent creating the default `en-US` language and using package migrations to add the languages instead. This is because the `package.xml` format doesn't include which language should be set as default:

```xml
<?xml version="1.0" encoding="utf-8"?>
<umbPackage>
  <Languages>
    <Language Id="1" CultureAlias="nl" FriendlyName="Dutch" />
    <Language Id="2" CultureAlias="en" FriendlyName="English" />
  </Languages>
</umbPackage>
```

Although Deploy _does_ correctly set the default language, the deployment is only run after Umbraco has started, which is too late, as the `UmbracoRequestMiddleware` is already invoked for the first request (before the deployment has completed)... This also requires you to have the deploy trigger file already present, which won't be the case for clean installs either.

**Comment by Zeegaan** [comment]
Fixed in https://github.com/umbraco/Umbraco-CMS/pull/13290
