### ISSUE TITLE
Add a simple way to clear yellow "Last deploy didn't go as planned." errors from Portal

### ISSUE THREAD

**Issue by hfloyd** [umbraco/Umbraco.Cloud.Issues#607]
### Issue description

Sometimes a deploy error occurs, where the schema doesn't update as expected on a deployment triggered via the Portal. Showing the yellow error message there is lovely and helpful:

![image](https://user-images.githubusercontent.com/1252593/197045788-72821924-010a-45a2-98ba-f74c82bedc1f.png)

Except... savvy Cloud devs know how to re-trigger the schema update (via Kudu or the back-office Deploy dashboard). Generally, that resolves the issue and the schema is all sync'd up. BUT the yellow message - and the RED dot are still shown on the Portal. 

The message, and info I have gotten from support, says to "make a little change and re-deploy to clear up the message.", which works, I suppose, but it takes time, and clutters up the repo with unnecessary commits. 

Where is this message coming FROM? I know that build/upgrade messages are shown based on stuff in the "site/locks/" folder, and if you navigate there via Kudu and delete the flag files, those yellow message go away. But this isn't a possibility for the Deployment messages. It seems to be that these messages should be generated based on the flag files inside the "deploy" folder, but that seems not to be the case.

**Comment by hfloyd** [comment]
Somewhat related to: https://github.com/umbraco/Umbraco.Cloud.Issues/issues/553

**Comment by mclausen** [comment]
Hi @sajumb and @hfloyd!

I might be able to add a bit more context to this. Whenever a deployment fails we leave a deploy-failed marker file in the wwwroot+deploy folder. Whenever we load the ProjectOverview we check for that marker file, and if it's present we show that yellow line. If you remove the deploy-failed marker file, the yellow line should also disappear 🤞

We have no way of proving info for the failed deployment, except in the console that pops up during the deployment, or that yellow line.

**Comment by hfloyd** [comment]
Hi @mclausen Thanks for jumping in. So, I took at look for one of my projects which is showing the red dot on the environment (Umbraco 9.5.4) ... 
![image](https://user-images.githubusercontent.com/1252593/199769753-78fc4a6e-34d8-4b55-92cb-1b07f740ceea.png)

Using Kudu, I navigate to "C:\home\site\wwwroot>" there is no "deploy" folder there... there is a "data" folder, but that only contains a "backoffice" folder. I can find a "Deploy" folder here: "C:\home\site\wwwroot\umbraco\Deploy>" and this is what I see there:
![image](https://user-images.githubusercontent.com/1252593/199769515-836d446a-a406-43f0-9f17-83e7c476ee09.png)
No failure flag.

**Comment by queenie-wong** [comment]
Hi there, I got the same issue with my project.
![image](https://user-images.githubusercontent.com/117815354/200789991-da11b30d-20d5-4ff3-a938-0544e93f72e9.png)
![image](https://user-images.githubusercontent.com/117815354/200790016-83ae7d64-8bdd-4d9f-85ab-2e45e65a1dbb.png)


I followed above instruction and could not find a "Deploy" folder.

I also reached Umbraco support for further investigation.
Support team asked me to follow this guide to resolve the issue. But I could not the "upgrading" file under site > locks for all environments too.
https://our.umbraco.com/Documentation/Umbraco-Cloud/Troubleshooting/Deployments/Deployment-Failed/#fixing

![image](https://user-images.githubusercontent.com/117815354/200790902-a4e2b569-b604-42e9-b39a-7c12e045ea7d.png)

**Comment by sinanaltaii** [comment]
> Hi there, I got the same issue with my project. ![image](https://user-images.githubusercontent.com/117815354/200789991-da11b30d-20d5-4ff3-a938-0544e93f72e9.png) ![image](https://user-images.githubusercontent.com/117815354/200790016-83ae7d64-8bdd-4d9f-85ab-2e45e65a1dbb.png)
> 
> I followed above instruction and could not find a "Deploy" folder.
> 
> I also reached Umbraco support for further investigation. Support team asked me to follow this guide to resolve the issue. But I could not the "upgrading" file under site > locks for all environments too. https://our.umbraco.com/Documentation/Umbraco-Cloud/Troubleshooting/Deployments/Deployment-Failed/#fixing
> 
> ![image](https://user-images.githubusercontent.com/117815354/200790902-a4e2b569-b604-42e9-b39a-7c12e045ea7d.png)

**Comment by mclausen** [comment]
Hi @hfloyd and @sinanaltaii, Sorry that the fix didn't work, I think my memory failed me on how that label worked, or maybe I missed a commit or two somewhere on Umbraco Cloud 😅.

We'll take an extra look internally, and get back to you.

**Comment by sinanaltaii** [comment]
> 

Umbraco support helped me to solve my issue and they mentioned that they followed instructions in this url [Deploying Schema from Data Files on your Cloud Environments](https://our.umbraco.com/Documentation/Umbraco-Cloud/Deployment/Deploy-Operations/Deploy-schema/ )

**Comment by mclausen** [comment]
@hfloyd I agree, it does not make any sense to make a slight change to the schema, so it can deploy correctly so that the yellow message disappears🙃.

We'd like to have a look at it, and from our side, we need to get a full overview of what is going into it. From the oust it looks like something that is just a UI change, but it can also be something akin to how the engine works.  We are taking it in for maturing 👍

**Comment by hfloyd** [comment]
I trust you guys to get to the bottom of this, and make the **right** fixes :-) good luck!

**Comment by MarcStoecker** [comment]
In the past we always found a way to get rid of this yellow bar. Not this time. Quite frustrating. Deploy logs clean, no lock files, hmm.

**Comment by mclausen** [comment]
Hi everyone, I am just letting you know that we have taken it in for the next sprint, and we plan to have it delivered by early January.

**Comment by mclausen** [comment]
We've made an update so you are now able to dismiss the yellow bar 🙂

Happy Holidays 🎄

**Comment by hfloyd** [comment]
@mclausen  I got to use this the other day - works a treat! Thanks so much and Happy New Year! 🥂😘
