### ISSUE TITLE
Tiny typo in Backoffice link

### ISSUE THREAD

**Issue by greystate** [umbraco/Umbraco.Cloud.Issues#609]
### Issue description

Just noticed in the new hover links that **backoffice** is missing the "i":

<img width="553" alt="Link that says 'Go to backoffce', missing an 'i'" src="https://user-images.githubusercontent.com/5463/198975247-60f35894-e7e9-408c-a591-ae5298a790b6.png">

**Comment by sajumb** [comment]
Ahh, yes. You are absolutely right. We will add the missing 'i' one of these days.
Thanks for reporting this. :-)

**Comment by sajumb** [comment]
Hi Chriztian,
We are the proud supplier of an extra "i" to the work "backoffice". As we find that the amount of contained i's now is at an appropriate level, we close this ticket.
