### ISSUE TITLE
2FA for V7 on Umbraco-Cloud

### ISSUE THREAD

**Issue by c9mb** [umbraco/Umbraco.Cloud.Issues#611]
### Issue description

2FA for v7 back-office was constantly promised as "coming" during its support phase, but never implemented.

I am fully aware that Umbraco v7 is now in 'security' phase, and due to enter EOL in 12mths time. 

However, when I polled all of my clients running v7 sites on Umbraco-Cloud, not one of them was willing to contemplate paying anything to migrate or changing anything, or re-training staff.

Basically, the current economic conditions mean that any work on their site that doesn't explicitly pay for itself won't be budgeted for, and migrating to a new version doesn't qualify in their eyes.

Every one of them intended to continue hosting as-is until the required something that could not be implemented on their existing v7 platform, which they see as "good enough".

Nevertheless, given the current state of the internet and daily hack attacks, one issue was consistently raised as a problem - lack of 2FA security on the back-office for v7. i.e. They don't want to change what they have, but do want 2FA

There have been a few packages over the years, but none of them have ever worked reliably - the closest to working being: https://github.com/Offroadcode/Umbraco-2FA

I believe that v7 does technically have provision to support Umbraco Identity, and has the potential to support Umbraco 2FA.

While it might appear to be a bit contrived, I'd suggest that sites running on Umbraco-Cloud without 2FA provision, is actually a security issue.

Given the damage that can potentially be wrought, and the lack of distinction made in any exposure on Umbraco-Cloud, I'd suggest that adding 2FA to v7 could be worthy of consideration.

I'd also suggest that if non-trivial, a fair price could be charged for a reliable package to implement it.

**Comment by RyuLindow** [comment]
Hey @c9mb 

I recommend looking into Azure AD B2C integration instead. Here's an article for v8 https://24days.in/umbraco-cms/2019/aad-and-headless/umbraco8-aadb2c/

I'll check with @sajumb about the 2FA you've asked about, though.

**Comment by sitereactor** [comment]
Umbraco Id does exist for v7. You can find versions of the Umbraco Cloud Identity Cms assembly on nuget. The reason why it hasn't been released or rolled out to v7 was due to the Backoffice integrations, which were difficult to so on v7 and not fully on-par with the version for v8.

If you have a project or environment that can be used for testing, a simple first approach could be to install the nuget package to try it out.

https://www.nuget.org/packages/Umbraco.Cloud.Identity.Cms/1.0.275 (minimum version is 7.5).
