### ISSUE TITLE
Feature request: Separated environments on dedicated resources

### ISSUE THREAD

**Issue by FinnSandbeck** [umbraco/Umbraco.Cloud.Issues#613]
### Issue description

Right now every environment shares the same resource pool in the cloud. This means that doing an intensive test on staging/QA can impact performance in the production environment. The option to split the infrastructure into separate dedicated servers would be beneficial for some high-end clients.

**Comment by sajumb** [comment]
Hi @FinnSandbeck 
Thanks for the feature request. We have noted your request and we understand the scenario. We will update this thread when we have an update on this subject.

**Comment by fredriklange-nexer** [comment]
This feature is very high up on our wish list for Umbraco cloud.

**Comment by tcmorris** [comment]
Also interested in this becoming a feature. Having an isolated production environment at the very least would help, dev/staging could be shared for testing purposes.

**Comment by sajumb** [comment]
Just a quick update. We are planning to look into details for separated environments on dedicated resources later this year. And we expect to deliver it in the first quarter of 2024.

**Comment by mclausen** [comment]
Hi @FinnSandbeck , @tcmorris  and @fredriklange-nexer  👋

You know the saying, better late than never 😜

As of last week, the Cloud Teams released an MVP for feature Dedicated Environments, which gives you the option to either
- Separate your live environment on a dedicated, and have the rest of your environments run on shared hardware
- Have all environments on the same dedicated machine

This is an MVP, so please feel free to give us feedback.

Kind regards
@mclausen
