### ISSUE TITLE
UK phone number is unreachable for multi-factor authentication

### ISSUE THREAD

**Issue by sussexrick** [umbraco/Umbraco.Cloud.Issues#614]
### Issue description

I have multi-factor authentication configured on my Umbraco Cloud account with a UK mobile number. 

When signing in to the Cloud portal I get the following error if I click 'Send Code', yet if I click 'Call Me' it works so clearly my number is registered correctly.

![image](https://user-images.githubusercontent.com/1260550/200132709-5507a865-074b-46f9-b8d9-4eb551766c4c.png)

**Comment by sitereactor** [comment]
@sussexrick Can you reach out to our support team through the Umbraco Cloud Portal and give them your details, so we can investigate? If you refer back to this post they will know to give the details to me for investigation :)
