### ISSUE TITLE
Swagger UI is not working in Umbraco Cloud

### ISSUE THREAD

**Issue by MjDhaneshKumar** [umbraco/Umbraco.Cloud.Issues#615]
### Issue description

In one of our Cloud Projects (Professional Plan), We implemented an API functionality and for maintaining the Doc for the API, we used [Swagger ](https://learn.microsoft.com/en-us/aspnet/core/tutorials/getting-started-with-swashbuckle?view=aspnetcore-6.0&tabs=visual-studio) for that, it's working perfectly in the local environment and as well in another environment(one of our VM), but it's not working in Umbraco Cloud.

**Comment by sitereactor** [comment]
Thanks for reporting your issue here on the tracker. Unfortunately its not an issue with Umbraco Cloud, so will have to close it as an issue that is not cloud/hosting related. Please work with our support team to get insights into how this can be configured to work in your Umbraco environment.

**Comment by MjDhaneshKumar** [comment]
Yes @sitereactor , you are right, I fixed the issue, anyway thanks for the fast response :)

**Comment by sitereactor** [comment]
Good to hear you got it fixed. Our support team reached out about this internally as well, but don't know if you managed to fix it before they could reply with suggestions :)
