### ISSUE TITLE
All v7 sites failing to auto-update to recent patch versions

### ISSUE THREAD

**Issue by c9mb** [umbraco/Umbraco.Cloud.Issues#617]
### Issue description

All of my v7 sites are stuck on 7.15.7 despite patches .8 .9 and .10 supposedly being rolled out via auto-update

I note that, according to Umbraco Cloud Status, last night .10 was rolled out, but again, none of my v7 sites received the update.

Of course, I could go through the tedious process of building some sites off-line so I could make comparisons, find the updated files, push them to my baseline and then update the children... but this is all supposed to happen automagically.

While I'm sure it's just a typo, I do note that the description of the scheduled update is:
"Umbraco CMS 7.15.10 is released and will be automatically upgraded on projects running version **8.15.X**  respectively."

**Comment by mclausen** [comment]
Hi @c9mb 
Thank you for noticing the typo, which it definitely was. 

Regarding the upgrades rolling out 7.10.15 yesterday, we ran into challenges where a small subset of sites was not responding well after receiving the upgrade. Out of an abundance of caution for the existing websites, we decided to halt the auto-upgrades to investigate options moving forward. We've made the upgrade available via our manual-upgrade feature where you are in control of when to upgrade.

We can at this point not disclose when we will be rolling the auto-upgrade again until we have figured out how to move forward from here.
