### ISSUE TITLE
Email invitation has expired when inviting users

### ISSUE THREAD

**Issue by bjarnef** [umbraco/Umbraco.Cloud.Issues#625]
### Issue description

We have tested invite user flow from backoffice on a few Umbraco Cloud projects, but we get this error "Unfortunately your email has expired" after accepting the email invitation sent.

I suspect it happens for users not already on Umbraco ID as I was able to get access for my private mail, which already is on Umbraco ID. A few colleagues get the same error and the customer as well.

We also tried re-sending the invitation, but same issue.

![image](https://user-images.githubusercontent.com/2919859/206674633-f5ea1343-b2ed-4947-b99c-11a791c4012b.png)

I raised a ticker in https://support.umbraco.com where a suggesting was to invite from the portal, which we could, but the client can also invite other users and will most likely do this from backoffice. This has also worked in the past, so I am not sure why it fails.

In the portal we can see the invitations are active and should first expire on December 14, 2022.

This is a bit critical to us and our clients as the currently doesn't work as expected and prevents the client from working on content in the project.

**Comment by sajumb** [comment]
Hi @bjarnef,
Thanks for reporting this. We are looking into this just now, but have not succeeded in obtaining a how-to-reproduce. Would you be able to create a detailed bug report including which emails are encountering the issue and a screenshot of their /profile/pendinginvites page? That would be a great help!

I know that our Support can provide you with a walkaround fixing this issue (basically by requesting a new password), but we would like to see a screenshot of the pending page before fixing this user.

If you can provide this including the project name, then please email it to me at saj @umbraco .dk! Thanks

**Comment by bjarnef** [comment]
Hi @sajumb 

I sent you an email with a bit more details.

**Comment by djoike** [comment]
To reproduce, we invite a user, either from the Umbraco Cloud portal, or from the backoffice.
The specific email address does not seem to matter - the key point is that the email address is not previously connected to Umbraco Identity.

After receiving the invitation via mail, simply click the "Get started" button and you will not get taken to your pending invites, but instead to a page which Bjarne already screenshotted in the issue description.
The link will be similar to: https://www.s1.umbraco.io/profile/activate/?email=name%40domain.tld&token=TDQ1fVt5zk3XVE5WFFfOcnUqQWhDdnBOZjplelhvPXg1 (obviously this link is not real and will never work).

We've been testing in incognito mode to avoid issues with our other Umbraco Identity users being logged in.

**Comment by djoike** [comment]
Thank you for this update, however we have also tried with e-mail addresses which have not previously been used on any project (we have created completely new addresses to make 100% sure we're not dealing with "old data").

And the experience with a 100% new address is the same.

**Comment by sajumb** [comment]
Thanks for the great material that you send to me by mail.
Looking into this we can conclude, that this particular issue with expired UmbracoID creation email invites solely is related to inviting a user with an email that was invited to Umbraco Cloud more than 21 days ago without accepting the original invite.

We are currently looking into a fix, which we expect to be shipped in the next couple of days.

**Comment by sajumb** [comment]
This issue has been resolved. The issue was related to re-invites of a new user that haven't responded for more than three weeks on his/her first invitation to Umbraco Cloud.

**Comment by djoike** [comment]
@sajumb What does resolved mean? As in.. a fix is in place at this time or?

**Comment by sajumb** [comment]
Yes, the issue that Bjarne describes regarding expired invitations to the Umbraco Cloud Portal has been resolved. Sorry for the ambiguity
