### ISSUE TITLE
Idle screen is missing an option to log back in

### ISSUE THREAD

**Issue by greystate** [umbraco/Umbraco.Cloud.Issues#628]
### Issue description

Regularly while developing a site, the Backoffice on Umbraco Cloud will (I'm guessing after a specific idle time) log you out and display a screen resembling the login screen:

<img width="676" alt="Screenshot 2022-12-21 at 21 43 23" src="https://user-images.githubusercontent.com/5463/209002536-38c2dfe9-bcbd-4850-a553-1410ae264bc4.png">

But it's just giving you two options:

1. Edit your Umbraco ID profile
2. Change your Umbraco ID password

None of these are what you need if you've just been "idled out" - you just need a "Log back in" button, or a "Log in using Umbraco ID" button.

I don't know what to do on this screen - do I dare Reloading the browser tab? (That's what I do currently).

**Comment by sajumb** [comment]
Hi @greystate ,
Thanks for highlighting this. We will look into this. 😃

**Comment by sajumb** [comment]
Hi @greystate,
For Umbraco 10 and newer, the users are now presented with a one-click option to log right back into the backoffice, when the user session has ended.
