### ISSUE TITLE
Partial restore should have the option to skip unpublished pages

### ISSUE THREAD

**Issue by LennardF1989** [umbraco/Umbraco.Cloud.Issues#63]
We've seen that unpublished pages usually have problems like using deleted images and such, preventing a tree-sync from continueing. It should be possible to skip unpublished (or pages containing errors in general) during a partial restore.

**Comment by ronaldbarendse** [comment]
There seems to to an undocumented feature to allow ignoring broken dependencies (https://issues.umbraco.org/issue/UAAS-660). Although that would still deploy/restore the unpublished content, it would at least allow you to do a sync (without first manually removing all broken dependencies from the pages).

To enable this setting, update `~/config/UmbracoDeploy.Settings.config` with the following:
```xml
<?xml version="1.0" encoding="utf-8"?>
<settings xmlns="urn:umbracodeploy-settings">
  <deploy ignoreBrokenDependencies="true" />
</settings>
```

**Comment by KennethJakobsen** [comment]
The config @ronaldbarendse is talking about should do the trick

**Comment by LennardF1989** [comment]
I don;t agree with the closure, just because the trick works doesn't mean it does what I asked for ;) This solution skips errors, not unpublished pages in general.
