### ISSUE TITLE
TLS Cipher wrong order

### ISSUE THREAD

**Issue by FransdeJong** [umbraco/Umbraco.Cloud.Issues#638]
### Issue description

One of our clients did a security check on their site and their test suite threw an error on the order of the Ciphers.

I checked it with SSLLabs and indeed there are 3 weaker ciphers between the better ones:

![image](https://user-images.githubusercontent.com/29602162/226935617-81a88bb6-fcba-48a1-a510-2e7d90d3373f.png)

I don't know the exact risk but maybe this is an easy fix?

**Comment by RyuLindow** [comment]
Heya Frans

I'm not sure if the order of cipher suites matters even though it would make sense that it does.

Here's a list of cipher suites enabled on every Cloud project by default - https://developers.cloudflare.com/ssl/reference/cipher-suites/supported-cipher-suites/

If you write to me at security@umbraco.com with:

1. comma separated list of hostnames you wish to edit the ciphers on. Do note that non www and www hostnames count as separate.
 
2. comma separated list of the ciphers below that you would like to DISABLE.
 
   "ECDHE-ECDSA-AES128-GCM-SHA256",
   "ECDHE-ECDSA-CHACHA20-POLY1305",
   "ECDHE-RSA-AES128-GCM-SHA256",
   "ECDHE-RSA-CHACHA20-POLY1305",
   "ECDHE-ECDSA-AES128-SHA256",
   "ECDHE-ECDSA-AES128-SHA",
   "ECDHE-RSA-AES128-SHA256",
   "ECDHE-RSA-AES128-SHA",
   "AES128-GCM-SHA256",
   "AES128-SHA256",
   "AES128-SHA",
   "ECDHE-ECDSA-AES256-GCM-SHA384",
   "ECDHE-ECDSA-AES256-SHA384",
   "ECDHE-RSA-AES256-GCM-SHA384",
   "ECDHE-RSA-AES256-SHA384",
   "ECDHE-RSA-AES256-SHA",
   "AES256-GCM-SHA384",
   "AES256-SHA256",
   "AES256-SHA",
   "DES-CBC3-SHA"

**Comment by FransdeJong** [comment]
Thanks @RyuLindow,
The recommendation comes from a IT Guide for TLS from the Dutch National Cyber Security Centre.

The translation of that part is:

**Prefer faster and safer algorithms**
The NCSC advises configuring Good algorithm selections before phasing out Adequate and then Outdated ones. This preference is for the fastest and most secure algorithms. Choose the order within the different security levels yourself. This is mainly a performance consideration. If the server only supports Good algorithm selections, then the client's preference may be leading, and the server does not need to enforce its own ordering.

So it's mainly performance.

Is it possible to change the order instead of disabling them?
