### ISSUE TITLE
Environments are shown in project list after they are deleted

### ISSUE THREAD

**Issue by MichaelNielsenDK** [umbraco/Umbraco.Cloud.Issues#639]
### Issue description

We've had a development environment on a project for upgrading, and it has since been deleted, but it is still shown in the prject list
https://prnt.sc/OyJcsuYXYcEy

**Comment by RyuLindow** [comment]
Hi @MichaelNielsenDK 

Can you please reach out to our Support about it?

**Comment by MichaelNielsenDK** [comment]
I figured it might be a general issue perhaps with some caching, that is why I creatd the issue. 

But sure thing, I'll send it to Support.

**Comment by RyuLindow** [comment]
It's likely that it was related to the incident Azure had today - https://status.umbraco.io/incidents/zvg05t4d9hfg - as it directly affected the provisioning/removing of resources if you remove the environment while the incident was ongoing.

Support should be able to verify that and clean up the dev env for you :)

**Comment by sajumb** [comment]
Even though it is seldom, then it can happen that an environment is not created. When this happens the platform will automatically perform a rollback of what was created. For this particular environment, the reference between the environment that was deleted during the rollback and the project was not deleted.

There is no problem or implications besides that the Development environment is listed in the "Projects dashboard". This is an isolated case, and it will be resolved through the support ticket that you have created. Accordingly, I am closing this GitHub issue.
