### ISSUE TITLE
CPU and memory usage graphs available to admins

### ISSUE THREAD

**Issue by djoike** [umbraco/Umbraco.Cloud.Issues#640]
### Issue description

To be able to comply with Umbraco Cloud's usage thresholds, it would be nice (or even a requirement) to be able to see graphs of CPU and memory usage, either in the project portal or through any other means.

Doesn't have to be easily accessible to anyone, but at the moment we have no way of seeing this (except to ask for dumps from you).

**Comment by RyuLindow** [comment]
Hi there

Please, see:
https://github.com/umbraco/Umbraco.Cloud.Issues/issues/623
https://github.com/umbraco/Umbraco.Cloud.Issues/issues/544
