### ISSUE TITLE
NuGet.config sometimes misconfigured

### ISSUE THREAD

**Issue by LennardF1989** [umbraco/Umbraco.Cloud.Issues#643]
### Issue description

We had an issue on one of our environments where dotnet restore would not work:
```
remote: C:\home\site\repository\src\UmbracoProject\UmbracoProject.csproj : error NU1100: Unable to resolve 'Microsoft.NETCore.App.Ref (= 6.0.14)' for 'net6.0'.
remote: C:\home\site\repository\src\UmbracoProject\UmbracoProject.csproj : error NU1100: Unable to resolve 'Microsoft.WindowsDesktop.App.Ref (= 6.0.14)' for 'net6.0'.
remote: C:\home\site\repository\src\UmbracoProject\UmbracoProject.csproj : error NU1100: Unable to resolve 'Microsoft.AspNetCore.App.Ref (= 6.0.14)' for 'net6.0'.
remote:   Failed to restore C:\home\site\repository\src\UmbracoProject\UmbracoProject.csproj (in 896 ms).
remote: Failed exitCode=1, command=dotnet restore "C:\home\site\repository\src\UmbracoProject\UmbracoProject.csproj"
remote: An error has occurred during web site deployment.
remote:
remote: Deployment Failed.
remote: Error - Changes committed to remote repository but deployment to website failed.
```

Under /AppData/NuGet is a NuGet.config file that has no further configuration, this is the same for all environments.

However, specifically on Production, it makes a fuzz about it with the above error. After manually adding the NuGet v3 package source to the NuGet.config it started working.

A workaround to never make it fail is to place a nuget.config file in the root of your respository.

Reporting this issue because there is apparently a potential misconfiguration possible between environments.

**Comment by sajumb** [comment]
Thanks for reporting this @LennardF1989! 👍 
I will pass it on to the Cloud Platform team who will consider it soon.

**Comment by mclausen** [comment]
Hi @LennardF1989 
Can you share your Nuget.Config file before and after you've added the changes?

This is not an issue we'd heard of before, so I am very curious as to what is going on. Do you by any chance have `global.json` in your project?

**Comment by LennardF1989** [comment]
Hello @mclausen - we had no NuGet.config in the project at all, so we relied on the system doing it correctly.

We also didn't have a global.json - stuff worked perfectly fine on dev/staging, but not on production.

I tried running on a "nuget list sources" command on all environments, none of them report anything (unless you change the nuget.config in the AppData or include one in the current config). So somehow dotnet build magically gets the NuGet feed from somewhere on dev/staging, but not on production.

**Comment by mclausen** [comment]
Hi @LennardF1989 
It seems strange because I can resolve these packages on my local machine and multiple test projects. As for the misconfiguration, I can't seem to point to where it could potentially break 🤔.

Would you mind sharing more details about your project?
- What version of Umbraco are you running?
- What is the Project Alias?

**Comment by LennardF1989** [comment]
@mclausen Please sent me an e-mail (someone at communications of HQ probably has it for you) and we can schedule a session where I'll show you on the actual environments.

**Comment by mclausen** [comment]
Hi @LennardF1989 

Please reach out directly to support. You can find your way to support either via the cloud portal, or www.Umbraco.com, and have a look in the lower right corner. From there support will help you in the right direction :) 

![image](https://user-images.githubusercontent.com/3600782/233162856-ec70a840-fecb-4288-a829-319cf69d8940.png)

**Comment by LennardF1989** [comment]
Done! I left a message to forward my e-mail to you :)

**Comment by mclausen** [comment]
Hi @LennardF1989 
I am hoping that support takes good care of you. I will be closing this ticket for now. Have a good week ahead :)
