### ISSUE TITLE
Projects overview shows project is a child even though it is not.

### ISSUE THREAD

**Issue by aguyfromdenmark** [umbraco/Umbraco.Cloud.Issues#648]
### Issue description

Some project that are not a child of a baseline, but used to be, is still showing up in the Project overview with the "Child" tag on it. 

Examples:

![image](https://github.com/umbraco/Umbraco.Cloud.Issues/assets/6904597/6185d1e3-7434-4499-a532-36d5ce949c9a)
![image](https://github.com/umbraco/Umbraco.Cloud.Issues/assets/6904597/02b58589-1fb4-411e-997b-6aaa484ad5b9)

![image](https://github.com/umbraco/Umbraco.Cloud.Issues/assets/6904597/9a90571c-f543-467d-b0c8-e7a76a5f60c0)
![image](https://github.com/umbraco/Umbraco.Cloud.Issues/assets/6904597/98aa813c-000f-4130-a754-f8c62403529c)

![image](https://github.com/umbraco/Umbraco.Cloud.Issues/assets/6904597/36687bd0-185e-4c26-9c37-e53fc6ff97da)
![image](https://github.com/umbraco/Umbraco.Cloud.Issues/assets/6904597/9b7faa29-b50f-48b5-ab54-a55073021f79)

What I would expect to see when it says that it is a child (The one in the examples are not children anymore): 
![image](https://github.com/umbraco/Umbraco.Cloud.Issues/assets/6904597/89e2603f-7da8-4633-ae8e-8ea9ecc25f2b)

**Comment by sajumb** [comment]
Hi @aguyfromdenmark,
Thanks for your post. We are aware that a minority of cloud projects have an outdated reference in the "Projects Overview". The consequence is that the "Child" tag still remains on the page.

 Currently, the process from our side is to remove the reference manually. Please create a support ticket and let them know which of your project that are affected. Or alternatively, send them to me directly and I will create an intern ticket for us to remove these references, so the "Child" tag will be removed as expected. Thanks 😄

**Comment by sajumb** [comment]
Hi @aguyfromdenmark,
We have cleaned the references for a few cloud projects. The connection to the baseline for these projects was removed with an older implementation that we believe had a bug resulting in the reference still showing on the _Projects Dashboard_. Please try again and let me know how it turns out.

**Comment by aguyfromdenmark** [comment]
Hi @sajumb , it seems like the references are gone now :)
