### ISSUE TITLE
Inviting a user directly from the backoffice results in dead-end

### ISSUE THREAD

**Issue by krebil** [umbraco/Umbraco.Cloud.Issues#649]
### Issue description

If i invite a user directly from the backoffice (either because the user is a copywriter and doesn't need to access the cloud portal or they only need access to a single environment). The accept button in the email sent to them links to: `https://www.s1.umbraco.io/profile/pendinginvites`. If they are not logged in this page redirects to the login screen.
This flow assumes that they already have an account, the login screen has no way of signing up. This makes the process very confusing.

I would love if the link could be dynamic. Sending signed-up users to the pending-invites page and non-signed-up users to a signup page.

![image](https://github.com/umbraco/Umbraco.Cloud.Issues/assets/1363512/e1a44ce0-e60e-4b94-ad26-ed02459f4092)

**Comment by sajumb** [comment]
Hi @krebil,
Umbraco Identity does have a dynamic flow where a non-signup-user will receive an email to register before receiving the email about joining a cloud project. Accordingly, I would expect the user already to have an UmbracoID account. Please verify this. It can potentially be done to request a password reset on the login dialog and here let the user reset her password and log into the Umbraco Cloud portal.

If the users managed to login in, the pending invite to the project can be accepted at https://www.s1.umbraco.io/profile/pendinginvites.

I hope this helps. 😃

**Comment by sajumb** [comment]
Hi,
I am closing this as we believe the signup/invite flow to be working 100% as expected.
