### ISSUE TITLE
Text in notification title is cut off

### ISSUE THREAD

**Issue by bjarnef** [umbraco/Umbraco.Cloud.Issues#650]
### Issue description

I notification title I noticed part of the text is being cut off, e.g. brackets.

![image](https://github.com/umbraco/Umbraco.Cloud.Issues/assets/2919859/8ee8f691-aaf3-4768-b226-02a02e20f937)

Increase the line height to fix this.

![image](https://github.com/umbraco/Umbraco.Cloud.Issues/assets/2919859/6f4cc2cf-3e2b-4f43-9c16-0d8a287bbc56)

**Comment by sajumb** [comment]
Hi @bjarnef,
Thanks for highlighting this. Now that you point it out, it is obvious that we could tweak the header of the Umbraco Cloud just a bit to ensure that the notification title is not cut off.

However, we are going to reimplement the header bar into a new tech stack just after the summer. The ambition is to add a more modern look to the Umbraco Cloud portal. And to avoid having small glitches and prevent minor blemishes like this.

We will increase the height of the title as suggested.

**Comment by sajumb** [comment]
I promise to include this in the new implementation of the notification feature. 😄 I am closing this one.
