### ISSUE TITLE
Modal can't be closed using `esc` key

### ISSUE THREAD

**Issue by bjarnef** [umbraco/Umbraco.Cloud.Issues#651]
### Issue description

When modal opened from the "read more" button in notification title, can't be closed using `esc` key.

![image](https://github.com/umbraco/Umbraco.Cloud.Issues/assets/2919859/9d28aaf9-4d84-4a98-8acf-b26605736dff)

**Comment by sajumb** [comment]
I promise to include this in the next implementation of the modal. 😄 I am closing this one.
