### ISSUE TITLE
cache TTL limit

### ISSUE THREAD

**Issue by mordchay** [umbraco/Umbraco.Cloud.Issues#652]
### Issue description

we have a proffesional license for Umbraco cloud
and we tring to change the cache TTL to 5 minutes,
and is show validation error wich the minimum is 30 minutes.
but in your documentation in the link:
https://docs.umbraco.com/umbraco-cloud/set-up/project-settings/manage-cdn-caching
is show for proffesional license:
The minimum Cache TTL varies as follows:
Starter: 2 hours/120 minutes
Standard: 30 minutes
Professional: 2 minutes
![Umbraco Cache](https://github.com/umbraco/Umbraco.Cloud.Issues/assets/135003655/b66ed93f-22cd-4859-bcd4-7da577ae66ee)

**Comment by sajumb** [comment]
Hi @mordchay,
Thanks for reaching out regarding this. We got a report from our Support this Friday regarding Professional plans. We fixed the issue immediately. So please try again! :-)

**Comment by mordchay** [comment]
Thanks, it is worked

בברכה,
מרדכי (מוטי) פרהדיין
מנהל פיתוח
[תיאור: C:\Users\gabi_r\AppData\Roaming\Microsoft\Signatures\malamteamlogo.bmp]

טלפון 02-6408792
פקס  02-6753222
נייד 052-3980024
דוא"ל ***@***.******@***.***>
