### ISSUE TITLE
2FA on Kudu

### ISSUE THREAD

**Issue by Stkl150** [umbraco/Umbraco.Cloud.Issues#655]
### Issue description

Since last year we got 2 factor authentication when logging in into https://identity.umbraco.com/ which is great. Unfortunately, the Kudu endpoint is still publically available using only username and password. 
Is it possible add another layer of security over Kudu to prevent username + password abuse?

**Comment by sajumb** [comment]
Hi @Stkl150,
You created an identical issue last month https://github.com/umbraco/Umbraco.Cloud.Issues/issues/647. Let's continue our chat about the feature request in that thread. 😄 I will be closing this one to avoid any confusion.
