### ISSUE TITLE
Issue with "Invite title" 

### ISSUE THREAD

**Issue by chrismarath** [umbraco/Umbraco.Cloud.Issues#659]
### Issue description

Just wanted to report an issue about project invitations sent through the portal. We noticed that if you edit the "Invite title" field in the user invitation dialog, then the email reaching to the invitee still has the default value in its mail template. 

![image](https://github.com/umbraco/Umbraco.Cloud.Issues/assets/126063446/409ee4b5-89bd-4c6c-abd3-c0b0e8b393d4)

**Comment by sajumb** [comment]
Hi @chrismarath 
Thanks for the report. As you correctly state, the "Invite title" is currently not really used in a meaningful manner in the mail template (besides being added to the HTML as the title). We believe that it will be sufficient to have the "invite message" field and we will accordingly remove the title input option early next week.

**Comment by sajumb** [comment]
We have removed the invite title that no longer was used. Thanks once again.

**Comment by chrismarath** [comment]
Thank you very much for the update. 😉
