### ISSUE TITLE
Typo on CMS version list

### ISSUE THREAD

**Issue by greystate** [umbraco/Umbraco.Cloud.Issues#663]
### Issue description

When you create a new project on Umbraco Cloud, you have the option to choose a version — there's a teeny typo on this screen, as it says "Recomended for most users" - missing an 'm' in "Recommended".

<img width="1060" alt="portal-typo" src="https://github.com/umbraco/Umbraco.Cloud.Issues/assets/5463/f85ad704-16be-469e-80b4-d7bd2f372a7b">

**Comment by sajumb** [comment]
Oh yes! I cannot believe that we missed that... We will add an extra 'M' in there and release it later today.
Thanks! 😄

**Comment by sajumb** [comment]
We have added the missing letter. I am closing this thread.
