### ISSUE TITLE
Invitations fails if logged in with Umbraco ID, but invited on another email

### ISSUE THREAD

**Issue by bjarnef** [umbraco/Umbraco.Cloud.Issues#666]
### Issue description

Mostly when working with Umbraco Cloud projects I am logged in with Umbraco ID using my business email, but I noticed when inviting myself on a private email I receive the email, but accepting this failed with this message.

![image](https://github.com/umbraco/Umbraco.Cloud.Issues/assets/2919859/1471febf-54e0-4e9a-8141-f56596cda39f)

![image](https://github.com/umbraco/Umbraco.Cloud.Issues/assets/2919859/c66b5521-0b74-40a5-aeb0-43eafb544127)

I have seen it is a few times and mostly because I have logged in with Umbraco ID on another email, which doesn't have this pending invite and solved it logging out this Umbraco ID first.

Maybe it should force a logout or could it compare the email in the link with the existing logged in Umbraco ID?

**Comment by Musealali** [comment]
Hey @bjarnef 

I was not able to re-produce the issue - this seems to be an old issue and has since then been resolved after moving to the new tech stack. 

If you however still experience anything similar please do not hesitate to reach back to us. 

Best Regards
