### ISSUE TITLE
Feature: ability to restore (transfer) Document Types from Live to Development

### ISSUE THREAD

**Issue by romeguarin** [umbraco/Umbraco.Cloud.Issues#667]
### Issue description

Right now, there's no way to restore or transfer Document Types that was created in Live environment to Development environment. Having this capability promotes better synchronization between environments.

**Comment by sajumb** [comment]
Our recommended workflow revolves around a "left to right" deployment model, where developers commit all necessary assets to source control as a complete unit. This includes code, templates, and schema definitions for document types. These changes are then pushed from development to the live environment after undergoing the review process. We designed this workflow to ensure that developer-controlled assets move in a one-way direction, streamlining the deployment process and minimizing potential conflicts.

While the flow you're considering—moving "developer assets" from live to development—might be achievable, it's important to note that our recommended model doesn't involve this type of deployment. We encourage developers to keep their work consistent and aligned across the environments, committing all related changes as a unit. Content, on the other hand, created by editors, is expected to move from development to live as it's created and reviewed.

Understandably, you're looking for flexibility, and I want to clarify that each Cloud environment has its own associated Git repository. This means that pulling and copying files between environments is technically possible. However, it's not our upfront method, and it might lead to complexities and potential conflicts.

To ensure the smoothest deployment experience and to avoid complications, we strongly recommend adhering to our "left to right" deployment model. This will not only streamline your workflow but also enhance consistency and minimize the chances of conflicts.

Accordingly, it is not something we currently are considering to support in Umbraco Cloud.

**Comment by romeguarin** [comment]
sorry for the late response. what would you recommend to do to enforce the workflow of dev (to staging) to live? is there a way to restrict access to the settings of an staging or live environment? that way changes would only occur in development.
