### ISSUE TITLE
Feature request: Add ':' as allowed character in secret names

### ISSUE THREAD

**Issue by jemayn** [umbraco/Umbraco.Cloud.Issues#671]
### Issue description

Hey there!

We want to use the Umbraco Cloud secret management for a new project.

We thought we could just add secrets in a local not-comitted appsettings.json file locally, and then add settings with the same secret name in Umbraco Cloud so we could just use the same code to get them.

The way we set up the appsettings is fx like this:

```js
{
  "$schema": "appsettings-schema.json",
  "Servicename": {
    "WebsiteApi": {
      "AccessToken": "",
      "ClientId": "",
      "ClientSecret": "",
      "StoreHash": "",
      "ApiPath": ""
    }
  }
}
```

And then in the Program.cs we have:
```js
public static IHostBuilder CreateHostBuilder(string[] args)
{
    return Host.CreateDefaultBuilder(args)
        .ConfigureUmbracoDefaults()
        .ConfigureAppConfiguration((context, builder) =>
        {
            builder.AddJsonFile($"appsettings.Local.json", true, true)
                .AddEnvironmentVariables();
        })
        .ConfigureWebHostDefaults(webBuilder =>
        {
            webBuilder.UseStaticWebAssets();
            webBuilder.UseStartup<Startup>();
        });
}
```

This should allow us to add both env vars and our local appsettings file so we can get the config values the same way.

However, for this to work we need to set the secret keys to be fx: `Servicename:WebsiteApi`, which the Cloud portal wont accept.

![image](https://github.com/umbraco/Umbraco.Cloud.Issues/assets/79840720/d88aed42-6cf7-4fd2-8b0a-efdaa3fb90a6)

As far as I can tell the only way to get it to work is to not nest our config values, which makes typed config annoying to deal with.

**Comment by sajumb** [comment]
Hi @jemayn,
Thanks for the feature request. However, I am happy to say that you already can add a key with the pattern <name1>:<name2>. In Azure, colons are translated into two underscores, that is '__', so the correct way to add the secret name would, in this case, be `Servicename__WebsiteApi`.

You can read more about the use of double underscores for secrets here: https://docs.umbraco.com/umbraco-cloud/set-up/project-settings/secrets-management#access-secrets-in-a-umbraco-solution

I fully acknowledge that the current error message lacks helpfulness and may even lead to confusion. We will provide a more informative message in cases where the key name contains a colon.

Let me know if using the double underscores helps you out. 😃

**Comment by jemayn** [comment]
Hey @sajumb 

Thanks for the quick response!

I just double checked and it works just as you said, guess I should have read the docs more carefully 😅
I agree an informative message would be great though!

I will close this issue as it was already working I just didn't read the docs carefully enough!
