### ISSUE TITLE
New Region in AU

### ISSUE THREAD

**Issue by benq-z7** [umbraco/Umbraco.Cloud.Issues#673]
### Issue description

I work for an agency that support an Umbraco Cloud site for one of our clients. During the initial scoping phase of their project they indicated quite strongly that they preferred to use Umbraco Cloud and as our agency is an Umbraco partner, that was something we could easily support.

Since release they have added an additional integration with an API service that is available in Australia. Unfortunately due to licensing restrictions with this API service we are unable to allow caching of the data from the API. If the API provided identifies that data is being cached then the client will lose access to this service which is critical for their business. The side effect of this is then that users have to wait for, sometimes multiple, API requests to be completed before their page can load. For reference, general latency between AU and either the EU or US is about 250ms meaning that each request to the API will take at least 250ms to complete not including processing time on the API side.

Moving to a host available in Australia would significantly reduce the API latency to a negligible level but our client has indicated quite strongly that it is important for them that the stay with Umbraco Cloud. Therefore as a result I am looking to open this feature request for Umbraco Cloud hosting in an AU region.

**Comment by sajumb** [comment]
Hi @benq-z7,
Thanks for the feature request for adding a new region Australia for Umbraco Cloud. We understand that having a dedicated Umbraco Cloud region in Australia would not only improve the performance but also cater to the specific needs and preferences of our Australian users.

To gather more insights and understand the demand for a Umbraco Cloud region in Australia, other users who share this requirement are welcome to post a reply in this thread as well. Your collective feedback will aid us in gauging the community's interest and assessing the feasibility of such an expansion.

**Comment by c9mb** [comment]
@sajumb Yes I believe that it's needed - and I have some specific input to contribute regarding this subject - I just sent an email to contact@ with the details, if you want to follow up.

**Comment by sajumb** [comment]
And it is live! https://umbraco.com/blog/umbraco-cloud-expands-with-regional-hosting-option-in-australia/
🇦🇺 -> ☁️
