### ISSUE TITLE
Login error after Upgrade from 12.0.1 to 12.1.0

### ISSUE THREAD

**Issue by rammi987** [umbraco/Umbraco.Cloud.Issues#675]
### Issue description

Hello.

I have just upgrade a solution from version 12.0.1 to 12.1.0. This upgrade was not without hike ups.
First off all when enter debug mode on my local machine I runned into the bug: https://github.com/umbraco/Umbraco-CMS/issues/14658 well with that out off it way, I can not run the solution.

But then the next problem occured. Then trying to login into the backoffice using the "sign in with Umbraco ID" failed.
On the step the Umbraco solution was about to Upgrade so the url /umbraco was redirected to /umbraco/authorizeupgrade.
But still i need to login becouse i didn´t have uanttened setting filled.

When clicking on the login with Umbraco ID a popup, come acrosse as excpeted, but it showed the same login screen, toke a look into the url of the popup and it was localhost:xxxx/umbraco/authorizeupgrade and could agian now inside popup click login with Umbraco ID.

Inside the popup if clicked on the sign in button, it just redirect to the same popup, so I got stuck on the Upgrade.

The temp solution I found was to delete the database and temp files, and rerun the Umbraco Solution on my local machine and everything work, but lost all of my test data, and was now need to copy it agian from the next enviroment.

**Comment by sajumb** [comment]
Hi @rammi987,
Sorry to hear about the upgrading issue that you have encountered. Have you tried to follow the same instructions that is highlighted on this page from our documentation: https://docs.umbraco.com/umbraco-cloud/product-upgrades/major-upgrades#step-4-finishing-the-upgrade

 It might be relevant to give that a go. In case that doesn't help, please contact our support who might have the golden solution to this particular issue.

**Comment by mclausen** [comment]
HI @rammi987 👋
Lots of water has flowed under the bridge since this issue was last visited. 

I can tell that @sajumb did provide general directions on how to upgrade, and we haven't received any reply since thin. If this still is an issue feel free to re-open.

Kind regards
@mclausen Cloud Platform/Core Teamlead
