### ISSUE TITLE
Invite User - BackOffice User Groups dropdown does not load when part of multiple organizations

### ISSUE THREAD

**Issue by jamiepollock** [umbraco/Umbraco.Cloud.Issues#680]
### Issue description

My Umbraco Cloud admin user no longer appears to be able to select a Backoffice user group for new or existing users in any projects I am a part of.

# Steps to reproduce

1. Go to a project
2. Click "Invite User"

![image](https://github.com/umbraco/Umbraco.Cloud.Issues/assets/5408006/90c2ea0b-f879-4cb9-9c05-fd1b20fe637f)

I am still able to invite a user to a project but they do not have a backoffice user set.

# Additional information

It appears the API call for getting the user groups succeeds but the "potential" organization call afterwards fails.

![image](https://github.com/umbraco/Umbraco.Cloud.Issues/assets/5408006/e5e255f0-ffa1-476e-98d5-67486fc189e6)

When my Umbraco Cloud user was created I was part of my company's Cloud organization but I recently added to a client organization too. This seems to be a deciding factor as I got a colleague, who is part of one organization, to test this and on a project we both share and they could not replicate this issue.

I can only see the new client organization and not my company's organization in the Umbraco Cloud admin.

**Comment by sajumb** [comment]
Hi @jamiepollock,
Thanks for the bug report. We have tried to reproduce this but we were not successful with this initially. If you would be so kind as to send me the email of your UmbracoID account. My email starts with saj.

**Comment by jamiepollock** [comment]
Hi @sajumb! Thanks for this. I've sent over my Umbraco ID to a support agent who is aware of this ticket.

Let me know if I can provide anything else.

**Comment by jamiepollock** [comment]
Hi @sajumb! Do have any update on this or should I follow up via the internal issue tracker?

**Comment by sajumb** [comment]
Hi @jamiepollock,
Sorry for the late reply. But yes, we believe to have found the issue in the front-end of the pages, that made the "backoffice user group" box fail in rare scenarios. Please try once again! 😄

**Comment by jamiepollock** [comment]
@sajumb I can confirm this is now working as expected! Thanks!
