### ISSUE TITLE
Explanation of failed deploys needs to be improved

### ISSUE THREAD

**Issue by tormnator** [umbraco/Umbraco.Cloud.Issues#684]
### Issue description

In short, when a deploy (e.g. from Dev to Live) fails, I expect a clear message of what went wrong, and how the issue can be resolved. The screenshot below is from a case last week:

![image](https://github.com/umbraco/Umbraco.Cloud.Issues/assets/15617453/e3897411-0d1d-4e3a-b860-703ac738a2c4)

The problems here are:

1. "_Last deploy didn't go as planned_": this is too vague and not helpful at all in trying to resolve the issue. Is there a problem with my code? Is there a problem with my data (schema mismatch)? Is it due to a bug in Deploy? Or is there a problem on the Cloud sites?
2. "_Often this problem is solved by making a change and do a new deployment._": This is too vague as well. What do you mean by "Often"? What exactly does redeploying do to solve the issue?
3. "_If you need help please contact support_": This is typically the last resort, particularly when the issue arises after hours (which tends to be the case since we don't want to cause our Live site to go down or restart during business hours), and I know that support isn't available until next morning. And again, **how do I know if I need help?**

Fundamentally I need to know if the issue can be resolved by me, or if it can only be solved by Cloud Support. In last week's case, knowing that the issue couldn't be solved by me would've saved me hours of troubleshooting, searching for evidence of what went wrong, and trial-and-error.

In my opinion, giving me the exact error messages, exceptions, log details etc. that were generated is the best option. Preferrably put it right on the screen on the portal page. If this is not possible, give me the specific location(s) of the log file(s) containing the information I need to make a determination of what went wrong. I spend way too much time looking for log files and scanning them for valuable information.

Related to the "Contact support" option, this has become too time consuming now. First I have to wait (3 hours it said, but ended up being overnight) for level 1 support to reply and ask me to try redeploy (yes of course, I had already tried that a few times), then I have to wait another few hours (or another overnight) for level 2 support to take over. With better information, support would and should know immediately whether the case should be escalated to level 2 (how many levels are there?).

Finally, last week's case was eventually resolved by someone on level 2 (I think). I asked for details on what went wrong so that I can learn from this and improve the troubleshooting next time, but the answer wasn't of much help:

> "Tor I checked with the team and this is not something that you can do yourself. So if you see this again let us know for sure"

**Comment by sajumb** [comment]
Hi @tormnator,
Thank you for taking the time to provide such detailed feedback on your experience with our deployment process. We completely understand your frustration with the lack of clarity in our error messages and the inefficiency of our support process. Your points are valid, and we appreciate your constructive criticism.

We are actively investigating the specific issues you've encountered during your deployments. Our team is committed to resolving these issues as quickly as possible to ensure a smoother deployment experience in the future. We do have a log entry for the incident that caused the issue you encountered. It was a Site extension not responding. We have only seen this on a very limited number of environments, but we will look into and resolve it, so it won't happen again.

We have started a new project called "Enhanced Process Visibility for Umbraco Cloud," which you can find on our public roadmap at https://abcdefg.ijk/mnopqrst/vwxyzabcd-fghijk/mnopqrs/. This project aims to make long-running operations more informative and satisfying for users. We're starting with improving the "add new environment" and "change plan" processes, and we'll expand these enhancements to the deployment process too. This initiative will ensure, that the user - when an issue occurs - gets detailed information about what happened and what can be done to resolve the issue smoothly. 

Regarding your concerns about our support levels, we understand that the current process can be time-consuming. We are looking into ways to streamline the support process, including quicker escalation to higher support levels when necessary.

Once again, thank you for your valuable feedback. It plays a crucial role in helping us improve our services. If you have any more questions or need further clarification, please don't hesitate to reach out.

**Comment by McGern** [comment]
Same thing here. Just did a deploy that gave me the message, never seen it before, but I can't see what went wrong. All the changes I made seem to be there and there is nothing in the deploy logs that suggest an error. Nor can I actually see the umbraco log for that period, it seems to be stalled and not downloading.

**Comment by sajumb** [comment]
Hi @McGern, 
Thank you for your feedback. We acknowledge that the information provided during deployment errors hasn't always been as clear or helpful as it could be. Recognizing this, we've made substantial improvements over the past year to enhance the clarity and usefulness of the information presented during such events. However, we're aware that our work in this area is far from complete.

We're actively working on an initiative aimed directly at addressing well-known deployment challenges more effectively. This includes automatically resolving collision errors and better handling of false positives—situations where warnings are issued even though the deployment proceeds without issues, like the one your project encountered recently.

Stay tuned for updates. Our goal is to continually improve the deployment process, striving to provide a seamless and friction-free experience for every deployment.

**Comment by Musealali** [comment]
Thanks for reaching out and letting us know about the detailed git messages you used to see during deployments. We understand how helpful those were for troubleshooting.

Good news! We’ve introduced a new feature that keeps a record of all deployment information. This feature includes all the details you need to understand and diagnose any issues during a deploy.

We believe this will provide you with the comprehensive insights you're looking for.

I have attached a video showing this new feature. 

https://github.com/user-attachments/assets/f9538e78-258b-4bc3-ad39-cd30fbff2711

If you have any questions or need further assistance, feel free to reach out!

**Comment by ben637** [comment]
I too have been getting mighty frustrated with deployments in Umbraco Cloud. We are experiencing a high number of failures when deploying from our CI/CD pipeline into Development. That video above is great, I was not aware of this extra info. However it is only present for failures from Development to Staging to Live, not the deployments into Development. 

Is there any way of getting that info as all we get to see is "An unknown error has occurred. Check the diagnostic log for details."
Re-deploying 5 times sometimes solves it (with restarts in between). But the fact I change no code and eventually it works, implies an issue with the process rather than code.

Our issues have been mainly going to development, but that is because this project is not live yet and we are not doing deployments to Staging very frequently. At best we are seeing a 50% success rate in deployments.

As it stands every deployment feels me with dread, and failed deployments cost us a lot of time.
