### ISSUE TITLE
Unable to view or download Umbraco logs

### ISSUE THREAD

**Issue by tormnator** [umbraco/Umbraco.Cloud.Issues#685]
### Issue description

I am unable to view or download the Umbraco logs shown in the screen shots below:

![image](https://github.com/umbraco/Umbraco.Cloud.Issues/assets/15617453/74c827cf-c317-4f1a-8d6e-78f349ea3278)

![image](https://github.com/umbraco/Umbraco.Cloud.Issues/assets/15617453/02bc3a13-ee02-48e8-95ea-5908d7dbacf5)

**Comment by sajumb** [comment]
Hi @tormnator,
Thanks for your report. It is highly appreciated.
Please note that we currently show all files in the overview. Also, the ones that are under creation or empty. The one you are highlighting has a very small size of 281 bytes and is properly under creation. I can see that the same file now has a size of 75.5 kB and can be opened.

All other files in the list can be opened directly in the portal if you click it them. But you are right, that we shouldn't display the ones that are either empty or haven't been fully created by the logging mechanism. The /logs pages are some of the remaining pages that haven't been updated with a new tech stack. When they will be, we will only show the ones that can be opened.
