### ISSUE TITLE
Cloud portal chat could be improved

### ISSUE THREAD

**Issue by tormnator** [umbraco/Umbraco.Cloud.Issues#686]
### Issue description

1. I am currently not receiving any e-mails with notifications/transcripts of new messages in the chat. This used to work before.
2. There is no option to download or have the entire chat e-mailed to me.

**Comment by PratheesUmbraco** [comment]
Hi @tormnator 
Thanks for reporting this! It looks like there is an issue with our chat vendor. I will get in touch with them and get your 1st request fixed. 

2. Usually mails will be the way to download your ticket as a thread. Soon enough there will be a dedicated portal where you can view all of your tickets. It will be launched soon :) 


I will keep you posted 

Best regards,
Prathees

**Comment by PratheesUmbraco** [comment]
Hi Tormanator - The issue has been fixed :) I'm closing this thread. Sorry for not coming back to you earlier
