### ISSUE TITLE
Error logs: use exception if message is empty

### ISSUE THREAD

**Issue by ronaldbarendse** [umbraco/Umbraco.Cloud.Issues#69]
If an error is logged without a message, the overview is completely useless:

![Error log overview without messages](https://user-images.githubusercontent.com/1051287/55081922-0aa43080-50a1-11e9-84a6-3ea0594f61fa.png)

Before you say _"But you should always add a message!"_, the ImageProcessor library uses it's own logging interface and Umbraco Core proxies this into an `ImageProcessingException`, but without the original message (https://github.com/umbraco/Umbraco-CMS/blob/91c52cffc8b7c70dc956f6c6610460be2d1adc51/src/Umbraco.Web/ImageProcessorLogger.cs).

So it would be nice if a fallback to the exception message would be added or the exception type is shown in the overview.

**Comment by ksuvec** [comment]
@ronaldbarendse 

Thanks so much for submitting this. Super suggestion that has now been released. So no more empty entires in the error log.
