### ISSUE TITLE
Process explorer broken by authentication

### ISSUE THREAD

**Issue by james-whittington1** [umbraco/Umbraco.Cloud.Issues#691]
### Issue description

The kudu "process explorer" does not work as the requests to the api endpoint return a 401 error.

https://<project_id>.scm.azurewebsites.net/api/processes/<number>

![image](https://github.com/umbraco/Umbraco.Cloud.Issues/assets/37091895/b69ecd66-9185-46d7-acf8-7384cbc9fb63)
Note that the project_id obscured here is different than the one used to access the scm panel.

**Comment by sajumb** [comment]
Hi @james-whittington1,
Sorry about the late reply on this one.

It appears there's a mix-up with the domain used to access the KUDU "process explorer". The correct domain format is {projectalias}.scm.{stamp}.umbraco.io, not the *.azurewebsites.net domain. Replace {projectalias} and {stamp} with your specific project details.

Furthermore, it seems there's an attempt to use personal Microsoft credentials. Ensure you're using credentials with the necessary permissions for the Azure resource.

Let me know if that resolves the issues.

**Comment by james-whittington1** [comment]
Hi, sorry I don't think I explained it well, the when accessing process explorer though kudu, using the "kudu" link in the portal, it requests some data from azure, which presumable are resources that I don't have access to (Owned by Umbraco's tenancy?).



![image](https://github.com/umbraco/Umbraco.Cloud.Issues/assets/37091895/21ead5d2-62e8-4144-a464-132c3acb2354)

**Comment by mclausen** [comment]
Hi @james-whittington1,

Looks like quite a bit of water has flowed under the bridge since we last chatted about this ticket!

I’m pretty sure the issue has been resolved 🤠 - but if not, feel free to reopen it.

Cheers,
@mclausen - Cloud Platform/Core Team Lead
