### ISSUE TITLE
User invite fails when name contains `Š`

### ISSUE THREAD

**Issue by bjarnef** [umbraco/Umbraco.Cloud.Issues#693]
### Issue description

I invited some of my coworkers to an Umbraco Cloud, where all went well except one which failed.
I suspect it was because the last name starts with `Š`.
It worked when I just wrote his first name - or if I just replace `Š` with `S`.
Maybe it's an issue with other special characters like `Ü`, `Ö`, `É` etc... but it seem to work with Danish letters like `Æ`, `Ø` and `Å`.

![image](https://github.com/umbraco/Umbraco.Cloud.Issues/assets/2919859/82e709d4-507b-492d-a5bf-17dc3555bb86)

![image](https://github.com/umbraco/Umbraco.Cloud.Issues/assets/2919859/dfb4dae7-fb9b-480b-9010-d08dfb8f890a)

**Comment by bjarnef** [comment]
@sajumb not sure if this is a general issue?
This specific project is an Umbraco Heartcore trial. Not sure if it should matter though.

**Comment by bjarnef** [comment]
I got this issue again on a regular Umbraco Cloud project as well.
However it does work when inviting user to an organization.

**Comment by sajumb** [comment]
Awesome. Thank you very much for reporting this @bjarnef!
We have started to consider this and will have a fix out soon!

**Comment by sajumb** [comment]
The issue has been successfully resolved. We have improved the flexibility of the invite popup, allowing for a wider range of characters to be included in names.
