### ISSUE TITLE
Add support for outbound rewrites

### ISSUE THREAD

**Issue by aguyfromdenmark** [umbraco/Umbraco.Cloud.Issues#695]
### Issue description

I had a long conversation with support about the presence of outbound rewrites, will crash a website on Umbraco Cloud. 
Basically, if you add outbound rewrites that manipulate the HTML, the sites will crash in a similar manner to this:

![outboundUrlRewriteError](https://github.com/umbraco/Umbraco.Cloud.Issues/assets/6904597/832efce3-1769-4e8f-bab2-4a2c5f7aeb9d)

There is much history and research behind this, but this ticket has all the info: #1384500026605

**Comment by sajumb** [comment]
Hi @aguyfromdenmark,
Thank you for reaching out and sharing your concern regarding the outbound rewrites on Umbraco Cloud. We understand that this issue has previously been discussed with our support team and that it poses a significant problem when manipulating HTML, leading to website crashes.

However, to further evaluate and address this concern, we would need more detailed information than what has been provided. The ticket number #1384500026605 you referenced appears to be a good starting point, but for a comprehensive understanding and to consider this for further action, we would require additional insights such as:

1. Specific scenarios or conditions under which this issue occurs.
2. The exact error messages or logs generated during the crash.
3. Any known workarounds or steps taken to mitigate this issue.
4. Detailed descriptions or documentation regarding the history and previous research on this issue.

We will have to set a bar for the quality of reports that we consider in this public issue tracker. A reference to an internal support ticket is not sufficient. Or insightful for other users who might be experiencing the same problem. Accordingly, I will close this ticket.

You can either update the existing task with the requested information and reopen it, or if you prefer, create a new task with the detailed information.
