### ISSUE TITLE
Minimum width of table cell with tag

### ISSUE THREAD

**Issue by bjarnef** [umbraco/Umbraco.Cloud.Issues#699]
### Issue description

Could we set `min-width: 80px;` on table cells containing tags for each environment?
E.g. under https://www.s1.umbraco.io/organization/my-organization/accessrights

Currently it looks like this, because project name and user cells may squeeze these columns.

![image](https://github.com/umbraco/Umbraco.Cloud.Issues/assets/2919859/7e9dd39f-4445-4a29-a70e-bc0f6fe3648a)

I think this looks nicer 😁

![image](https://github.com/umbraco/Umbraco.Cloud.Issues/assets/2919859/7e836187-490b-4cde-a4a0-e07665298d7a)

**Comment by sajumb** [comment]
Thank you for the keen observation! 😄 We will make the necessary adjustments.

**Comment by sajumb** [comment]
Hi @bjarnef ,
We have changed the setting for the min-width so it matches your suggestion.
