### ISSUE TITLE
Environment left in Debug Mode after update

### ISSUE THREAD

**Issue by MichaelNielsenDK** [umbraco/Umbraco.Cloud.Issues#7]
After updating children from a Baseline project, 5 out of 9 children were in Debug Mode after the update.

**Comment by mikkelhm** [comment]
Hi @MichaelNielsenDK 
Thanks for reporting - Do you have a bit more insights, was this when doing a minor upgrade to the children, or "just" a regular code update to them?

Also can I get you to send me the names of the projects? just to easier debugging? (mikkel@umbraco.com or support@umbraco.com) you elaborate on which projects it where they didnt go into debug mode, and which did?

**Comment by MichaelNielsenDK** [comment]
Yea sorry about the lack of information, but there wasn't much information to give, without listing project names. 

It was just a code update, no upgrade. 

I've sent you a list of projects who went into debug and who did not.

**Comment by MichaelNielsenDK** [comment]
Just want to update this issue with that it happened again. The exact same 5 children as last week, went into debug mode after they were updated from the Baseline.

**Comment by pijemcolu** [comment]
Hello  we've found the issue. The issue was on our side due to new functionality we've released allowing baseline child minor upgrades.

The

**Comment by MichaelNielsenDK** [comment]
How do I hi-five on GitHub :-D 

Thanks!

**Comment by mikkelhm** [comment]
I'm closing this issue - @MichaelNielsenDK - for your sites(which you sent us a list of) we have manually fixed the issue, so it wont happen again, and we will updating the entire infrastructure, next week, so others not run into the same issue in the future - Thanks for reporting
