### ISSUE TITLE
Error logs: automatically clean UCErrorLog table

### ISSUE THREAD

**Issue by ronaldbarendse** [umbraco/Umbraco.Cloud.Issues#70]
As Umbraco Cloud adds a log4net `AdoNetAppender` (which is not documented by the way) to log errors to the `UCErrorLog` table (in the website database), this can quickly become a very large table.

The Cloud portal only allows marking the error as read: there's no delete or clean option. It might be a good option to automatically delete read errors after a specified amount of time, as that keeps the table/database size down.

It's currently not possible to customize the appender itself (see https://github.com/umbraco/Umbraco.Cloud.Issues/issues/36), otherwise the following query could be added to the `commandText` (after the INSERT):
```sql
DELETE FROM UCErrorLog WHERE Read = 1 AND Date < DATEADD(Month, -3, GETDATE());
```

**Comment by pijemcolu** [comment]
@ronaldbarendse 

We already do this for entries older then 30 days. Internally we use elastic database jobs. Can you confirm that the table in your project contains more then 30/31 days of entries?

**Comment by ronaldbarendse** [comment]
@pijemcolu I've just noticed projects with 100.000+ errors in the table (lots of spamming by Examine, ImageProcessor and failed/bad requests).

Some indication or documentation of the automatic cleanup would be nice, maybe just rewrite the introduction on the error logs page, like this:

> Umbraco Cloud is collecting error logs from your site while it's running. Use this page to get an overview of what has happened on your site.
> 
> Mark the errors you've already taken care of as read to remove them from the portal overview. You can see previously acknowledged error logs for this environment under the "Read" tab. **Errors older than 30 days are automatically removed.**

And does it also remove errors that are not yet read? If not, the table could still grow bigger and bigger...

**Comment by pijemcolu** [comment]
@ronaldbarendse . Thanks for the idea 🥇, I have extended the text exactly as you said it. ) Yes, all logs, read or unread get cleaned up after 30 days, I have confirmed that looking at the implementation. I'll close this now.
