### ISSUE TITLE
Security page shows "Manage hostnames" in breadcrumb

### ISSUE THREAD

**Issue by bjarnef** [umbraco/Umbraco.Cloud.Issues#700]
### Issue description

I noticed when browser "Hostnames" and "Security" menu item in the portal, the pages are shown like this, but confusing that the security page shows "Manage hostnames" in breadcrumb.

https://www.s1.umbraco.io/project/my-project/hostnames

![image](https://github.com/umbraco/Umbraco.Cloud.Issues/assets/2919859/9cbd69cc-268b-4fb5-8247-2f627b0fdda2)

https://www.s1.umbraco.io/project/my-project/security

![image](https://github.com/umbraco/Umbraco.Cloud.Issues/assets/2919859/8cc4bfb9-bfdd-4ca3-bb1c-6308e8ab09c5)

**Comment by bjarnef** [comment]
@sajumb probably an easy fix, but yet confusing 😅

**Comment by sajumb** [comment]
Thank you for pointing that out! 😄 We'll ensure to update it as suggested.

**Comment by sajumb** [comment]
We have fixed this. 😄 
Issue is closed accordingly
