### ISSUE TITLE
Edit project alias duration creation of project

### ISSUE THREAD

**Issue by bjarnef** [umbraco/Umbraco.Cloud.Issues#702]
### Issue description

We have a project where we would like a project name, but keep the alias short/simple. Often we face this issue.

I think the workaround is to create the project with a simple name first and rename it afterwards.

However in this case we would like the project alias on 3 characters, but Umbraco Cloud doesn't allow this.

![image](https://github.com/umbraco/Umbraco.Cloud.Issues/assets/2919859/bd550efd-6d17-4a14-a38e-3c36c563ebeb)

Any specific reason for this restriction?

Alternatively if the name should be at least 4 characters, could it generate the alias similar to in Umbraco backoffice and allow to unlock this and adjust the project alias?

E.g. something similar to this from the new backoffice UI using UI library.

![image](https://github.com/umbraco/Umbraco.Cloud.Issues/assets/2919859/7bcee4dc-552d-4b80-9860-e5bd3cae2103)

The project alias we would like is an abbreviation for the project name referred to on daily basis and seems to be available.

**Comment by bjarnef** [comment]
@sajumb it would be great if it was possible to rename alias during creation of project.

Any specific reason for minimum length of 4 characters and 3 characters are not valid?

**Comment by sajumb** [comment]
There is a specific technical rationale behind the minimum requirement of 4 characters.

Regarding your feature request, it appears to align with an existing issue we've documented on [Umbraco Cloud Issue #48](https://github.com/umbraco/Umbraco.Cloud.Issues/issues/48). To maintain efficiency and avoid duplication of efforts, this issue will be closed. Thank you for your understanding.
