### ISSUE TITLE
Choosing users from organization adds organization text on name

### ISSUE THREAD

**Issue by Amalie-Wowern** [umbraco/Umbraco.Cloud.Issues#708]
### Issue description

When im adding a user to a project from my organization it adds a (Organization name) on the end of the users name

Reproduce

Find a existing project
Add user
Choose a user from dropdown
![image](https://github.com/umbraco/Umbraco.Cloud.Issues/assets/84070696/db252f3f-b075-4692-b4ad-99f7e994c349)

**Comment by sajumb** [comment]
Hi @Amalie-Wowern, 
Thank you for bringing this to our attention. You are currently utilizing our suggestive feature, which is designed to recommend members from your organization(s) based on the entered input, thereby simplifying the selection process. Note that the organization itself is not included in the invitation mail.

Your observation regarding the need for front-end validation to accommodate special characters like '/' is spot on. The front end should tolerate this, so you don't have to manually remove it before the invite can be sent. We will fix that!

**Comment by Amalie-Wowern** [comment]
Hi @sajumb 

Thanks for the quick response :-)

I love the suggestion feature and have lived with the "bug" for a long time and just removed the organization to send the invite. 
First i thought, this will I be able to fix and make a pull request, but the portal repository is not open.

Im happy to hear that you will look into it :-D

**Comment by sajumb** [comment]
Hey @Amalie-Wowern,
We have resolved this issue, so the front-end validation will accept the '/' char.
