### ISSUE TITLE
Pasting value to project name doesn't generate/check alias

### ISSUE THREAD

**Issue by bjarnef** [umbraco/Umbraco.Cloud.Issues#711]
### Issue description

When pasting a value to project name input in portal it doesn't check/generate alias and just shows this.

![image](https://github.com/umbraco/Umbraco.Cloud.Issues/assets/2919859/c6d07580-8509-477b-889d-910c2f287785)

One has to actually type something into input to trigger this.

![image](https://github.com/umbraco/Umbraco.Cloud.Issues/assets/2919859/01b84e85-86d9-444e-8588-a12d2f7acc9a)

Sometimes it does seem to trigger the check, but not always.
However when continue the alias seems to be generated anyway.

**Comment by sajumb** [comment]
Thanks for the report. We will have a look and optimize when the event for the validation is triggered.

**Comment by bjarnef** [comment]
Great :) 

I am migrated a project from Umbraco 8 to 10, but with the same name was valid. I noticed this is because the name includes `&` and the alias generated ignores the characters after `&` in alias generation.

**Comment by kenniholm** [comment]
Hey @bjarnef :)

Thanks for reporting this issue and sorry that it took a while to get back to you.

I have investigated and fixed the two mentioned issues, this behaviour should no longer occur.

Closing this one, please let us know if you find anything else!
