### ISSUE TITLE
Menu items doesn't have same indent

### ISSUE THREAD

**Issue by bjarnef** [umbraco/Umbraco.Cloud.Issues#713]
### Issue description

It seems the menu items doesn't have same indent, e.g. "Edit team".

![image](https://github.com/umbraco/Umbraco.Cloud.Issues/assets/2919859/6a5105c5-250e-46fe-a483-b3a6effe93d9)

Looking at the source it also seems there should be some icons - I recall it used to show icons.

![image](https://github.com/umbraco/Umbraco.Cloud.Issues/assets/2919859/29cc18fb-c4a3-4046-81ac-a962eba7cdbe)

**Comment by sajumb** [comment]
Hi @bjarnef,
Yes, we could, and perhaps should visit this old menu implementation to make it perfectly aligned. However, we have decided to put all our front-end efforts into giving you something better than the current project settings menu. That will be out in the first quarter of next year. 😃

**Comment by bjarnef** [comment]
@sajumb okay 😊 but maybe just remove the icons at `<slot>` element for now, since there are not rendered at the moment anyway?

**Comment by sajumb** [comment]
@bjarnef We are committed to working solely on the upcoming navigation. And not to make even minor changes to the existing. So we won't consider this issue, this time around 😄
