### ISSUE TITLE
Upgrade available doesn't show latest patch release

### ISSUE THREAD

**Issue by bjarnef** [umbraco/Umbraco.Cloud.Issues#714]
### Issue description

I noticed this on a few of our projects suggesting v12.3.1

![image](https://github.com/umbraco/Umbraco.Cloud.Issues/assets/2919859/3727fbeb-6d4b-475d-9276-eabf37aa6c18)

where the link goes to: https://our.umbraco.com/download/releases/compare/?from=12.2.0&to=12.3.1

but it should say "Upgrade available - Umbraco 12.3.5" and Umbraco Cloud already patch updated several projects to 12.3.4 and shortly after 12.3.5.

**Comment by sajumb** [comment]
Thanks. This is noted.

**Comment by mikkelhm** [comment]
Hi @bjarnef 

I know this is not worth much now, but it has been fixed (a while ago) - Making the versions available on Umbraco Cloud is for now a manual task in our end, and at this point, we didn't have it part of our "normal" cloud release procedure. It is now, and in the future, we should get this done, so the version that is available will be the latest one what we have rolled upgrades out for.

Kind regards - Mikkel
