### ISSUE TITLE
An error occurred trying to start process 'C:\home\site\wwwroot\Chrome\Win64-117.0.5938.62\chrome-win64\chrome.exe' with working directory 'C:\home\site\wwwroot'. The application has failed to start because its side-by-side configuration is incorrect. 

### ISSUE THREAD

**Issue by LidiaDishnica29** [umbraco/Umbraco.Cloud.Issues#715]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

Umbraco Cloud  12.1.2

### Bug summary

hello, 
I am having an issue with Umbraco Cloud 12.
I have implemented PupeteerSharp for conversion from html to pdf.
And everything works perfectly in localhost, but when i pushed my changes in cloud environment, I am having this error:
**An error occurred trying to start process 'C:\home\site\wwwroot\Chrome\Win64-117.0.5938.62\chrome-win64\chrome.exe' with working directory 'C:\home\site\wwwroot'. The application has failed to start because its side-by-side configuration is incorrect.** 

My code is:
            var browserFetcher = new BrowserFetcher();
            var wwwRootPath = Path.Combine(Directory.GetCurrentDirectory(), Constants.RootDirectory);
            var chromePath = Path.Combine(wwwRootPath, Constants.ChromeDirectory);
            await browserFetcher.DownloadAsync();
            await using var browser = await Puppeteer.LaunchAsync(new LaunchOptions
            { Args = new[] { "--no-sandbox", "--disable-setuid-sandbox",
                "--disable-dev-shm-usage", "--disable-extensions","--single-process", "--disable-gpu"  }, Headless = true 
               , ExecutablePath = chromePath
            });

### Steps to reproduce

To reproduce it, it is needed just to install the Pupeteersharp and try the sample example and try to push in cloud environment

### Expected result / actual result

To work the same as it works in localhost

**Comment by sajumb** [comment]
Hi @LidiaDishnica29, 
After reviewing the specifics of your problem, I believe this situation requires direct assistance from our specialized Support team at Umbraco. We cannot say whether this is related to your configuration of the Umbraco solution or the PupeteerSharp package. The issue you're encountering involves specific configurations and environment settings that are best handled through our dedicated support channels.

Please reach out to our Support team directly via the Umbraco Cloud platform. They have the necessary tools and access to provide more personalized and in-depth assistance to resolve your issue effectively.

I will be closing this issue on the public tracker.

**Comment by LidiaDishnica29** [comment]
I already asked them, but not answered yet
