### ISSUE TITLE
Feature request: Renew invitation request

### ISSUE THREAD

**Issue by jemayn** [umbraco/Umbraco.Cloud.Issues#716]
### Issue description

If you are invited to an Umbraco Cloud project it has an expiration time, which makes perfect sense.

However once that has happened it just sits there and shows an expired error once you try to accept it:
![image](https://github.com/umbraco/Umbraco.Cloud.Issues/assets/79840720/3c63a8e6-88cb-48c7-a03c-f03d75444b34)

Would love it if there was a button for requesting a new invitation from the person who sent it, could just be an email notification to the sender which leads them to the project invites page.

The current workflow is that the invited person has to reach out to the person, and often atleast in my case it is not nessecarily the contact person you have which is the one inviting so it has to go through several people.

**Comment by sajumb** [comment]
Hi @jemayn,
Thank you for the feature request regarding the invitation process in Umbraco Cloud. 
We recognize that a nice feature to add, and I have created a backlog item to implement a feature that allows users to request a resend of an expired Umbraco Cloud project invitation. This enhancement aims to streamline the invitation process and make it more user-friendly.

We will keep you updated on the progress of this feature.

**Comment by sajumb** [comment]
Hi @jemayn,
Sorry for the late update but in case you haven't yet noticed, the feature request was applied in January.
You can find the release notes [here](https://docs.umbraco.com/umbraco-cloud/release-notes/) and the specific section about the resend feature [here](https://docs.umbraco.com/umbraco-cloud/release-notes/2024-01-releasenotes#project-invitation-renewal-request).

**Comment by jemayn** [comment]
Hey @sajumb 

I did see it in the product update, that's great! Thanks for the quick work, I will close this issue then 🙂
