### ISSUE TITLE
Upgrade bar not shown when NuGet packages has known high severity vulnerability

### ISSUE THREAD

**Issue by bjarnef** [umbraco/Umbraco.Cloud.Issues#717]
### Issue description

After not working a specific Umbraco Cloud project for a while, I noticed the Development enviroment had a warning due to NuGet packages with known high severity vulnerability.

However I found it a bit odd the upgrade bar isn't available in such case to upgrade to newer version of Umbraco.

![image](https://github.com/umbraco/Umbraco.Cloud.Issues/assets/2919859/22901eed-21a4-463b-a0c4-ac977b7fb6ad)

**Comment by sajumb** [comment]
Hi @bjarnef,
Thanks for the report. We are currently implementing a new way of depicting errors or warnings related to deployment and upgrades. I cannot say that the above message is the cause for the upgrade bar not to be displayed. But when a new version of the project page has been launched a potential relation between the failed upgrade and upgrade button should be decoupled and resolving this potential issue.
