### ISSUE TITLE
English Translation in Upgrade Project flow incorrect for the "Outgoing IP" information.

### ISSUE THREAD

**Issue by TomChancer** [umbraco/Umbraco.Cloud.Issues#719]
### Issue description

Noticed this morning when updating a project from starter to standard a little bit of a weird description under the External IP accordion notification here:

![image](https://github.com/umbraco/Umbraco.Cloud.Issues/assets/56866089/d47a74b3-e7ec-40cd-bc06-582d944a2461)

Very minor issue but would suggest altering the text to something like:

"Upgrading a plan will change the outgoing IP of the project. If your solution has an external service that was configured with the IP addresses from before your upgrade. You may need to update the external service to reflect the new IP addresses."

**Comment by sajumb** [comment]
Hey @TomChancer 
Thanks. We will alter the text and make it better.

**Comment by sajumb** [comment]
Hi @TomChancer,
We have improved the wording of according so it matches your suggestion.
