### ISSUE TITLE
Repeatedly clicking the same read notification decreases notification count

### ISSUE THREAD

**Issue by aguyfromdenmark** [umbraco/Umbraco.Cloud.Issues#722]
### Issue description

If you click on a notification to mark it as read, the notification counter at the bell will decrease by one. 
You can continue to repeatedly click the same notification, causing the counter to decrease further. 
Clicking it enough times will cause the counter to continue past zero. 
![image](https://github.com/umbraco/Umbraco.Cloud.Issues/assets/6904597/f1be42a2-21e8-406b-84ad-4cfbda7027f1)

**Comment by sajumb** [comment]
Hi @aguyfromdenmark,
Thank you for bringing this issue to our attention. We will soon start a technical and visual overhaul of the top bar and notification counter on the Umbraco Cloud platform. This update is designed to enhance overall user experience and functionality.

Thanks to your report, I can assure you that repeatedly clicking on a notification causes the counter to incorrectly decrease past zero, now is on our radar. We are committed to ensuring that this issue will be resolved in the upcoming release of the updated top bar and notification system.
