### ISSUE TITLE
Live dashboard became unavailable for entire team for several days

### ISSUE THREAD

**Issue by kieron-mcintyre** [umbraco/Umbraco.Cloud.Issues#730]
### Summary

We had an instance this month (Jan '24) were the entire live CMS dashboard became unavailable for several days. Instead, the following page was displayed to all users:

![thumbnail_image](https://github.com/umbraco/Umbraco.Heartcore.Issues/assets/1391597/0e76f243-93db-4f1f-877d-9e5339891d30)

The issue isn't necessarily that the CMS instance became unavailable but that no one was notified.

### Steps to reproduce

This isn't reproducible now, fortunately/hopefully, however:

1. We requested /umbraco
2. This redirected to an authorize endpoint
3. A final page is then loaded but is missing and the above screenshot was displayed.

![image](https://github.com/umbraco/Umbraco.Heartcore.Issues/assets/1391597/c316cb3e-3a75-43c3-94e3-c8c99bdfb312)

### Expected result

 - Notifications sent to Umbraco that something is wrong;
 - Notifications sent to project admins that something is wrong but that Umbraco are aware and resolving the issue under the terms of the SLA;
 - The issue was resolved without contacting Umbraco support.

### Actual result

1. No notifications were sent to our admins notifying them that there was an issue;
2. No notifications were sent to Umbraco notifying them that there was an issue;
3. The issue would have remained unresolved had I not got in contact to report the issue;
5. The explaination from Umbraco was:

    > "What I can tell you is that it was the client securet for Umbraco ID that I needed to regenerate"

    which presumably means that an automated process had failed, or a process that should have been automated, wasn't.

**Comment by kieron-mcintyre** [comment]
> Hi Kieron,
> 
> Thanks for your report. As this is a generic Cloud error and not specific to Heartcore only, I am transferring it to the Cloud issue tracker where hopefully it will get the attention it deserves.

Is this internal or something we can have access to see the progress of?

It really is vital that there are notifications in place for services going offline.

**Comment by jmf-umbraco** [comment]
Hi @kieron-mcintyre,

We've discussed this one at length internally, and we believe that the issue that caused the CMS back-office to become available is not a widespread issue and we need to conduct further analysis internally before we can take action on a fix. Therefore I will close this ticket.

We acknowledge that in this specific incident you needed to raise a support ticket and were not alerted by us, and we understand the frustration that comes alongside that. We're always keen to discuss how we can improve our monitoring and notification process, but this is a discussion better had elsewhere - if you would like to talk about this with us further then please let us know in your support ticket.
