### ISSUE TITLE
Unable to install self-signed certificate in Umbraco Cloud.

### ISSUE THREAD

**Issue by sandeepkmrnishad** [umbraco/Umbraco.Cloud.Issues#735]
### Issue description

We are validating our SAML response through custom certificate (.CRT-self signed) .
We want to install our custom certificate to the Umbraco cloud environment similar as “Trusted root certification Authorities” in windows.  As per discussion with Umbraco team, Umbraco cloud is not providing such feature/functionality to validate certificate through "Trusted root".
 
 
We can establish trusted root relationship with our self sign certificate on our local machine/Azure VM by installing it in Trusted Root Authorities. The same we wanted to do in Umbraco Cloud.
 
Our multiple clients requested this feature to implement in Umbraco Cloud Project and we are unable to help them.

**Comment by meyntony** [comment]
@sandeepkmrnishad as discussed currently we don't support installing custom certificates in your Azure Web App like described in [this document](https://learn.microsoft.com/en-us/azure/app-service/configure-ssl-certificate?tabs=apex)

But instead you could load your custom certificate from the file system, this would mean that in case you want to validate the signature of the custom certificate, you will not be able to as the Root certificate used to the sign your custom certificate does not exist with Umbraco Cloud.

**Comment by pijemcolu** [comment]
We don't use App Service Environments, but App Services "only". This complicates the part of the feature request with uploading a custom root certificate. 

Uploading custom certificates and loading those on demand through c#, that'd be potentially possible even now and is a matter of implementation in Umbraco Cloud. Root CA cert updates are a large feature request, requesting changes to the underlying hosting model.

**Comment by mikkelhm** [comment]
I'm closing this issue for now, its been 5 months since the last interactions
If this is a feature request, please create a new discussion on this tracker, where we can discuss how to get the feature implemented -> https://github.com/umbraco/Umbraco.Cloud.Issues/discussions
