### ISSUE TITLE
"NO LICENSE FOUND" error

### ISSUE THREAD

**Issue by christintom** [umbraco/Umbraco.Cloud.Issues#736]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

8.6.3 (Uno)

### Bug summary

Some times "NO LICENSE FOUND" error in the front end of website. When I restart the site it go away, but several times repeated so I need a permanent solution

### Steps to reproduce

.

**Comment by sajumb** [comment]
@christintom  Please contact our support with this bug report, if you haven't already done so.
We will close the ticket here.
