### ISSUE TITLE
Feature Request: Implement setting to allow "go to backoffice" and "view page" links to open in a new window/tab

### ISSUE THREAD

**Issue by hjaltedaniel-umbraco** [umbraco/Umbraco.Cloud.Issues#742]
### Issue description

When opening the "Go to backoffice" and "View page" links on the portal home screen, it opens in the same window by default.
The purpose of this feature request is to suggest implementing a setting, under "Settings" to allow users to choose whether they want the default behavior (which I could see could be very useful for someone who does not care about the portal eg. content editors) or if they want to open the links in a new window/tab (which would cause less frustrations for someone like me, who actually wants to keep the portal window open).

![image](https://github.com/umbraco/Umbraco.Cloud.Issues/assets/61144403/78cfa307-84cc-4c55-acf5-b0f2d83bb1f6)

**Comment by ksuvec** [comment]
Hi @hjaltedaniel-umbraco 

Thank you for the input, we will consider this within the team!

**Comment by ksuvec** [comment]
@hjaltedaniel-umbraco

Fixed. Thanks
