### ISSUE TITLE
Icons/buttons above overlay

### ISSUE THREAD

**Issue by bjarnef** [umbraco/Umbraco.Cloud.Issues#743]
### Issue description

I had a look at the new UI at https://www.s1.umbraco.io/project-new/my-project

It seems the icons/buttons are above the overlay opened from the three dots:

![image](https://github.com/umbraco/Umbraco.Cloud.Issues/assets/2919859/9875bbd3-ea4a-417d-974f-67bcd0f3448f)

**Comment by ksuvec** [comment]
Hi @bjarnef 

Thanks for testing our new UI 🤩! Feedback has been forwarded to the team

**Comment by Musealali** [comment]
Hey @bjarnef - hope you are well!

We wanted to let you know that the issue with the icons/buttons being above the overlay has been resolved. We apologize for the delay in responding to this and appreciate your understanding.

If you have any other questions or run into any further issues, please don't hesitate to reach out.

Best regards,
