### ISSUE TITLE
Make search input wider in project overview

### ISSUE THREAD

**Issue by bjarnef** [umbraco/Umbraco.Cloud.Issues#747]
### Issue description

In project overview we have some longer project names. It'ts a shame the search input is a bit short, when there is plenty of space on the right.

![image](https://github.com/umbraco/Umbraco.Cloud.Issues/assets/2919859/3b8262b4-9245-4ad3-98e1-c707222c94cc)

![image](https://github.com/umbraco/Umbraco.Cloud.Issues/assets/2919859/058f35f3-818a-4230-bccf-03f89087da8c)

**Comment by julczka** [comment]
Hi @bjarnef ! 
I'm happy to inform that we fixed that one :) 
Have a great day!
