### ISSUE TITLE
Scroll container only take up 50dvh

### ISSUE THREAD

**Issue by bjarnef** [umbraco/Umbraco.Cloud.Issues#748]
### Issue description

It noticed when opening accordion menu in the new portal UI, it only take up 50dvh, hiding the part of the navigation although there is space enough to increase height of navigation.

![image](https://github.com/umbraco/Umbraco.Cloud.Issues/assets/2919859/177f5702-4fa1-4b75-bc75-050297e8874d)

**Comment by ksuvec** [comment]
Hi @bjarnef 

Thanks for having an eye on the details. This has been fixed! 

Keep em coming
