### ISSUE TITLE
We need have consistency in what we call things. 

### ISSUE THREAD

**Issue by Aaen** [umbraco/Umbraco.Cloud.Issues#75]
We should be more consistency in what we call things in different places in the CMS on Umbraco Cloud. 

Reproduction
------------

If you do the content transfer from the Content tree then its called queue for transfer.

If you do it on a single node then we call it Deploy

<img width="749" alt="Skærmbillede 2019-04-10 kl  18 02 28" src="https://user-images.githubusercontent.com/2038482/55894774-13c1f100-5bbb-11e9-9466-320fc86e4b80.png">
<img width="1430" alt="Skærmbillede 2019-04-10 kl  18 02 55" src="https://user-images.githubusercontent.com/2038482/55894775-13c1f100-5bbb-11e9-982c-ee07670c54b2.png">

**Comment by KennethJakobsen** [comment]
That is because the single node button does not queue - it actually does a single deploy.

**Comment by pijemcolu** [comment]
@KennethJakobsen shouldn't we then `Queue for Deploy` instead of `Queue for Transfer`?
