### ISSUE TITLE
Deploy button still enabled during deployment.

### ISSUE THREAD

**Issue by readingdancer** [umbraco/Umbraco.Cloud.Issues#753]
### Issue description

If you trigger a deployment between environments, the two environments turn Yellow ( which is good ) but the Deploy button is still enabled and you can click it to trigger the deployment to run again, this doesn't seem right?

![Screenshot](https://github.com/umbraco/Umbraco.Cloud.Issues/assets/4398217/b7769506-2882-45e5-a0e7-2120460de968)

My expectation is that when you are in the middle of a deployment, you are unable to try and start a new one, so this button should be greyed out... / disabled.

**Comment by ksuvec** [comment]
hi @readingdancer 

Thank you for reporting this, we will take a look!

**Comment by julczka** [comment]
Hello all, 
This is fixed now :) 
Deployment button is blocked when there is a deployment in progress or when there is another activity running
