### ISSUE TITLE
Bug: CSV Download under availability and Performance currently only has date and value

### ISSUE THREAD

**Issue by thonaj** [umbraco/Umbraco.Cloud.Issues#755]
### Issue description

Steps to reproduce

1. Log into umbraco.io
2. Expand Insights
3. Click availability and performance
4. Click the menu icon under the graph
5. Click download CSV

Currently the CSV download only has date and value as described above. If the CSV was a summary with only 1 value per day, then I would expect to have just a date. However, this is a detail list of all data points, and they are not identified accurately without the complete timestamp.  Not having the complete timestamp renders the download unusable in its current state. 

Assume I am looking into issues with scheduled jobs, and I am going to use the log files and compare the data with the csv download. I am unable to do that without a timestamp.

**Comment by ksuvec** [comment]
@thonaj 

This has been fixed, thanks again for making the Umbraco Cloud a better platform :)
