### ISSUE TITLE
GUID instead of environment name in Security > Public Access

### ISSUE THREAD

**Issue by dwlkev** [umbraco/Umbraco.Cloud.Issues#756]
### Issue description

GUID is shown instead of environment name in Security > Public Access making it difficult to know which is selected. 
Confirmed across multiple cloud projects and also with Umbraco staff on support ticket #72156

![image](https://github.com/umbraco/Umbraco.Cloud.Issues/assets/88844242/73b165d4-edd7-490c-982a-66d356105420)

**Comment by ksuvec** [comment]
Thank you for reporting this @dwlkev 

We are looking into the issue!

**Comment by dwlkev** [comment]
Thanks. Can see this has been fixed so will close
