### ISSUE TITLE
Changing .net version under "Advanced" for Development will restart Live env

### ISSUE THREAD

**Issue by jesperlange** [umbraco/Umbraco.Cloud.Issues#759]
### Issue description

When you go to a project under Configuration -> Advanced, and choose another .net version for your development, then it states that it will apply the changes and restart the **live** environment
![image](https://github.com/umbraco/Umbraco.Cloud.Issues/assets/54025229/04d10975-7960-409d-875e-43d3fda2220d)

You can reproduce this yourself by going to any v9+ project, then try and change the .net version to anything.

The workaround to fix this: 
- Choose "Live" then choose a .net version
- Cancel it
- Go back to dev -> choose a .net version
- Now it shows correctly, that it will restart Development
- 
![image](https://github.com/umbraco/Umbraco.Cloud.Issues/assets/54025229/51397475-b6c9-4a8a-839b-cbbbdaa28e54)

*words

**Comment by kenniholm** [comment]
Hey @jesperlange 

I have investigated the issue you are describing and it is very easy to reproduce, thanks for the easy steps.

A fix for the issue should be deployed shortly then this should no longer occur.

Marking this one as closed.
