### ISSUE TITLE
Fails to edit email of technical contact

### ISSUE THREAD

**Issue by bjarnef** [umbraco/Umbraco.Cloud.Issues#762]
### Issue description

I wanted to edit technical contact of an Umbraco Cloud project, but it failed.
I thought it was a general issue, but adding a new technical contact works, and I could edit name and phone.

It turns out it fails, when I edit email of the technical contact.

![chrome_5Yx8eBsVCF](https://github.com/umbraco/Umbraco.Cloud.Issues/assets/2919859/0d79d213-331b-48e0-9cfe-faaf7ab72ab0)

Also when editing an existing technical contact change label to "Edit" instead of "Add".

**Comment by danlister** [comment]
Thanks for raising this issue @bjarnef 😄 I'll take a look

**Comment by danlister** [comment]
Thanks for raising this issue @bjarnef 😄 

Both the text and ability to edit a technical contact should be fixed now.
