### ISSUE TITLE
Arrange environment tabs left to right

### ISSUE THREAD

**Issue by bjarnef** [umbraco/Umbraco.Cloud.Issues#765]
### Issue description

Most places in the portal Development tab is on left and Live on right, which makes sense as the deployment flow is left to right.

![image](https://github.com/umbraco/Umbraco.Cloud.Issues/assets/2919859/19f7b09e-d9cd-45ea-936e-bb8653d1adce)

But I find it confusing is is something the opposite, e.g. under SQL Connection Details and Blob Storage Connection Details.

![image](https://github.com/umbraco/Umbraco.Cloud.Issues/assets/2919859/797a1ef6-f5a0-4dea-86b0-7517f6bf44e0)

![image](https://github.com/umbraco/Umbraco.Cloud.Issues/assets/2919859/6de10aaa-ec93-411a-b03e-b13f945deedb)

I also think it makes sense the Live environment actively need to be selected (unless only Live environment exists), so one pay extra attending when connecting to live database and blob storage.

**Comment by ksuvec** [comment]
Hi @bjarnef 

Thank you for reporting this. We will ensure that at least the sorting is correct. On the other pages I am certain the default choice is not Live if you have more than one environment

**Comment by julczka** [comment]
Hi Bjarne! 
That should be fixed now :) 
Thanks for pointing it out.
