### ISSUE TITLE
Runtime setting not is not always selected

### ISSUE THREAD

**Issue by bjarnef** [umbraco/Umbraco.Cloud.Issues#766]
### Issue description

It seems Umbraco Cloud figure out to select target framework based on deployment based on project, but sometimes it doesn't select to select to option and it has explicit to be selected from portal.

![chrome_GEH7Jx6cat](https://github.com/umbraco/Umbraco.Cloud.Issues/assets/2919859/eabd4957-3db0-4516-9ae4-e08567c8ec98)

![image](https://github.com/umbraco/Umbraco.Cloud.Issues/assets/2919859/2651f9c5-27a3-4320-ad94-a184ff609e27)

**Comment by Musealali** [comment]
Hey @bjarnef,

Sorry for the delay in response.

I've investigated the issue you described and am in the process of deploying a fix. It should be live shortly.

If you encounter any further issues, please don't hesitate to reach out.

Marking this issue as closed.

Thank you for your patience!
