### ISSUE TITLE
Feature Request: Bring back the log of GIT messages when doing a deployment in the portal

### ISSUE THREAD

**Issue by MatsLimetta** [umbraco/Umbraco.Cloud.Issues#768]
### Issue description

Before, there was git messages logged in detail when making a deploy from one environment to another. Please bring those back. It helps quite a bit to understand where the problem is if/when there is an issue with a deploy.

**Comment by Musealali** [comment]
Thanks for reaching out and informing us about the detailed git messages you used to see during deployments. We understand how helpful those were for troubleshooting.

Good news! We’ve introduced a new feature that records all deployment information. This feature includes all the details you need to understand and diagnose any issues during a deployment.

We believe this will provide you with the comprehensive insights you seek.

I have included a small recording of this feature aswell. 

If you have any questions or need further assistance, feel free to reach out!


https://github.com/user-attachments/assets/54b4479e-f959-416a-bb10-e4c9ce06b935
