### ISSUE TITLE
Cannot create project based on baseline in Safari

### ISSUE THREAD

**Issue by greystate** [umbraco/Umbraco.Cloud.Issues#769]
### Issue description

If you're using Safari, it is currently not possible to create a new project based on a baseline, because the custom dropdown is empty. It does its thing where it says it's loading baselines, but it ends up being empty.

No messages or errors in the Console.

Using Firefox (or Chrome, I assume) it works fine.

(I was using Safari `v17.4.1` on macOS Sonoma `v14.4.1`)

**Comment by ksuvec** [comment]
Hi @greystate 

Thanks for reporting. We will look into this

**Comment by julczka** [comment]
Hi all! That is fixed now.
