### ISSUE TITLE
Add a user role to allow or disallow content transfer/deployments from backoffice.

### ISSUE THREAD

**Issue by simonbusborg** [umbraco/Umbraco.Cloud.Issues#77]
Add a user role to allow or disallow content transfers/deployments from backoffice.

This could be solved by adding the option  **"Allow content transfer between environments"** to a user group.

**Comment by simonbusborg** [comment]
Bump :)

**Comment by simonbusborg** [comment]
Any news on this one @nul800sebastiaan ? 🤞

**Comment by nul800sebastiaan** [comment]
Thanks for the reminder @simonbusborg - looks like we have good news on that front! This feature will be available in the next release of Deploy coming in the next few weeks (version 3.4.5).
You'll be able to choose for each user group if they will be allowed to deploy content/media changes from the backoffice of Umbraco.

I'll close this one as "coming to a Deploy near you soon".
