### ISSUE TITLE
Need to know more about Flexible Environment

### ISSUE THREAD

**Issue by Nikhilgirirajdigital** [umbraco/Umbraco.Cloud.Issues#770]
### Issue description

I am currently working on an Umbraco Cloud project where we can create a maximum of three environments: Development, Staging, and Live. The corresponding `appsettings.json` transform files for these environments are `appsettings.Development.json`, `appsettings.Staging.json`, and `appsettings.Production.json` respectively.

I recently learned about the upcoming feature of Flexible Environments and I have a few questions regarding this:

1. When adding a new flexible environment, will Umbraco Cloud automatically create a corresponding transform file in each environment's git repository?
2. If an environment is deleted, will its corresponding transform file be removed automatically?
3. What will be the naming convention for the transform files corresponding to the flexible environments?

**Comment by danlister** [comment]
Thanks for your questions about the upcoming Flexible Environments feature on Umbraco Cloud. Here’s some information that might help clarify things:

1. Automatic Creation of Transform Files
Currently, we don't have plans in place to automatically create transform files for each new flexible environment. This aspect is still under consideration and hasn't been decided yet.

2. Automatic Removal of Transform Files
Similarly, the automatic removal of transform files when an environment is deleted has not been finalised. We're exploring the best approaches to manage environment-specific configurations effectively.

3. Naming Convention for Transform Files
One option we could explore is allowing developers to specify the ASPNET_ENVIRONMENT variable for each environment. This way, developers can choose which appsettings file to use. For example, if you create a new environment called "QA", you could set the ASPNET_ENVIRONMENT variable to QA and manage your settings in appsettings.QA.json.

This approach could provide more flexibility and control over configurations without enforcing a strict structure. I hope this helps! It's not a definite answer as we are still exploring options 😄 

Let me know if you have any other questions or suggestions.

**Comment by Nikhilgirirajdigital** [comment]
Got it. Thank you @danlister 👍
