### ISSUE TITLE
CORS issue when using node package

### ISSUE THREAD

**Issue by SSmale** [umbraco/Umbraco.Cloud.Issues#80]
Using the code from the example repo [here](https://our.umbraco.com/documentation/Umbraco-Cloud/Headless/Headless-Node-Client/) i have filled in my details and get a 400 and cors error using a standard chrome browser. when using the disable cors flag i am able to access the headless CMS.

Is there a setting on the cloud portal that will allow this or am I missing something in my config?

**Comment by SSmale** [comment]
Any update on this?

**Comment by jmayntzhusen** [comment]
Hey @SSmale 

Sorry about the lack of replies here!

I see you had this issue originally on the headless beta. I haven't seen others with the same issue on the now launched Heartcore so will close this issue. If you still have the problem on Heartcore then please reply here and we will make sure to look further into it!
