### ISSUE TITLE
Deleted database backups are still present

### ISSUE THREAD

**Issue by mikkelhm** [umbraco/Umbraco.Cloud.Issues#801]
### Issue description

When I delete a database backup from my list, it's state will go to deleted, the backup is gone, but it is still present in the list.
If I end up having many of those it will clutter the list alot.

Would be nice with the deleted ones just not being in the list or maybe having it's own list, or even just a checkbox that would allow one to see deleted backups, being unchecked by default.

**Comment by jesp209i** [comment]
Hi @mikkelhm 
After some discussions on the team, we decided to remove the deleted backups altogether from the list in the UI.
The reasoning behind this is that a user would not be able to do anything with that information and that the backup of course also would be gone.

Thanks for the great suggestion

**Comment by mikkelhm** [comment]
That is amazing, great work, make sure to give my highest praises to the team that implemented this feature, #h5yr
