### ISSUE TITLE
Typo on "Advanced settings" screen

### ISSUE THREAD

**Issue by greystate** [umbraco/Umbraco.Cloud.Issues#82]
On the **Advanced settings** screen in the portal (`https://www.s1.umbraco.io/project/advanced/<projectname>`), "IIS" is misspelled as "ISS" in the description under the heading.

**Comment by nul800sebastiaan** [comment]
Thanks! We'll have a look soon 👍

**Comment by KennethJakobsen** [comment]
This has been fixed
