### ISSUE TITLE
Configuration tabs show wrong environment

### ISSUE THREAD

**Issue by callumbwhyte** [umbraco/Umbraco.Cloud.Issues#824]
### Issue description

When you have a project with multiple environments, the "Connections" section of the Cloud portal initially shows shows the wrong tab as selected.

e.g. By default the text says the live environment is selected, and the live environment details show, but the tab highlighted is "Development"

<img width="1007" alt="Screenshot 2024-07-29 at 10 43 49" src="https://github.com/user-attachments/assets/e3b50070-14bc-4a65-9113-c56f41392f6a">

**Comment by jesp209i** [comment]
Hi @callumbwhyte 
Thanks for pointing this out  👍 - It looks like we corrected this issue, but never got back to you.
When I log on to the Connections page things are in sync again so I will close this issue.

Kind Regards,
Jesper, Umbraco Cloud Team
