### ISSUE TITLE
Restore of backups on Umbraco Cloud breaks SQL Azure firewall rules

### ISSUE THREAD

**Issue by RosenPetrovFFW** [umbraco/Umbraco.Cloud.Issues#831]
### Issue description

Hello,

I just noticed that when I restore a database with the newly released feature in Umbraco Cloud my existing SQL Azure firewall rules which include some whitelisted IPs stop working. The solution is that I have to remove and add them manually. I expect this to be handled automatically after my restoration. 

Thanks

**Comment by Musealali** [comment]
Hi Rosen,

Thank you for bringing this issue to our attention! I appreciate your report. I’m currently investigating it and will update you as soon as I have more information.

Best Regards

**Comment by Musealali** [comment]
Hey @RosenPetrovFFW 

We have now rolled out a fix for this - sorry for the delay. 

If you have any more questions please do not hesitate to reach back to us.

I will mark this as closed.
