### ISSUE TITLE
Set top size for images.

### ISSUE THREAD

**Issue by FernandoFeliciotti** [umbraco/Umbraco.Cloud.Issues#84]
A brief description of your feature request goes here.
It would be really good to be able to set a top size for Images given that anyone could upload a high size image like 10 mbs or more and that would harm your performance site.

**Comment by nul800sebastiaan** [comment]
Hey there @FernandoFeliciotti - Each Umbraco site comes with ImageProcessor, make sure to limit the size when you put it in your frontend templates, you could make sure to use "Resize min" or "Resize max", see: https://imageprocessor.org/imageprocessor-web/imageprocessingmodule/resize/

For further help with this, make sure to head to the forum: https://our.umbraco.com where you can get some help getting the best results.
