### ISSUE TITLE
Agency users

### ISSUE THREAD

**Issue by FransdeJong** [umbraco/Umbraco.Cloud.Issues#86]
We as a agence have a lot of sites in our cloud account. Every employee has access to the cloud portal via the main support email address.
We could give every employee his own login but for example 5 employees x 15 sites x 5 euro is 375 euro. We want to migrate all our sites to cloud and that means 40 x 5 x 5 =  1000 euro for employee access. Also if we get a extra employee or a employee leaves we need to go through 40 sites to give or block access.

It would be great if we add a user to a project that we could somehow give this user agency rights and therefore he would be able to access all cloud sites instead of giving the user access to our main cloud account which is a serious risk in my opinion.

**Comment by jmayntzhusen** [comment]
As Cloud users are now free, we recommend that each person gets their own user 🙂

If you have a specific feature request about granting access to all organization sites fx, please open a new issue about that!
