### ISSUE TITLE
grid.editors.config.js should not be overwritten on upgrades on cloud

### ISSUE THREAD

**Issue by rbaty-barr** [umbraco/Umbraco.Cloud.Issues#9]
A brief description of the issue goes here.

LeBlender is a wonderful tool for content managers... it allows for custom gird types to be created. It stores the info in the grid.editors.config.js... which is probably where it should be stored, right? however, it appears that file is overwritten during upgrades on cloud. It also appears that this has come up before... https://our.umbraco.com/packages/backoffice-extensions/leblender/general-discussion/75159-leblender-and-umbraco-as-a-service - please note, Seb's solution.

Reproduction
------------

if you make a custom leblender grid editor - after upgrades on cloud, those grid editors go away.

**Comment by nul800sebastiaan** [comment]
Going through some ooooold issues. This has since been fixed, we won't touch this file any more!
