### ISSUE TITLE
Spelling mistakes in deployment dashboard

### ISSUE THREAD

**Issue by lukehook** [umbraco/Umbraco.Cloud.Issues#92]
### Bug summary

Possibly a pedantic one so I apologise in advance, also would rectify myself with a PR but I couldn't find the relevant source code for this dashboard.

When triggering a content transfer there are a couple of spelling mistakes on the deployment dashboard. 'Transferring' is spelt with a single 'r' rather than the correct double 'r' as is 'Transferred'.

### Steps to reproduce

1. Queue any content for transfer
2. Navigate to the content / deployment dashboard (Your workspace)
3. Misspelling in grey 'pending changes' box
4. Trigger transfer by clicking 'Send changes to {environment} workspace'
5. Misspelling of 'Transferring' in the updated progress indicator

### Expected result

- Content in grey transfer summary box should be spelt **transferred**
- Content in grey transfer progress box should be spelt **transferring**

### Actual result

- Content in grey transfer summary box is spelt **transfered**
- Content in grey transfer progress box is spelt **transfering**

![Umbraco-Deploy-Typo-2](https://user-images.githubusercontent.com/7995797/60453254-97bece80-9c28-11e9-8398-eea30bb85dd9.PNG)
![Umbraco-Deploy-Typo](https://user-images.githubusercontent.com/7995797/60453255-97bece80-9c28-11e9-944a-d38d6774cade.PNG)

**Comment by mikkelhm** [comment]
Woohoo - this has been fixed, and will be released in the next version of Umbraco Deploy (release date is currently unknown) :-)

Thanks for reporting it @lukehook
