### ISSUE TITLE
Change profile image in Cloud project portal should not link to Wordpress

### ISSUE THREAD

**Issue by rhealefever** [umbraco/Umbraco.Cloud.Issues#93]
Clicking "Change image" on the Cloud project portal 

![image](https://user-images.githubusercontent.com/47108275/60587389-99a5a080-9d94-11e9-940a-dfbb4c9a291d.png)

Takes us to https://en.gravatar.com/ which requires a Wordpress login.

Maybe we could change this to something on the same framework?

**Comment by mikkelhm** [comment]
Hi @rhealefever 

This will be fixed in the next release - the fix for now has been to remove the Gravatar functionality, it might be replaced with a proper avatar-service sometime in the future.

Im closing this issue down
