### ISSUE TITLE
Extend public API with support for deployment from external platform (Azure Dev Ops)

### ISSUE THREAD

**Issue by renewerkmankiwa** [umbraco/Umbraco.Cloud.Issues#94]
We use Azure Dev Ops for the source control/scrum boards/release/deployment process. Also we have set per stage approval steps. This is needed for our ISO certification. In other words our SDLC depends on the tooling of Azure Dev Ops. It would be great that the Umbraco Cloud API exposes an action or actions for the deployment actions.

**Comment by pijemcolu** [comment]
@renewerkmankiwa Could you elaborate on what exactly is your use case?

Currently the deployment from source to Umbraco Cloud is done through git. Can you not deploy to Umbraco Cloud using git from within Azure DevOps? Or are you interested in deployments between different Umbraco Cloud environments?

**Comment by nul800sebastiaan** [comment]
I'll close this for now as we haven't gotten a reply yet, make sure to update the issue if you have more info to add! 👍
