### ISSUE TITLE
Environment history overview usability improvement

### ISSUE THREAD

**Issue by umbracowulser** [umbraco/Umbraco.Cloud.Issues#95]
As a user/end customer of an Umbraco Cloud site I would like to correlate web analytics data indicating that there was a change in user behavior on my site, with which changes has been pushed to Live on the dates where I started seeing the user behavior change.

I thought I could see this in the Cloud portal.

At the moment, all I can see is a list that shows environment history based on how many days ago changes were made.

Also if changes are more than a month old, the specific amount of days ago a change was made, is replaced with the even less specific: "A month ago", "Two months ago" etc. This makes it very difficult for me to track what changes were made by whom that could have lead to the change in visitor behavior.

![image](https://user-images.githubusercontent.com/34370822/61110591-dace3c80-a487-11e9-84f8-4eda62e9b18e.png)

I would like regular timestamps to be displayed instead of a calculation of how many days ago changes were made.

**Comment by hfloyd** [comment]
Hi @umbracowulser , Somewhat related to your suggestion... take a look: https://github.com/umbraco/Umbraco.Cloud.Issues/issues/128

**Comment by jmayntzhusen** [comment]
As of today the portal now has timestamps on the change history 🙂

![image](https://user-images.githubusercontent.com/36075913/74314203-57563000-4d75-11ea-97d5-4a71119f7709.png)


Thanks for submitting this feature request!

**Comment by umbracowulser** [comment]
Fantastic, thank you! :)

-- 

Kind regards / Med venlig hilsen


Martin Wülser Larsen

Online Communications Dragoon





*https://umbraco.com* <https://umbraco.com/>

Mobile: +45 27 59 14 26
