### ISSUE TITLE
Project boxes has different sizes when filtering

### ISSUE THREAD

**Issue by bjarnef** [umbraco/Umbraco.Cloud.Issues#96]
When filtering Umbraco Cloud projects in the portal via the search input, the boxes sometimes have different sizes.

It seems to happen, because the parent container with class ´projectList` doesn't use full width.
The class have some invalid css rendered ` width: calc(1 + $spacing);` which isn't compiled correct from e.g. Sass or Less.. or just invalid included css.

![image](https://user-images.githubusercontent.com/2919859/61581780-d9091680-ab22-11e9-9e1c-63b36ba3f0fd.png)

Adding `flex: 1 1 100%;` to this class seems to fix the issue.

```
.projectList {
    flex-direction: row;
    margin-left: -20px;
    justify-content: flex-start;
    align-items: flex-start;
    flex: 1 1 100%;
} 
```

**Comment by nul800sebastiaan** [comment]
Thanks for the help @bjarnef - The Cloud team has now implemented your fixes and they've been rolled out today!
