### ISSUE TITLE
Increase in outages on Umbraco Cloud

### ISSUE THREAD

**Issue by MichaelNielsenDK** [umbraco/Umbraco.Cloud.Issues#98]
We are experiencing an increase in outages on Umbraco Cloud. 

I have been in contact with Umbraco Support regarding this issue, and was told is the sites being moved around, and to create an issue about it here. 

Our monitoring shows sites being moved almost daily last week (week 29), before it was maybe once every week or two. 

Are there any particular reasons that it seems to happen more often than before, meaning have you done any changes that might make these moves more prolific? Or is it just coincidental?

Here's some examples

onlineski.dk (https://www.s1.umbraco.io/project/onlineski)
https://i.imgur.com/PG0ZtVi.png 

baerenbachhof.at (https://www.s1.umbraco.io/project/hotel-baerenbachhof)
https://i.imgur.com/l76AaR4.png 

grafenbergresort.at (https://www.s1.umbraco.io/project/grafenberg-resort)
https://i.imgur.com/8CD7kwq.png

**Comment by dzordzs** [comment]
Hey Michael, sorry for confusion here, let's move this out of issues as it's something that should go through support. 
We are looking into this and SWAT will be in touch with you :) 

Best,
Georgs
